- youtube_dlc/downloader/youtube_live_chat.py
https://github.com/blackjack4494/yt-dlc/pull/262 by @siikamiika
> make sure playerOffsetMs is positive

- youtube_dlc/extractor/vlive.py
https://github.com/blackjack4494/yt-dlc/pull/223 by @kyuyeunk
> [vlive] add support for playlists

- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/mildom.py
- youtube_dlc/utils.py
---
---
This adds an extractor for Mildom, which is similar website to Twitch.
> [mildom] add support for mildom.com

- youtube_dlc/downloader/__init__.py
- youtube_dlc/downloader/dash.py
- youtube_dlc/downloader/external.py
- youtube_dlc/downloader/fragment.py
- youtube_dlc/downloader/hls.py
---
Adds support for aria2c threaded downloading for HLS and MPEG-DASH extractors.
Examples:
https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8
https://dash.akamaized.net/dash264/TestCases/1c/qualcomm/2/MultiRate.mpd
> Aria2c support for MPEG-DASH and HLS

- youtube_dlc/downloader/external.py
---
---
Fixes #71 and makes file concatenation consistent. Removes shutil dependency.
> Aria2c bug fix (Fixes #71)

- .github/workflows/build.yml
- README.md
- pyinst.py
- requirements.txt
- setup.py
---
---
Fixes crypto support in binaries. (Closes #74)
> Fix crypto support (Closes #74)

- README.md
- youtube_dlc/YoutubeDL.py
- youtube_dlc/__init__.py
- youtube_dlc/downloader/f4m.py
- youtube_dlc/downloader/hls.py
- youtube_dlc/extractor/brightcove.py
- youtube_dlc/extractor/ceskatelevize.py
- youtube_dlc/extractor/common.py
- youtube_dlc/extractor/corus.py
- youtube_dlc/extractor/crackle.py
- youtube_dlc/extractor/globo.py
- youtube_dlc/extractor/hotstar.py
- youtube_dlc/extractor/ivi.py
- youtube_dlc/extractor/kaltura.py
- youtube_dlc/extractor/limelight.py
- youtube_dlc/extractor/ninecninemedia.py
- youtube_dlc/extractor/ninenow.py
- youtube_dlc/extractor/npo.py
- youtube_dlc/extractor/prosiebensat1.py
- youtube_dlc/extractor/rtbf.py
- youtube_dlc/extractor/ruutu.py
- youtube_dlc/extractor/shahid.py
- youtube_dlc/extractor/sonyliv.py
- youtube_dlc/extractor/toggle.py
- youtube_dlc/extractor/toutv.py
- youtube_dlc/extractor/tvnow.py
- youtube_dlc/extractor/viki.py
- youtube_dlc/extractor/wakanim.py
- youtube_dlc/extractor/youtube.py
- youtube_dlc/options.py
---
---
Adds the --allow-unplayable-formats argument to download unplayable formats.
> Allow downloading of unplayable formats

- .github/workflows/build.yml
- pyinst.py
---
---
Fixes incorrect file hashing in the releases and fixes crypto support on x86.
> Fix GitHub actions hashing and crypto support

- .github/workflows/build.yml
- pyinst.py
- youtube_dlc/update.py
---
---
Implement SHA256 hash checking for autoupdater, fix crypto support
> Implement SHA256 hash checking for autoupdater, fix crypto support

- pyinst.py
Originally in commit 7b400ac40b8e9ce5abaa6d0293fa9d4f017cf1f3 but
lost when make_win.bat was tossed out.
---
---
> pyinst.py: don't use UPX to pack vcruntime140.dll

- .github/workflows/build.yml
---
---
Use python wheels to avoid compilation for GitHub Actions. Python 3.4 support was improved by locking the package versions to officially supported releases.
Hash calculation on Windows now uses PowerShell rather than legacy certutil.
> GitHub Actions release improvements

- youtube_dlc/downloader/hls.py
---
---
Adds basic support for EXT-X-MAP in HLS manifests.
> Basic support for HLS media initialization

- yt_dlp/extractor/viki.py
Revert some recent "new way to..." changes in order to ensure the user's token is used on all API calls.
---
---
Over the last few months there have been several issues related to Viki Pass Plus failures, here and in other related project forks.
I traced through the code a few times and I noticed that after a successful authentication with my credentials that I was then getting the paywall error on the "Downloading video JSON" transaction. After digging into it a bit more I realized that it was due to not passing the user token to that API. Then I …
> [viki] Fix viki play pass authentication

- yt_dlp/extractor/common.py
---
---
Fixes HTTP headers not being passed to HLS playlists. Fixes #125.
> Fix HLS playlist downloading (Fixes #125)

- .gitignore
- MANIFEST.in
- Makefile
- devscripts/release.sh
- setup.py
---
---
* 359d6d8 forgot `setup.py` logic doesn't support globbing for file to install
`MANIFEST.in`:
* 65156eb renamed `ChangeLog` to `Changelog.md`
* 0bc0a32 deleted `AUTHORS`, autogenerate it instead
* b965087 forgot `docs/ytdlp_plugins.md`
* `docs/supportedsites.md` was never packaged
* In general, simplified packaging logic for `docs/`
> Fix packaging bugs

- yt_dlp/extractor/cbs.py
---
---
Adds support for paramountplus.
> [cbs] Add support for ParamountPlus

- yt_dlp/extractor/mxplayer.py
---
---
Allows downloading episodes from mxplayer with the episode url.
> [MXPlayer] Rewrite Extractor

- yt_dlp/extractor/rai.py
---
Raise an error for DRM protected videos before proceding to extract formats.
> [rai] drm check + test

- README.md
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/83
> [Documentation] Inclusion of install two-line script for Unix

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mtv.py
---
**Added support for MTV Italia (mtv.it)**
- MTVItalia: Support for single video
- MTVItaliaProgramma: Support for series/playlist videos
- MTVServicesInfoExtractor: Added series/season_number/episode_number tag extraction
> [mtv] Added support for MTV Italia (mtv.it)

- yt_dlp/YoutubeDL.py
- yt_dlp/downloader/dash.py
- yt_dlp/downloader/external.py
- yt_dlp/downloader/hls.py
---
---
Some changes to the external downloader code to make it more flexible for future changes.
Byteranges are not supported.
> Improve HLS/DASH external downloader code for future support of more downloaders, cleanup code

- supportedsites.md
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/wimtv.py
> [wimtv] add support for wim.tv vod, live and embeds

- .gitignore
- README.md
- yt_dlp/__init__.py
- yt_dlp/downloader/dash.py
- yt_dlp/downloader/external.py
- yt_dlp/downloader/hls.py
- yt_dlp/options.py
---
---
Implements threaded downloading without aria2c.
> [hls, dash] Implement concurrent fragment downloading natively

- yt_dlp/extractor/rcs.py
---
- improved video_data extraction
- added an extra fallback value for 'description'
- improved regex in RCSVariousIE
- updated tests
- added some comment in the code to explain certain things
> [rcs] various fixes

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/stitcher.py
merge stitcher extractor from youtube-dl
(fixes #21)
> [stitcher] merge from youtube-dl

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/la7.py
---
Added support for pages containing podcast both single episode and playlist
> [la7] Add podcast support

- yt_dlp/extractor/dplay.py
- yt_dlp/extractor/extractors.py
TODO:
* Check if it is possible to make this work without cookies
* Write test
> [DiscoveryPlus] Add discoveryplus.in

- yt_dlp/extractor/mildom.py
---
note that I copied the code from [here](https://github.com/nao20010128nao/ytdl-patched/blob/master/youtube_dl/extractor/mildom.py), which is my own work.
---
This PR fixes the extractor to comply with current proxy.
> [mildom] update extractor to comply with current proxy

- yt_dlp/extractor/youtube.py
---
---
As title. Premium label appears as one of the video badges. 
Note: needs testing on an account that has premium.
> [YouTube] Add support for premium availability state in info json

- yt_dlp/extractor/discoveryplusindia.py
- yt_dlp/extractor/dplay.py
- yt_dlp/extractor/extractors.py
---
---
Add supports for downloading all the episodes in all the seasons of a DCVRY+IN show. 
Example url:  https://www.discoveryplus.in/show/how-do-they-do-it
> [DiscoveryPlusIndia] Add DiscoveryPlusIndiaShowIE

- yt_dlp/extractor/nitter.py
---
---
see #215
it may select the wrong tweet and extract totally wrong info.
fixes #215
> [nitter] Fix nitter extractor

- yt_dlp/extractor/youtube.py
---
---
This is an implementation based on https://github.com/ytdl-org/youtube-dl/commit/1b0a13f33cfb3644cc718d35951ea85bb1905459 which fixes https://github.com/ytdl-org/youtube-dl/issues/28702
I've added some improvements (in addition to making it compatible with yt-dlp modifications):
- Generalize the …
> [youtube] Use INNERTUBE_CONTEXT and x-goog-visitor-id header for API requests.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/tubitv.py
---
---
Now supports downloading whole shows from tubitv.com
> [TubiTv]Add TubiTvShowIE.

- yt_dlp/extractor/youtube.py
---
---
Potential fix for https://github.com/ytdl-org/youtube-dl/issues/28697
This method looks for the "show unavailable videos" button, and if present, re-downloads the playlist metadata using the API.
> [youtube:tab] Prefer playlist with unavailable videos

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mxplayer.py
---
---
Added support to use show urls for mxplayer.
> [Mxplayer]Add MxplayerShowIE.

- yt_dlp/extractor/mediasite.py
---
Generalise the URL pattern to cover more sites. This fixes ytdl-org/youtube-dl#25135.
> [mediasite] Generalise the URL pattern

- yt_dlp/downloader/__init__.py
- yt_dlp/downloader/external.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/whowatch.py
---
For note, `whowatch.py` has been taken from https://github.com/nao20010128nao/ytdl-patched/blob/9e4a0e061a558cdb05a618e27f47ca0ac56ece94/youtube_dl/extractor/whowatch.py , which is my own work.
---
This fixes #223. 
Btw I have a question regarding this PR, please check Discord.
> [whowatch] add support for whowatch.tv (closes #223)

- yt_dlp/extractor/sonyliv.py
---
---
Previously it was appending the Series name and Episode title. 
Now title is episode title and series title is separate.
`title = metadata['episodeTitle']` this works for movies as well.
> [SonyLiv]Fix key extraction and add series key.

- yt_dlp/extractor/audius.py
- yt_dlp/extractor/extractors.py
---
---
---
This PR addresses [https://github.com/yt-dlp/yt-dlp/issues/315](https://github.com/yt-dlp/yt-dlp/issues/315), and allows for downloading straight from someone's Audius profile as a playlist.
> [audius] add support for profile pages

- yt_dlp/extractor/youtube.py
---
---
see https://github.com/yt-dlp/yt-dlp/issues/319
> [youtube] add `html5=1` param to `get_video_info` page requests (workaround for #29086)

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/telemundo.py
---
---
---
This PR addresses #284 by adding an info extractor for Telemundo.
> [telemundo] add extractor (#284)

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/sonyliv.py
---
---
Added support to download whole series/shows from sonyliv.
> [SonyLIV] Add SonyLIVSeriesIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/shemaroome.py
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/307
This is a bare bones implementation and can be improved a lot. I'll try to add more features to this in future. 
Also the release date and description searching takes a lot of time (well it's noticeable), i am open to ideas to make it much faster.
> Add ShemarooMeIE.

- yt_dlp/extractor/sonyliv.py
---
---
Adds support for downloading subtitles if any.
> [SonyLIVIE]Add subtitle support.

- yt_dlp/extractor/patreon.py
---
---
Fix vimeo embeds. Closes https://github.com/yt-dlp/yt-dlp/issues/274
> Handle Patreon's vimeo embeds

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/voot.py
---
---
Add support for downloading full shows from voot.com
Removed kids url from VootIE test as voot has long closed that. All the kids shows are now only on their app and even the url pattern is not same. They are also encrypted but still can be downloaded using `voot:id`
> [Voot] Add VootSeriesIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/hotstar.py
---
---
Allows downloading whole show.
> [Hotstar] Add HotStarSeriesIE.

- .github/workflows/build.yml
- yt_dlp/update.py
---
---
SHA256 provided with the release cannot be verified using standard Linux tools:
```bash
$ sha256sum -c SHA2-256SUMS
sha256sum: SHA2-256SUMS: no properly formatted SHA256 checksum lines found
```
The reason is two-fold:
1. `file:hash` is not a standard checksum syntax, `coreutils` understands only GNU `hash  file` or BSD `SHA256(file) = hash` styles.
2. For some reason, `SHA2-256SUMS` has Windows line endings, not Unix ones.
Version line is immaterial and will simply generate a warning:
```
sha256sum: WARNING: 1 line is improperly formatted …
```
> GNU-style release SHA512 sums

- yt_dlp/extractor/youtube.py
---
---
Fix for #393 
Handling of a case where the SAPISID cookie does not exist but __Secure-3PAPISID does. YouTube requires SAPISID cookie for auth requests, so I'm not sure how you would end up without this.
This sets the SAPISID cookie from __Secure-3PAPISID if it didn't already exist. I set the expiry time here to an hour in the future to minimize any issues with it expiring. The better option would be to copy expiry from __Secure-3PAPISID, but not worth the work considering this would be a very rare issue that would only occur a couple years …
> [youtube] Handle case where SAPISID cookie does not exist but  __Secure-3PAPISID does (fixes #393)

- yt_dlp/extractor/yahoo.py
---
---
A quick and dirty fix for https://github.com/ytdl-org/youtube-dl/issues/28290.
This extractor could use more work, as many of the tests and logic are outdated, but this fixes the most pressing breakage for now.
Example videos fixed with this patch:
```
https://www.yahoo.com/entertainment/vin-diesel-the-rock-fast-and-furious-feud-143355696.html
https://au.news.yahoo.com/david-suzuki-rates-planets-chances-survival-060127745.html
https://www.yahoo.com/money/house-passes-biden-relief-package-including-stimulus-checks-070640949.html
```
> Fix yahoo extraction

- yt_dlp/extractor/youtube.py
---
---
Fixes bug in https://github.com/yt-dlp/yt-dlp/issues/439 where `browse` is incorrectly assumed to always be a dict. I'm not sure why it was a list in this case, but the continuation contents does not seem present.
I also added some basic handling for where some other errors may show up & added …
> [youtube:comments] Fix error handling & add itct to params

- yt_dlp/extractor/videa.py
---
---
Fixed the Videa extractor, as it seems the parameter that looks like `?f=8.1735598.2138180.0` is now required for two requests. It's extracted automatically from the page.
See ytdl-org/youtube-dl#29067
> [videa] Fix extraction

- yt_dlp/extractor/adobepass.py
Added Spectrum AP-mso, credit to Kevinoconnor7:  
https://github.com/ytdl-org/youtube-dl/pull/26792
---
---
Spectrum Seems to have updated their AP-MSO, as it's been broken for quite sometime now.  Thanks to Kevinoconnor7's PR over at ytdl-org, this fixes the issue and once again allows users to login via their Spectrum account.
> Add Spectrum Adobe MSO - Credit to Kevinoconnor7

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/fancode.py
---
---
Adds support for fancode live streams, and fixes vod extraction (brightcove user id is no longer available in the file name).
Since it uses openid to login, use `refresh` as the username and the `__refreshToken` as the password to login instead.
> [fancode] support fancodeLive and fixes

- README.md
- yt_dlp/extractor/viki.py
- yt_dlp/extractor/viu.py
---
---
Since viki updated all content to DRM, I found a way to find the non drm content. and I've updated all api and fixed some little bugs.
> [VIKI] Api updated and fixed all bugs

- yt_dlp/extractor/youtube.py
---
---
Fixes #506 
Adds support to parse vote counts in forms such as "200K".
> [youtube:comments] Improve vote count parsing

- yt_dlp/extractor/youtube.py
> [youtube] Fix session index extraction and headers for non-web player clients

- yt_dlp/extractor/youtube.py
---
---
Just doing some cleanup. Removing unused/duplicate code etc (feel free to suggest any)
- update some `extract_response` calls to keep them consistent
- cleanup continuation extraction related code (use new API format)
- improve data sync id function to support multiple parameters (why not)
- put get_text related functions into one
- update INNERTUBE_CONTEXT_CLIENT_NAME with integer values
> [youtube] misc cleanup and bug fixes

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/pornflip.py
---
---
Add extractor for [pornflip.com](https://www.pornflip.com) videos.
> [pornflip] Add new extractor

- yt_dlp/extractor/youtube.py
---
---
Fixes issue reported here: https://github.com/yt-dlp/yt-dlp/issues/511#issuecomment-883024350
`contentCheckOk` appears to be the API equivalent to providing the `bpctr` parameter (found using TV interface).
> [youtube] Fix controversial videos not working when requested via API

- README.md
- yt_dlp/downloader/youtube_live_chat.py
- yt_dlp/extractor/youtube.py
- yt_dlp/utils.py
Review and more testing needed
@colethedj 
TODO:
> [youtube] Extract data from multiple clients

- yt_dlp/extractor/youtube.py
---
---
adds debug message when extracting sapisid cookie
> [youtube] Add debug message for SAPISID cookie extraction

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/utreon.py
---
---
https://github.com/ytdl-org/youtube-dl/issues/29594
> Add UtreonIE.

- yt_dlp/extractor/hotstar.py
---
---
Fixed regex.
Note: Removing `$` ensures that urls with refs are also matched.
> [HotStarSeriesIE]Fix regex.

- README.md
- yt_dlp/extractor/youtube.py
---
---
Adds MWEB (mobile web) client.
There is no known embedded equivalent. 
Found by @Zirro:
On some videos this client include formats 597, 598, 599 and 600.
They represent two 15fps 144p mp4/webm videos, and two m4a/opus audios with the quality labeled as 'ULTRALOW'
> [youtube] Add MWEB client

- yt_dlp/extractor/discoveryplusindia.py
- yt_dlp/extractor/dplay.py
- yt_dlp/extractor/extractors.py
---
---
Sciencechannel.com updated their site to be more like discoveryplus.com. So I went and added it to the dplay extractor so it functions just like downloading from Discoveryplus.com.
> Science channel update

- yt_dlp/extractor/hotstar.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/583
removed `_generate_device_id()` as it wasn't being used
> [HotStarIE]Add cookies support.

- yt_dlp/extractor/vidio.py
---
---
Fixes login errors not getting caught with the new UI interface. Also adds custom login error due to social media linkage (which isn't supported yet)
> [Vidio] Fix login error detection

- yt_dlp/extractor/adobepass.py
…dlp#300)
---
Add support for Sling TV MSO to Adobepass. Duplicate of PR submitted to youtube-dl.
Tested with http://stream.nbcolympics.com/2018-winter-olympics-nbcsn-evening-feb-8
> [adobepass] Add support for Sling TV (mso slingtv) (closes yt-dlp/yt-dlp#300

- yt_dlp/extractor/cbs.py
- yt_dlp/extractor/extractors.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/602
> Add ParamountPlusSeriesIE.

- yt_dlp/extractor/vimeo.py
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/597
> [VimeoIE]Add support to download original file.

- yt_dlp/extractor/vine.py
---
---
Fix 403 Error on some vines.
> [Vine] Fix 403 Error on some vines

- yt_dlp/extractor/canvas.py
Cherry picked from https://github.com/ytdl-org/youtube-dl/pull/29614
---
---
vrt.nu has login issues. It was recently fixed by @pgaig for youtube-dl. Original PR: https://github.com/ytdl-org/youtube-dl/pull/29614
I simply applied those fixes onto the yt-dlp repo. 
Tested by myself and I can confirm it is working.
> [VrtNU] Fix XSRF token

- yt_dlp/extractor/nbc.py
---
Update the NBC Olympics extractor to work with latest formats.
> [nbcolympics] update extractor for 2020 olympics (fixes a secondary bug discussed in #617 but does not close)

- README.md
- yt_dlp/extractor/canvas.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rcti.py
---
---
Adds support for live/missed events, and TV (live events but with their own section + they presumably run forever)
Also fixes regex matching for series, adds basic geoblock detection, and fixes `live_status` docs (as per @pukkandan's request)
> [RCTIPlus] Support events and TV

- yt_dlp/extractor/newgrounds.py
---
---
Fix broken playlist extractor, fix broken test and some improvements.
> [Newgrounds] Improve extractor and fix broken playlist extractor

- yt_dlp/extractor/aenetworks.py
---
Sister commit for PR ytdl-org/youtube-dl#29749.
Updates the key and secret for URL signing.
> [aenetworks] Update _THEPLATFORM_KEY and _THEPLATFORM_SECRET

- yt_dlp/extractor/youtube.py
Signed-off-by: Slava <slash@i-slash.com>
---
---
> [youtube] fix for signature decode function detection

- yt_dlp/extractor/peertube.py
---
---
Fix invalid md5 hash and videos without description
> [peertube] Fix invalid md5 hash and videos without description

- yt_dlp/extractor/hotstar.py
---
---
Should not result in timeout/blocks when downloading big series.
> [HotStar]Rewrite HotStarIE to use API.

- .github/workflows/build.yml
> Github Actions: Use custom pyinstaller wheel from yt-dlp/pyinstaller-builds

- yt_dlp/extractor/blackboardcollaborate.py
- yt_dlp/extractor/extractors.py
---
---
Add extractor for Blackboard Collaborate session videos.
Should fix #642.
> [blackboardcollaborate] Add new extractor

- yt_dlp/extractor/eroprofile.py
- yt_dlp/extractor/extractors.py
---
This adds an album extractor to adult website EroProfile.
I don't think it needs to handle authentication, as each video should handle logging in on its own.
> [eroprofile] Add album downloader

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/filmmodu.py
---
---
Adding new extractor to download movies from [filmmodu.org](https://www.filmmodu.org/).
Should fix #288.
> [filmmodu] Add new extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/voicy.py
---
Note that the code is taken from [my fork](https://github.com/ytdl-patched/ytdl-patched/blob/ytdlp/yt_dlp/extractor/voicy.py), which is my own work.
---
This PR adds support for voicy.jp, which is a podcast service in Japan.
example URL for single podcast: https://voicy.jp/channel/1253/122754
example URL for user: https://voicy.jp/channel/1253
note that the service serves each tracks (chapters) as a separated file, so all extractor always return playlist.
> [voicy] add support for voicy.jp

- yt_dlp/downloader/hls.py
RFC 8216 §3.5 warns us of the possibility of overflow in MPEG timestamps.  We try to address this warning by checking the MPEG timestamp value in the X-TIMESTAMP-MAP header against the values found in earlier segments.  If a segment appears with an MPEG timestamp lower than those found before, we treat this as overflow condition
and perform an appropriate fixup.  This would have worked well, if it weren’t for the fact that in some streams empty segments may appear with a bogus, non-monotone MPEG timestamp.  This has been observed in the wild; see <https://www.byutv.org/player/037d9221-8799-4508-8a00-d218c6df052b/dwight-in-shining-armor-fancy-pants>.
Perhaps it might be prudent to remove the overflow handling entirely, given how vanishingly rare this case is expected to be.  It does seem …
> Fix timestamp overflow adjustment in WebVTT segments

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/pornhub.py
---
---
Current extractor that handle playlists is broken (only for playlists), i think a new one would be better rather than fixing current one because playlist pagination through url param (`?page=N`) no longer works.
Should fix #680.
> [pornhub] Add playlist extractor

- yt_dlp/extractor/paramountplus.py
> [ParamountPlus] Fix geo verification proxy (Closes #681)

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/hungama.py
---
---
Site changed how music is served.
> Fix HungamaSongIE and Add HungamaAlbumPlaylistIE.

- yt_dlp/extractor/bilibili.py
- yt_dlp/extractor/extractors.py
---
---
This adds an extractor to match URLs like https://www.bilibili.com/v/kichiku/mad , predefined categories on Bilibili, and download all videos.
> [bilibili] Category Extractor

- yt_dlp/extractor/bannedvideo.py
- yt_dlp/extractor/extractors.py
---
PR to add support for BannedVideo, as requested by @loveriusa here: https://github.com/yt-dlp/yt-dlp/issues/669
Original author @smege1001
Original pull request for Youtube-dl: https://github.com/ytdl-org/youtube-dl/pull/24572
> [BannedVideo] Add Extractor

- yt_dlp/extractor/zee5.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/728
> Fix Zee5IE and also add Subtitles extraction.

- yt_dlp/extractor/hearthisat.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/740
> [HearThisAtIE] Fix extractor.

- yt_dlp/extractor/tv5mondeplus.py
---
---
tv5monde has changed a bit its json format, now only one url, without files.
Issue URL: https://github.com/ytdl-org/youtube-dl/issues/29097
search duration in content metadata, and update test URLs
> [tv5mondeplus] fix download after json format change

- yt_dlp/extractor/youtube.py
> [youtube] add av01 itags

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/brightcove.py
- yt_dlp/extractor/ceskatelevize.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/corus.py
- yt_dlp/extractor/crackle.py
- yt_dlp/extractor/globo.py
- yt_dlp/extractor/hotstar.py
- yt_dlp/extractor/ninecninemedia.py
- yt_dlp/extractor/ninenow.py
- yt_dlp/extractor/npo.py
- yt_dlp/extractor/prosiebensat1.py
- yt_dlp/extractor/rai.py
- yt_dlp/extractor/ruutu.py
- yt_dlp/extractor/shahid.py
- yt_dlp/extractor/sonyliv.py
- yt_dlp/extractor/toggle.py
- yt_dlp/extractor/tv2.py
- yt_dlp/extractor/vidio.py
- yt_dlp/extractor/wakanim.py
- yt_dlp/extractor/wat.py
- yt_dlp/extractor/youtube.py
- yt_dlp/options.py
> [extractor] Better error message for DRM

- yt_dlp/extractor/aljazeera.py
---
---
Simple change, fixes https://github.com/yt-dlp/yt-dlp/issues/762
> [AlJazeera] Fix extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gab.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/499
> Add GabTVIE.

- yt_dlp/extractor/iwara.py
---
---
Added thumbnail extraction for iwara
> [iwara] Add thumbnail extraction

- yt_dlp/extractor/epicon.py
- yt_dlp/extractor/extractors.py
---
---
related : https://github.com/ytdl-org/youtube-dl/issues/28240
Also yes this is the most stable way i could come up with to get a clean title
` title = self._og_search_title(webpage).replace('Short Film ', '').replace('Watch ', '').replace(' |', '').replace(' Online at EPIC ON', '').replace(' Online On EPIC ON', '')`
> Add EpiconIE and EpiconSeriesIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/projectveritas.py
---
---
Related: https://github.com/ytdl-org/youtube-dl/issues/26749
> Add ProjectVeritasIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/tv2hu.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/799
Note to users: use with brains, if provided the show url in the form `https://tv2play.hu/<show name>` for example `https://tv2play.hu/mintaapak`
It will download all clips, full episodes, extra videos, etc.
Therefore u might trigger some sort of limits.
Also this is added `raise ExtractorError('Incorrect URL.', expected=True)` to not give useless error. The site might have more that videos and shows (maybe broadcasts, music, etc) for which support can be added in future if an issue is …
> Add TV2HuSeriesIE and fix TV2HuIE.

- yt_dlp/extractor/atvat.py
---
---
Upstream PR: https://github.com/ytdl-org/youtube-dl/pull/29083 by @NeroBurner 
+ did some cleanup.
Fixes https://github.com/ytdl-org/youtube-dl/issues/29079
Note: Geo-restricted to Austria
> [ATV.at] Fix extractor for ATV.at

- yt_dlp/extractor/motherless.py
---
---
Fixes #806 and https://github.com/ytdl-org/youtube-dl/issues/29626. The group extractor also appeared to be broken so I fixed that.
My regex skills ain't great so feel free to suggest improvements.
> [Motherless] Fix extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/startv.py
---
---
Original PR: https://github.com/ytdl-org/youtube-dl/pull/24382 by @mrfade
I made some minor modifications for future error handling.
I notice there is a fair few "star tv" sites around. Maybe this would be better named "StarTVTR"?
Note: this site appears to have intermittent back-end issues
> [StarTV] Add extractor for startv.com.tr

- yt_dlp/extractor/cda.py
---
---
Fix videos defaulting to 480p fix #791 , fix https://github.com/ytdl-org/youtube-dl/issues/29844.
With current master
```
$ yt-dlp -F https://www.cda.pl/video/5739761ed          
[CDA] 5739761ed: Downloading webpage
[info] Available formats for 5739761ed:
ID EXT RESOLUTION | PROTO | VCODEC  ACODEC
-- --- ---------- - ----- - ------- -------
0  mp4 unknown    | https | unknown unknown
```
With my commits
```
$ yt-dlp -F https://www.cda.pl/video/5739761ed 
[CDA] 5739761ed: Downloading webpage
[CDA] 5739761ed: Fetching 360p url
[CDA] …
```
> [CDA] Fix download only video with default quality

- .github/workflows/build.yml
- README.md
- devscripts/update-formulae.py
---
---
This PR provides automated update for yt-dlp Homebrew formulae, and guide for installation in README.
For users using macOS, please try running `brew install yt-dlp/taps/yt-dlp` and let me know if it works. Thanks
**edit:** got report that installation on macOS was successful. thanks @gaato
~~@pukkandan Can you please create a new PAT and add it to secrets as `GH_TOKEN`? it is required to update `homebrew-taps` repository.
This PR is in draft state until PAT is ready.~~
> Homebrew support

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/tokentube.py
---
---
Adds `TokentubeIE` and `TokentubeChannelIE` closes #800.
> [Tokentube] Add extractor

- yt_dlp/extractor/mediaset.py
---
---
This should fix the geo-restriction error in #851 happening even when you're using an Italian residential IP.
> [mediaset] Fix extraction for more videos

- yt_dlp/extractor/reddit.py
---
---
Some subreddits are quarantined which prevents yt-dlp from fetching the JSON metadata. This PR adds a cookie that fixes this. There isn't any check for if the subreddit is quarantined before adding the cookie but having it present anyways doesn't appear to cause any issues in my testing. Some quarantined subreddits will still fail with this if reddit requires an account with a verified email.
Example link: https://www.reddit.com/r/NoNewNormal/comments/kxc8s7/video_from_2020_spring_this_one_aged_like_fine/
> [reddit] Fix for quarantined subreddits

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/ichinanalive.py
---
I'm going to omit source of the code from this time, if it is taken from my fork.
---
This adds support for 17.live. Not geo-restricted.
example live URL: https://17.live/live/377650
example clip URL: https://17.live/profile/r/1789280/clip/1bHQSK8KUieruFXaCH4A4upCzlN
> [17live] add support for 17.live

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mediaklikk.py
- yt_dlp/utils.py
---
---
Adds extractor for mediaklikk.hu, hirado.hu, petofilive.hu and m4sport.hu
This PR is derived from https://github.com/ytdl-org/youtube-dl/pull/25098 by @mrx23dot, which in turn is derived from https://github.com/ytdl-org/youtube-dl/pull/17453 by @tmarki
Upstream request: resolves https://github.com/ytdl-org/youtube-dl/issues/21431
> MédiaKlikk is the free VOD video platform of MTVA.
MTVA (Media Services and Support Trust Fund) is Hungary's state-owned national public-service broadcasting organization, and it's the successor of MTV (state …
> [Mediaklikk] Add Extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gotostage.py
---
---
GoToStage is platform for recordings of Webinars. I added an extractor to download a video.
There is a [page for all videos](https://www.gotostage.com/). I used a [specific video](https://www.gotostage.com/channel/8901680603948959494/recording/60bb55548d434f21b9ce4f0e225c4895/watch) for testing.
> [extractor/gotostage] Add GoToStage extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/yandexvideo.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/885
> Add ZenYandexIE and ZenYandexChannelIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/olympics.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/897
> Add OlympicsReplayIE.

- test/test_subtitles.py
- yt_dlp/extractor/pbs.py
---
---
Original PR:  https://github.com/ytdl-org/youtube-dl/pull/24430 by @gesa
I added tests from https://github.com/ytdl-org/youtube-dl/pull/17434, which is an older PR for adding subtitles.
Fixes: https://github.com/ytdl-org/youtube-dl/issues/18796, https://github.com/ytdl-org/youtube-dl/issues/17273 I suppose too?
> [pbs] Fix subtitle extraction

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nzherald.py
- yt_dlp/extractor/tiktok.py
---
---
This adds supports for videos on nzherald.co.nz (NZ news site)
Upstream request: resolves https://github.com/ytdl-org/youtube-dl/issues/28267
They use Brightcove so this extractor redirects to that once we extract the relevant player url.
From my testing there are at least two page formats for videos:
- video embedded in article
- dedicated video page
~~I notice a few other similar extractors hard code the Brightcove player and account ids. Might be a bit overkill but I've added them as a fallback here and opted to try extract them first~~ …
> [nzherald] Add NZHeraldIE

- yt_dlp/webvtt.py
Closes #921 
See the issue for details/discussion
> [WebVTT] Fix parser for PBS

- yt_dlp/extractor/zype.py
> [zype] Extract subtitles from the m3u8 manifest

- yt_dlp/extractor/bilibili.py
- yt_dlp/extractor/extractors.py
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/879 and https://github.com/yt-dlp/yt-dlp/issues/611
> Add BiliIntlIE and BiliIntlSeriesIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/newgrounds.py
> [Newgrounds] Add NewgroundsUser and improve extractor

- yt_dlp/extractor/itv.py
---
---
From Upstream PR: https://github.com/ytdl-org/youtube-dl/pull/28955 by @sleaux-meaux, with help from @Vangelis66 (https://github.com/ytdl-org/youtube-dl/issues/28906#issuecomment-831008270).
I also cleaned up a couple things and added support for extracting subtitles from m3u8 data, if they exist.
Fixes https://github.com/yt-dlp/yt-dlp/issues/861, fixes https://github.com/ytdl-org/youtube-dl/issues/28906, fixes https://github.com/ytdl-org/youtube-dl/issues/29337, fixes https://github.com/ytdl-org/youtube-dl/issues/29190, fixes …
> [ITV] Fix Extractor

- yt_dlp/extractor/fancode.py
---
---
Fix the issue where it falsely detects stream as offline until the toss happens. 
Credit to @m3jorri for finding this bug and the fix for it.
> [Fancode] fix live streams

- .gitignore
- Makefile
This allows removing artefacts in `test/` by running `git clean -f test`
Imho, 337e0c62f894722e9c268b14d02a85b84c96024d should be seriously reconsidered.
Ignored artefacts are starting to appear in root as well for me.
Originally this has to do something with #352, but tl;dr... sorry.
> [dont-ignore-me] Fix allows clean

- yt_dlp/extractor/mxplayer.py
---
---
More reliable h265 formats and now subs aswell.
> Rewrite MxplayerIE to use mobile api.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/radlive.py
---
---
Implemented extractor for https://rad.live/.
Closes #312.
> [radlive] Add new extractor

- yt_dlp/extractor/hidive.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/952 and maybe https://github.com/yt-dlp/yt-dlp/issues/408 aswell
> Fix HiDiveIE.

- yt_dlp/extractor/globo.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/991
> Fix GloboIE.

- yt_dlp/extractor/ndr.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/959
> Rewrite NDRIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/mediaite.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/969
> Add  MediaiteIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/streamanity.py
---
---
Added Streamanity support
> Streamanity extractor

- yt_dlp/extractor/cam4.py
- yt_dlp/extractor/extractors.py
---
---
Added support for CAM4
> Added CAM4 extractor

- yt_dlp/extractor/itv.py
---
---
Bug fix for https://github.com/yt-dlp/yt-dlp/issues/986
@sleaux-meaux if you can confirm this fixes the issue that would be great thanks.
> [itv] Prefer last matching featureset

- yt_dlp/extractor/damtomo.py
- yt_dlp/extractor/extractors.py
---
---
Damtomo is a service to expose users' singing scenes.
example video url: https://www.clubdam.com/app/damtomo/karaokeMovie/StreamingDkm.do?karaokeMovieId=2414316
example record url: https://www.clubdam.com/app/damtomo/karaokePost/StreamingKrk.do?karaokeContributeId=27376862
> [damtomo] add support for Damtomo service

- yt_dlp/extractor/safari.py
> [Oreilly] update the web url to match the new location

- yt_dlp/extractor/cgtn.py
- yt_dlp/extractor/extractors.py
- yt_dlp/utils.py
> [CGTN] Add new extractor

- yt_dlp/extractor/nuvid.py
---
---
Fix https://github.com/ytdl-org/youtube-dl/issues/29886.
> [Nuvid] Fix extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/peertube.py
> [Peertube] Add Channel extractor

- yt_dlp/extractor/dplay.py
- yt_dlp/extractor/extractors.py
---
---
AnimalPlanet.com changed their website to reflect something more akin to DiscoveryPlus.com
I was going to try and make changes to dplay.py to encompass all of their affiliates once they changed over to the new design, but still haven't had time. But this should take care of AnimalPlanet at least in the mean time.
> AnimalPlanet Update

- yt_dlp/extractor/comedycentral.py
---
Add support for extra urls to the comedycentral extractor:
eg: https://www.cc.com/collection-playlist/cosnej/stand-up-specials/t6vtjb
> [comedycentral] added 'collection-playlist' in _VALID_URL

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/hotstar.py
---
---
Add ref to HSIE to download subs 
`Note: /in is important`
Modifications in `YoutubeDL.py` by pukkandan
> Add referer to HotstarIE for subs.

- yt_dlp/downloader/niconico.py
> [downloader/niconico] pass proxy for heartbeat (#1057)

- yt_dlp/extractor/chingari.py
- yt_dlp/extractor/extractors.py
> Add ChingariIE and ChingariUserIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/koo.py
---
---
https://www.kooapp.com/
> Add KooIE.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/theta.py
---
---
Added Theta stream extractor
> Add Theta stream extractor

- yt_dlp/extractor/spankbang.py
---
---
Fixes https://github.com/yt-dlp/yt-dlp/issues/833 by extracting the correct `uploader`.
Also adds the `uploader_id`.
> Fix SpankBang uploader and uploader_id

- yt_dlp/extractor/newgrounds.py
> [Newgrounds] Fix view count on songs

- yt_dlp/extractor/linkedin.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1072
> Add subtitles to LinkedInLearningIE.

- yt_dlp/cookies.py
---
A fix for https://github.com/yt-dlp/yt-dlp/issues/1073
when the `keyring` package is not installed on MacOS, the built in `security find-generic-password ...` command is used to obtain the password that the browser uses to encrypt cookies. There was a problem with this fallback implementation where the returned password has a newline at the end which causes decryption with the password to fail.
> fixed find-generic-password method of obtaining keyring password

- yt_dlp/extractor/polskieradio.py
---
---
Code taken from https://github.com/ytdl-org/youtube-dl/pull/26069, Fix #1033
> Fix PolskieRadio and PolskieRadioCategory

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/veo.py
---
---
https://github.com/ytdl-org/youtube-dl/issues/29445
> [Veo] Add new extractor

- yt_dlp/extractor/reddit.py
> [reddit] Add support for embedded urls

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/n1.py
> [N1] Add extractor

- yt_dlp/extractor/linkedin.py
> [LinkedInLearningIE] Fix newline bug in subtitles

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gettr.py
---
---
(closes https://github.com/ytdl-org/youtube-dl/issues/29589)
> [Gettr] Add new extractor

- yt_dlp/extractor/adobepass.py
Add MSO support for RCN
---
---
Added RCN authentication field names to MSO section in adobepass extractor. No other changes are needed to allow logging in through the RCN site. No other test coverage should be needed.
> Add MSO support for RCN

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/theta.py
---
---
Added Theta video extractor
> Add Theta video extractor

- yt_dlp/aes.py
---
It's about 70% faster, meaning time needed is reduced by this amount.
> [aes-generator] Boost performance slightly

- yt_dlp/extractor/adobepass.py
- yt_dlp/extractor/bilibili.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1015, code taken from https://github.com/y2361547758/bcc2ass.
> [Bilibili] Add subtitle converter

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/vupload.py
---
---
Fix https://github.com/ytdl-org/youtube-dl/issues/29877
> [Vupload] Add extractor

- yt_dlp/extractor/newgrounds.py
> [Newgrounds] Add age_limit and fix duration

- yt_dlp/extractor/parliamentliveuk.py
> [parliamentlive.tv] Fix extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gopro.py
---
---
(Fixes https://github.com/ytdl-org/youtube-dl/issues/30044)
> [GoPro] Add extractor

- yt_dlp/extractor/mediaite.py
---
---
Adds support for `news` category. Closes https://github.com/yt-dlp/yt-dlp/issues/1131
But I am in support for relaxing the regex altogether - just from a quick look at the sitemap I can find many more categories (e.g. look at https://www.mediaite.com/post_part1.xml)
Maybe something like: …
> [Mediaite] Add support for more categories

- .github/workflows/build.yml
- .github/workflows/quick-test.yml
- README.md
- pyinst.py
---
---
Use pycryptodomex instead of pycryptodome for PyInstaller builds.
> Use pycryptodomex for PyInstaller

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mediaset.py
- [ x At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
---
Add playlist support to the Mediaset extractor as requested in #1372
> [mediaset] Added playlist support

- yt_dlp/extractor/naver.py
- yt_dlp/extractor/vlive.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1472
> [VLive] Add upload_date and thumbnail

- yt_dlp/extractor/ceskatelevize.py
- yt_dlp/extractor/extractors.py
---
---
Videos for https://www.ceskatelevize.cz/ are currently broken.
The problem was already reported for youtube-dl and the fix is fairly easy.
> [ceskatelevize] Fix request url 

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/planetmarathi.py
---
---
Use this extractor only if u have read the readme.
> [PlanetMarathi] Add extractor

- yt_dlp/extractor/olympics.py
> [Olympics] Fix extractor

- yt_dlp/extractor/vk.py
---
---
You can download subtitles for videos from vk.com.
> [vk] subtitles support added

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/radiokapital.py
- yt_dlp/extractor/tvp.py
- yt_dlp/extractor/wppilot.py
radiokapital extractors## Please follow the guide below
---
---
> haruhi-dl backports, batch 2

- yt_dlp/extractor/vk.py
---
---
Fix login page. Close #1459
> [vk] login fix

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/n1.py
> [N1] Add support for nova.rs

- yt_dlp/extractor/vupload.py
> [Vupload] Fix extractor

- yt_dlp/extractor/newgrounds.py
> [Newgrounds] Fix description

- yt_dlp/extractor/imdb.py
---
---
---
The IMDB extractor wasn't returning any thumbnails so I took a look and can see that we are `try_get`ing off the wrong hash. Should be `info` (like all the attribute lookups) and not `video_metadata`.
Simple.
> [IMDB] Thumbnail lookup fix

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gab.py
> [Gab] Add extractor

- yt_dlp/extractor/iprima.py
---
---
A quick fix for the change of parameter required for successful login. I will investigate further to see if there is an underlying cause for this and if similar failures could be prevented in the future.
> [iPrima] Fix redirect uri

- yt_dlp/extractor/tokentube.py
> [Tokentube] Fix description

- yt_dlp/extractor/roosterteeth.py
---
---
Works around big seasons not getting extracted by inflating per_page count (like the site does)
Probably not the smartest idea tho
> [RoosterTeethSeries] (Hacky) fix for not extracting all videos

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/onefootball.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1598
> [OneFootball] Add extractor

- yt_dlp/extractor/espn.py
- yt_dlp/extractor/extractors.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1635
> [ESPNCricInfo] Add extractor.

- yt_dlp/extractor/amazon.py
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/1698
> [AmazonStoreIE] Fix regex to not match vdp urls

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/peertv.py
> [peer.tv] Add extractor

- yt_dlp/extractor/canvas.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mixch.py
---
---
This PR adds support for mixch.tv which is a streaming service in Japan.
Live URL: https://mixch.tv/u/16236849/live
(you can find another one here: https://mixch.tv/)
upstream issue:
- ytdl-org/youtube-dl#28727
> [mixch] add support for mixch.tv

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/linkedin.py
> [LinkedIn] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rtrfm.py
---
---
Downloads audio from the RTRFM radio station using their restreaming infrastructure. The test cases pass, except for the old one which expired and the show page, which has an id which changes daily and of course the downloaded file changes daily so the md5 cannot be checked.
> [rtrfm] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/stripchat.py
---
---
Adds extractor for the webcam site, https://stripchat.com/
> [Stripchat] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/reddit.py
---
---
Basically, the problem is that Reddit does not provide all formats when requesting with the base DASH and HLS playlist urls (e.g., https://v.redd.it/33hgok7dfbz71/DASHPlaylist.mpd). To fix this, certain query parameters must be attached to it, which must be obtained from the video page itself. Although this requires an additional request, it is well-justified as now one can download 1080p videos (i.e., highest quality)
I am quite surprised this wasn't fixed earlier, seeing that Reddit is quite a popular platform.
BEFORE:
```
$ python -m …
```
> [Reddit] Add support for 1080p videos

- yt_dlp/extractor/vidlii.py
---
---
Adds 720p (partner resolution) support for VidLii videos.
> [VidLii] Add 720p support

- supportedsites.md
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/willow.py
---
---
Extractor for willow.tv, which has both free and subscriber-only content. Only support for free videos was added as I am not a paid subscriber.
> [willow] new extractor

- yt_dlp/extractor/cozytv.py
- yt_dlp/extractor/extractors.py
---
---
CozyTV (https://cozy.tv/) is a live streaming site for american neo-nazis, criminals, "terrorists" and "degenerates".
> [CozyTV] Add extractor

- yt_dlp/extractor/xvideos.py
---
---
Support default URL for embeds
> [xvideos] fix embed videos detection

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/streamff.py
> Streamff extractor

- yt_dlp/extractor/breitbart.py
- yt_dlp/extractor/extractors.py
---
Support of breitbart.com website links. Examples of links:
https://www.breitbart.com/videos/v/eaiZjVOn/
https://www.breitbart.com/videos/v/5cOz1yup/?pl=Ij6NDOji
> [extractor/breitbart] Breitbart.com website support

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/ninecninemedia.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1768
> [CPTwentyFour] Add extractor

- yt_dlp/extractor/xvideos.py
---
---
Fixed an extractor bug where it does not consider the display id portion of the url when downloading the webpage
https://github.com/yt-dlp/yt-dlp/issues/1788
> [xvideos] extractor fix

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/redgifs.py
---
- There is another RedGifs extractor here #1631, but that's pages, rather than searches. But there will be merge conflicts with this due to filename. I'm happy to either rename file, or wait until that one is merged and resolve conflicts!
---
I'm adding a playlist extract for RedGifs searches.
There's another PR Ive noted above, #1631 which does redgifs pages. I'm happy to resolve merge conflicts if that goes in first, and neaten things up. Or to move this to a different file to avoid conflicts. I'm open to your suggestion there.
I wasn't sure …
> [RedGifsSearch] Add RedGifs search (and user) extractor

- yt_dlp/extractor/trovo.py
---
---
Fixes #1782 by adding an `Accept` header on the GraphQL request to make the site return JSON instead of HTML.
> [trovo] Fix extraction

- yt_dlp/extractor/amazon.py
- yt_dlp/extractor/canalalpha.py
- yt_dlp/extractor/chingari.py
- yt_dlp/extractor/cozytv.py
- yt_dlp/extractor/epicon.py
- yt_dlp/extractor/euscreen.py
- yt_dlp/extractor/gab.py
- yt_dlp/extractor/gronkh.py
- yt_dlp/extractor/hotstar.py
- yt_dlp/extractor/koo.py
- yt_dlp/extractor/mlssoccer.py
- yt_dlp/extractor/musescore.py
- yt_dlp/extractor/mxplayer.py
- yt_dlp/extractor/onefootball.py
- yt_dlp/extractor/planetmarathi.py
- yt_dlp/extractor/projectveritas.py
- yt_dlp/extractor/shemaroome.py
- yt_dlp/extractor/skynewsau.py
- yt_dlp/extractor/threespeak.py
- yt_dlp/extractor/utreon.py
- yt_dlp/extractor/voot.py
- yt_dlp/extractor/zee5.py
---
---
@nao20010128nao can u take a look at these please?
> [CleanUp] Clean regexes

- yt_dlp/extractor/cableav.py
- yt_dlp/extractor/extractors.py
---
---
Extractor for cableav.tv. Seems like the generic extractor gets confused, so a custom one is needed?
> Add CableAV extractor

- yt_dlp/extractor/rai.py
---
- fix #1862
- fix alt_title generation following test failure
- substituted 1080p test with an available url
> [rai] Rainews fix #1862

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/trueid.py
> [TrueID] Add extractor

- yt_dlp/extractor/common.py
- yt_dlp/extractor/ntvcojp.py
---
See https://github.com/ytdl-org/youtube-dl/issues/30309
---
This fixes extractor for cu.ntv.co.jp. Geo-restricted.
closes https://github.com/ytdl-org/youtube-dl/issues/30309
> [ntvcojp] fix extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gofile.py
---
---
An extractor for gofile.io links, this was requested on #1831. It seems to be working, and every run it requests a guest account. So currently there's no support for being logged in and downloading restricted files (not even sure if this exists in this service, not that familiar.) I'm new to contributing to this project so feel free to comment what's up with the code.
When given a link such as "https://gofile.io/d/AMZyDw" as in the test, it downloads all the files available.
> gofile Add extractor

- yt_dlp/extractor/brightcove.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/toggo.py
---
---
Adds support for https://www.toggo.de/.
> [toggo] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rutube.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1966
> [Rutube]Add RutubeChannelIE

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nate.py
---
---
A lot of the code is from https://github.com/ytdl-org/youtube-dl/pull/30330
> [NateTV] Add extractor(s)

- yt_dlp/extractor/sonyliv.py
---
---
Ugly "fix" for https://github.com/yt-dlp/yt-dlp/issues/1945
Edit: thanks to @nyuszika7h for the device id function
> [SonyLiv]Add otp login support

- yt_dlp/extractor/olympics.py
> [olympics] Cleanup

- yt_dlp/extractor/nova.py
---
Another update of NovaEmbed after their recent ad related changes.
> [NovaEmbed] Fix extractor

- yt_dlp/extractor/gronkh.py
---
This PR updates the URL pattern of the gronkh.tv extractor as the website recently changed its URL schema.
The old URL schema is still accepted by the server so I didn't remove it.
Example URL:
https://gronkh.tv/watch/stream/546
> [gronkh] Fix url pattern

- yt_dlp/extractor/audiomack.py
---
---
It resolves an issue filed in yt-dl [#29800](https://github.com/ytdl-org/youtube-dl/pull/29810).
I already submitted a PR there but the project is dormant for a while and yt-dlp looks like a worthy successor.
Co-authored-by: dirkf <fieldhouse@gmx.net>
> [extractor/audiomack] Updated album and song URL regex

- yt_dlp/extractor/lbry.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2054
> [LBRY] Add support for live streams.

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/opencast.py
- yt_dlp/utils.py
Original found at https://github.com/ytdl-org/youtube-dl/pull/26934
Author: C0D3D3V
---
---
[Opencast](https://opencast.org/) is a open source software used  by universities to publish recorded lectures. This allows to download lectures presented by Opencasts' "paella"-player.
> [OpenCast] Add extractor

- yt_dlp/extractor/steam.py
> [Steam] Fix extractor

- README.md
- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gamejolt.py
---
---
Adds extractors for GameJolt posts, along with user, game wall, and community post lists
> [GameJolt] Add extractors

- yt_dlp/extractor/bilibili.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1744
> [BiliIntl] Fix extractor

- yt_dlp/extractor/drooble.py
- yt_dlp/extractor/extractors.py
> [Drooble] Add extractor

- yt_dlp/extractor/bilibili.py
---
---
- Add login
- Properly catch error codes
- Fix videos with "broken" subtitles
> [BiliIntl] Add login + misc improvements

- yt_dlp/extractor/xvideos.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/1823
> [XVideos] Check HLS formats

- yt_dlp/extractor/redbulltv.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2151
> [RedBullTV] Parse subtitles from manifest

- yt_dlp/extractor/zdf.py
---
---
For some shows, ZDF provides chapters in the player. This adds extraction for the chapters, and also fixes some failing tests.
I'm unsure about adding the empty chapter at the start -- see also https://github.com/yt-dlp/yt-dlp/pull/2031#discussion_r777132430
> [zdf] add chapter extraction

- yt_dlp/extractor/dropbox.py
---
---
Adds support for downloading transcoded formats and support for password protected files.
> [Dropbox] Add support for more formats and password protected files

- yt_dlp/extractor/vk.py
---
---
Add support for new list id like in this url https://vk.com/video-93049196_456239755?list=ln-cBjJ7S4jYYx3ADnmDT
> [vk] Add new list id format

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/gfycat.py
---
---
Added support for gfycat embeds
Closes https://github.com/yt-dlp/yt-dlp/issues/2214
> [gfycat] Support Embeds

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/pornez.py
---
- [ x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [x ] I am the original author of this code and I am willing to release it under …
> [Pornez] Add extractor

- yt_dlp/extractor/europeantour.py
- yt_dlp/extractor/extractors.py
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/2208
> Add EuropeanTourIE

- yt_dlp/extractor/vk.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2196
> Fix VKUserVideosIE

- yt_dlp/extractor/nexx.py
---
---
Fixes episode data extraction, added subtitle extraction, added cast extraction (note that I can't find any videos for this yet, so mostly just for futureproofing), fixed API token generation (note that I can't find any videos that require this either), and updated tests to skip spiegel and non-arc …
> [Nexx] Extract more metadata and update tests

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rule34video.py
---
---
Add support for downloading rule34video.com videos (Rule34VideoIE).
This is my first extractor writing, please advise if any improvement is required.
> [Rule34video] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/noodlemagazine.py
---
---
Add extractor for noodlemagazine.com.
> [noodlemagazine] Add extrator

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rai.py
---
add support for raiplaysound.it, single episode and playlists
fixes #1951
Drafted as I still have to check code for live streams.
> [rai] Raiplaysound support, fixes #1951

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/pokergo.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2316
> [PokerGo] Add extractors.

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/glomex.py
---
---
* Use `_merge_subtitles`
* Do not resolve scheme for embedded URLs
* Add comment to test (in `GenericIE`) for `_extract_urls`
> [extractor/glomex] Minor fixes

- yt_dlp/extractor/thisoldhouse.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2341
> Fix ThisOldHouseIE

- yt_dlp/extractor/daftsex.py
- yt_dlp/extractor/extractors.py
> [daftsex] Add new extractors

- yt_dlp/extractor/generic.py
---
---
* Fix generic test for `glomex:embed`: Add missing thumbnail
* Add generic tests for `megatvcom:embed`
> [extractor/generic] Fix/add tests

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mixch.py
---
---
Add support for /archive/ URLs for mixch.tv. Paid video.
Too few fields? I'm serious. (see below)
Closes #2363
> [mixch:archive] add support for /archive/ URLs (closes #2363)

- yt_dlp/extractor/tver.py
> [TVer] extract message for unaired live (closes #2365)

- yt_dlp/extractor/ctvnews.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2370
> [CTVNewsIE] Add fallback for video search

- test/test_subtitles.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/ted.py
---
---
TED has restructured their site and a rewrite for TED extractor is required (#2343).
changes:
- rewrite talks and playlist handling
- added series handling
- removed handling /watch/ urls (was very old code and new watch pages no longer contains a single video as the old extractor expects)
I have used quite a bit of the old parsing code as some of them still matches the new json structure. There are parts of code which I am not sure if they are still necessary with their new player (e.g. audio_download and rtmp source), but since they are …
> [TED] extractor rewrite

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rtnews.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2371
> [RTNews] Add extractor

- yt_dlp/extractor/instagram.py
---
---
This pull request fixes two things:
* Fixes full name extraction for all stories (seems to be no longer available in the story JSON, if it ever was)
* Fixes username extraction for story highlights, where the username is `highlights` and the story JSON only has the user ID.
These require an additional request to the Instagram API with a proper Instagram app user agent. The additional request is only made if either of the fields are missing or the username is `highlights`, just in case the normal JSON still has the proper info in some …
> [instagram] Fix full name extraction for stories, username extraction for highlights

- yt_dlp/extractor/theta.py
---
---
Adjust Theta stream extractor regex to include "-", which is a valid username character on Theta
> Adjust regex of Theta stream extractor

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/iqiyi.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/704
Note: Untested with VIP accounts
> [iq.com] Add extractor

- yt_dlp/extractor/youtube.py
---
---
Extracts channels banners if available. They are set to a lower preference than the channel avatar. Also try get the original/uncropped banner as described in https://github.com/yt-dlp/yt-dlp/issues/2237#issuecomment-1013694714.
Closes https://github.com/yt-dlp/yt-dlp/issues/2237
> [youtube:tab] Extract channel banner

- yt_dlp/extractor/crowdbunker.py
- yt_dlp/extractor/extractors.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2356
> [CrowdBunker] Add extractors

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/lnkgo.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2268
> [LnkIE] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/newsy.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2346
> [Newsy] Add extractor

- yt_dlp/extractor/cam4.py
---
---
Added thumbnail extraction for CAM4
> [CAM4] Add thumbnail extraction

- yt_dlp/extractor/thisoldhouse.py
---
---
https://github.com/yt-dlp/yt-dlp/issues/2443
> [ThisOldHouseIE] Improve Premium URL check

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/musicdex.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/2204
#TODO
Add playlist support (waiting for a url with more ~50 songs)
> [Musicdex] Add extractors

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/vimm.py
---
---
Add Vimm recorded stream extractor
> [Vimm] add recording extractor

- yt_dlp/extractor/iqiyi.py
---
---
Support downloading VIP-restricted videos and formats using cookies (Login request is CAPTCHA'd most of the time)
cc @Sparh4wk
> [iq.com] Add VIP support

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/yandexvideo.py
---
---
Support for videos from yandex video search page. (#1794)
URL examples:
https://yandex.ru/video/preview/?filmId=10682852472978372885&text=summer
https://yandex.ru/video/preview/5275069442094787341
> [YandexVideoPreview] Add extractor for yandex video preview urls

- yt_dlp/extractor/myspass.py
> [MySpass] fix video url processing

- yt_dlp/extractor/odnoklassniki.py
---
---
Fixed URL extraction from embedded players. Sample links:
https://ok.ru/video/3568183087575 -> vk
http://ok.ru/video/1484130554189 -> coub
https://m.ok.ru/video/5377168585 -> pladform -> rutube (require fixes #2550)
https://ok.ru/video/5357900818 -> pladform -> rutube (require fixes  #2550) …
> [Odnoklassniki] Improve embedded players extraction

- yt_dlp/extractor/dplay.py
- yt_dlp/extractor/extractors.py
---
---
Updating the site change for tlc.com to go.tlc.com
> Discovery Affiliates Site Change Update

- yt_dlp/extractor/fc2.py
> [fc2] fix extraction

- yt_dlp/extractor/twitcasting.py
---
---
`--video-password` breaks if the password contains characters outside ASCII and the locale encoding is not UTF-8.
```
[debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
```
> [twitcasting] enforce UTF-8 for POST payload

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mediaset.py
---
as per title if fixes #2149 plus it improved infos extraction making difference from movie to episode
Idea on how to create a non DRM url was found here: https://greasyfork.org/it/scripts/2129-video-mediaset-it-native-video-player-and-direct-links , adapted and simplified. It needs testing before merge.
> [mediaset] fix #2149

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nfb.py
---
---
Added extractor for the National FIlm Board of Canada (https://www.nfb.ca/)
> [nfb] Add extractor

- yt_dlp/extractor/afreecatv.py
---
---
AfreecaTV livestreams may be protected by a password. This PR updates the extractor to support the existing `--video-password` param, and to raise an ExtractorError if no password is provided and the livestream metadata indicates that a password is required.
Due to the temporary nature of livestreams, I don't know if there's a way to meaningfully unit test this; I can at least confirm by manual testing that it:
> [afreecatv] Support password-protected livestreams

- yt_dlp/extractor/beeg.py
---
---
Fixing #2592 
Removed beeg.porn from valid url ( this domain doesn't host any video, it only links to others sites)
Removed tests URLs that are using links that returns 404 on browser.
Almost all code was not working, so i rewrote it.
I didn't use extract_m3u8_formats because i can't figured out how to process mp4 extension as m3u8 and generate mp4 file.
If there is a way, or better way, please enlighten me.
> Fixing #2592

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/gettr.py
---
---
Add support for gettr /streaming/ url
(closes #2654)
> [Gettr] Add `GettrStreamingIE`

- yt_dlp/extractor/bigo.py
- yt_dlp/extractor/extractors.py
---
---
Rewrite of #933 as it seems stale
Closes #933 (superseeding)
Closes ytdl-org/youtube-dl#18357
> [bigo] add support for bigo.tv

- yt_dlp/extractor/youtube.py
> [youtube] Ensure subtitle urls are absolute

- yt_dlp/extractor/caltrans.py
- yt_dlp/extractor/extractors.py
---
- [] Improvement
---
Requested in #2775 
California Department of Transportation CCTV
> First version of Caltrans Extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/peekvids.py
> [peekvids] add new extractor

- yt_dlp/extractor/atvat.py
> [ATVAt] Detect georestriction

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/murrtube.py
---
---
Add support for (NSFW) [Murrtube](https://murrtube.net/), a site that hosts furry porn videos.
> [murrtube] Add new extractor

- yt_dlp/extractor/twitcasting.py
---
---
Fixes auth for password-protected live, and deprioritizes WebSocket formats as there's report about 403 error. I couldn't reproduce 403 error but there's no reason for WS to be preferred over HLS too.
> [twitcasting] Fix extraction

- yt_dlp/extractor/peekvids.py
> [peekvids] use JSON-LD

- yt_dlp/extractor/twitcasting.py
---
---
Closes #2792. 
Not tested properly, so currently drafted.
> [twitcasting] Add fallback for finding running live

- yt_dlp/postprocessor/ffmpeg.py
- yt_dlp/postprocessor/modify_chapters.py
---
---
1. First commit fixes https://github.com/yt-dlp/yt-dlp/issues/2769.
2. Second commit facilitates debugging of concat-related issues by keeping concat spec when `--keep-video` was requested.
> Sponsorblock minor fixes

- yt_dlp/extractor/washingtonpost.py
---
---
#2778
Add feature to read data from JSON that will be read by page JS.
> [washingtonpost] Add feature to read data from json that will be loaded on page.

- test/test_youtube_signature.py
- yt_dlp/extractor/youtube.py
---
---
Changes regex matching to not assume `nfunc` to have a length of 3
> [youtube] Fix n-function variable name capturing for phone player JS

- yt_dlp/extractor/biqle.py
---
---
Fixing Biqle extractor as reported on #193
```
D:\ytdlp\yt-dlp>flake8 yt_dlp\extractor\biqle.py
D:\ytdlp\yt-dlp>python -m yt_dlp --test "https://biqle.ru/watch/-2000421746_85421746"
[BIQLE] -2000421746_85421746: Downloading webpage
[BIQLE] -2000421746_85421746: Downloading embed webpage
[BIQLE] -2000421746_85421746: Downloading JSON metadata
[info] -2000421746_85421746: Downloading 1 format(s): 720p
[download] Resuming download at byte 486450
[download] Destination: Forsaken By Hope Studio Clip [-2000421746_85421746].mp4
[download] 100% of …
```
> Fixing Biqle #193

- yt_dlp/extractor/tubitv.py
- yt_dlp/utils.py
---
---
Fixes tubitv's TV series extraction (TubiTvShowIE) by handling `new Date("..")` values in embedded JS blobs. Also adds additional metadata to the main extractor when the title matches a series : episode format
> [tubitv] TV series extraction fix & metadata improvements

- yt_dlp/extractor/bilibili.py
---
---
Bilibili now force Referer to be set on every format, so I modified the code to fix: 'ERROR: unable to download video data: HTTP Error 403: Forbidden' when download audio parts
```
yt-dlp http://bilibili.com/video/BV1uR4y177hu 
[BiliBili] 1uR4y177hu: Grabbing original ID via API
[BiliBili] 338861482: Downloading webpage
[BiliBili] 338861482: Extracting videos in anthology
[BiliBili] Downloading anthology 338861482 - add --no-playlist to just download video
[download] Downloading playlist: 分享动态
[BiliBili] playlist 分享动态: Downloading 1 videos …
```
> [Bilibili] Fix extractor

- yt_dlp/extractor/twitcasting.py
> [TwitCasting] Check for password protection

- yt_dlp/extractor/zee5.py
---
---
Added support for Web Series.
> Added support for web-series

- yt_dlp/postprocessor/sponsorblock.py
---
---
https://wiki.sponsor.ajay.app/w/Types:
1. Apparently Highlight now requires `poi` `actionType`.
2. Ignore entire video segments.
> SponsorBlock: a few fixes more

- yt_dlp/extractor/gettr.py
---
---
- make m3u8 extraction non-fatal
- remove preference of ovid format
- add test for tags
Partially fixes? #2557
> [Gettr] Minor improvements

- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nhk.py
---
---
This adds support for [NHK for School](https://www.nhk.or.jp/school/). Likely not geo-restricted.
Closes ytdl-org/youtube-dl#29115
> [nhk] Add support for NHK for School

- yt_dlp/YoutubeDL.py
---
---
This PR is to fill some fields for playlists (especially `multi_video`) too.
> [YoutubeDL] Fill more fields for playlists

- yt_dlp/extractor/mirrativ.py
---
---
Cleans up extractor code for Mirrativ. This includes extractor-side patch for #2921. No dependency between the two.
> [mirrativ] Cleanup extractor code

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/niconico.py
---
---
This adds support for watch history and series, as well as reducing duplicated code.
> [niconico] Add playlist extractors and refactor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/telegram.py
> [New extractor] telegram

- yt_dlp/extractor/daystar.py
- yt_dlp/extractor/extractors.py
> Feat: new extractor daystar

- yt_dlp/extractor/zingmp3.py
---
---
In the future 'mp3.zing.vn' will be disabled and upgraded to 'zingmp3.vn' with new feature and UI. And all the method to get data, and endpoint of API will be changed. This PR will update the function to get data from 'mp3.zing.vn' and 'zingmp3.vn'.
> Feat: update new version for zingmp3

- yt_dlp/extractor/gettr.py
---
---
- Detect embedded posts/videos
- Fix timestamp scale
- Extract subtitles
- Add expect types to `try_get`
> [Gettr] Improve extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/videocampus_sachsen.py
> [VideocampusSachsen] Add extractor

- yt_dlp/extractor/adobepass.py
Addresses issue #2704 to add Suddenlink MSO authentication
---
---
Addresses issue #2704 to add Suddenlink MSO for authentication
> [adobepass] Add Suddenlink MSO

- yt_dlp/extractor/mgtv.py
---
---
Improve extractor for [MangoTV](https://w.mgtv.com/) and update testcase for zingmp3
> [MangoTV] Improve extractor

- yt_dlp/extractor/zingmp3.py
---
---
zingmp3.vn have already updated function hash for signature and this PR update function get signature for API and update the initialize that we need to call to dummy API to update cookie instead of domain
> [Zingmp3] Hotfix for get signature

- yt_dlp/extractor/youtube.py
---
---
Improves time text extraction:
- support scheduled streams
- prefer regex that is fixed to the US date format
- don't bother extracting time text for live/scheduled streams/premieres unless required (I think there might be a couple more edge cases for these e.g. right before the stream is starting. So better not to bother at this time)
- **fixes a fatal bug/regression where if the above edge case were to occur, the extractor would crash** (due to the fallback regex not having a group :facepalm: )
> [youtube] refactor and improve time text extraction

- yt_dlp/extractor/cbs.py
- yt_dlp/extractor/paramountplus.py
---
---
Paramount and CBS got rid of the show, movie, and episode names from their URLs. So this should take care of the new format and the old as that seems to still work as well.
> Paramount+/CBS URL Changes

- yt_dlp/extractor/veo.py
---
---
- Fix download problems with some videos (e.g. https://app.veo.co/matches/20201027-last-period/)
- Minor improvement (inlining, improve format_url checking, etc...)
> [Veo] Fix extractor

- yt_dlp/extractor/azmedien.py
---
---
Add support for [TVO Online](https://www.tvo-online.ch/) which is another TV station under the AZ Medien/ch media umbrella.
> [azmedien] Add TVO Online to supported hosts

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/lastfm.py
> [LastFM] Add extractor

- yt_dlp/extractor/youtube.py
---
---
Useful for allowing filtering of shorts by the shorts url.
Closes https://github.com/yt-dlp/yt-dlp/issues/3165
> [youtube:tab] Use shorts video url

- yt_dlp/extractor/banbye.py
- yt_dlp/extractor/extractors.py
> [BanBye] Add extractor

- yt_dlp/extractor/viki.py
---
---
Fixes some videos showing 403 instead of DRM protected (#1379).
> [viki] Don't attempt to modify URLs with signature

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/wasdtv.py
> [WasdTV] Add extractor

- yt_dlp/extractor/dailymotion.py
- yt_dlp/extractor/extractors.py
> [dailymotion] Improve extractor

- yt_dlp/extractor/xnxx.py
> Added xnxx.com's alternative domain support.

- .editorconfig
<details> <summary> Boilerplate (own contribution, improvement) </summary>
- Improvement
</details>
This adds an EditorConfig file (<https://editorconfig.org/>) conforming to the project’s style guidelines; a slight quality-of-life improvement for developers.
> Add a simple .editorconfig file

- yt_dlp/extractor/craftsy.py
- yt_dlp/extractor/extractors.py
---
---
#3140
Added Crafsy site support using BrightcoveNew extractor.
> [Craftsy] Add support for craftsy site.

- yt_dlp/extractor/azmedien.py
---
---
TeleZüri moved their video library from `telezueri.ch` to `tv.telezueri.ch` (but the URLs are still valid, they get redirected).
> [AZMedien] Add support for tv.telezueri.ch

- yt_dlp/extractor/niconico.py
- yt_dlp/utils.py
> [niconico] Fix extraction of thumbnails and uploader

- yt_dlp/extractor/rai.py
---
Rai updated the urls for some media on their website. Regex is fixed to catch all media like before.
> [rai] fix #3270

- yt_dlp/extractor/youtube.py
---
---
adds support for these:
no idea where else they show up.
TODO
> [youtube:search] Support hashtag tile entry

- yt_dlp/extractor/tenplay.py
---
---
Episode data is incomplete after JSON data and keys changed. Subtitles now also available on platform. Need for username and password removed for unrestricted videos.
> [tenplay] Add subtitles and fix info

- yt_dlp/extractor/common.py
- yt_dlp/extractor/elonet.py
> [elonet] Fix extractor

- yt_dlp/extractor/openrec.py
> [openrec] Downloading archived livestreams

- yt_dlp/extractor/cybrary.py
- yt_dlp/extractor/extractors.py
---
---
This is an extractor for [Cybrary](https://www.cybrary.it/). It supports individual videos ('activities') and playlists ('courses'.) The videos are hosted on Vimeo and are not protected -- you just need to pass the proper referrer when Vimeo VideoID is known.
> [Cybrary] Add extractor

- yt_dlp/extractor/imdb.py
> [Imdb] Improve extractor

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/ruutu.py
---
Add extractor for video clips in nelonen.fi, which uses ruutu.fi for streaming.
> [ruutu] Add extractor for nelonen.fi

- yt_dlp/extractor/fptplay.py
---
---
Fix bug get title, description and video info by episode.
> [fptplay] Improve extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/moviepilot.py
---
---
This add support for Trailers on Moviepilot. The whole topic is a little bit complicated:
- Trailers aren't self hosted but hosted at Dailymotion (since 2 years or so).
- Most movies link to a bunch of trailers, for example see [Interstellar](https://www.moviepilot.de/movies/interstellar-2/trailer).
- On the main movie site exactly one "main" trailer is played.
My extractor extracts this "main" trailer as playlist and forwards it to the Dailymotion extractor.
I'm not really sure, if this is a good method. Especially the test cases aren't really expressive because of that.
Moviepilot sometimes changes it's source code. Currently, the video ID of the "main" trailer is only mentioned in a script comment when retrieving the plain website, so I take this. I'm not sure how stable this …
> [Moviepilot] Add extractor

- yt_dlp/extractor/tver.py
> [TVer] Fix extractor

- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
> [youtube] extract uploader correctly for collaborative playlists

- yt_dlp/extractor/afreecatv.py
- yt_dlp/extractor/extractors.py
> [AfreecaTV] Improve extractor

- yt_dlp/extractor/nrk.py
> [NRK] Improve extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/jable.py
> [Jable] Add extractor

- yt_dlp/extractor/gofile.py
> [Gofile] Fix download issues

- yt_dlp/extractor/gofile.py
> [Gofile] Support password-protected links

- yt_dlp/extractor/pearvideo.py
> [PearVideo] Improve extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/icareus.py
---
Add extractor for sites with videos hosted at icareus.com. This was [submitted](https://github.com/ytdl-org/youtube-dl/pull/28510) to youtube-dl, but got nowhere.
Could probably benefit from a cleanup, but works as is.
> [icareus] Add new extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/lrt.py
---
- Fixed extractor tests; for some reason, MD5 hash has changed. Maybe they have changed the original video's quality somehow i.e. re-encoded it? It still looks good to me.
- Separated the extractor into two - one for VODs, one for streams. Added support for streams on the same website.
> [lrt] improve extractor

- yt_dlp/extractor/bilibili.py
- yt_dlp/extractor/extractors.py
---
---
add  support for `live.bilibili.com`
> [bilibili] Add extractor for live.bilibili.com

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/fifa.py
---
---
New extractor for #3408
> [Fifa.com] New Fifa Extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/masters.py
---
- [ x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [ x] I am the original author of this code and I am willing to release it under …
> [masters] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/likee.py
> [Likee] Add new extractor

- yt_dlp/extractor/tver.py
source: https://egg.5ch.net/test/read.cgi/streaming/1648663464/492
The author of the code declares to release it under Unlicense.
---
This reduces regression for TVer metadata extraction, as well as extracting more metadata.
> [TVer] improve extraction

- yt_dlp/extractor/khanacademy.py
---
---
Updates khan academy api.
> [khan academy] Fix extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/iwara.py
---
Add extractors for iwara `/playlist/` and `/users/` URLs.
> [iwara] Add extractors

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/zingmp3.py
---
---
Add new support for chart, user and update API to get streaming for video
ZingMp3ChartHomeIE
ZingMp3WeekChartIE
ZingMp3ChartMusicVideoIE
ZingMp3UserIE
> [ZingMp3] Improve extractor

- yt_dlp/extractor/tmz.py
---
Fix the tests for the tmz.com extractor.
```
$ python -m unittest discover -k TMZ
...
Ran 10 tests in 5.634s
OK
```
They where all failing.
The extractor itself is working fine.
> Update tmz.com extractor tests

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/ruutu.py
---
Add Ruutu embeds from hs.fi.
> [ruutu] Add hs.fi embeds

- README.md
- yt_dlp/extractor/radiko.py
---
This PR improves debuggability of extractor, even without verbose log. (of course we should always require it!) And some other small fixes.
TODO
> [radiko] Fix extractor

- yt_dlp/extractor/kaltura.py
---
* POST multirequest service with JSON API
* list query for videos with filter
* possible fix for #3636
> [kaltura] update API call

- yt_dlp/extractor/jamendo.py
---
Add artist and album metadata, closes #3359
Fix tests
> [Jamendo] Add metadata, fix tests

- yt_dlp/extractor/toggo.py
adding support for "toggolino" videos
---
Explanation of your *pull request* in arbitrary form goes here. Please **make sure the description explains the purpose and effect** of your *pull request* and is worded well enough to be understood. Provide as much **context and examples** as possible.
> [toggo] Fix _VALID_URL to support toggolino

- yt_dlp/extractor/drtv.py
---
DR have changed their URL scheme for radio episodes from `https://www.dr.dk/radio/` to `https://www.dr.dk/lyd/`, so this PR changes to allowed URL. There's also a couple of fixes to old tests in there to make them all green.
> [DRTV] Fix extractor to allow for new URL scheme for radio episodes

- yt_dlp/extractor/youtube.py
---
Adds urls for other instances of piped as outlined in https://github.com/yt-dlp/yt-dlp/issues/3661
Didn't add tests as the insidious instances in the same file do not have tests, have tested and all instances work however
> Added piped instance urls

- yt_dlp/extractor/adn.py
---
Update the AES key component needed for subtitle decryption
Fixes #2002
```bash
yt_dlp -vU --write-subs --skip-download "https://animedigitalnetwork.fr/video/boruto-naruto-next-generations/7936-episode-1-boruto-uzumaki"
```
```bash
[debug] Command-line config: ['-vU', '--write-subs', '--skip-download', 'https://animedigitalnetwork.fr/video/boruto-naruto-next-generations/7936-episode-1-boruto-uzumaki']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Git HEAD: 12ffc6962
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-110-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe …
```
> [adn] Update AES key component

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/podchaser.py
---
This adds support for podchaser.com, a podcast aggregator. All the podcast info is grabbed in JSON from Podchaser's API (api.podchaser.com). If multiple episodes are found, it returns a playlist--otherwise, just the one result.
> [Podchaser] Add extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/goodgame.py
---
Add basic extractor for streams on https://goodgame.ru
> [goodgame] Add extractor

- Makefile
> add uninstall option in Makefile

- yt_dlp/extractor/crunchyroll.py
---
Closes #2052... Kind of. The original creator of that issue was almost certainly having a different problem than this solves, but the discussion of the problem this solves is contained there, so...
> [crunchyroll:beta] match api change in policy_reponse

- yt_dlp/extractor/streamcz.py
---
This simply implements the fix that [dirkf](https://github.com/dirkf) mentioned in the issue, which is already present in youtube-dl.
Closes #3579
> Fix StreamCZ extractor

- yt_dlp/extractor/rumble.py
<details> <summary> Boilerplate: own code, extractor improvement </summary>
- Fix or improvement to an extractor (Make sure to add/update tests)
---
</details>
Fixes #3132.
> [rumble] Extract subtitles

- yt_dlp/extractor/bloomberg.py
- [ x ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ x ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)
- [ x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ x ] Fix or improvement to an extractor (Make sure to add/update tests)
---
Explanation of your …
> [bloomberg] fix: new playback endpoint

- yt_dlp/extractor/curiositystream.py
---
I have implemented support for using auth token from a browser for Curiosity Stream. It resolves #3753. I have little to no experience with Python and this is a first time seeing yt-dlp code base, so please do a thorough code review.
> [curiositystream] Add getting auth from browser cookie.

- yt_dlp/extractor/duboku.py
---
Explanation of your *pull request* in arbitrary form goes here. Please **make sure the description explains the purpose and effect** of your *pull request* and is worded well enough to be understood. Provide as much **context and examples** as possible.
> [duboku] Fix hostname change and require referer

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/playsuisse.py
**This is a copy of the original [youtube-dl PR](https://github.com/ytdl-org/youtube-dl/pull/28142). Now supports subtitles!**
---
---
Provide extractor for playsuisse.ch as requested in https://github.com/ytdl-org/youtube-dl/issues/27682 .
The website requires authentication, which can be provided to youtube-dl using the `--username,  --password` option, `--add-header` should also work. `.netrc` wasn't tested.
Account information for testing purposes:
E-Mail: tichis1964@einrot.com
Password: asdfasdf12341234!
> [playsuisse] Add new extractor

- yt_dlp/extractor/iwara.py
---
Iwara has some edge-cases that user profile URL and video listing URL are slightly different. This PR fixes to work flawlessly with these cases.
Related: ytdl-patched/ytdl-patched#34
> [extractor/iwara:user] Make paging better

- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/fourzerostudio.py
---
This adds support for 00:00 Studio. Livestream support is not implemented as it uses WebRTC to deliver video streams.
> [extractor/0000studio] Add support for 00:00 Studio

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/southpark.py
---
Support for South Park Latam....
note: I can't shorten the regex any more, without breaking the script.
> [SouthPark] South Park with Spanish Latam (Regex Fixed)

- yt_dlp/extractor/ccc.py
Extract `view_count` for media.ccc.de
> [extractor/ccc] Extract view_count

- yt_dlp/extractor/atscaleconf.py
- yt_dlp/extractor/extractors.py
---
closes: https://github.com/yt-dlp/yt-dlp/issues/3961
> [AtScaleConfEvent] Add IE

- README.md
- yt_dlp/extractor/youtube.py
---
Allows the Innertube api host and/or the key to be overriden for all API requests. Workaround for some network restrictions.
> [extractor/youtube] Add `innertube_host` and `innertube_key` extractor args

- yt_dlp/extractor/tver.py
> [extractor/tver] Use valid version for episode call

- yt_dlp/extractor/pornhub.py
---
Extracts `uploader_id` field (part of `/model/NAME HERE`) in PornHub videos
> [extractor/pornhub] Extract `uploader_id` field

- yt_dlp/extractor/radiofrance.py
---
This adds support for FIP, Le Mouv and France Musique.
> [extractor/radiofrance] Add support for FIP, Le Mouv, France Musique

- yt_dlp/extractor/foxnews.py
---
Update the url extraction regex for Fox News embeddings
Fixes #4023
```bash
yt-dlp "https://www.breitbart.com/clips/2022/06/08/kennedy-price-of-gas-is-so-high-that-it-would-be-cheaper-to-buy-cocaine-and-just-run-everywhere/"
```
```bash
python3 -m yt_dlp "https://www.breitbart.com/clips/2022/06/08/kennedy-price-of-gas-is-so-high-that-it-would-be-cheaper-to-buy-cocaine-and-just-run-everywhere/"
[generic] kennedy-price-of-gas-is-so-high-that-it-would-be-cheaper-to-buy-cocaine-and-just-run-everywhere: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] kennedy-price-of-gas-is-so-high-that-it-would-be-cheaper-to-buy-cocaine-and-just-run-everywhere: Downloading webpage
[generic] kennedy-price-of-gas-is-so-high-that-it-would-be-cheaper-to-buy-cocaine …
```
> [extractor/foxnews] Update url extraction

- yt_dlp/extractor/youtube.py
---
Addresses https://github.com/yt-dlp/yt-dlp/issues/2555. Sets the playback progress on a video in addition to setting it watched, allowing the "red bar" to properly show on youtube:
> [extractor/youtube] Fully implement "mark_watched"

- yt_dlp/extractor/cwtv.py
---
Explanation of your *pull request* in arbitrary form goes here. Please **make sure the description explains the purpose and effect** of your *pull request* and is worded well enough to be understood. Provide as much **context and examples** as possible.
Extract thumbnails from CWTV
> [CWTV] get thumbnails

- yt_dlp/extractor/lbry.py
---
This PR enables detection of multiple streaming formats.
Example: https://odysee.com/@BacktoBasics:e/101-Revisiting---Karen-Kinsgton:7
Currently only one format (1280x720) is provided. By applying the PR additionally formats (256x144 and 640x360) are provided.
> [lbry] use head request to determine m3u8 file for streaming url

- .github/workflows/build.yml
- README.md
See also https://github.com/actions/virtual-environments/issues/1256#issuecomment-770270252
- [ x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)
- [ x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) …
> Support macOS from 10.9

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/livestreamfails.py
---
Add an extractor for [Livestreamfails](https://livestreamfails.com/), a Twitch clip mirror site for [r/livestreamfail](https://reddit.com/r/LivestreamFail/).
> [livestreamfails] Add new extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/liputan6.py
</details>
DESCRIPTION
This PR add site-support for liputan6.com, this PR only add support for hls video
Fixes #4303
> [extractor/liputan6] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/audiodraft.py
</details>
This adds an extractor for audiodraft.com. Supersedes #4259.
Sorry for splitting this into two commits. My regular dev machine is broken, so I uploaded this from the GitHub UI, which apparently has neither any way to amend commits, nor have multiple files modified in a single commit. (And to think multi-file changesets were half the point of git in the first place. Sigh.) Since you usually squash them anyway, I think you won’t mind.
> Audiodraft

- yt_dlp/extractor/fifa.py
</details>
This PR updates the extractor to use the new required sequence of API calls to obtain the video. The old extractor included a call to a pointer that no longer exists, which was returning a 404 error. I understand there is another PR open for this extractor, but it looks like more of an enhancement, and I'm not sure it works with the updated version of the site.
Fixes #
> [FIFA] Fix extractor for replays and highlights

- yt_dlp/extractor/bigo.py
</details>
DESCRIPTION
Fixes #4139
> [extractor/bigo] Fix extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/syvdk.py
- [ x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ x] New extractor ([Piracy websites will not be …
> [syvdk] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/theholetv.py
> [theholetv] Add extractor

- yt_dlp/YoutubeDL.py
</details>
This PR improves the docs of `download_ranges` as proposed in https://github.com/yt-dlp/yt-dlp/issues/4338#issuecomment-1181688769 .
> Clarify download_ranges

- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
</details>
Currently there's no reliable way to get amount of frames, rows or columns in storyboard format. This PR adds `rows`, `columns` fields to JSON output and `fps` to be able to calculate storyboard frame count.
> [extractor/youtube] More parameters for storyboards

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/cellebrite.py
</details>
DESCRIPTION
This PR add site-support for cellebrite.com, mainly for video in blog sites.
Fixes #4014
> [extractor/cellebrite] Add extractor

- yt_dlp/extractor/ximalaya.py
</details>
DESCRIPTION
Tested:
```
python test/test_download.py TestDownload.test_Ximalaya_all
python test/test_download.py TestDownload.test_XimalayaAlbum_all
```
Remove nonexistent test url  https://www.ximalaya.com/11045267/sound/15705996/
> [extractor/Ximalaya] fix Ximalaya

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/detik.py
</details>
DESCRIPTION
This PR adds support  for 20.detik.com. This PR didn't include `/program` url as this url have different structure
Fixes #4283
> [extractor/detik] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/acfun.py
AcFun is like NicoNico and Bilibili.
</details>
DESCRIPTION
Fixes #
> [extractor/acfun] add video, bangumi

- yt_dlp/extractor/trovo.py
> [Trovo] Fix extractor

- pyinst.py
</details>
DESCRIPTION
Pyinst.py generates build name "yt-dlp_linux_x86" on ARM(32bit). Also "x86" is not compatible with PEP 425.
Fixes #
Introduces MACHINE variable filled by platform.machine() and replaces "AMD64" with "x86_64" according to PEP 425.
> make pyinst.py build name more PEP425 compatible

- yt_dlp/extractor/abematv.py
</details>
DESCRIPTION
Fixes #4351
This will make AbemaTVTitle paging, resulted in a small refactoring
> [extractor/AbemaTVTitle] Implement paging

- yt_dlp/extractor/globo.py
</details>
Added closing quotes to fix video ID matches.
Added .strip to remove leading and trailing spaces to title.
#4198
> [GLOBO] Add closing quotes to proper match video IDs

- yt_dlp/extractor/vgtv.py
fixes #4400 
Just adding the new url that works with the existing code.
The old urls still work so there's nothing else to modify.
> tv.vg.no support

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/rai.py
Rainews introduced a new player. I removed one of the old test that is no longer relevant and updated the extractor to get infos from the player json data.
Fixes #3911
> [rai] Rainews fix #3911

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/dplay.py
</details>
MotorTrend finally changed their website to the standard layout that the other Discovery websites are on, so had to update extractor to get downloads back up and running.
> Discovery Network - Motortrend Site Changes

- yt_dlp/extractor/hidive.py
Closes #3336
</details>
Fixes #3336
I originally wanted to check for the proper cookies, but I couldn't get it to work, so this was the best I can do. It simply checks if the login form is available at the login url, and if it is not assumes we are already logged in.
> [extractor/hidive] fix cookie login

- yt_dlp/extractor/go.py
---
Explanation of your *pull request* in arbitrary form goes here. Please **make sure the description explains the purpose and effect** of your *pull request* and is worded well enough to be understood. Provide as much **context and examples** as possible.
Extracts airdate from Go streams (particularly ABC). Not sure how to properly safely get the first element of the list if the list does not exist, my solution feels a little hacky so feel free to update for style. May also need to update previously existing code to remove compat code to pass tests
> [Go] Extract original airdate

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/tempo.py
</details>
DESCRIPTION
This PR add site support for video.tempo.co. This PR didn't include extraction in podcast.tempo.co as the actual website that provide the podcast is anchor.fm (using embed). This PR assume all video played/served by IVSPlayer
Fixes #
> [extractor/tempo] Add extractor

- yt_dlp/extractor/naver.py
</details>
This PR fixes the extractor to incorporate site url format and api endpoint changes.
> [extractor/NaverNow] Fix for site/endpoint changes

- yt_dlp/extractor/vk.py
---
The other day vk.com dev removed method of getting info for video.
This PR partially fixed issue: https://github.com/yt-dlp/yt-dlp/issues/4097#issuecomment-1159448112
> [extractor/vk] fix video extractor

- yt_dlp/extractor/bbc.py
</details>
Fixed videos on BBC news articles, which may now have a type of `video` instead of `media`.
> [bbc] Fix news articles

- yt_dlp/extractor/archiveorg.py
- yt_dlp/extractor/tubitv.py
- yt_dlp/utils.py
</details>
DESCRIPTION
Fixes https://github.com/yt-dlp/yt-dlp/issues/3832
- Skip formats that we cannot access (i.e. marked as private). 
- Note that I am choosing not to skip private formats if any user is logged in. This is because I do not have access to an account that has access to any private files to check/test how we can tell a user has access to a file.
- Prioritise "original" (source) formats (and note this in format note)
- support mpg files
- fix tests
> [extractor/archiveorg] Fix handling of formats

- yt_dlp/extractor/ina.py
</details>
Like described in #4419, some pages don't contain its id in the url so we failed to extract them. This is fixed by extracting the 'asset_id' from the api url that is inside the webpage, and now this works in all cases.
Fixes #4419
```bash
[debug] Command-line config: ['-vU', '-F', 'https://www.ina.fr/ina-eclaire-actu/arletty-carriere-conseils-actrice-marcel-carne']
[debug] yt-dlp version 2022.07.18 [135f05ef6] (source)
[debug] Git HEAD: 0bacb5947
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-122-generic-x86_64-with-glibc2.29 (glibc 2.31) …
```
> [extractor/ina] Update extractor

- yt_dlp/extractor/cloudflarestream.py
</details>
DESCRIPTION
Fixes incorrect padding issue for cloudflarestream. Credit to @parrukeisari for the [solution](https://github.com/ytdl-org/youtube-dl/issues/26640#issuecomment-845449888).
> Fixed incorrect padding issue for cloudflarestream 

- yt_dlp/extractor/stripchat.py
</details>
DESCRIPTION
Fixes #4486
> fix: '@' symbol in url [stripchat]

- yt_dlp/extractor/doodstream.py
</details>
DESCRIPTION
* Add support to more url
* Use the title html tag content as an alternative
> [extractor/doodstream] Add support to more url

- yt_dlp/extractor/twitch.py
</details>
Notes for the reviewer:
- I have updated the test case for vod with id `v6528877`, because it tested for an empty chapters array
- The test case I added for the new feature fails because of a 403 on the storyboard json url. What should I do? If I open the vod in browser, the devtools shows the same 403 error on the url twice
Fixes #4421
> Extend chapter extraction for single chapter VODs

- yt_dlp/extractor/espn.py
</details>
Extracts duration from ESPN+ / WatchESPN videos and updates the tests to reflect currently available videos.
> [ESPN] Extract duration and update tests

- README.md
- yt_dlp/options.py
</details>
Just a spelling correction, because the search in pagers is (at least by default) case sensitive.
> [doc] Fix capitalization in references

- yt_dlp/extractor/yahoo.py
</details>
DESCRIPTION
Closes #3646
Closes #3516
This fixes news.yahoo.co.jp support
#3646 is not usable because the site has changed since then
> [extractor/YahooJapanNews] Fix extractor

- yt_dlp/extractor/xfileshare.py
</details>
DESCRIPTION
Add Referer in HTTP header
> [extractor/xfileshare] Add Referer in HTTP header

- yt_dlp/extractor/vidio.py
</details>
This PR add support for `/embed` link in vidio.com. Some sites like enamplus.liputan6.com use this embed link. This PR also fix test error based on test return 
Fixes #
> [extractor/vidio] Add support for /embed link, fix test in VidioIE

- yt_dlp/extractor/fifa.py
> Fix issue #4566

- yt_dlp/extractor/ninegag.py
</details>
Added _9GAG post uploader_ data to NineGagIE
Refactored some of NineGagIE to comply with https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions
Updated exisiting test and added another to test the uploader data
Fixes #4587
> [extractor/ninegag] Update to 9GAG extractor

- .github/workflows/build.yml
- .github/workflows/core.yml
- .github/workflows/download.yml
- .github/workflows/quick-test.yml
</details>
This PR improves the GitHub actions release and CI workflows by:
1. Bumping versions of actions such as actions/checkout and actions/setup-python
2. Uses artifacts instead of release assets
3. Creates the GitHub release at the very end of the build workflow
> [build] Improve build process

- yt_dlp/extractor/tubitv.py
</details>
This PR improves tubitv.com extraction by extracting DASH and an addition HLS manifest. This also results in 1080p streams being available.
> [tubitv] Extract additional formats

- yt_dlp/extractor/patreon.py
</details>
Patreon was returning with some dud media along with the real video, which was prioritized due to the extractor flow. This media entry appears to have the characteristic of it's filesize being set to None/null in the API response, so we skip it based on that.
I also notice that instead of using `media` in the API includes, `audio,media_attachments` does the same thing but without including erroneous media if they exist. This is what the Patreon app appears to do, so should be safe...
Fixes https://github.com/yt-dlp/yt-dlp/issues/4608
> [patreon] Ignore erroneous attachment media

- yt_dlp/extractor/aenetworks.py
</details>
Fix bug with certain aenetworks video files returning the error `None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences `
Fixes #4093
> Add formats parameter to aenetworks TP_SMIL_QUERY items

- CONTRIBUTING.md
- Changelog.md
- README.md
- supportedsites.md
- yt_dlp/YoutubeDL.py
- yt_dlp/downloader/f4m.py
- yt_dlp/extractor/abematv.py
- yt_dlp/extractor/arte.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/openload.py
- yt_dlp/extractor/youtube.py
- yt_dlp/minicurses.py
- yt_dlp/options.py
- yt_dlp/utils.py
</details>
This PR unifies various _exempli gratia_ with "e.g." in many places
supportedsites.md and Changelog.md are excluded from replacing
> Unify various _exempli gratia_ with "e.g."

- yt_dlp/extractor/doodstream.py
</details>
Add DoodStream .wf TLD
Fixes #
- Add .wf TLD
> Add DoodStream .wf TLD

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/truth.py
- yt_dlp/postprocessor/ffmpeg.py
</details>
This patch adds support for Truth Social, the social network founded by former U.S. president Donald J. Trump. His posts are of interest to journalists and other open-source intelligence researchers. This addition would make it easier to collect the videos he posts.
fix #3865
> [truth] added new extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/jixie.py
- yt_dlp/extractor/kompas.py
- yt_dlp/extractor/moview.py
</details>
This PR add site support moview.id. This site actually use the same backend in kompas. Some video of this site return drm hls but as far i can see, it also always return the direct link of the video (but this link is usually in low quality).
Fixes #
> [extractor/moview] Add extractor

- yt_dlp/extractor/toggo.py
Changed regexp to also support /video/ url-part.
> Updated toggo valid url

- yt_dlp/extractor/sovietscloset.py
> [SovietsCloset] Fix extractor

- yt_dlp/extractor/rai.py
Stupid error by me introduced in a previous PR
Fixes #4690
> [extractor/rai] fix for #4690

- yt_dlp/extractor/redbee.py
</details>
Sometimes RTBF returns our jwt session token as a cookie and doesn't allow us to make more requests to `/accounts.getJWT`. 
This fixes an issue where we could only use username and password, but not cookies.
Fixes #4683
> [extractor/rtbf] Fix jwt extraction

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/islamchannel.py
> [extractor/IslamChannel] Add extractors

- yt_dlp/extractor/huya.py
</details>
Update Huya's extractor as the site changed the stream info format
Huya updated their stream format from base64-encoded to just JSON describing the stream data. This PR changes the extractor in order to conform to that format
Fixes #4658 
<details><summary>The relevant JSON data</summary><p>
```js
stream: {
"data": [
{
"gameLiveInfo": {
"uid": "1199561476483",
"sex": 2,
"gameFullName": "体育",
"gameHostName": "tiyu",
"startTime": 1661830096,
"activityId": 0,
"level": 31,
"totalCount": 192856,
"roomName": "不要在外面偷看",
"isSecret": 0,
"cameraOpen": 0,
"liveChannel": "1199561476483",
"bussType": 8,
"yyid": "35184489517472",
"screenshot": "http://live-cover.msstatic.com/huyalive/1199561476483-1199561476483-5435714470993199104-2399123 …
```
> [extractor/huya] fix stream extraction

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/newspicks.py
</details>
This adds support for newspicks.com
> [extractor/newspicks] Add extractor

- yt_dlp/extractor/stripchat.py
Stripchat room urls internally append a slash after the room name inside the extractor.
Urls ending in a slash are now redirected to the non-existent stripchat.ssr domain causing getaddrinfo failure, skipping the trailing slash works as normal.
New tests not required as the interface is being passed urls without a trailing slash, purely an internal change to  the class.
Fixes #
> [extractor/stripchat] remove trailing slash from url causing redirect to dummy domain.

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/epoch.py
</details>
Added a new extractor for EpochTV. Issue: https://github.com/yt-dlp/yt-dlp/issues/4714
Fixes #
> [extractor/epoch] Add extractor

- yt_dlp/extractor/bilibili.py
</details>
Bilibili newly added support for lossless FLAC support, which is
available at `window.__playinfo__.data.dash.flac.audio`.
> [extractor/bilibili] Support flac format.

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/triller.py
</details>
Adds support for triller.co, a short-form video social media platform
Closes #4703 
> [extractor/triller] Add Triller extractor

- Makefile
DESTDIR is only usefull in install* and uninstall* target[0]. The tar
target only generates a distribution file and doesn't install anything.
Also don't set DESTDIR if not set.
[0] https://www.gnu.org/prep/standards/html_node/DESTDIR.html
Direct installing from the a tar or the git repo currently requires to manual unset DESTDIR.
Fixes #
</details>
> Make `make tar' ignore DESTDIR

- yt_dlp/extractor/triller.py
</details>
Fixes bug with authorization in 92aa6d6
The auth token for logged in users was not being sent with API requests for individual videos
> [extractor/triller] Fix auth token bug

- yt_dlp/extractor/amazon.py
</details>
Retry to avoid captcha page that you sometimes get
Users may wish to increase `--extractor-retries`
> [extractor/amazonstore] Retry to avoid captcha page

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/mediaworks.py
- yt_dlp/extractor/mediaworksnz.py
</details>
Adds generic support for videos on most MediaWorks NZ news sites (e.g. todayfm)
> [extractor/mediaworksnz] Add MediaWorksNZVOD extractor

- yt_dlp/extractor/adobepass.py
</details>
Adding Support for Optimum.TV (AlticeOne) MSO for Suddenlink rebrand to Optimum. 
Fixes #4874 
> [adobepass] Add Support for Optimum.TV/AlticeOne MSO

- yt_dlp/cookies.py
</details>
Last bugfix missed a spot, and the `--cookies` option was raising an AttributeError (`'YoutubeDLCookieJar' has no attribute 'is_path'`)
Fixes bug in 941e881e
> [cookies] Fix bug in 941e881e

- yt_dlp/YoutubeDL.py
- yt_dlp/__init__.py
- yt_dlp/options.py
</details>
This will allow `--download-sections` and its relatives to allow using range with the other end missing (e.g. `*2-`, `*-60`)
> Allow open ranges for chapters

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/wistia.py
</details>
Adds URL query string checks to Wistia embed extraction. Fixes #4985 
Confirmed that the embed JS parses the query params `wmediaid`, `wvideoid` and `wvideo` for ID values:
`https://fast.wistia.com/assets/external/E-v1.js`
Updates WistiaIE tests and generic Wistia embed tests.
> [extractor/wistia] Match IDs in embed URLs

- yt_dlp/extractor/hungama.py
</details>
Hungama extractor was not returning subtitles. Added code to return video subtitle.
Fixes #
> [Hungama] Added Subtitle feature

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/youtube.py
</details>
Closes #4911 
Still need to settle on an extractor name and prefix.
Also there is an issue where if the given video is not the audio of any short then the feed will include itself. This is likely just a bug on YouTube's end and not much we can do (I mean, you'll never run into this case in the app).
> [extractor/youtube] Add support for extracting shorts audio pivot feed

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/smotrim.py
</details>
This adds support for Smotrim, as a shortcut for RUTV
Closes #4789
Closes #4110
#4789
> [extractor/Smotrim] Add extractor (again)

- test/test_utils.py
- yt_dlp/utils.py
</details>
Implement `utils.traverse_obj` tests, update docstring
and reimplement the function completely to fix various issues.
Also allow the now stabilized dict key for public consumption.
> [core] `traverse_obj`: Various fixes

- yt_dlp/extractor/soundcloud.py
</details>
Moved _extract_info_dict, _IMAGE_REPL_RE, _ARTWORK_MAP from SoundCloudIE to SoundcloudBaseIE so that they could be used in any subextractor. Modified _extract_info_dict to take an 'extract_flat' argument. When false, it will still extract info from a SoundCloud track, but it will not make any network requests. Used _extract_info_dict(extract_flat=False) to then fatten up search results of SoundcloudSearchIE. I also fixed SoundcloudSearchIE's test case by adding the 'id' field.
Preview:
```json
{
"id": "hello",
"title": "hello",
"_type": "playlist",
"entries": [
{
"id": "230155983",
"uploader": "Grace Davies",
"uploader_id": "44817748",
"uploader_url": "https://soundcloud.com/gracedaviesofficial",
"timestamp": 1445871069,
"title": "Hello - Adele",
"description": …
```
> [soundcloud] Enriched search results

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/wordpress.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/4955
> [extractor/wordpress] Add generic playlist embed extractor

- yt_dlp/extractor/ondemandkorea.py
</details>
The ondemandkorea extractor is currently broken. This PR fixes the regex to extract the player configuration.
Current format:
```javascript
odkPlayer.init([{'tracks': [], 'sources': [{'file': 'DUMMY_VALUE'}]}]);
````
Previous format:
```javascript
var playlist = [{'tracks': [], 'sources': [{'file': 'DUMMY_VALUE'}]}]
```
New regex now supports both formats. Failing tests have also been updated.
> [extractor/ondemandkorea] Update jw_config regex

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/crunchyroll.py
Provide meta hardsub format if we have softsubs available otherwise extract all hardsub formats.
Can still be overwritten by the `hardsub` extractor argument.
This does not affect the DASH stream type.
Fixes #3397 
> [extractor/crunchyroll:beta] Provide hardsub formats where possible

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/nbc.py
</details>
Adds support for NBC-owned television station news sites (referred to as `nbcstations` internally). These sites use `theplatform` a bit differently than the other extractors, so it was not beneficial to make this IE a subclass of `ThePlatformIE`.
Fixes #4571
Supports extraction of VOD and livestreams -- but NOT the live TV streams, ONLY the newscast livestreams that are available only during the actual broadcasts. The Live TV streams are region-locked and it would be a fool's errand to try to implement them, IMO.
> [extractor/nbc] Add NBCStationsIE

- yt_dlp/extractor/trovo.py
Fixes: https://github.com/yt-dlp/yt-dlp/issues/4878
This is still available? Сould not find it used on platform.
https://github.com/yt-dlp/yt-dlp/blob/ae1035646a6be09c2aed3e22eb8910f341ddacfe/yt_dlp/extractor/trovo.py#L299-L300 and
https://github.com/yt-dlp/yt-dlp/blob/ae1035646a6be09c2aed3e22eb8910f341ddacfe/yt_dlp/extractor/trovo.py#L332-L333
> [extractor/trovo] fix extractor

- yt_dlp/extractor/yandexvideo.py
</details>
Update the `_VALID_URL` regex for `YandexVideoPreviewIE`.
Fixes #5065
> [extractor/yandexvideopreview] Update valid url regex

- yt_dlp/extractor/tv2.py
</details>
This should add support for the new url format used in tv2, while still supporting the old one.
Also the TV2Article extractor should extract assetId correctly now.
Fixes #4973
> [extractor/tv2] Support new url format

- yt_dlp/extractor/mxplayer.py
</details>
I figured out the latest API url and parameters of the website's streams and fixed the extractor accordingly. Since the tests were failing due to outdated API, I updated the tests. Please note this only fixes MxplayerIE and <b>NOT</b> MxplayerShowIE, which I'll cover in the future, since I don't know the correct API url for it currently.
Fixes #4946
> [Mxplayer] Fix extractor

- yt_dlp/downloader/external.py
</details>
When aria2c is used for dash/m3u8 downloads and filenames contain leading whitespace, there are download errors. This affects both the 'in' file itself that is passed to aria2c and the 'out' file names specified in the 'in' file.
The in file is created by yt-dlp with the whitespace, but is attempted to be opened by aria2c without the whitespace. This is a similar issue as the one was resolved in eb55bad5a.
For the out files, the situation is similar. Without this fix, files are created by aria2c without the leading WS, with yt-dlp then expecting it to be present.
Examples (latest master - 576faf00b2496 - with this patch applied: https://github.com/std-move/yt-dlp/commit/b6760bb38b4 as without it, the website will fail to download with my Python/OpenSSL version):
<details> …
> [downloader/aria2c] fix errors when temp files for fragment downloads contain leading whitespace

- yt_dlp/extractor/bongacams.py
</details>
bongacams.com was moved to bongacams.net. This commit updates _VALID_URL to work with bongacams.net.
Fixes #5075
> [extractor/bongacams] Update bongacams.py

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/iltalehti.py
</details>
Extractor for iltalehti.fi.
> [extractor/iltalehti] New extractor

- yt_dlp/extractor/hrfensehen.py
> [extractor/hrfensehen] : fixed `hrfensehen` broken extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/bundesliga.py
</details>
Adds support for downloading videos from <https://www.bundesliga.com>
Fixes #2339
> [extractor/bundesliga] Add extractor

- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/jwplatform.py
</details>
See: https://github.com/yt-dlp/yt-dlp/issues/5106#issuecomment-1264566402
Embed wasn't being picked up as url in script src is not quoted:
```html
<script src=https://cdn.jwplayer.com/players/R10NQdhY-LzurxrFK.js></script>
```
Not sure if this is non-standard or not, but the web browser seems to handle it so we probably should.
> [extractor/JWPlatform] Fix extractor

- yt_dlp/extractor/amazon.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/5110
Seems like the `_html_search_regex` the extractor was using was unescaping an escaped `"`, causing the JSON parsing to fail. 
I've just moved it over to `search_regex` and the other tests seem to pass (though the playlist titles seem to have changed, I verified and they seem to be correct).
Only issue is I'm not sure why `_html_search_regex` was there to start with. Was the JSON data encoded or something at some point?
> [extractor/AmazonStore] Fix JSON extraction

- yt_dlp/extractor/holodex.py
Fixes inability to parse video id with dashes. Example:
```r
$ yt-dlp https://holodex.net/watch/A-_Gmvmv4Lc
ERROR: No suitable extractor (Youtube) found for URL https://www.youtube.com/watch?v=A
```
> [extractor/holodex] fix id regex

- yt_dlp/extractor/nfl.py
</details>
Fixes #1708
Now that the Anvato extractor is fixed, this can be as well.
> [extractor/nfl] Fix extractor

- README.md
- yt_dlp/downloader/__init__.py
- yt_dlp/extractor/youtube.py
</details>
This allows you to download whole archived livestream (longer than 4hrs), even though it's immediately after it finishes.
Known problems:
- Since number of total fragments won't increase, maybe it may force enumerate all the fragments first
> [extractor/youtube] Download manifestless post-live videos from the start

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/israelnationalnews.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/4019
> Add Israel National News extractor

- yt_dlp/extractor/bilibili.py
</details>
- fix BilibiliSpaceBaseIE with playlist-items
- refine BilibiliSpaceVideoIE message when being blocked
- the whole message refine needs https://github.com/yt-dlp/yt-dlp/pull/4945
> [Bilibili] fix BilibiliSpaceBaseIE with playlist-items

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/cnn.py
- yt_dlp/extractor/detik.py
</details>
This PR add site-support for www.cnnindonesia.com. This site is Indonesian news sites that seems to use detik player. However, this PR didn't use detikVideo Player. This PR get video from `embed_url` from json_ld and then make request from there. In the `embed_webpage`, this extractor search `videoUrl: '` string and then extract them as m3u8
Fixes #
> [extractor/detik] Generalize detik extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/booyah.py
</details>
This PR add site-support for booyah.live. This PR didn't extract user or channel video, only individual video
Partially fixes #4583 
> [extractor/booyah] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/prankcast.py
</details>
Added a new extractor for prankcast.com
Fixes #
> [extractor/prankcast] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/onenewsnz.py
</details>
Adds support for https://www.1news.co.nz/ articles.
The site uses the similar `Fusion.globalContent` JSON as the nzherald extractor, however the paths to extract videos seems to be a little different. I'm not entirely sure what the relationship is, so don't think they can be merged together at this stage.
> [extractor/onenewsnz] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/dplay.py
</details>
Adds support for motortrendondemand.com
Closes #5141 
> [extractor/dplay] Add MotorTrendOnDemand extractor

- README.md
- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/4843
Adds a new field:
```
concurrent_view_count: How many users are currently watching the video on the platform.
```
For YouTube, this also applies to upcoming streams/premieres where they have the "waiting" count.
> [extractor/youtube] Extract concurrent view count for live streams

- yt_dlp/extractor/tubitv.py
</details>
This PR works to eliminate ambiguous "No video formats found" error messages, instead raising clear & appropriate errors if the requested content is DRM protected or has been removed from Tubi.
Closes #5128
> [extractor/tubitv] Better DRM detection

- test/test_utils.py
- yt_dlp/utils.py
</details>
This PR implements traversal into `re.Match` objects and related tests.
These keys are supported:
- `...`: returns `match.groups()`
- `function`: gives groupno, value as parameters (group 0 is the whole match).
- `str`/`int`: returns `match.group(key)`. Supports `casesense`.
> [utils] `traverse_obj`: Allow `re.Match` objects

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/screen9.py
</details>
Extractor for screen9.com and sites using it as backend.
> [extractor/screen9] Add extractor

- yt_dlp/extractor/vk.py
</details>
VK changed their playlist URLs from 
`https://vk.com/videosPAGEID?section=album_PLAYLISTID` to 
`https://vk.com/video/playlist/PAGEID_PLAYLISTID`, 
which meant new URLs had to be rewritten to the old format by hand to work. 
a70b71e85ad61c5f7c85ef920d72f949fb767d53 then removed support for the old version by changing the regex to fix another URL related issue.
This PR now restores playlist downloads by correctly parsing the new URL and indirectly restores support for the old format via an automatic redirect to the new page.
Fixes #2825
> [VK] Fix playlist URLs

- yt_dlp/extractor/viu.py
Some shows will contain more than one subtitle as shown below, this commit added support for extracting it.
Testing URLs are also not available anymore, they were updated accordingly.
URL: `https://www.viu.com/ott/hk/zh-hk/vod/430078/%E7%AC%AC%E5%85%AD%E6%84%9F-3`
```
{
"is_default":1,
"name":"繁體中文",
"url":"https://d2anahhhmp1ffz.cloudfront.net/4279146490/799524ec920a46b1960dc18729d2a98261bcb8e3",
"subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/4279146490/799524ec920a46b1960dc18729d2a98261bcb8e3",
"product_subtitle_id":"240856",
"product_subtitle_language_id":"1",
"second_subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/2156290699/c04164fcd48fc654733a877382f018f1cb381d89",
"second_subtitle_position":1,
"code":"zh-Hant"
}
``` …
> [extractor/viu] Added support for second subtitle and updated testing url

- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
</details>
Secures `traverse_json_ld` against unexpected types.
Fixes #5144, #5143
> [extractor/common] Fix `json_ld` type checks

- yt_dlp/extractor/sbs.py
Adds support for tv/news series URL format.
Fixes #5045 
> [extractor/sbs] Improve _VALID_URL

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/podbayfm.py
- yt_dlp/utils.py
> [extractors/podbayfm] Add extractor

- test/test_cookies.py
- yt_dlp/cookies.py
</details>
Changes the key regex to match Morsels `_LegalChars`. This prevents errors when setting the key value pair.
Also updates behavior for prefixed attributes and simplify regex loop using `re.finditer`
Fixes #5186
> [cookies] Fix and simplify `LenientSimpleCookie` parsing behavior

- test/test_utils.py
- yt_dlp/utils.py
</details>
`js_to_json(R'"\^\$\#"')` currently results in invalid json since only specific escapes are getting processed.
This PR provides an alternate implementation with tests against this.
It also tries to clean up the function a bit.
> [utils] `js_to_json`: Fix unneccesary escape handling

- yt_dlp/extractor/cda.py
</details>
speeds up download if login details are provided, as there's no need to walk through webpages for each quality
> cda: allow using api

- yt_dlp/extractor/fox.py
</details>
Filled out a PR based on changes proposed in issue #1679 (support for cwtv thumbnails added in PR #4185)
Added support for episode thumbnails downloaded from fox.com.
Updated extractor test case.
Fixes #1679
> Add Fox TV thumbnail support

- README.md
- test/test_postprocessors.py
- yt_dlp/options.py
- yt_dlp/postprocessor/modify_chapters.py
- yt_dlp/postprocessor/sponsorblock.py
Renamed `_categories` to `_titles` and added in the chapter description when applicable. In tests, renamed the function to be clearer with sponsor chapters also existing separately, but if that's too confusing, I can change it to something else.
> [SponsorBlock] Add support for chapter category

- yt_dlp/extractor/voot.py
> [extractor/voot] fix regex

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/zeenews.py
> [zeenews] Add extractor

- .github/workflows/build.yml
- devscripts/update-version.py
- devscripts/utils.py
</details>
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://cs.github.com/yt-dlp/yt-dlp?q=set-output
Test: https://github.com/Lesmiscore/yt-dlp/actions/runs/3296638758
> Replace all `set-outut` usages with $GITHUB_OUTPUT

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/mlb.py
</details>
This PR add site-support for mlb.com/news/. This PR didn't include url from milb
Fixes #3475 
> [extractor/mlb.py] Add MLBArticle extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/japandiet.py
</details>
This adds support for proceedings live/record for House of Representatives (Shugiin) and House of Councillors (Sangiin) of Japan.
> [extractor/japandiet] Add extractors

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/agora.py
- yt_dlp/utils.py
> add agora extractors (tokfm, wyborcza)

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/genius.py
Adds support for genius.com video pages (atypical Brightcove embeds) and song lyrics pages (Youtube+Soundcloud embeds).
Closes #5209 
> [extractor/genius] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/oftv.py
</details>
Sorry for the duplicate PR as I failed to rebase my feature branch onto upstream.  This included other people's commits in my branch which you can see in #5120 .
This feature adds support for the video streaming website https://of.tv/. Two extractors have been created for single videos and entire playlists. While the generic extractor can handle this website, it extracts irrelevant videos.
Fixes #5017 
> OF.TV extractors

- yt_dlp/extractor/twitcasting.py
</details>
Now `data-movie-playlist` may contain a reversed base64 containing JSON
Closes #5451
> [extractor/twitcasting] Fix `data-movie-playlist` extraction

- yt_dlp/extractor/lbry.py
</details>
pass authentication token from cookies
Fixes #5431
> [lbry] pass authentication token from cookies

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/skyit.py
</details>
- fix #5392 by removing _extract_akamai_formats and using _extract_m3u8_formats for both live and vod content
- removed SkyItAcademy extractor as website no longer exist
- updated _VIDEO_ID_REGEX for SkyItArte extractor after website changes
- updated _VALID_URL for TV8It extractor after website changes
- updated _TESTS for various extractor
> [extractor/skyit] Various fixes and cleanups

- yt_dlp/utils.py
</details>
Backport the default SSL ciphers and minimum TLS version settings from 3.10. This is to ensure consistent behavior across Python versions, and help avoid fingerprinting in some situations
Python 3.10 dropped OpenSSL versions below 1.1.1, so to be safe I am only applying this to the 1.1.1 and newer. I don't even know if yt-dlp works on the older versions anyways.
I also backported the openssl version in the debug header from #2861 to help with debugging should the need arise.
Fixes partially https://github.com/yt-dlp/yt-dlp/issues/4627, Fixes https://github.com/yt-dlp/yt-dlp/issues/5433, Fixes https://github.com/yt-dlp/yt-dlp/issues/5425
and the 403 issue reported in …
> Backport SSL cipher and TLS min. level configuration from Python 3.10

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/deuxm.py
- yt_dlp/extractor/youtube.py
</details>
This adds an extractor for 2m.ma, the website for the biggest TV channel in Morocco.
> Add extractors for 2m.ma

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/tvp.py
</details>
refactor of the TVP extractors, mostly adapting to the new VOD frontend, a few general improvements (updated TVP domain list, detecting the video geo-block, detecting paid videos), fixes for the tests
Fixes #5328
> tvp: vod refactor, domain list update, general improvements

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/fox.py
- yt_dlp/extractor/qingting.py
> New extractor for Qingting.fm(蜻蜓FM)

- yt_dlp/compat/__init__.py
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/listennotes.py
</details>
Add extractor for listennotes.com
Fixes #5262
> [listennotes.com] Add extractor

- README.md
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/crunchyroll.py
</details>
Crunchyroll beta is no longer beta, so the old beta extractor needs to become the main extractor, and it needs to be adapted to the new server location.
Fixes #5292
> [extractor/crunchyroll] Beta is no longer beta

- yt_dlp/extractor/telegram.py
- yt_dlp/utils.py
- Add playlist support for Telegram when multiple videos are embedded
- Fix IE to obey `single` query param and only extract single video from multi-video embeds
- Add support for `--no-playlist` option
- Improve metadata extraction (add `uploader`, `timestamp`, `duration`)
- Eliminate unnecessary 2nd webpage request
Credit to @bsun0000 for bringing this issue to light and drafting an early version of this PR (#5333)
> [extractor/telegram] Add playlist support and more metadata

- yt_dlp/utils.py
</details>
https://github.com/yt-dlp/yt-dlp/commit/5b9f253fa0aee996cf1ed30185d4b502e00609c4#commitcomment-89054368
> Do not backport 3.10 ciphers for LibreSSL

- yt_dlp/extractor/stripchat.py
</details>
Stripchat changed the parameter used to find the host portion of the m3u8 URL. This fixes it.
Fixes #5227
> [extractor/stripchat] Fix hostname for HLS stream

- yt_dlp/compat/shutil.py
- yt_dlp/postprocessor/movefilesafterdownload.py
</details>
This PR works around `shutil.move` causing unhandled `PermissionError` on FreeBSD when using `restricted` ACL mode. As @pukkandan suggested, I've removed the user-facing option. Please see [the original PR](https://github.com/yt-dlp/yt-dlp/pull/5306) for more info.
> [movefiles] Work around `PermissionError` on FreeBSD

- yt_dlp/extractor/mxplayer.py
</details>
Improve extractor for `thirdParty` providers
Fixes #5276
> [mxplayer] Improve extractor

- yt_dlp/extractor/odnoklassniki.py
- yt_dlp/utils.py
</details>
Fix for 1440p and 2160p quality sorting
Example: https://ok.ru/video/313203755634
Add boosty.to support, fix https://github.com/yt-dlp/yt-dlp/issues/4212
Thanks for help @Lesmiscore 
Example:
https://boosty.to/vitaly/posts/acd4db50-18a8-40a0-a0bc-3bdee2022dbe
https://ok.ru/videoembed/3696046058009
> [extractor/odnoklassniki] Boosty.to support

- yt_dlp/extractor/stripchat.py
</details>
fixed unbound formats variable
Fixes #
> [extractor/stripchat] fix unbound formats variable

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/camsoda.py
</details>
Adds an extractor for the adult webcam site, [Camsoda](https://camsoda.com). Manual test:
```
▶ python -m yt_dlp https://www.camsoda.com/lizzhopf
[Camsoda] lizzhopf: Downloading webpage
[Camsoda] lizzhopf: Downloading JSON metadata
[Camsoda] lizzhopf: Downloading m3u8 information
[info] lizzhopf: Downloading 1 format(s): hls-1
[download] Destination: lizzhopf 2022-11-06 13_22 [lizzhopf].mp4
```
> [camsoda] Add extractor

- yt_dlp/extractor/bitchute.py
</details>
Raise on geo-restricted BitChute videos or channels. 
Examples:
https://www.bitchute.com/channel/GxILiMestsqQ/ (channel restricted in DE)
https://www.bitchute.com/channel/Yjg4ObtFSUCT/ (channel restricted in DE)
https://www.bitchute.com/video/WEnQU7XGcTdl/ (single video restricted in DE)
> [bitchute] raise on restricted videos

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/unsupported.py
</details>
As discussed in discord. Raise an error for sites that are known to be entirely DRM'd and will not be supported by yt-dlp. This is for when we have to remove support for a site because it has gone full-DRM.
I've added some to start with that have commonly shown up in our issue tracker. Open to suggestions of more to add.
> [extractor/unsupported] Add extractor

- .github/workflows/build.yml
- .github/workflows/core.yml
- .github/workflows/download.yml
- .github/workflows/quick-test.yml
</details>
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an …
> GitHub Workflows security hardening

- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/5068
comments and comment_count will be set to None (i.e. not set) in the info json as opposed to an empty list and 0 respectively.
- [ X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)
> [extractor/youtube] Differentiate between no comments and disabled comments

- yt_dlp/extractor/youtube.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/4669
If a comment reply thread request gets incomplete data, it will cause the entire comment extraction to stop, even if there are more comments to be extracted.
Q: Should we put this behind --ignore-errors? That comes with a cost that if the pages fail for some other reason then those errors will too be suppressed.
> [extractor/youtube] Ignore incomplete data error for comment replies

- yt_dlp/extractor/nzherald.py
</details>
site now provides videos via an additional API request.
- [ X At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
> [extractor/nzherald] Support new video embed

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/archiveorg.py
- yt_dlp/extractor/yle_areena.py
</details>
Added new extractor for single videos from areena.yle.fi and corresponding test.
Fixes #2508
> Add areena.yle.fi video download support

- dump_veoh_user_urls.bat
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/veoh.py
This PR allows downloading a user's videos on Veoh.
> Veoh user IE support

- yt_dlp/extractor/youtube.py
</details>
The official frontend instance of Piped recently got useless due to a DMCA takedown, hence the official frontend is now located at `piped.video`, thus it's being added by this PR.
I wasn't sure whether to remove `piped.kavin.rocks` from the supported list, but as some users might still have some txt files with lists of videos pointing to `piped.kavin.rocks` and the domain is still online I decided not to.
Closes #5518 
Similar to #5441
> Add support for `piped.video`

- yt_dlp/extractor/redgifs.py
Fixes bug in 8c188d5d09177ed213a05c900d3523867c5897fd (#5352) where the token refresh loop never actually made a 2nd attempt
> [extractor/redgifs] Fix bug in 8c188d5 (#5352)

- yt_dlp/extractor/reddit.py
</details>
Current fallback format is missing "vcodec" attribute which is used by other program(eg: mpv), this PR add that "vcodec" attribute so that script relies on "vcodec" can continue to work.
> [extractor/reddit] add vcodec to fallback format

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/kanal2.py
This is a third attempt to get this extractor merged. Hopefully goes better with new maintainers :)
```
$ python test/test_download.py TestDownload.test_Kanal2
$ youtube_dl/__main__.py https://kanal2.postimees.ee/pluss/video/?id=40792 -v -F
```
----
Carry https://github.com/ytdl-org/youtube-dl/pull/18547
Replaces https://github.com/ytdl-org/youtube-dl/pull/18547, https://github.com/ytdl-org/youtube-dl/pull/10291
> Add new extractor: Kanal2

- yt_dlp/extractor/gronkh.py
</details>
Gonkh.tv switched to a new url format. I have updated the regex to include both the new scheme and the old one. I have added new tests. However the tests will fail because `view_count` field is required and it is a dynamic value. I have tested it with the current accurate value and it works.
Fixes #5531
> added the new url format for Gronkh and tests [Issue #5531]

- yt_dlp/extractor/reddit.py
Adds support for Reddit text submissions that contain video embeds.
Closes #5612
> [extractor/reddit] Extract video embeds in text posts

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/noice.py
</details>
This PR add site-support for open.noice.id/content/<content_id>.
Fixes #
> [extractor/noice] Add NoicePodcast extractor

- yt_dlp/extractor/yle_areena.py
</details>
Some site videos does not provide inside JSON metadata episode and season numbers (Variables episode_number and season_number are null). This will cause the extractor to crash due strict number conversion.
It's also not possible to download restricted videos. These videos require the http header to be properly filled and a referrer is required by Kaltura API. 
This PR addresses both of these issues. New test for extractor is included.
Fixes #5734
> [yle_areena] Extended to proceed protected content.

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/mediaset.py
</details>
- assumed that when no formats are found is because the content is behind paywall and DRM
- removed _extract_from_webpage as no longer needed
- cleaned up unnecessary tests and fixed/updated not working ones
- f-strings
- added _EMBED_REGEX and _TEST_WEBPAGES
reported various times by @Heros99
https://github.com/yt-dlp/yt-dlp/issues/4125#issuecomment-1322060176
https://github.com/yt-dlp/yt-dlp/pull/1463#issuecomment-1326027800
https://github.com/yt-dlp/yt-dlp/pull/2158#issuecomment-1271146511
> [extractor/mediaset] Better DRM/Paywall message + _EMBED_REGEX

- yt_dlp/extractor/slideslive.py
The response data from the site's API is now a [custom/fake m3u8](https://github.com/yt-dlp/yt-dlp/issues/1532#issuecomment-1160351219) instead of JSON.
Closes #1532
> [extractor/slideslive] Fix extractor

- yt_dlp/extractor/pinterest.py
In the API response JSON there are two possible paths where the video formats may be found, but only one of them was being checked previously. This PR has the extractor traverse both paths, and also adds support for Vimeo embeds.
Closes #1772
> [extractor/pinterest] Fix extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/airtv.py
</details>
This PR add site support for www.air.tv. Some of video from this site is also streamed in popular video stream website (eg: youtube). This is extractor didn't add support in embed.air.tv. Thanks @coletdjnz for pointing out about nextjs  
Fixes #5132
> [extractor/airtv] Add extractor

- yt_dlp/extractor/netverse.py
</details>
This PR add comment field at NetverseIE and fix some test. This PR using v3 API of Netverse
Fixes #
> [extractor/netverse] Add capabilites to extract comment

- yt_dlp/extractor/rutube.py
Rutube requires a special URL argument for private (unlisted) videos (`?p=...`) which needs then to be passed to the API. It also adds a `/private/` fragment to the URL, like the following:
* an unlisted video: `https://rutube.ru/video/private/884fb55f07a97ab673c7d654553e0f48/?p=x2QojCumHTS3rsKHWXN8Lg`
* a normal one: `http://rutube.ru/video/3eac3b4561676c17df9132a9a1e62e3e/`
This PR adds the optional `private` fragment to the URL regexp and for the "secret" argument `?p=...`, and passes it down to the `_download_...` functions where needed.
> [extractor/rutube] Support private videos

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/oneplace.py
</details>
This PR add site support for oneplace.com. This extractor just extract individual audio url (podcast episode)
Partially fixes #5543
> [extractor/oneplace] Add OnePlacePodcast extractor

- yt_dlp/extractor/reddit.py
> [extractor/reddit] Extract crossposted media

- yt_dlp/extractor/bilibili.py
</details>
Fixes live URL of Bilibili like https://live.bilibili.com/blanc/13 which is an iframe inside https://live.bilibili.com/13.
- Put an `x` into all the boxes `[ ]` relevant to your *pull request* (like [x])
-->
> [extractor/bilibili] Fix live URL with `blanc/`

- yt_dlp/extractor/ard.py
</details>
This PR adds support for WebVTT to the extractor for ardmediathek.de.
The context: TTML is essentially not supported by ffmpeg (see eg. [issue 4859: TTML subtitle decoding](https://trac.ffmpeg.org/ticket/4859)), thus players like MPV that rely on ffmpeg are not able to display the subtitles (specifically, they show that a subtitle file exists but they don't show anything). WebVTT on the other hand is supported in MPV.
As for the implementation, the WebVTT URL is undocumented but it is very similar to the TTML one that the GraphQL API returns.
I tested this change and I am now able to watch ARD videos with subtitles in MPV.
> [ARD] Add WebVTT subtitles

- yt_dlp/extractor/arte.py
</details>
This PR adds extraction for chapters from Arte VOD. They are mostly present in the "ARTE Concert" section, e.g.:
https://www.arte.tv/de/videos/101309-006-A/moderat-im-grand-palais/
https://www.arte.tv/de/videos/110203-006-A/zaz/
Concerning the leftover TODO comment - I haven't found a video yet which has data in the `stream['segments']` attribute. If I do, I'll add that, but until then, I'll leave it there ^^'
> [ArteTV] extract chapters

- yt_dlp/extractor/ciscowebex.py
> [extractor/ciscowebex] Support password-protected videos

- yt_dlp/extractor/youku.py
> [extractor/youku] Fix youku extraction

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/kankanews.py
</details>
Add support for Kankanews.
Kankanews is a Chinese website focusing on recent news, and each page has a short video to play. This PR adds a new extractor for it.
> [extractor/kankanews] Add new extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/netverse.py
</details>
This PR add support for searching video in netverse.id
> [extractor/netverse] Add NetverseSearch extractor

- yt_dlp/extractor/twitcasting.py
</details>
Apply patch provided by @bashonly  to fix twitcasting extractor on password protected videos.
Fixes #5888 
https://github.com/yt-dlp/yt-dlp/issues/5888#issuecomment-1366311045
> [extractor/twitcasting] Fix extractor for protected twitcast videos

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/videoken.py
Depends on #5784
Adds support for icts.res.in, cncf.io, neurips.cc, and videoken.com; 4 sites that share the same API (and the first 3 sites share the exact same interface). The content is lectures, talks, presentations, etc. Every link I've tested is either a slideslive embed or youtube embed.
Closes #5818
> [extractor/videoken] Add extractors

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/amazon.py
Closes #5766
Addresses https://github.com/yt-dlp/yt-dlp/pull/5111#issuecomment-1363567678
> [extractor/amazon] Add `AmazonReviewsIE`

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/soundcloud.py
</details>
Fixes #5841.
Adds support for downloading from SoundCloud users via ID, which is resistant to profile URL changes.  URLs are in the form `https://api.soundcloud.com/users/30909869`.
~~This PR also adds `_API_V1_BASE`, as the resolve endpoint does not work with the V2 subdomain.~~
Only the 'all' resource is supported.
> [extractor/soundcloud] Implement user permalink support

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/adn.py
- yt_dlp/extractor/discovery.py
- yt_dlp/extractor/funimation.py
- yt_dlp/extractor/linuxacademy.py
- yt_dlp/extractor/tencent.py
- yt_dlp/extractor/tiktok.py
- yt_dlp/extractor/videa.py
- yt_dlp/extractor/viu.py
- yt_dlp/extractor/vrv.py
- yt_dlp/extractor/youku.py
</details>
Avoiding for loops
Fixes #
> fix: avoid for loop.

- yt_dlp/extractor/bandcamp.py
</details>
This patch adds an `album_artist` metadata field in the `BandcampIE` extractor class by scraping the track's webpage for the name of the artist who owns the album. This makes it easier to download albums into an `artist/album/track.mp3` directory structure when downloading compilation albums (tracks of varying artists).
Fixes #5536 
> [extractor/bandcamp] Add album_artist metadata (#5536)

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/testurl.py
- yt_dlp/plugins.py
</details>
- Improve plugin documentation for replacing existing extractors.
- Add information about plugins that replace extractors in debug output
> Misc. plugin improvements

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/peekvids.py
- yt_dlp/extractor/thisvid.py
</details>
Backports code from upstream yt-dl.
Notable changes:
- Add `ThisVidIE`, `ThisVidMemberIE` and `ThisVidPlaylistIE`
- More RTA patterns
- `jwplayer_data` imprvements (more data, better matching, fallback source type)
- update kvs embed extraction (This moves kvs extraction in front of `json-ld`)
- Refactor `PeekVidsIE` and `PlayVidsIE`, add more data
Ref: https://github.com/ytdl-org/youtube-dl/compare/de39d1281cea499cb1adfce5ff7e0a56f1bad5fe..master
> Port things from upstream yt-dl

- yt_dlp/extractor/joj.py
This PR fixes the Joj extractor failing in some cases due to unexpected resolution string in the download URL. I also made fix to existing test, since the website returns extension-less AVIF thumbnail by default.
</details>
> [Joj] fixed extractor

- yt_dlp/extractor/bilibili.py
This PR add support for `/media/<series_id>` url to `BiliIntlSeriesIE`. This PR also fix failed test at `BiliIntlSeriesIE`
Fixes #
</details>
> [extractor/bilibili] Add `/media` url to `VALID_URL`

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/volejtv.py
This PR add site support for single video in volej.tv
Fixes #5883
</details>
> [extractor/volejtv] Add extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/aitube.py
This PR add site-support for single video extraction in aitube.kz
Fixes #5627
</details>
> [extractor/aitube.kz] Add extractor

- yt_dlp/update.py
Fixes the updater code and reverts the previous workaround which only worked for x64. These changes are tested on Windows 7 (6.1.7601-SP1) 32bit and Windows 11 (10.0.22000).
Fixes #5632
</details>
> [updater] Fixes the updater file removal on windows

- yt_dlp/extractor/nbc.py
The NBC extractor stopped working due to a change in a graphql query
Fixes #5918
</details>
> Update nbc extractor with update to ThePlatform query parameter

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/drtv.py
</details>
This pull request implements support for downloading whole series and seasons on dr.dk/drtv. URLs like:
- https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
- https://www.dr.dk/drtv/serie/frank-and-kastaniegaarden_6954
Fixes #3567
> [extractor/drtv] Add series and season support for DRTV extractor

- yt_dlp/extractor/reddit.py
This adds the name of the subreddit (as the common "channel" field name)
Fixes #5684
> [extractor/reddit] Add the name of the subreddit as channel

- yt_dlp/extractor/crunchyroll.py
</details>
This will reintroduce the `language` filter, that has been available for the old Crunchyroll layout.
Usage is the same `--extractor-args crunchyroll:language=de-DE` as of the old extractor.
> [extractor/crunchyroll] Add language filter for playlist

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/xanimu.py
This PR add site support for xanimu as requested in #5810
Closes #5810
</details>
> [xanimu] Add extractor

- yt_dlp/extractor/drtv.py
Fixes bug in ab4cbeff00ac08f142f78a6281aa0c1124a59daa
Closes #5993
</details>
> [extractor/drtv] Fix bug in `ab4cbef`

- yt_dlp/extractor/common.py
- yt_dlp/extractor/nbc.py
* Improves `NBCIE._VALID_URL` to match new ID format
* `InfoExtractor._parse_smil_formats` now sends a HEAD request for mimetype info when no extension can be determined from the returned URL so that m3u8 formats can be properly detected/extracted (credit to @dirkf for suggesting this solution)
* Fixes broken `NBCStations` VOD extraction, adds support for `--wait-for-video` to livestreams
Closes #6019
</details>
> [extractor/nbc] Fix `NBC` and `NBCStations` extractors

- yt_dlp/utils.py
Fixes #6056
https://github.com/yt-dlp/yt-dlp/pull/6056#issuecomment-1397186958
</details>
> [utils] Fix `time_seconds` to use the provided TZ

- yt_dlp/extractor/freesound.py
Freesound.org downloads are broken due to how the preview URLs sometimes appear in the HTML: `<meta property="og:audio" content="https://freesound.orghttps://cdn.freesound.org/..." />`.
This PR will fix the URL if necessary by removing the `https://freesound.org` part of the url when it seems like there is another one after it.
Fixes #6146
</details>
> Fix freesound download

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/niconico.py
</details>
This adds support for [like history](https://www.nicovideo.jp/my/history/like).
Like history URLs have the same prefix as watch history URLs.  Therefore, I fixed the regular expression of NiconicoHistoryIE (watch history extractor).  Specifically, URLs with `like` after `history/` are excluded.
Fixes #
> [extractor/niconico] Add support for like history

- yt_dlp/extractor/zdf.py
Updates the test cases for the ZDF extractor and switch to the android player api endpoint, which enables UHD downloads.
</details>
> [extractor/zdf] Use android API endpoint for UHD downloads

- yt_dlp/extractor/goplay.py
Uses the new API (`api.goplay.be`) for the GoPlay extractor. The old API (`api.viervijfzes.be`) seems to have been shut down. The API domain now matches the extractor name as well (see https://github.com/yt-dlp/yt-dlp/pull/3412 for the initial rename).
Fixes #6032
</details>
> [GoPlay] Uses new API

- yt_dlp/extractor/reddit.py
Adjusts regex to allow video downloads from user posts outside of subreddits.
Also added channel_id to crosspost test as it was missing.
> [extractor/reddit] Adjust regex for user posts

- yt_dlp/extractor/huya.py
Huya's HD streams were not recognized (unknown resolution and tbr). As the best quality stream usually has `iBitRate` set to 0, the only way to tell its bitrate is from the display name.
This commit adds a very simple override array to fill in the correct bitrate and also add more resolution recognization matches. This has covered all current different bitrate options I found on the website and works pretty well with mpv selecting `bestvideo`.
</details>
> [extractor/huya] Add support for HD streams

- yt_dlp/extractor/hidive.py
Currently the Hidive extractor is broken:
- It doesn't extract subtitles.
- It doesn't select a Hidive profile, if the user has multiple profiles defined. This applies age-restriction to the content.
After login, Hidive redirects your browser to a profile-selection page. On that page, you need to click the button/icon you want to use, which sends a JSON request to the server which sets the profile id as a cookie.
Also, the subtitle information is no longer available (from what I've seen) in a "data-captions" element on the page, but they _are_available in the "rendition" data structure that Hidive gives us.
Fixes:
- https://github.com/yt-dlp/yt-dlp/issues/4279
- https://github.com/yt-dlp/yt-dlp/issues/408
> Fix Hidive - Subtitles and Age-restriction.

- yt_dlp/extractor/moviepilot.py
Fixing extraction of Moviepilot trailers. The website content was changed.
Unfortunately, some keys are not available anymore. They are now coming from the Dailymotion extractor, I guess.
Because of the changed extraction, some other metadata are trivial to extract now.
However, they belong to the original movie, not the trailer, therefore I have sketched them as commented lines.
If you think, these metadata can be embedded in the video, I will update the extractor accordingly otherwise I will remove the lines.
Fixex (no bug assigned).
</details>
> [extractor/moviepilot] Fix extractor

- yt_dlp/extractor/stripchat.py
This PR implements the fix, provided by @bashonly, for https://github.com/yt-dlp/yt-dlp/issues/5963 by expanding the search for the m3u8 url as well as updating the m3u8 url template.
Fixes #5963 and #5866
</details>
> [Stripchat] fix: implement patch for stripchat
