yt_dlp/extractor/tnaflix.py
This is a small change to the tnaflix.com extractor, updating the xml url to their (apparent) new scheme. Unfortunately, something in the download chain (claims to still be XML download, but I can't replicate it in browser) now fails to ssl-verify, so `--no-check-certificate` is required as well as this change. I'd appreciate any help there, if there's a way to get the certificate check to pass.
The  tests do not pass on this branch (ssl), however, they do not pass on master either (#6085)
Fixes #6085 (though note the remaining SSL issue)
</details>
=> Update tnaflix.com extractor url

yt_dlp/extractor/clyp.py
This PR added support to download wav's from clyp.it
Clyp API not returned links to wav's (only mp3 and ogg), but in html page exists link to wav file. I'm added this to extractor.
</details>
=> [extractor/clyp] Added wav download support

yt_dlp/extractor/bfmtv.py
Updated bfmtv URL regex to support rmc prefix, added test, updated original test to fix duration/tags/thumbnail errors raised during 'python test/test_download.py TestDownload.test_BFMTV'
Fixes #6021
</details>
=> added support for rmc prefix to bfmtv

yt_dlp/extractor/npo.py
The NPO extractor is currently broken. I restored basic functionality and added support for HD downloads.
I also removed some legacy code that hasn't been working since 2019. 
A cursory look at the other extractors in the file reveals that some of them are also broken. More work is needed, but I don't plan on addressing that in this PR.
</details>
=> [extractor/npo] Fix extractor and add HD support

yt_dlp/extractor/tvp.py
not much done design-wise but it all works on json now and has a new domain name
</details>
=> [extractor/tvp] fix for new tvp stream

yt_dlp/extractor/ximalaya.py
Updated album URL regex to support https://www.ximalaya.com/album/<album_id> format. Also fixed category in XimalayaIE test and added additional test for XimalayaAlbumIE.
Fixes #6059
</details>
=> [extractor/ximalaya] updated album URL regex, tests

yt_dlp/extractor/crunchyroll.py
This PR adds a intro chapter if available. 
</details>
=> [extractor/crunchyroll] Add intro chapter #HSFDPMUW

yt_dlp/extractor/bilibili.py
This PR add intro and ending chapter if available, the `start_time` and `end_time` seems a bit off even based on js, it the correct formula
</details>
=> [extractor/biliInt] Add intro and ending chapter

yt_dlp/extractor/vk.py
As reported [here](https://github.com/yt-dlp/yt-dlp/pull/4930#issuecomment-1409576726), VK playlist downloads stopped working. The reason is, that their API has been changed yet again and now requires "playlist_ID" instead of just "ID" as a request parameter. With this fix everything works again
Fixes  https://github.com/yt-dlp/yt-dlp/pull/4930#issuecomment-1409576726
</details>
=> [extractor/vk] playlist fix for new API requirements

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/nzonscreen.py
Adds support for videos on nzonscreen.com
Fixes #6193
</details>
=> [NZOnScreen] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/nfl.py
Adds support for subscription "NFL Plus" content on nfl.com
Closes #6165 
</details>
=> [extractor/nfl] Add `NFLPlus` extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/odkmedia.py
This PR add support for extracting single episode in www.ondemandchina.com
Fixes #3354
</details>
=> [extractor/odkmedia] Add OnDemandChinaEpisode extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/ebay.py
This PR seeks to add an extractor for ebay video listings as described in issue #6134
Fixes #6134 
</details>
=> feat: add extractor for ebay video listings

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/anchorfm.py
This PR add site support for anchor.fm. This PR use extraction as bashonly said in https://github.com/yt-dlp/yt-dlp/issues/6081#issuecomment-1401947887 (thanks @bashonly). This PR also include embed extraction to extract anchor.fm link from webpage (eg: Tempo Podcast)
Fixes #6081 
</details>
=> [extractor/anchor.fm] Add Episode Extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/hypergryph.py
This PR add support single audio extraction in monster-siren.hypergryph.com 
Fixes #6052
</details>
=> [extractor/hypergryph] Add MonsterSirenHypergryphMusic extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/boxcast.py
This PR add site support for single video extraction in boxcast.tv. This PR also include embed extraction and `/channel/<channel_id>?b=<broadcast_id>` and `/video-portal/<some string>/<some_string>/<broadcast_id>` url extraction
Fixes #5769
</details>
=> [extractor/boxcast] Add extractor

yt_dlp/extractor/youtube.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/6290
Authored by: coletdjnz
Fixes https://github.com/yt-dlp/yt-dlp/issues/6290
The above case has the entire comment section looping. This stops the comment extraction if it detects that.
Note that this will not stop any other kind of looping e.g. a single page repeating.
</details>
=> [youtube:comments] Detect comment section loop

yt_dlp/extractor/iprima.py
Fixes access token retrieval due to changes in iPrima.
Fixes extraction of video title and more importantly video id.
Fixes #6187
</details>
=> [extractor/iprima] fix token retrieval, fix extractor

yt_dlp/extractor/mediastream.py
=> [extractor/mediastream] Support WinSports URLs without IDs

yt_dlp/extractor/espn.py
Fixes #6164 
- Put an `x` into all the boxes `[ ]` relevant to your *pull request* (like [x])
-->
</details>
=> ESPNcricinfo extractor url update

yt_dlp/extractor/common.py, yt_dlp/extractor/rutube.py, yt_dlp/extractor/youtube.py
This allows to extract chapters (timecodes) from a video description. Youtube parser is reused for the extraction.
</details>
=> [extractor/rutube] Add extraction of chapters from description

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/xvideos.py
Adds support for the quickies videos type by converting it to a standard xvideos URL scheme
Fixes #6356
</details>
=> [xvideos] Added support for quickies

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/lumni.py
Added extractor for lumni.fr URLs. Extractor forwards video id to francetv extractor.
Fixes #6202
</details>
=> added lumni.fr extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/nubilesporn.py
=> [extractor/nubilesporn] Add NubilesPorn extractor

yt_dlp/extractor/chilloutzone.py
=> [extractor/chilloutzone] Fix extractor

yt_dlp/extractor/opencast.py
I'm the original author of the Opencast Extractor (bwildenhain then took care of it further so that it would be merged into yt-dlp. Thanks again for that), and I want to make an update to the extractor.  Opencast now has a new "interface" to access playlists, and that is now used more often than the old one. For that reason I extended the valid URLs of the OpencastPlaylist Extractor
Also I fixed the Tests. oc-video.ruhr-uni-bochum.de seems to be down currently so I replaced it with an other example. I also added the missing keys to the first test.
</details>
=> [extractor/opencast] Add ltitools interface to OpencastPlaylistIE and fix Tests

yt_dlp/extractor/cbc.py
Simple update of the URL matcher for CBC Gem, as they recently changed their URLs.
Fixes #6395
</details>
=> [extractor/cbc] CBC Gem: update URL regex

yt_dlp/extractor/opencast.py
For some reason, when my extractor was adopted for yt-dlp, the two functions were swapped. They were correct in the original extractor :D 🤷🏾  (https://github.com/ytdl-org/youtube-dl/pull/26934)
This is only a minor problem, since both formats are only used very rare on opencast. (I do not even have test data for these, but they are implemented in the opencast source code)
</details>
=> [extractor/opencast] Fix: do not add subtitles to formats

yt_dlp/extractor/detik.py, yt_dlp/extractor/rokfin.py
The Rokfin JSON endpoint (https://prod-api-v2.production.rokfin.com/api/v2/public/(post|stream)/XXXXX) for video info serves the timeline URL unconditionally, but the video URL conditionally, depending on whether you are authenticated as a premium user or not. We can extract the video URL by doing some regexp replaces on the timeline URL, and get free premium videos.
JSON examples:
Regular post:
```json
{
...
"content": {
"contentUrl": "https://stream.v.rokfin.com/6Zd5jkqFqdjPtjsPR9yyfBhqMpFQTjBUuyw3TTQ3bt8.m3u8",
"timelineUrl": "https://image.v.rokfin.com/6Zd5jkqFqdjPtjsPR9yyfBhqMpFQTjBUuyw3TTQ3bt8/storyboard.vtt",
...
},
...
"premiumPlan": 0,
...
}
```
Premium post:
```json
{
...
"content": {
"contentUrl": "fake.m3u8",
"timelineUrl": …
```
=> rokfin: extract premium video url from timeline url

yt_dlp/extractor/nebula.py
Currently if you try to download a video from nebula but put a beta.nebula.tv link in, it won't work. This patch fixes that.
Fixes #
</details>
=> Add beta.nebula.tv to Nebula extractor

yt_dlp/extractor/mediastream.py
This PR adds a base class and improves the embed extraction that is needed by both `WinSportsVideoIE` and generic. Also fixes a few bad regex patterns.
Closes #6419
</details>
=> [extractor/mediastream] Improve `WinSportsVideo` and embed extraction

yt_dlp/extractor/genius.py
IMO [this branch's approach](https://github.com/yt-dlp/yt-dlp/compare/master...bashonly:yt-dlp:fix/genius-base) is cleaner, but a base class seemed like overkill for such minute differences between its subclasses, so I went with this instead.
Closes #6465
</details>
=> [extractor/genius] Add support for articles

yt_dlp/extractor/iwara.py
Fixes #6549
Fixes #3851 (no longer applies after website renewal)
Notes
- Website is now unstable. Extractions may fail
- Due to migration, only recent videos (uploaded after Mar 10?) do play. Older videos do not play on website and yt-dlp gives `No video formats found!` error
</details>
=> [extractor/iwara] Overhaul extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/hollywoodreporter.py
It looks like all of the videos on the site are JWPlayer/JWPlatform. In the video page source there is an unused iframe tag for youtube embeds, so I've added code to handle youtube just in case; however, I haven't been able to actually find any youtube examples.
Closes #6525
</details>
=> [extractor/hollywoodreporter] Add extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/triller.py
* Add support for shortened links, e.g. `https://v.triller.co/WWZNWk`
* Detect when videos have been removed due to licensing restrictions and `raise_no_formats` (currently the extractor tries to `_extract_m3u8_formats` from a placeholder mp4 file)
* Refactoring and code cleanup
</details>
=> [extractor/triller] Support short URLs, detect removed videos

yt_dlp/extractor/nbc.py
The NBC stations sites sometimes/rarely serve direct mp4 links instead of m3u8 from their ThePlatform endpoint, which was breaking extraction.
</details>
=> [extractor/nbc] Fix `NBCStations` direct mp4 formats

yt_dlp/extractor/iwara.py
=> [extractor/iwara] Detect private video

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/yahoo.py
Yahoo! GYAO! released their EOL date, 31st Mar 2023 17:00 JST
source: https://gyao.yahoo.co.jp/thankyou [(archive)](https://archive.is/vBOOL)
To collaborators: the https://github.com/yt-dlp/yt-dlp/labels/do-not-merge excuses not to merge before the date
</details>
=> [extractor/YahooGyaOIE,extactor/YahooGyaOPlayerIE] Delete extractors for Yahoo GYAO

yt_dlp/extractor/youtube.py
Pinned comments may repeat a second time - this is expected.
Authored by: coletdjnz
Fixes https://github.com/yt-dlp/yt-dlp/issues/6712
See https://github.com/yt-dlp/yt-dlp/issues/6712#issuecomment-1497064377 for description
</details>
=> [extractor/youtube] Fix comment loop detection for pinned comments

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/hrefli.py
avoids a redir follow by generic extractor. all links outgoing from tumblr have href.li prepended
</details>
=> [extractor/hrefli] new extractor

yt_dlp/extractor/niconico.py
Closes https://github.com/yt-dlp/yt-dlp/issues/6760
Fixes #6760
Things to consider:
- new and legacy formats have different structure; should we assign an another language for the new one?
</details>
=> [extractor/niconico] Download comments from the new endpoint

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/gmanetwork.py
This PR add site support for single video in gmanetwork.com. This PR assume all video either from Youtube or Dailymotion. 
Partially fixes #5770  (as this PR didn't include playlist extraction) 
</details>
=> [extractor/gmanetwork] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/brainpop.py
Adds BrainPOP movie extractor for the main website, localized spanish/french/hebrew websites, alongside BrainPOP Jr. and BrainPOP ELL.
Solves https://github.com/ytdl-org/youtube-dl/issues/10000
</details>
=> [BrainPOP] Add extractors

yt_dlp/extractor/iwara.py
This PR fixes that the quality selection defaults to `preview` (and also selects `preview` as `best`)
also adds a error for when `fileUrl` is `None` instead of erroring later on `rsplit`
Note: i am still new to python and especially this project's code
re https://github.com/yt-dlp/yt-dlp/pull/6557#issuecomment-1485013062
</details>
=> Fix iwara quality selection

yt_dlp/extractor/adobepass.py
"Spectrum" is the cable brand of "Charter Communications." The `name` value of the `MSO_INFO['Charter_Direct']` dict is `Charter Spectrum`. The `Charter_Direct` MSO ID seems to be a relic, but it also seems to be what some Spectrum customers think is their MSO ID.
I am not able to personally test this, but based on the discussion/results in #5930 and https://github.com/yt-dlp/yt-dlp/issues/5742#issuecomment-1507474220, it looks like the `Charter_Direct` MSO ID should be handled as `Spectrum`.
</details>
=> [extractor/adobepass] Handle `Charter_Direct` MSO as `Spectrum`

yt_dlp/extractor/reddit.py
- Add support for shortened `https://redd.it/{display_id}` links, which redirect to a `https://www.reddit.com/comments/{display_id}` URL without a subreddit path
- Add support for cookies by removing old/broken quarantine-bypass method
- Add error handling for quarantined/private subreddits
Closes #6665, Closes #6753
</details>
=> [extractor/reddit] Support cookies and short URLs

yt_dlp/extractor/pornez.py
The extractor wasn't working for https://pornez.net/watch/leana+lovings+stiff+for+stepdaughter/ (missing video id)
Fixes #6791, Fixes #6298
</details>
=> [pornez] Issues with missing url video id

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/stageplus.py
stage-plus.com is a subscription-only site that streams live/VOD concerts and albums, mostly of classical music.
This PR only adds support a VOD concerts, not live concerts or albums.
Each VOD concert is a playlist made up of multiple works (videos). I opted not to make them `multi_video` playlists, because each work is then broken down into multiple movements (chapters).
There is a huge graphQL request body, but most of the metadata being requested is either useful or potentially useful (if/when livestream/album extractors are added). It seemed more efficient to leave it intact than to try and carefully perform surgery on it, only to maybe have to restore parts later.
Closes #6806
</details>
=> [extractor/stageplus] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/wevidi.py
WeVidi is a YouTube alternative video-sharing site that started in early 2021.
The extractor currently supports ripping WeVidi videos in all available formats (144p - 1080p). WeVidi encodes all of its content with `avc1.42E01E` (H.264 Constrained Baseline Profile Level 3) and `mp4a.40.2` (AAC-LC), always in an MP4 container.
Fixes #6129
</details>
=> [extractor/wevidi] Add support for WeVidi

yt_dlp/extractor/bitchute.py
On some video pages the seed* subdomain returned is invalid. This is a workaround for broken Bitchute pages (it is also broken in a web browser).
For example:
```shell
yt-dlp https://www.bitchute.com/video/IY0H2LkbpfnK/
```
Will fetch the url:
```
https://seed191.bitchute.com/SIxxyuOpyzP9/IY0H2LkbpfnK.mp4
```
Which is invalid and subsequently try the current hardcoded fallback subdomains which also fail.
This patch adds additional [tested] subdomains to use as fallback when the page returns an invalid url.
</details>
=> [bitchute] Add additional fallback subdomains

yt_dlp/extractor/pornhub.py
It adds two additional cookies to the extractor that were recently introduced by the site and prohibit the access to download the metadata.
The fix is from https://github.com/ytdl-org/youtube-dl/pull/31916
Closes #4299
</details>
=> [extractor/pornhub][fix] fix changed ageverification cookie

yt_dlp/extractor/cbc.py
Fixes livestream downloads for CBC Gem, which were completely broken due to a site update. Also updates a URL regex for non-livestream playlists, which I should have added in my previous PR #6499.
</details>
=> [extractor/cbc] Fix livestream downloading and playlist URL regex

yt_dlp/extractor/reddit.py
=> [extractor/reddit] Add login support

test/test_utils.py, yt_dlp/utils.py
Fixes:
- Branching should always result in list even if `traverse_string`
- `traverse_obj(None, ..., traverse_string=True)` => `[]`
- Using a `slice` on a `dict` should not throw
- `traverse_obj({}, slice(1))` => `None`
- Fix tests and docstrings regarding the `Iterable` change from 21b5ec86c2c37d10c5bb97edd7051d3aac16bb3e. Thanks to @dirkf for catching that one
- Add `is_iterable_like` helper function, as proposed by https://github.com/yt-dlp/yt-dlp/commit/21b5ec86c2c37d10c5bb97edd7051d3aac16bb3e#r110428208
</details>
=> [utils] `traverse_obj`: More fixes

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/clipchamp.py
Adds support for clipchamp.com, a video editing/sharing platform owned by Microsoft
Closes #6973
</details>
=> [extractor/clipchamp] Add extractor

yt_dlp/extractor/tvp.py
fixes https://github.com/yt-dlp/yt-dlp/issues/6987
switches extraction of vod completely to the new vod apis
Fixes #6987
</details>
=> [extractor/tvp] switch vod completely to vod api

yt_dlp/extractor/abematv.py
Fixes #6645 (closed due to inactivity)
Looks like there is a case that the video is still downloaded despite the webpage says sorry, so it adds a fallback for extracting title
In addition, it extracts metadata that are available in the JSON new logic relies on
</details>
=> [extractor/abematv] Add fallback for title and description extraction and extract more metadata

README.md, yt_dlp/YoutubeDL.py, yt_dlp/__init__.py, yt_dlp/downloader/common.py, yt_dlp/options.py
See https://github.com/yt-dlp/yt-dlp/issues/3643#issuecomment-1509633440
Closes #3643, Closes #6812
</details>
=> [core] Implement `--color` flag

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/bibeltv.py
As brightcove support seems to be dropped, this extractor is now implemented by using webpage and JSON API extraction.
Added support for live stream and series as playlist (with tescases).
Note: 
- The site has some DRM protected content, this will be signaled when trying to download.
- Not sure if the auth-token is universally usable and how long it's valid
</details>
=> [bibeltv] new implementation

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/wykop.py
new service support, no own video hosting but just storing metadata to others
</details>
=> [extractor/wykop] new extractors

yt_dlp/extractor/livestream.py
Fixes livestream test cases and adds support for downloading videos of events of an account
Fixes #2225
- [] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
</details>
=> Livstream: support for downloading videos with account id

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/zingmp3.py
Update the secret key and api key from main.min.js file.
Add hub extractor
</details>
=> [extractor/zingmp3]: add Hub extractor and update secretKey and apiKey

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/owncloud.py
I'm not sure if we want this extractor in yt-dlp, because in Owncloud there is no download block option, and there is always a download button. Since the extractor has been used in my project for years (https://github.com/C0D3D3V/Moodle-DL/blob/main/moodle_dl/downloader/extractors/owncloud.py)  I thought I make a PR, and if you want it you can review it, or reject it.
Also for now I only added two known OwnCloud servers, since I do not know if you want the extractor I did not search for more.
</details>
=> [extractor/owncloud] New Extractor for Owncloud

yt_dlp/extractor/playsuisse.py
Support new URL scheme where episode ID is a separate unique ID.
</details>
=> [extractor/playsuisse] fix new url format

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/idolplus.py
idolplus.com is South Korean entertainment site featuring mainly kpop video content.
This PR supports downloading of free content without authentication.
Partially fixes #6246
</details>
=> [extractor/idolplus] New extractor for idolplus.com

yt_dlp/cookies.py
* ~~Add cookies support for [Orion](https://browser.kagi.com)~~
* ~~Refactoring of Safari/WebKit parts to support more macOS WebKit based browsers in the future (such as [DuckDuckGo for Mac](https://spreadprivacy.com/introducing-duckduckgo-for-mac/))~~
* Add support for Safari custom cookies path
</details>
=> [cookies] Add support for Safari custom cookies path

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/dacast.py
Adds VOD support for dacast.com, a French "streaming as a service" platform.
Livestreams and "expo" streams have different URL formats and are not supported with this PR.
Dacast purchased Vzaar in 2019, for which there is an extractor, and is in the process of sunsetting it. But some Vzaar links seem to still be alive and well, and are not redirecting to Dacast. Dead Vzaar links redirect to the Dacast home page.
Closes #6163
</details>
=> [extractor/dacast] Add extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/crunchyroll.py, yt_dlp/extractor/jstream.py
This PR adds extractor for J Stream, which is providing embedded players, like Brightcove
P.S. this is absolutely not hurry. please release first
</details>
=> [extractor/JStream] Add extractor

yt_dlp/downloader/__init__.py, yt_dlp/downloader/niconico.py, yt_dlp/extractor/_extractors.py, yt_dlp/extractor/niconico.py
</details>
Closes #367 (except the GPL part we're not allowed to copy into our tree)
=> [extractor/niconico:live] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/rottentomatoes.py
Fix broken extractor (rottentomatoes) by extracting video info from embedded json on the page. Additionally the valid url regex was extended to include the default movie trailer as described in #6729. 
Fixes #6729
</details>
=> [RottenTomatoes] fix: update rotten tomatoes regex and extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/nekohacker.py
Add support for `https://nekohacker.com/` website
</details>
Notes:
- ~~currently the test fails with `AssertionError: {'filename'} is not false : Missing keys in test definition: filename`, but adding a `filename` property to the test definition makes it fail with `AssertionError: 'test_NekoHacker_01-Spaceship.mp3' != None : Invalid value for field filename, expected 'test_NekoHacker_01-Spaceship.mp3', got None`, what is the proper way to fix this?~~
- by default filenames result in `Spaceship [01-Spaceship].mp3`, i dont think this is correct, what is the proper way to set it?
=> [extractor/nekohacker] Add Extractor

test/test_cookies.py, yt_dlp/cookies.py
Brings `--cookies-from-browser` up to date with recent changes to chromium.
Prompted by https://github.com/yt-dlp/yt-dlp/issues/6880 I had a look at [what had changed in chromium (note: link takes a long time to load)](https://chromium.googlesource.com/chromium/src/+log/refs/heads/main/components/os_crypt) since the feature was initially added. It turned out none of the changes were relevant to that issue though. The notable changes relevant to yt-dlp are:
- more supported (auto detected) Linux desktop environments
- better KDE/KWallet support (including KDE6 which I didn't test because even KDE Neon testing edition is still on plasma 5 and I couldn't be bothered to compile from source)
- fallback to empty password on Linux (chromium found and worked around the bug that I found first …
=> Cookie fixes

yt_dlp/extractor/ard.py
=> Add thumbnail for ARD Beta, Fixes #6889

yt_dlp/extractor/eurosport.py
This PR add extract more new url format. This PR support dashed year (eg: `2022-2023`) and url with just category and slug. Thanks to @emilejanssens for pointing out the problem and explanation
Fixes #7042 
</details>
=> [extractor/eurosport] Change regex

yt_dlp/extractor/tagesschau.py
- updating testcases
- fix for URLs like https://www.tagesschau.de/multimedia/audio/podcast-11km-327.html, which provide only one mp3 format and are causing an index exception.
</details>
=> [tagesschau] fix for single audio media urls (e.g. podcasts)

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/brilliantpala.py
Greeting!
[Brilliant Study Centre Pala](https://elearn.brilliantpala.org/) is an online education website for a limited range of registered users, so there is no way to test it without an account.
This extractor works with both username/password pair and cookies.
`content_json` example:
```json
{
"order": 0,
"exam": null,
"html_content_title": null,
"html_content_url": "https://elearn.brilliantpala.org/api/v2.3/contents/$content_id/html/",
"free_preview": false,
"url": "https://elearn.brilliantpala.org/api/v2.4/contents/$content_id/",
"modified": "%Y-%m-%dT%H:%M:%S.%f+05:30",
"attempts_url": "https://elearn.brilliantpala.org/api/v2.3/contents/$content_id/attempts/",
"chapter_id": #number,
"chapter_slug": #string,
"chapter_url": …
```
=> [brilliantpala] Add extractor

yt_dlp/extractor/abc.py
Closes #8554
Supersedes #8572
</details>
=> [ie/abc.net.au:iview:showseries] Fix extraction

yt_dlp/extractor/drtv.py
=> [ie/drtv] Set ext for m3u8 extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/vidly.py
I was unable to find a single site using vid.ly for `_WEBPAGE_TESTS`. Maybe someone else has better luck looking for those.
</details>
=> [ie/vidly] Add extractor

yt_dlp/extractor/vocaroo.py
Switches from using the [deprecated](https://github.com/yt-dlp/yt-dlp/blob/66a0127d45033c698bdbedf162cddc55d9e7b906/yt_dlp/networking/common.py#L556) `Response.getheader` to `Response.get_header` to prevent a warning for Vocaroo requests.
</details>
=> [ie/vocaroo] change getheader to headers.get

.github/workflows/core.yml, .github/workflows/release-master.yml
This PR adds a cancel CI running on PRs so that we dont fill up the queue unnecessarily.
It also removes the cancel for master builds, so as to make it queue up neatly one after another. This would result in more frequent builds, and not having to wait for another build to finish for the next push.
</details>
=> [ci] Concurrency optimizations

yt_dlp/extractor/box.py
The direct http format URLs no longer work. In the IE there was commented-out code for extracting the DASH formats; I just simplified it and followed through on the "append query to every fragment URL" TODO note
Closes #5098
</details>
=> [ie/box] Fix formats extraction

yt_dlp/extractor/ondemandkorea.py
The site sometimes returns an empty m3u8 playlist on upgraded formats, so only making a HEAD request isn't enough to check if the upgraded url is valid.
Fixes #8675 
</details>
=> [ie/ondemandkorea] Fix format upgrade

test/test_utils.py, yt_dlp/YoutubeDL.py, yt_dlp/utils/traversal.py
Preparations for `traverse_obj` rewrite in combination with output template adjustments.
Both private parameters should be moved out of the function and into `outtmpl` instead.
</details>
=> [utils] `traverse_obj`: Move `is_user_input` into output template

yt_dlp/extractor/youtube.py
Issue #8759 mentions, "No longer extracting like_count for video metadata". It was happeing because `vpir` did not have the values of `like` and `dislike` counts where it was specified. So that was returning `None` value while `int` was expected.
Fixes #
So I updated the reference to the correct place of likes and the problems is solved. The test case is passing
</details>
=> fixed key error for like_count

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/rinsefm.py
This extractor supports urls under the `https://rinse.fm/episodes/[id]` format.
This was very straightforward as the returned HTML contains the file url in plaintext.
Please let me know if there are improvements to be made to the code before merging!
</details>
=> [RinseFM] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/bundestag.py
This PR opts to hardcode the share and playlist urls, they can be extracted dynamically once it breaks
Closes #8436
</details>
=> [ie/bundestag] Add extractor

test/test_utils.py, yt_dlp/utils/networking.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/8729
</details>
=> [networking] Strip whitespace around header values

yt_dlp/extractor/iheart.py, yt_dlp/extractor/kinja.py, yt_dlp/extractor/nba.py, yt_dlp/utils/_utils.py
Some minor fixes.
These should probably go into one of the regular clean-up commits.
This fixes some extra whitespace in messages (probably introduced by stripping "`").
It also fixes use of `IENAME`, as inherited from youtube-dl. It was already wrong there, see the partial fix https://github.com/ytdl-org/youtube-dl/commit/fc86d4eed0bf10f8f90326472811e5b4d4ad4bd9.
Note: `flake8 yt_dlp/utils/_utils.py` does not fail due to my changes.
</details>
=> minor fixes

.github/workflows/core.yml
Core tests tend to take quite long and also Pypy is having strokes from time to time. Since extractor changes are separate, running core tests on these changes does not make sense.
Quick tests will keep running everytime.
Fixes my sanity
</details>
=> [ci] Skip core tests on extractor only changes

yt_dlp/extractor/litv.py
=> [ie/litv] Fix premium content extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/epidemicsound.py, yt_dlp/extractor/imgur.py, yt_dlp/extractor/telewebion.py, yt_dlp/utils/_utils.py
Changes to backport:
- Ignores `Cc` (Control), `Cf` (Format), `Co` (Private Use, unused), `Cs` (Surrrogate, unused), `Mc` (Spacing Mark), `Me` (Enclosing Mark), `Mn` (Nonspacing Mark)
- Fixes #2598
- Fixes #3228
- yourub-dl is Unlicense
</details>
=> Backports from youtube-dl (2023-12)

README.md
This fixes a minor typo in the readme.
To my knowledge there is no associated issue.
[^1]: Field added by submitter of PR
</details>
=> nit: readme/deps/ffmpeg: fix minor typo

yt_dlp/extractor/nhk.py
R1 from Kanazawa is available as a temporary service due to [the earthquake on the noto peninsula](https://www3.nhk.or.jp/nhkworld/en/news/20240108_20/)
https://www3.nhk.or.jp/netradio/kanazawa/
it only has the bare minimum to be playable - no station info, no nothing, just the stream url and the area name
it may be of interest to record, so this PR makes it so that the metadata download is non-fatal. everything past that is also non-fatal, so it all degrades reasonably gracefully
for an example do `yt-dlp https://www.nhk.or.jp/radio/player/?ch=r1 --extractor-args nhkradirulive:area=kanazawa` before/after this commit
</details>
=> [extractor/nhkradirulive] make station info non-fatal

yt_dlp/extractor/piapro.py
Piapro ID's can contain both the characters a-z/A-Z and the character "-", which is currently missing from the _VALID_URL regex.
Fixes #
- Fixed the _VALID_URL regex for Piapro
</details>
=> fix: Piapro regex allowed characters

yt_dlp/extractor/cloudflarestream.py
This PR fixes a warning message stating **"subtitle tracks found in the HLS manifest"** are being ignored, following the change suggested in the issue.
Fixes #8830
</details>
=> [CloudflareStream] fix-subtitle-warning Fixes #8830

yt_dlp/extractor/googledrive.py
* Update new Domain/URL for source file download
* Identify with the new domain name (example: https://drive.usercontent.google.com/download?id=xxxxxxxx(&export=download))
Fixes https://github.com/yt-dlp/yt-dlp/issues/8976 #
</details>
=> [extractor/GoogleDrive] Update new Domain/URL for source file download

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/ilpost.py
Adds an extractor for podcasts from Italian online newspaper https://www.ilpost.it/.
</details>
=> [ie/ilpost] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/chzzk.py
Add extractors for CHZZK (Twitch alternative for Korea)
Example url: https://chzzk.naver.com/video/1754
Step 1
```
GET https://api.chzzk.naver.com/service/v1/videos/1754
```
<details>
<summary>Response</summary>
```json
{
"code": 200,
"message": null,
"content": {
"videoNo": 1754,
"videoId": "28F5A4200339976F880B8880C6DFA2B1982A",
"videoTitle": "치지직 테스트 방송",
"videoType": "REPLAY",
"publishDate": "2023-12-19 16:21:45",
"thumbnailImageUrl": "https://video-phinf.pstatic.net/20231219_183/1702970761280ULfy0_JPEG/43e9d4ba-9e3f-11ee-83b8-a0369ffd9e34_03.jpg",
"trailerUrl": null,
"duration": 15577,
"readCount": 62669,
"publishDateAt": 1702970505417,
"categoryType": null,
"videoCategory": "",
"videoCategoryValue": "",
"exposure": true, …
```
=> [CHZZK] Add extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/amadeustv.py
This pull request adds a new extractor for amadeus.tv, a platform hosting a variety of music and cultural videos. The extractor retrieves video information from the site, including the actual video URL from the sourceVideo field in the site's API response. This allows yt-dlp users to download videos from amadeus.tv, which was previously unsupported. The PR includes the necessary code changes, tests, and complies with yt-dlp's coding conventions.
Fixes: #8155  
</details>
=> Add support for Amadeus.tv

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/asobichannel.py
This PR implements an extractor for [ASOBI CHANNEL](https://asobichannel.asobistore.jp), which is a proprietary VOD platform run by Bandai Namco Entertainment Inc..
</details>
=> [ie/asobichannel] Implement Asobi Channel extractor

test/helper.py, test/test_networking.py, test/test_socks.py, test/test_websockets.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/8890
</details>
=> [test] Skip source address tests if the address cannot be bound to

yt_dlp/downloader/hls.py
If there is only a single fragment, it is just a full file and thus does not need to be parsed.
Fixes the symptoms of #5804
The webvtt parser should still be made more lenient.
</details>
=> [webvtt] Don't parse single fragment files

test/test_networking.py, yt_dlp/networking/_requests.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/9020#issuecomment-1901575385
See [comment](https://github.com/yt-dlp/yt-dlp/issues/9020#issuecomment-1901575385) for info
</details>
=> [rh:requests] Apply `remove_dot_segments` to absolute redirect locations

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/redge.py, yt_dlp/extractor/sejmpl.py
abstracting redcdn livx, it's the same in at least senat. backports from haruhi-dl
</details>
=> redcdn livx and sejm.pl extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/motherless.py
Adds an extractor to create playlists from Motherless uploader pages. This needed minor customizations to ensure the t=v URL parameter was set.
Add an additional extractor for the per-user upload playlists on motherless.com. Validated through unit tests and manual local runs.
</details>
=> [extractor/MotherlessUploader] Add extractor for uploader playlists

yt_dlp/extractor/newgrounds.py
Fix user page extractor
Fixes #7308
</details>
=> [Newgrounds] Fix user page extractor

yt_dlp/extractor/rule34video.py
Rule34Video seems to have changed the first part of the URL path from `/videos` to `/video`, and redirects the former to the latter. The extractor doesn't accept the latter, so it doesn't work for URLs taken from the current version of the website.
This changes the regex to accept both.
</details>
=> [ie/Rule34Video] Fix valid URL regex

yt_dlp/extractor/ard.py
See writeup in the issue. We can get a token using browser cookies to authenticate and this enables downloading videos with fsk protection before 22:00
Fixes #9035
</details>
=> [ie/ARDBetaMediathekIE] Add age verification

yt_dlp/extractor/pr0gramm.py
Pr0gramm added a new filter category for political content. This PR updates the flags to include the POL filter for the request.
It also removes the login requirement for downloading tags, as they are provided fully even without accounts.
</details>
=> [ie/pr0gramm] Enable POL filter and provide tags without login

yt_dlp/extractor/txxx.py
Added thumbnail
Added thumbnail.
</details>
=> [extractor/txxx] Added thumbnails

yt_dlp/extractor/gofile.py
change `'websiteToken': '7fd94ds12fds4'` to `'wt': '4fd6sg89d7s6'` get string from https://gofile.io/dist/js/alljs.js
Fixes https://github.com/yt-dlp/yt-dlp/issues/9073
</details>
=> Fix download gofile.io

yt_dlp/extractor/playsuisse.py
This implements the new requirement to login. 
Fixes #7974 
</details>
=> [extractor/playsuisse] fix #7974 with login

yt_dlp/extractor/viewlift.py
This commit enables the existing viewlift extractor to support chorki.com (another viewlift based ott platform).
Fixes #
This commit will fix yt-dlp#3369
</details>
=> [ie/ViewLift] Added support for chorki.com [yt-dlp#3369]

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/art19.py
Adds an art19 extractor, which can then serve as a basis for #8875 and #8838. Both are currently not dealt with due to their non-standard way to embed the podcast.
</details>
=> [ie/art19] Add extractors

README.md, yt_dlp/options.py
=> [core] Add `--compat-options 2023`

yt_dlp/cookies.py
Implement support for `--cookies-from-browser` for `snap` Firefox and do more specific searching for the`Profiles` dirs. It also allows `os.altsep` as a path separator for `_is_path`, so that `/` is correctly categorized on Windows.
This PR has the side effect of including `glob`, as well as no longer searching infinitely deep, therefore speeding up the cookie extraction by an immense amount.
Fixes [#7520](<https://github.com/yt-dlp/yt-dlp/issues/7520>), Closes [#9011](<https://github.com/yt-dlp/yt-dlp/issues/9011>)
</details>
=> [cookies] Fix `--cookies-from-browser` for `snap` Firefox

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/ninaprotocol.py
Implementation of ninaprotocol.com extractor, worked on it some time ago, didn't see it already was PRed. You can use this code or not. I tried to make it fuzzy as possible, by capturing all JavaScript code, then searching the 'release' key in the json substring, and looking for the right 'release', by looking up the name of the album.  Then I saw 
https://github.com/yt-dlp/yt-dlp/pull/8764#issuecomment-1855874207 and added it as a another try to find song data.
They treat songs as a release of an album. Individual songs are treated as an album with a single song. So, it doesn't matter if its one or multiple songs. I always treat the generic website link as a list of songs. 
Fixes #8709 …
=> [NinaProtocol] Add extractor

yt_dlp/extractor/redtube.py
Supports domain redtube.com.br (Portuguese language) of redtube.com
Fixes #
</details>
=> [ie/RedTube]Support redtube.com.br

yt_dlp/extractor/cineverse.py
cineverse seems to be cracking down on access without proper logins. it worked before, so at the time i didn't write anything to handle it not working
addresses #9072
</details>
=> [ie/cineverse] Report account requirement

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/viewlift.py, yt_dlp/extractor/zetland.py
This PR add site support for `zetland.dk`. This PR only test the OP url in #9024 as the other url require subscription. This PR only assume the article only contain 1 audio link with no other type of media
Fixes #9024
</details>
=> [ie/zetland] Add ZetlandDKArticle Extractor

yt_dlp/extractor/bilibili.py
Fixes #5083
Adding `buvid3` cookie required by auth of search API to fix HTTP 412 error.
</details>
=> [extractor/bilibili] fix BiliBiliSearch HTTP 412 banned

yt_dlp/extractor/ccma.py
=> [ie/CCMA] Add 1080p dash support

yt_dlp/extractor/eporner.py
Some videos are available with AV1 codec, that information is not returned in JSON from `xhr/video/{video_id}` but can be extracted from webpage. URL to download is identical as h264 file but with addition of `-av1` before file extension (`.mp4`).
Fixes #
<details open><summary>Add AV1 codec</summary> 
</details>
=> [eporner] Add support for AV1 codec

yt_dlp/extractor/nytimes.py
Fixes the ``NYTimesIE`` extraction, by adding the missing data (timestamp, upload_date).
</details>
=> [ie/NYTimes] - adjust _GRAPHQL_QUERY to include the field 'firstPublished'

yt_dlp/extractor/antenna.py
API endpoint changed
</details>
=> [ie/Ant1NewsGrEmbed] Fix extractor

yt_dlp/extractor/crooksandliars.py
=> [ie/CrooksAndLiars] Fix extractor

yt_dlp/extractor/funk.py
API endpoint no longer exists. Most of the metadata is provided by nexx, with the fields that aren't seemingly no longer being available.
</details>
=> [ie/Funk] Fix extractor

yt_dlp/extractor/lefigaro.py
NEXT JS data structure has changed
</details>
=> [ie/LeFigaroVideoEmbed] Fix extractor

yt_dlp/extractor/magellantv.py
JS hydration data is slightly different for episodes of a series.
</details>
=> [ie/MagellanTV] Add episode support

yt_dlp/extractor/svt.py
SVT News changed its API similar to SVTPlay
Previously downloading a video resulted in 404 Error (because of api change somewhere in September 2023)
This commit fixes SVTPage extractor to use a new api
Added a new tests and added `only_matching` tag for the old ones (because videos for the old articles is unavailable anymore)
Fixes #8930
</details>
=> [SVTPage] Fix extractor

yt_dlp/extractor/nova.py
Updates the regex used in the nova extractor to detect embeds. This feels like something that should have been done with `_EMBED_REGEX`. Furthermore, I am unsure if the code path after this is still used.
</details>
=> [ie/Nova] Update embed regex

yt_dlp/extractor/screencastify.py
Site uses a new URL format
</details>
=> [ie/Screencastify] Add new URL format

Makefile
Bugfix for beaa1a44554d04d9fe63a743a5bb4431ca778f28
</details>
=> [build:Makefile] Restore compatibility with GNU Make <4.0

yt_dlp/extractor/pornhub.py
the previous `is_logged` class checks were too generic and would always return True no matter the login state or page. The new regex targets the `#profileMenuDropdown` which is only shown when logged in and `.ph-icon-logout` which is also only shown when logged in
Fixes #7981 
No tests were added since a dummy account and matching playlist ID are required
</details>
=> [ie/pornhub] fix is_logged check

yt_dlp/extractor/err.py
Add https://lasteekraan.err.ee support
Examples:
- https://lasteekraan.err.ee/1092243/patu
- https://lasteekraan.err.ee/1608163129/nukitsamees
It's a "channel" view for children, the same content seems to be available from jupiter URLs:
- https://jupiter.err.ee/1092243/patu
- https://jupiter.err.ee/1608163129/nukitsamees
</details>
=> [err] Add lasteekraan.err.ee url match

yt_dlp/__init__.py, yt_dlp/options.py
Detect if the user opened the standalone executable by double-clicking, and display a helpful error message.
Co-authored by Grub4K.
</details>
=> [core] Warn user when directly launching `yt-dlp.exe`

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/nebula.py
Fixes #8838
Co-Authored by [c-basalt](https://github.com/c-basalt)
</details>
=> [ie/nebula] Add podcast support

yt_dlp/extractor/cloudflarestream.py
=> [ie/CloudflareStream] Improve `_VALID_URL`

yt_dlp/extractor/ntvru.py
[Authored by: dirkf](https://github.com/yt-dlp/yt-dlp/issues/8347#issuecomment-1762852362)
Closes #8347
</details>
=> [ie/ntvru] Fix extraction

yt_dlp/extractor/swearnet.py
=> [ie/swearnet] Raise for login required

yt_dlp/extractor/archiveorg.py
=> [ie/archiveorg] Fix download URL encoding

yt_dlp/extractor/cloudflarestream.py
Partially addresses #7858
</details>
=> [ie/CloudflareStream] Improve embed detection

yt_dlp/extractor/youtube.py
Ref: https://github.com/yt-dlp/yt-dlp/issues/8941#issuecomment-1879953441
</details>
=> [ie/youtube] Add helpful info if all responses are skipped

yt_dlp/extractor/bilibili.py
Fix a small bug where the call to _html_search_meta was missing a parameter.
</details>
=> [ie/bilibili] Fix call to _html_search_meta

yt_dlp/extractor/altcensored.py
The current `page_count` regexp does not take into account that `channel_id` may contain one or more dash "-" character(s). If a channel with such an id is downloaded, the detection of the number of pages fails and the default value "1" is used, resulting in only the first page being downloaded.
A `ChannelIE` download test was added to cover the scenario above. Also fixed a couple of failing existing tests in this extractor.
</details>
=> [AltCensoredChannelIE] Fix page_count regular expression

yt_dlp/extractor/rozhlas.py
=> [ie/MujRozhlas] Fix extraction

yt_dlp/extractor/cctv.py
Regex wasn't matching video id in webpage
Fixes #9299 : Add a new Regex to match the video id
</details>
=> [ie/CCTV] Fix video id Regex

yt_dlp/extractor/dumpert.py
Now supports any url with `?selectedId=` such as `https://www.dumpert.nl/toppers/dag?selectedId=100086074_f5cef3ac`
(Did not make issue because seem a fairly straightforward fix).
All tests run, see https://regex101.com/r/sXNP7f/1 to confirm that the regex still works properly for the other urls.
</details>
=> [Dumpert] Broader url support

README.md, devscripts/install_deps.py, pyproject.toml
This will eventually allow us to do something like this: 8e3f00284ec16b2e5cbb6c6cbc2b2cafc739a7ef
</details>
=> [build] Add `default` optional dependency group

yt_dlp/extractor/newgrounds.py
Based on #9334 by @mrmedieval, thx for the groundwork
- Fixes #9324
- Fixes #6488
See #9334
</details>
=> [ie/newgrounds] Fix login and clean up extraction

yt_dlp/extractor/craftsy.py
=> [ie/craftsy] Fix extractor

yt_dlp/extractor/roosterteeth.py
Addresses https://github.com/yt-dlp/yt-dlp/pull/9355#issuecomment-1984948706
</details>
=> [ie/roosterteeth] Extract release date and timestamp

yt_dlp/extractor/duboku.py
`player_data`
```json
{
"flag": "play",
"encrypt": 2,
"trysee": 0,
"points": 0,
"link": "/vodplay/4283-1-1.html",
"link_next": "",
"link_pre": "/vodplay/4283-1-31.html",
"url": "JTY4JTc0JTc0JTcwJTczJTNBJTJGJTJGJTczJTc0JTZEJTJFJTZFJTYyJTZGJTZCJTc1JTJFJTYzJTZGJTZEJTJGJTMyJTMwJTMyJTM0JTMwJTMyJTMwJTM3JTJGJTQ0JTRDJTcxJTM0JTQyJTUxJTQ1JTVBJTJGJTY5JTZFJTY0JTY1JTc4JTJFJTZEJTMzJTc1JTM4",
"url_next": "",
"from": "vidjs",
"server": "no",
"note": "",
"id": "4283",
"sid": 1,
"nid": 32
}
```
https://u.duboku.io/static/js/player.js
```js
if (player_data.encrypt == "1") {
player_data.url = unescape(player_data.url);
player_data.url_next = unescape(player_data.url_next);
} else if (player_data.encrypt == "2") {
player_data.url = unescape(base64decode(player_data.url));
player_data.url_next = …
```
=> [Duboku] Decrypt m3u8 url link

yt_dlp/extractor/youtube.py
Improving upon 413d3675804599bc8fe419c19e36490fd8f0b30f: hopefully buying us some more time before we need to bump these again, and also bumping the music client versions which hadn't been bumped in the original commit
</details>
=> [ie/youtube] Further bump client versions

yt_dlp/extractor/crtvg.py
This fixes an issue with url formats being different
</details>
=> Update regex for extractor in CrtvgIE extractor

yt_dlp/YoutubeDL.py
=> [core] Handle `--load-info-json` format selection errors

yt_dlp/YoutubeDL.py, yt_dlp/networking/common.py
Skip cleanup for non created request director
</details>
=> Don't access `ydl._request_director` on `close()`  (Fix 069b2aedae2279668b6051627a81fc4fbd9c146a)

yt_dlp/extractor/gofile.py
I'm not a Python expert but did some research and fixed the download error from gofile.io. Hope you will improve the code more optimally
Fixes #
</details>
=> Fix download gofile.py

yt_dlp/extractor/sonyliv.py
SonyLIV has begun (or always has been?) limiting season playlist pagination to 100 results per request. Some series, like the original extractor test, have "seasons" of "episodes 1-100", "episodes 101-200", etc, so they were not impacted by this limitation. But other series, like the test I added in this PR, have seasons consisting of more than 100 episodes, and extraction was being truncated at the 100th episode of each of those seasons. This PR fixes the pagination requests and modernizes the code
</details>
=> [ie/SonyLIVSeries] Fix season extraction

yt_dlp/extractor/imgur.py
This PR adds an 'Accept' header with the value '*/*' to the request sent to Imgur servers when downloading videos. It is done by modifying ```ImgurIE``` to include ```'http_headers': {'Accept': '*/*'}``` under the return statement of ```_real_extract``` function.
The change resolves issues with downloading certain video formats from Imgur URLs or those embedded in Reddit posts, ensuring that the download does not result in a corrupted file.
Fixes #9458 
</details>
=> [extractor/imgur] Fix Imgur Extractor

yt_dlp/extractor/youtube.py
From: https://github.com/yt-dlp/yt-dlp/issues/1400#issuecomment-1988317902
Authored by pukkandan
</details>
=> [ie/youtube] Fix tbr calculation

yt_dlp/extractor/youtube.py
This PR fixes the search parameters for `YouTubeSearchDateIE` to use the following filters: `sort:date`, `filter:videos`.
I didn't update the parameters for `YouTubeSearchIE` as the current parameters still seem to be correct and testing on the website gives me the same parameters when applying the`filter:videos` filter manually.
Fixes #9156 
<details open>
<summary>Template</summary>
</details>
=> [ie/YoutubeSearchDate] Fix search parameters

yt_dlp/extractor/box.py
Adds support for Box URLs of the form `/s/[shared_name]`.
Example: `https://utexas.app.box.com/s/2x6vanv85fdl8j2eqlcxmv0gp1wvps6e`
</details>
=> [ie/box] Add support for implicit file ID

yt_dlp/extractor/xvideos.py
Add support new url format
Fixes #9493
</details>
=> [ie/xvideos] Fix regex (#9493)

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/fathom.py
Extractor for fathom.video
Closes #8541
- Put an `x` into all the boxes `[ ]` relevant to your *pull request* (like [x])
-->
</details>
=> [ie/fathom] Add extractor

yt_dlp/extractor/thisoldhouse.py
~~Some~~ All(?) videos are Brightcove instead of Zype now
Closes #9570
</details>
=> [ie/thisoldhouse] Support Brightcove embeds

yt_dlp/extractor/soundcloud.py
=> [ie/soundcloud] Support cookies

README.md, yt_dlp/options.py
=> Add option `--no-break-on-existing`

yt_dlp/extractor/mixch.py
Thanks @nipotan for the API endpoint knowledge
Closes #9536
</details>
=> [ie/mixch] Fix extractor

yt_dlp/extractor/jiosaavn.py
=> [ie/jiosaavn] Fix format extensions

yt_dlp/extractor/jiosaavn.py
=> [ie/jiosaavn] Extract artists

yt_dlp/extractor/afreecatv.py
1. Due to AfreecaTV's GEO-IP restrictions, fix the problem of the extractor not working in Korea by making a request to a non-existent subdomain.
2. Fix the 400 Bad request error by adding the Referer header.
Fixes #4466
Fixes #9345
</details>
=> [ie/AfreecaTVLive] Fix extractor in Korea

README.md, yt_dlp/extractor/crunchyroll.py
Crunchyroll recently moved to a new stream delivering api. All endpoints are DRM encrypted now, except for the one. This PR changes the extractor to use this one, DRM-free, endpoint.
The endpoint update contains some major changes, most notably that HLS support was dropped, so streams are only available as MPD/DASH now.
Fixes #9453, Fixes #8161
</details>
=> [ie/crunchyroll] Fix extractor

yt_dlp/extractor/dropbox.py
=> [ie/dropbox] Fix anonymous download formats

yt_dlp/extractor/vk.py
=> [ie/vkplay] Fix `_VALID_URL`

yt_dlp/cookies.py
Flatpak stores application data in `~/.var/app/$FLATPAK_ID`
`org.mozilla.firefox` is an ID of Firefox in the most popular (de facto standard) repository [Flathub](https://flathub.org/).
</details>
=> [cookies] Add support for Firefox installed via Flatpak

yt_dlp/extractor/nhk.py
=> [ie/nhk] Fix NHK World extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/jiosaavn.py
=> [ie/jiosaavn] Support playlists

README.md, yt_dlp/YoutubeDL.py, yt_dlp/__init__.py, yt_dlp/downloader/common.py, yt_dlp/options.py
Adds the `--progress-delta` flag, which limits the output rate of the progress hook. Note that this does not affect the rate at which hooks actually occur
Fixes #5789
</details>
=> [progress] Implement progress update rate

.github/workflows/build.yml, README.md
Can add it back once https://github.com/yifeikong/curl-impersonate/pull/53 is merged and we bump our `curl_cffi` pin
</details>
=> [build] Do not include `curl_cffi` in `macos_legacy`

yt_dlp/extractor/jiosaavn.py
=> [ie/jiosaavn] Extract via API and fix playlists

.github/workflows/build.yml, README.md, pyproject.toml
=> [build] Normalize `curl_cffi` group to `curl-cffi`

test/test_utils.py, yt_dlp/utils/_utils.py
Improves handling of `\\` and `\r`: Old halding was passing doubly escaped values to executables. While the old way is easier to parse from within batch, the usual case is to call executables directly; therefore this new escaping is the prefered behavior.
Also adds round trip tests instead of the old "trust me, I know escaping" sort of tests.
</details>
=> [core:windows] Improve shell quoting and tests

.github/workflows/build.yml
[Fixes](https://github.com/bashonly/yt-dlp/actions/runs/8861128118/job/24332695890) the `macos_legacy` builds that were [broken by Github bumping `macos-latest` to `macos-14-arm64`](https://github.com/yt-dlp/yt-dlp/actions/runs/8858620650/job/24327487292)
</details>
=> [build] Run `macos_legacy` on `macos-12`

.github/workflows/build.yml, bundle/docker/compose.yml, bundle/docker/static/Dockerfile, bundle/docker/static/entrypoint.sh, yt_dlp/update.py
Adds a indipendant binary, statically linking musl libc, available to run on any OS with Linux Kernel 3.2+ (tested using Debian 7).
Fixes ***broken builds***
</details>
=> [build] Create linux_static build target

yt_dlp/extractor/soundcloud.py
=> [ie/soundcloud] Extract `genres`

yt_dlp/extractor/crunchyroll.py
Metadata can be extracted regardless of auth/premium, so this patch always makes it available if the user has passed `--ignore-no-formats-error`
Closes #9750
</details>
=> [ie/crunchyroll] Always make metadata available

yt_dlp/extractor/cbc.py
Update regex to support new cbc.ca URL format
Fixes #9825
</details>
=> [cbc.ca] support new URL format (fixes #9825)

yt_dlp/extractor/boosty.py
For paywalled posts (posts that require a subscription level), Boosty's API only returns the video URLs if the access token is set. This change attempts to extract the token from the provided cookies and sets the authorization header for the API call accordingly.
Fixes #9401
</details>
=> [ie/Boosty] include auth token in API call if available

yt_dlp/extractor/mixch.py
info_json:
```JSON
"comments": [
{
"author": "A",
"author_id": 42,
"id": "",  // could be an empty string
"text": "...",
"timestamp": 1700000000
},
{
"author": "B",
"author_id": 43,
"id": "item-1984",
"text": "...",
"timestamp": 1700000001
},
```
.
</details>
=> [ie/mixch] Add comment extraction; update a test

yt_dlp/extractor/vk.py
Sets the extension for http videos to `mp4`. While we can't be 100% sure that this will be the case for every video, I still think this is vastly preferable to `unknown_video`. Currently, all videos I checked are served as MP4s.
I've also added dash format extraction. [This video](https://vk.com/video-5642236_456240291) contains vp9 and av1 dash formats.
Fixes #5675
</details>
=> [ie/vk] Improve format extraction

yt_dlp/extractor/tva.py
Fixes the 404 error on tva/qub website. Used the fix proposed in the youtube-dl issue: https://github.com/ytdl-org/youtube-dl/issues/31240 
Fixes #
#4989
Took the code from this repo: https://github.com/dirkf/youtube-dl
This file exactly: https://github.com/dirkf/youtube-dl/blob/df-tva-extractor-ovrhaul/youtube_dl/extractor/tva.py
</details>
=> [ie/Qub] Fix extractor

yt_dlp/extractor/neteasemusic.py
Hello! I'm from https://github.com/yt-dlp/yt-dlp/pull/9197#issuecomment-2004082551.
Comparison:
```diff
[netease:program] Extracting URL: https://music.163.com/#/program?id=10109051 
[netease:program] 10109051: Downloading program info
- [netease:program] Downloading playlist 10109051 - add --no-playlist to download just the video 32591923
+ [netease:program] Downloading program 10109051 - add --no-playlist to download just the song 32591923
```
.
</details>
=> [ie/netease:program] Improve `--no-playlist` message

yt_dlp/extractor/canalalpha.py
HLS/DASH manifests are not parsed because wrong functions are used.
This PR makes the correction.
</details>
=> [ie/canalalpha] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/commonmistakes.py
Issue a proper error when a user passes a [blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) URL.
The old error message was not very helpful:
```
ERROR: Unable to handle request: Unsupported url scheme: "blob" (requests, urllib, websockets, curl_cffi)
```
</details>
=> [ie/commonmistakes] Raise error on blob URLs

yt_dlp/extractor/bilibili.py
Add `referer` header
Fixes #9892
</details>
=> [ie/bilibili] Add header to fix extraction

yt_dlp/extractor/hytale.py
Since CloudflareStreamIE is always used as the "final" extractor, making explicit use of it doesn't require yt-dlp to find the correct one itself.
</details>
=> [ie/hytale] Use CloudflareStreamIE explicitly

yt_dlp/extractor/xvideos.py
XVideos changed their quickies URL format, as such the extractor needs to be updated. The code has been checked using flake8 and the test has been updated and passes.
**This pull request introduces the following modifications:**
- Updates the quickies URL transformation to conform with the new XVideos URL format `https://www.xvideos.com/video.QUICKIES_ID/_`.
- Updates the quickies URL filter to be more lenient, since the quickies URL has quite a few variants _(e.g. can optionally include: `profiles/`, `amateur-channels/`)_.
- Updates ID match group to allow for letters as well, since XVideos updated their IDs to include letters.
**Example valid URLs with this fix:**
- `https://www.xvideos.com/lili_love#quickies/a/ipdtikh1a4c`
- …
=> [ie/XVideosQuickies] Fix extractor

yt_dlp/extractor/pornhub.py
Update PornHub login to use `email` field instead of `username`
Fixes #9717
Again, no tests were added since a dummy account and matching playlist ID are required
</details>
=> [ie/pornhub] Update login to email

yt_dlp/extractor/cda.py
Update to PR https://github.com/yt-dlp/yt-dlp/pull/6638
> This pull request updates age confirmation to work with the new form. The code is as it was proposed by @emqi, the original poster of https://github.com/yt-dlp/yt-dlp/issues/5980.
Looks like https://github.com/Szpachlarz is not active, so I updated it according to https://github.com/yt-dlp/yt-dlp/pull/6638#discussion_r1169983986. I hope it's ready to merge, write me if anything more requires to be updated.
Fixes https://github.com/yt-dlp/yt-dlp/issues/5980
</details>
=> [extractor/cda] Fix age restriction

README.md, yt_dlp/cookies.py
Currently, yt-dlp doens't support --cookies-from-browser Naver Whale browser because the browser uses its own directory in Windows, macOS, and Linux.
Luckily, Naver Whale is based on Chromium, so thanksfully I could just add a little bit of code.
Fixes https://github.com/yt-dlp/yt-dlp/issues/9307
- I didn't add a test because cookie-related tests seems that it doens't test each of browsers. But If it's needed, please tell me then I'll try my best.
- I did dog-fooding with macOS 14.2, Ubuntu Desktop 22.04, Windows 11. I failed on Windows because of https://github.com/yt-dlp/yt-dlp/issues/7271 but the user data directory is confirmed
</details>
edit: Add a mention for dog-fooding
=> [cookies] Add `--cookies-from-browser` support for Whale

.github/workflows/build.yml, README.md, bundle/py2exe.py, pyproject.toml, yt_dlp/networking/_requests.py
Revert [`6e36d17f`](<https://github.com/yt-dlp/yt-dlp/commit/6e36d17f404556f0e3a43f441c477a71a91877d9>) and add support for `requests` 2.32.2+ (see: [`psf/requests#6710`](<https://github.com/psf/requests/pull/6710/files>))
</details>
=> [rh:requests] Patch support for `requests` 2.31+, 2.32.2+

yt_dlp/extractor/crunchyroll.py
Credit to @stratuma for finding [this solution](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959). Also thanks to @napgiver for [bringing this to my attention](https://github.com/yt-dlp/yt-dlp/issues/9994#issuecomment-2125451825)
The extractor needs to use the Switch user-agent when making the stream endpoint request, and subsequently needs to invalidate the stream token to prevent being rate-limited.
This PR also fixes an oversight in cb2fb4a643949322adba561ca73bcba3221ec0c5 that caused the extractor to *not* always make metadata available, as [noted here](https://github.com/yt-dlp/yt-dlp/issues/9994#issuecomment-2123807032)
Fixes #9994
</details>
=> [ie/crunchyroll] Fix stream extraction 

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/godresource.py
This PR add GodResource extractor. This extractor only extract in `news.godresource.com` because i didn't have any link in `www.godresource.com` that have the video. This website is not giving reliable `title` so it just grab the `title` from html `title` tag (which is default to the site name, `God Resource`.
Fixes #9551
</details>
=> [ie/GodResource] Add extractor

yt_dlp/extractor/brilliantpala.py
Fixes #9771
Check if cookies are invalidated.
</details>
=> [ie/brilliantpala] Fix login

yt_dlp/extractor/tele5.py
Closes #3051, Closes #7955
Supersedes #8501
Supersedes #9792
</details>
=> [ie/tele5] Overhaul extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/dangalplay.py
=> [ie/dangalplay] Add extractors

yt_dlp/extractor/piapro.py
Piapro had a design overhaul and all extractors broke. I mostly just updated the relevant regexes.
Fixes #9884
- Fixed the piapro extractor
</details>
=> [ie/Piapro] Fix extractor

README.md, yt_dlp/options.py
=> [cleanup] Misc 2024.05.27

yt_dlp/extractor/peertube.py
Can be tested with current livestreams by searching sepiasearch: https://sepiasearch.org/search?search=&isLive=true I talked to bashonly on the discord and he wrote this and said I could PR it.
Sets is_live to true and uses the m3u8 method.
Fixes #2055 
</details>
=> [peertube] add livestream support

yt_dlp/extractor/orf.py
=> [ie/orf:on] Support segmented episodes

yt_dlp/extractor/francetv.py
=> [ie/francetv] Fix tokenized URL extraction

yt_dlp/extractor/francetv.py
=> [ie/francetv] Detect and raise errors for DRM

yt_dlp/extractor/brightcove.py
=> [ie/brightcove] Upgrade requests to HTTPS

yt_dlp/extractor/cloudflarestream.py
Addresses https://github.com/yt-dlp/yt-dlp/issues/9171#issuecomment-2179269086
</details>
=> [ie/cloudflarestream] Fix `_VALID_URL` and embed extraction

test/test_cookies.py, yt_dlp/cookies.py
Certain Linux distros such as [Ubuntu](https://askubuntu.com/a/227669) put the distro name in the colon separated fields in `$XDG_CURRENT_DESKTOP`, like `ubuntu:GNOME`. Currently, yt-dlp takes the first field as the DE and marks it as unknown, resulting in failure to load cookies:
```
[Cookies] Loading cookie      0/  4452XDG_CURRENT_DESKTOP is set to an unknown value: "ubuntu"                                                                  
WARNING: cannot decrypt v11 cookies: no key found
```
This pull request changes the code to go through the fields in `$XDG_CURRENT_DESKTOP` for a known desktop environment.
</details>
=> [cookies] Fix getting Linux desktop env from `$XDG_CURRENT_DESKTOP` in Ubuntu

yt_dlp/extractor/matchtv.py
=> [ie/matchtv] Fix extractor

yt_dlp/extractor/cloudycdn.py
New videos on CloudyCDN seem to have separate audio and video formats. The current implementation of `_parse_m3u8_formats_and_subtitles` always treats the video format as also containing audio if the `CODECS` attribute is missing, so videos are being downloaded without sound. There are PRs that could potentially fix this globally (#5924, #9562), but since they seem to be in limbo, here is a fix for this specific extractor.
Example with combined audio and video: https://embed.cloudycdn.services/ltv/media/46k_d23-6000-105
Example with separate audio and video: https://embed.cloudycdn.services/ltv/media/08j_d24-6000-074
</details>
=> [ie/cloudycdn] Fix videos with separate audio

yt_dlp/extractor/mediasite.py
Fix regression in add96eb9f84cfffe85682bf2fb85135746994ee8
Closes #10270
</details>
=> [ie/mediasite] Fix extraction

pyproject.toml, yt_dlp/extractor/atresplayer.py, yt_dlp/extractor/cbc.py, yt_dlp/jsinterp.py, yt_dlp/networking/_requests.py
Bumps ruff to 0.5.x series.
[PLE0643](https://docs.astral.sh/ruff/rules/potential-index-error/) was added to the ignores as there are false positives:
```python
a = [0, 0]
b = [*a, 0][2]
```
</details>
=> [cleanup] Bump Ruff to 0.5.x

yt_dlp/extractor/bitchute.py
Hotfix for bitchute by fetching data from old site. Long-term, the extractors should be rewritten to make use of the new API.
Fixes #10293
</details>
=> [ie/bitchute] Fix extractors

yt_dlp/extractor/mlb.py
=> [ie/mlbtv] Fix extraction

yt_dlp/extractor/digitalconcerthall.py
Closes #10228
Allow downloading individual works from a url like
https://www.digitalconcerthall.com/de/work/51854-4
This change still downloads the concert page, but only downloads the correct item from the playlist.
</details>
=> [ie/digitalconcerthall] Rework extractor

yt_dlp/extractor/afreecatv.py
AfreecaTV's vod API is not compatible with the TLS v1.2 cipher option used by yt-dlp.
Rather than modifying the cipher in yt-dlp core to solve the problem, I think it would be simpler to use HTTP for AfreecaTV's Vod API. Therefore, this is a patch that downgrades existing API requests from https to http.
I will submit a PR to revert this commit when the API server problem is resolved.
Fixes #8187
</details>
=> [ie/AfreecaTV] downgrade api protocol to http

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/afreecatv.py
Support afreecaTv catch-story(similar to YouTube Shorts)
Closes #10112
</details>
=> [afreecatv] Support catchstory

README.md, yt_dlp/extractor/orf.py
Fixes #10142
Can be used with
```
--extractor-args "orfon:prefer_segments_playlist" --concat-playlist never
```
</details>
=> [ie/orf:on] Allow downloading of video in segments

yt_dlp/extractor/pokergo.py
Sometimes PokerGO API returns no `show_tags` for the video, this results in `StopIteration` exception and video is not downloaded.
API response example without `show_tags` for video https://www.pokergo.com/videos/b649b11a-ecec-4e00-932f-26f0e4a1201a
<details><summary>large json file</summary>
```
{
"data": {
"id": "b649b11a-ecec-4e00-932f-26f0e4a1201a",
"property_id": "1dfb3940-7d53-4980-b0b0-f28b369a000d",
"title": "WSOP 2024 Bracelet Events | Event #65 $5K Seniors High Roller",
"description": "The Event #65: $5,000 Seniors High Roller final table is set at the 2024 World Series of Poker, with Mark Checkwicz holding the chip lead. Checkwicz leads ahead of Kevin Nathan, Michael Vela, Samuel Wagner, Arie Kilper, and Bruno Lopes, as the …
```
=> [ie/pokergo] Make metadata extraction non-fatal

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/graspop.py
Add new extractor: Graspop VoD: https://vod.graspop.be/fr/
</details>
=> [ie/graspop] Add extractor

yt_dlp/extractor/nuum.py
Pass Referer header to m3u8 playlists
Fixes https://github.com/yt-dlp/yt-dlp/issues/10310
</details>
=> [ie/nuum] Pass Referer header to m3u8 playlists

yt_dlp/extractor/banbye.py
Fix BanBye extractor by not hardcoding video URLs.
The updated logic in the extractor now handles HLS videos by attempting to retrieve formats from both reachable and unreachable m3u8 playlists. If the master playlist is unreachable (e.g., returns a 404 error), it falls back to using the JSON data provided by the API.
This change ensures robustness in fetching video formats from BanBye, accommodating different scenarios where the master playlist might not be accessible.
Fixes #8584
</details>
=> [ie/banbye] Fix extractor

.gitignore, Changelog.md, Makefile, README.md, devscripts/changelog_override.json, yt_dlp/options.py
=> [cleanup] Misc (for 2024.07.xx hotfix release)

yt_dlp/extractor/douyutv.py
`cdn.bootcdn.net` is considered to be under the control of a bad actor, see https://sansec.io/research/polyfill-supply-chain-attack for more information.
This PR removes the URL for another one serving the same content.
</details>
=> [ie/douyutv] Do not rely on a CDN under the control of a bad actor

yt_dlp/extractor/abematv.py
Set `availability` field.
</details>
=> [ie/abematv] set availability

yt_dlp/extractor/chzzk.py
CHZZK recently upgraded their API version from v2 to v3. The v2 endpoint is still working, but it is expected to be unavailable soon, just like v1.
I compared the API responses and found no difference, so it does not affect the functionality of yt-dlp.
</details>
=> [chzzk] Upgrade API version to v3

yt_dlp/extractor/yle_areena.py
=> [ie/yle_areena] Fix subtitle extraction

yt_dlp/extractor/yle_areena.py
=> [ie/yle_areena] Fix metadata extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/vtv.py, yt_dlp/extractor/vtvgo.py
Add extractor for [VTV Go](https://vtvgo.vn/)
and the [video section](https://vtv.vn/truyen-hinh-truc-tuyen.htm) of vtv.vn
Also support only for vietnamese and videos only (no live broadcast)
</details>
=> [ie/vtv] Add extractors

test/test_jsinterp.py, yt_dlp/jsinterp.py
Implements prototype resolving for known types that are using `Function.prototype.call` and `Function.prototype.apply`
</details>
=> [jsinterp] Implement `Function.prototype` resolving for `call` and `apply`

.github/workflows/build.yml, README.md, bundle/docker/static/entrypoint.sh, pyproject.toml, test/test_networking.py, yt_dlp/networking/_curlcffi.py
Adds support for upcoming curl-cffi 0.7.X
0.6.X is skipped due to issues when running on windows.
Currently leaving support for 0.5.10 in case there are issues. Will remove in future
</details>
=> [rh:curl_cffi] Support curl-cffi 0.7.X

yt_dlp/extractor/box.py
=> [ie/box] Support enterprise URLs

yt_dlp/extractor/tv5mondeplus.py
=> [ie/tv5monde] Fix impersonation (Bugfix for 9b95a6765a5f6325af99c4aca961587f0c426e8c)

test/test_networking.py, test/test_websockets.py, yt_dlp/networking/_curlcffi.py, yt_dlp/networking/_requests.py, yt_dlp/networking/_urllib.py, yt_dlp/networking/_websockets.py, yt_dlp/networking/common.py
- Add `legacy_ssl` request extension to allow `legacy_ssl_support`/`--legacy-server-connect` to be toggled per-request.
- Supported by all handlers, with CurlCFFIRH ignoring it
- Added some misc cookie tests and fixes
Fixes #
</details>
=> [networking] Add `legacy_ssl` request extension

yt_dlp/extractor/epidemicsound.py
Fixed Epidemic Sound SFX unsupported url pattern (https://www.epidemicsound.com/sound-effects/tracks/2f02f54b-9faa-4daf-abac-1cfe9e9cef69/)
Fixes #10435
</details>
=> Fix Epidemic Sound SFX unsupported url

yt_dlp/extractor/adn.py
ADN (Animation Digital Network) changed their domain to animationdigitalnetwork.com and removed local domains .fr and .de
Fixes #10442
</details>
=> [ie/adn] domain change from .fr/.de to .com

yt_dlp/extractor/youtube.py
Bugfix for 8b8b442cb005a8d85315f301615f83fb736b967a
</details>
=> [ie/youtube] Fix initial player response usage

yt_dlp/extractor/youtube.py
Fixes android clients being extracted first when using `player_client=all`, causing the broken android formats to be used over other existing web formats.
</details>
=> [ie/youtube] Reduce android client priority

README.md, test/test_utils.py, yt_dlp/extractor/digitalconcerthall.py, yt_dlp/utils/_utils.py
Addresses https://github.com/yt-dlp/yt-dlp/issues/10228#issuecomment-2198592768
</details>
=> [ie/digitalconcerthall] Extract HEVC and FLAC formats

yt_dlp/YoutubeDL.py
=> [core] Fix `noprogress` if `test=True` with `--quiet` and `--verbose`

pyproject.toml, yt_dlp/utils/_utils.py
=> [cleanup] Misc

yt_dlp/extractor/mlb.py
=> [ie/MLBTV] Fix extractor

yt_dlp/extractor/dplay.py
=> [ie/DiscoveryPlus] Support olympics URLs

yt_dlp/extractor/abematv.py
I noticed that episodes that WILL become free in the future have `"onDemandType":3`, even if they are premium-only at that time. As a result, their availability is not correctly recognized. Instead, you can use `"label":{"free":true}` to determine the availability.
</details>
=> [ie/abematv] fix episode availability extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/common.py, yt_dlp/extractor/learningonscreen.py
=> [ie/learningonscreen] Add extractor

yt_dlp/extractor/mlb.py
If a game is rescheduled for a later date (due to weather etc) then yt-dlp may have looked under the original/wrong date for broadcast data. This PR fixes that
Closes #10606
</details>
=> [ie/mlbtv] Fix makeup game extraction

yt_dlp/extractor/olympics.py
=> [ie/olympics] Fix extractor

yt_dlp/extractor/mediaklikk.py
The player url is not downloadable without a valid referer header any more.
Fixes #10588
</details>
=> [ie/mediaklikk] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/kick.py
Adds clips support for kick.com
IE_Names are added so user can see which extractor is used like twitch.tv
Minor adjustments on KickVODIE and KickIE
Tests are passing **for all 3 extractors**. DO NOT use hatch test, the extraction requires impersonation(curl_cffi).
Fixes #8115
</details>
=> [ie/kick:clips] Add extractor

yt_dlp/extractor/youku.py
This pull request addresses the issue where the Youku server returns error code -6004 with the message “客户端无权播放” (client is not authorized to play), specifically referenced in issue #10549. The error was occurring due to an invalid ccode value. The ccode has been updated to a valid value of 0564, which resolves the authorization issue and allows the client to play the video as expected.
Fixes #10549
</details>
=> Changed ccode value to 0564 in youku.py

yt_dlp/extractor/olympics.py
Bugfix for 2f1ddfe12a2c174bc777264c5c8ffe7ca0922d94
Closes #10592
</details>
=> [ie/olympics] Fix extraction

test/test_youtube_signature.py, yt_dlp/extractor/youtube.py
Fix player regex once again
</details>
=> [ie/youtube] Fix `n` function name extraction for player `b12cc44b`

yt_dlp/extractor/cbc.py
This PR adds support for downloading livestream events after the event has passed, if on-demand replay is available. An example URL for such a case is: https://gem.cbc.ca/live-event/42314
The download process is the same as CBC Gem live content, but the `formattedIdMedia` key-value pair is in a different part of the video info, it does not work for me with `appCode='mpx'`, and obviously it is not live.
</details>
=> [gem.cbc.ca] Add support for downloading live replay content

yt_dlp/extractor/niconico.py
=> [ie/niconico] Fix extractor

yt_dlp/extractor/bilibili.py
\[site-bug\] fix bilibiliie valid url regex
TODOs:
done in 6dba8cba2
Fixes #10739 
<details><summary>Template</summary> 
6dba8cba2, 86aeffa, etc.
8b889f0ab: Used bashonly's patch from https://github.com/yt-dlp/yt-dlp/issues/10739#issuecomment-2287232163
</details>
=> [ie/bilibili] fix bilibiliie valid url regex

yt_dlp/extractor/adn.py
ADN changed their API: you now always need the X-Target-Distribution header. Instead of the URL slug it is now required to only send the season ID.
Fixes #10748
</details>
=> [ie/adn] adjustments for API changes

yt_dlp/extractor/asobistage.py
The link to the ended live streaming will be redirected to its record, hence the type will be also changed:
```console
$ curl -s -XGET -I -L 'https://asobistage.asobistore.jp/event/<event>/player/live'
HTTP/1.1 307 Temporary Redirect
...
Location: /event/<event>/archive/live
...
```
Log:
```
[AsobiStage] Extracting URL: https://asobistage.asobistore.jp/event/<event>/player/live 
[AsobiStage] <event>/player/live: Downloading webpage
[AsobiStage] <event>/archive/live: Getting channel list 
```
.
</details>
=> [ie/asobistage] Support redirected URLs

yt_dlp/extractor/radiko.py
https://radiko.jp/#!/ts/INT/20240809230000 - interfm, 2024-08-09 23:00
https://radiko.jp/#!/ts/FMT/20240809230000 - Tokyo FM, 2024-08-09 23:00
they both aired at the same time, so they have the same ID of `20240809230000`
but they're completely different content from completely different stations/"channels"
(urls are geo-blocked to Kantō, Japan + expire at 2024-08-17 05:00 JST)
This PR adds the station ID to the video ID, changing the examples to `INT-20240809230000` and `FMT-20240809230000` respectively.
</details>
=> [ie/radiko] make video_ids unique by including station ID

yt_dlp/extractor/eurosport.py, yt_dlp/extractor/tvn24.py
Add local Eurosport variants. I needed to disable xff as that would make videos unavailable even when in the correct region.
Potentially in a follow-up PR the correct XFF header can be automaticly determined.
</details>
=> [ie/Eurosport] Support local variants

.github/workflows/core.yml, .github/workflows/quick-test.yml, pyproject.toml, test/test_websockets.py, yt_dlp/networking/_websockets.py
ssl_context was deprecated with an a deprecation warning causing our CI to fail (and maybe hang? will find out on this pr...). it was replaced with `ssl`.
bumped min websockets version to v13
</details>
=> [rh:websockets] Upgrade Websockets to v13

yt_dlp/extractor/rutube.py
Part of the change is copied from https://github.com/yt-dlp/yt-dlp/pull/10836#discussion_r1729569253.
Closes #4418, Closes #4594
</details>
=> [ie/Rutube] Support livestreams

.github/ISSUE_TEMPLATE/1_broken_site.yml, .github/ISSUE_TEMPLATE/2_site_support_request.yml, .github/ISSUE_TEMPLATE/3_site_feature_request.yml, .github/ISSUE_TEMPLATE/4_bug_report.yml, .github/ISSUE_TEMPLATE/5_feature_request.yml, .github/ISSUE_TEMPLATE/6_question.yml, .github/workflows/antispam.yaml, devscripts/make_issue_template.py
Temporary measure to combat the issue comment spam epidemic. Lock all new issues until they can be triaged to prevent the malware links from being posted.
</details>
=> [ci] Add issue tracker anti-spam protection

.github/workflows/build.yml
Fixes broken `macos` build flow
</details>
=> [build] Pin `delocate` version for `macos`

yt_dlp/extractor/khanacademy.py
Updates the hash used by the kahn acadamy extractor.
Calculating the hash ourselves is imo. not viable.
Fixes #10912
</details>
=> [ie/khanacademy] Fix extractor

yt_dlp/extractor/samplefocus.py
Sets the referrer for downloading the mp3, but also enables impersonation, as the main website is behind Cloudflare, and I was having trouble accessing it.
Fixes #10945
</details>
=> [ie/SampleFocus] Fix extractor

test/test_networking.py, yt_dlp/networking/_helper.py
=> [networking] Fix handler not being added to RequestError

yt_dlp/extractor/youtube.py
=> [ie/youtube] Support new shorts tab view model

yt_dlp/extractor/common.py
This jwplayer url contains https://cdn.jwplayer.com/v2/media/W86PgQDn the following source entry:
```json
{
"file": "https://cdn.piramide.tv/video/wWtBAORdJUTh/manifest.m3u8",
"type": "video/mp4"
}
```
This currently causes the m3u8 manifest to be downloaded as a single file with a .mp4 extension.
With this PR the logic is changed to prefer the actual file extension instead of the one by the mime type.
</details>
=> [core] Fix jwplayer format parsing

yt_dlp/extractor/bandcamp.py
The user page is lazy-loaded from the JSON embedded in the data-client-items attribute. Let's use it, if it exists.
</details>
=> [ie/bandcamp] Extract extended user page

yt_dlp/extractor/rtp.py
On the zigzag subdomain, the file property for the RTPPlayer constructor object is inlined, as opposed to being declared before the RTPPlayer instantiation. Add support for this.
</details>
=> [ie/RTP] Support more subpages

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/huya.py
This PR adds a new extractor HuyaVideoIE in [huya.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/huya.py) to handle "moment" videos.
Fixes #10679 
</details>
=> [ie/huya:video] Add extractor

yt_dlp/extractor/ximalaya.py
This PR try to fix #6928,  It support downloading VIP-restricted audios and formats using cookies. cc @bashonly @pukkandan   
@coletdjnz  @Sparh4wk
- example VIP audio for test: https://www.ximalaya.com/album/70349771
- `./yt-dlp -v --no-cookies --no-cache-dir https://www.ximalaya.com/album/70349771` , raise error like in #6928 
- `./yt-dlp -v --cookies www.ximalaya.com_cookies.txt https://www.ximalaya.com/album/70349771`, works perfect
https://github.com/user-attachments/assets/50641e7a-a274-4ded-9e6e-f8c115546775
</details>
=> [ximalaya.com] Add VIP support

yt_dlp/extractor/common.py
When a website returns a response with an incorrect encoding header, the request handler library will throw when trying to decode the content. This is currently caught by our networking code for `urllib`, since it decodes on request, but it is not caught for `requests` because `urllib3` decodes on read instead. This was causing non-fatal `_download_webpage` calls to throw when the `requests` RH is being used. This patch adds error handling in the extractor core code to handle the decode error for `requests`/`urllib3`.
</details>
=> [ie] Handle decode errors when reading responses

yt_dlp/extractor/pinterest.py
Fixes Pinterest regex
Some Pinterest videos now have a new format:
`https://pinterest.com/pin/dive-into-serenity-blue-lagoon-pedi-nails-for-a-tranquil-and-refreshing-spa-experience-video-in-2024--2885187256207927`
closes #10850 
</details>
=> Fix pinterest regex

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/lnk.py
The lnkgo.lt platform is no longer active and is completely replaced by lnk.lt. This PR also renames the module filename.
</details>
=> [ie/LnkGo] Remove extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/screenrec.py
This adds extractor for screen recording sharing website https://screenrec.com/.
Fixes #9780
</details>
=> [ie/screenrec] Add extractor

yt_dlp/extractor/tenplay.py
Switching to `vod.ten.com.au` API
Fixes #10926
</details>
=> [ie/tenplay] Fix extractor

yt_dlp/extractor/servus.py
Video playback api changed. The Endpoint used to get the description is also no longer available. Now using the webpage and also extracting some additional metadata to make that extra request worth it.
Fixes #10941
</details>
=> [ie/Servus] Fix extractor

yt_dlp/extractor/xinpianchang.py
=> [ie/Xinpianchang] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/sen.py
=> [ie/Sen] Add extractor

yt_dlp/extractor/iprima.py
The Zoom IPrima video ID is found at a different location in the page source ( e.g. at https://zoom.iprima.cz/porady/krasy-kanarskych-ostrovu/tenerife-v-risi-ohne).
Fixes #6100
</details>
=> [ie/IPrima] Fix extractor

yt_dlp/extractor/bilibili.py
Change `_HEADERS` from `'Referer': 'https://www.bilibili.com/'` to `'Referer': 'https://www.bilibili.tv/'`
Fixes https://github.com/yt-dlp/yt-dlp/issues/10996
</details>
=> [ie/BiliIntl] Fix referer header

yt_dlp/extractor/youtube.py
Fixes bug in 3a3bd00037e9908e87da4fa9f2ad772aa34dc60e
</details>
=> [ie/youtube] Fix `format_note` (Bugfix for 3a3bd00)

yt_dlp/cookies.py
=> [cookies] Improve error message for Windows `--cookies-from-browser chrome` issue

.github/workflows/build.yml, pyproject.toml
(Partially) fixes #10294 (?)
</details>
=> [build] Bump PyInstaller version pin to `>=6.10.0`

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/mojevideo.py
Closes #8159; closes #8157.
</details>
=> [ie/Mojevideo] Add extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/snapchat.py
=> [ie/SnapchatSpotlight] Add extractor

yt_dlp/extractor/ertgr.py
Only download the primary video. Also slightly refactors the extractor using traverse_obj.
Fixes #8955
</details>
=> [ie/ertgr] Fix video extraction

yt_dlp/extractor/rumble.py
Download from Rumble broke back in August 24. User bashonly put up a patch to fix the Rumble extractor and make it more robust. He asked someone to create the PR so I did so. He placed the patch into the public domain. 
Fixes #10833
User bashonly placed the patch into the public domain in the following message thread: https://github.com/yt-dlp/yt-dlp/issues/10833
</details>
=> Make Rumble extractor more robust.

yt_dlp/extractor/svt.py
SVT News slightly changed its API 
Small one-line fix
</details>
=> [ie/SVTPage] Fix extractor

yt_dlp/extractor/bilibili.py
=> [ie/bilibili] Fix chapters and subtitles extraction

yt_dlp/extractor/wistia.py
=> [ie/wistia] Support password-protected videos

yt_dlp/extractor/youtube.py
=> [ie/youtube:clip] Prioritize `https` formats

yt_dlp/extractor/niconico.py
=> [ie/niconico] Fix m3u8 formats extraction

yt_dlp/extractor/yle_areena.py
=> [ie/YleAreena] Support podcasts

yt_dlp/extractor/kick.py
=> [ie/kick:clips] Support new URL format

yt_dlp/extractor/dropbox.py, yt_dlp/extractor/yandexdisk.py
Supported password, thumbnail
Fixes #9864
</details>
=> [ie/dropbox] Fix password-protected video support

yt_dlp/extractor/loom.py
=> [ie/loom] Fix hls format

devscripts/changelog_override.json, yt_dlp/update.py
Related:
- https://github.com/yt-dlp/yt-dlp/issues/10086
- https://github.com/yt-dlp/yt-dlp/issues/10087
- https://github.com/yt-dlp/yt-dlp/pull/8638
</details>
=> Raise minimum recommended Python version to 3.9

yt_dlp/extractor/applepodcasts.py, yt_dlp/extractor/common.py
Apple rewrote podcasts.apple.com to turn it into a web app, but in the process eliminated the old JSON data structure used to extract podcast metadata and introduced a new one.  Modify the ApplePodcasts info extractor to account for the change in JSON.
Fixes #10809
</details>
=> [ie/ApplePodcasts] Fix extractor

.github/workflows/core.yml, .github/workflows/quick-test.yml, pyproject.toml
Tests, especially websockets, are quite flaky. This PR reruns failed tests up to 3 times, with 3 seconds inbetween them, to hopefully get more accurate CI results.
Open for know tweaking, 3 reruns and 3 seconds is what came to mind.
</details>
=> [test] Rerun failed tests

yt_dlp/extractor/patreon.py
=> [ie/patreon] Extract all m3u8 formats for locked posts

yt_dlp/extractor/noodlemagazine.py
The site now embeds the urls of the videos inside a json in the webpage itself. So the previous method no longer works. 
All we need now is to download the json from the webpage itself.
Fixes #9936 
</details>
=> [NoodleMagazine] fix extractor

yt_dlp/extractor/cwtv.py
Update API URL
Fixes #11131
</details>
=> [ie/cwtv] Fix extractor

yt_dlp/extractor/weverse.py
=> [ie/weverse] Fix extractor

yt_dlp/extractor/drtv.py
This pull request addresses an issue with the DRTV extractor where the login system has changed. Now, using the mobile API on Android, we can retrieve an "anonymous token" for stream access, avoiding the need for email and password login. The relevant API request was modified from using the web browser endpoint to using the mobile phone API to obtain this token.
It should be noted that it seems like DRTV has rolled back the new system for now—probably due to too much load on the servers—but they will bring the new system back. Also, the mobile API works with the new system as well.
Fixes #11137
</details>
=> [ie/drtv] Fix DRTV token extraction by using android API

yt_dlp/extractor/cwtv.py
=> [ie/cwtv] Fix extraction

yt_dlp/extractor/patreon.py
=> [ie/patreon:campaign] Make `_VALID_URL` more strict

yt_dlp/YoutubeDL.py
This fixes python 3.9 compat in traceback generation for e59c82a74cda5139eb3928c75b0bd45484dbe7f0
</details>
=> Fix Python 3.9 compatibility in traceback generation (Fix e59c82a74cda5139eb3928c75b0bd45484dbe7f0)

README.md, yt_dlp/extractor/generic.py
Adds the `impersonate` extractor arg to the generic extractor.
Also automatically tries to use impersonation for the generic website request if impersonation is available.
Fixes #11150
</details>
=> [ie/generic] Add `impersonate` extractor arg

README.md, devscripts/make_lazy_extractors.py, yt_dlp/YoutubeDL.py, yt_dlp/plugins.py
=> [build] `make_lazy_extractors`: Force running without plugins

test/test_utils.py, yt_dlp/utils/_utils.py
Reimplement `sanitize_path` function without usage of `os.path` to make it behave the same in all Python versions.
Fixes #8136, Fixes #8137
</details>
=> [utils] `sanitize_path`: Reimplement function

yt_dlp/extractor/reddit.py
This is a small and quick fix.
Fixes #10924.
</details>
=> [ie/reddit] Improve HTTP 403 error message

yt_dlp/utils/_utils.py
Fixes regression introduced in fb8b7f226d251e521a89b23c415e249e5b788e5c
Ref: https://github.com/pyinstaller/pyinstaller/pull/8634
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://pyinstaller.org/en/v6.10.0/common-issues-and-pitfalls.html#independent-subprocess
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://pyinstaller.org/en/v6.10.0/CHANGES.html#incompatible-changes
Closes #11259
</details>
=> [utils] `Popen`: Reset PyInstaller environment

yt_dlp/extractor/substack.py
=> [ie/substack] Resolve podcast file extensions

yt_dlp/extractor/funk.py
Site changed their subdomain yet again
</details>
=> [ie/Funk] Extend `_VALID_URL`

yt_dlp/extractor/imgur.py
This pull request adds support for the new format of imgur URLs which contain a title slug, for example:
https://imgur.com/mrw-gifv-is-up-running-without-any-bugs-A61SaA1
instead of simply:
https://imgur.com/A61SaA1
It doesn't seem a bug was raised for this, which seems surprising
</details>
=> [ie/imgur] Support new URL format

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/cda.py
It implements CDAFolderIE supporting folders in CDA
Closes: https://github.com/yt-dlp/yt-dlp/issues/5429
</details>
=> [ie/cda] Support folders

yt_dlp/extractor/imgur.py
=> [ie/imgur] Fix thumbnail extraction

yt_dlp/extractor/cbc.py
Fix 1080p stream detection for CBC Gem, and remove obsolete function.
The URL format the CBC uses has changed and is a lot simpler.  `_find_secret_formats` is no longer required and can be replaced with a single `re.sub` that removes the `manifestType=` filter.
The change was tested with `https://gem.cbc.ca/media/murdoch-mysteries/sXXeXX` for a number of seasons and episodes.
```
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/murdoch-mysteries/s18e01
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading m3u8 information
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading secret XML
WARNING: [gem.cbc.ca] murdoch-mysteries/s18e01: Failed to parse XML: syntax …
```
=> [CBC Gem] Fix 1080p detection after URL format change

yt_dlp/extractor/mitele.py, yt_dlp/extractor/telecinco.py
*IMPORTANT: PRs without the template will be CLOSED
Description of your pull request and other information
add referer header to _extract_m3u8_formats
Return http_header to mitele for proper origin and referer headers
Properly usage of geo restriction. Allowing download with geo-restrict-proxy
follow yt-dlp coding conventions, use traverse_obj
Fixes https://github.com/yt-dlp/yt-dlp/issues/10986
And fixes https://github.com/yt-dlp/yt-dlp/issues/11106
Template
Before submitting a pull request make sure you have:
At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions) …
=> [ie/Telecinco] Fix extractor: Add headers

yt_dlp/extractor/tubitv.py
Fix [ie/tubitv](https://tubitv.com/tv-shows/408804/s02-e01-the-grass-the-furious) episode title having whitespaces at the end.
Fixes #10794
</details>
=> [ie/tubitv] strip spaces from episode title

.github/workflows/build.yml, devscripts/changelog_override.json
=> [cleanup] Misc (post-release)

.github/workflows/build.yml, CONTRIBUTING.md, README.md, devscripts/make_issue_template.py, pyproject.toml, setup.cfg, test/test_update.py, yt_dlp/__init__.py, yt_dlp/compat/compat_utils.py, yt_dlp/compat/functools.py, yt_dlp/extractor/pornbox.py, yt_dlp/plugins.py, yt_dlp/update.py, yt_dlp/utils/_utils.py
=> Remove Python 3.8 support

README.md, yt_dlp/extractor/generic.py
Fixes regression in edfd095b1917701c5046bd51f9542897c17d41a7
Fixes #11335
</details>
=> [ie/generic] Do not impersonate by default

yt_dlp/extractor/niconico.py
Updated the API version for NiconicoUserIE, as v1 seemingly stopped working some time back. Also improved the _VALID_URL string to allow for the /video pathname
Partially addresses #10084
NiconicoUserIE, as it gave a 404 error before; as well as its _VALID_URL, as links with /video at the end would default to the generic extractor.
</details>
=> [ie/niconico] Fix NiconicoUserIE

yt_dlp/extractor/common.py
=> [ie] Safeguard against improper language values in ISM manifests

devscripts/changelog_override.json, devscripts/make_changelog.py
=> [devscripts] `make_changelog`: Parse full commit message for fixes

yt_dlp/extractor/ccma.py
Changed the valid domain from ccma.cat to 3cat.cat
Also changed the test urls, it just need time to stop working the redirections
Fixes #11163
</details>
=> [ie/ccma] Update ccma.cat domain to 3cat.cat

yt_dlp/extractor/soundcloud.py
=> [ie/Soundcloud] Extract artists

test/test_traversal.py, yt_dlp/utils/_utils.py, yt_dlp/utils/traversal.py
Fixes b6dc2c49e8793c6dfa21275e61caf49ec1148b81
</details>
=> [utils] Allow partial application for even more functions

yt_dlp/extractor/bfmtv.py
Fix broken extractors. The generic would have worked.
</details>
=> [ie/bfmtv] Fix extractors

yt_dlp/extractor/chzzk.py
Fixes #11226
I can't add a proper test for this PR because the issue occurs for at least 2 hours.
I've written a script to automatically download replays for a few streamers and am testing it now.
If this commit works well for a week, I'll un-draft it.
</details>
=> [ie/chzzk] Fix video(fast replay) download

yt_dlp/extractor/dailymotion.py
This is useful for the thumblr extractor, since that can return URL results with the shortened links to DailymotionIE. It also saves a web request if passed to yt-dlp.
While at it, I also fixed the thumbnail code and extracted subtitles from m3u8 playlists ([example](https://dai.ly/x94cnnk)).
</details>
=> [ie/Dailymotion] Support shortened URLs

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/gamedevtv.py
Adds support for gamedev.tv
</details>
=> [ie/GameDevTV] Add extractor

yt_dlp/dependencies/Cryptodome.py
To help with https://github.com/yt-dlp/yt-dlp/issues/11479 and https://www.reddit.com/r/youtubedl/comments/1gn7ljh/python39_and_latest_ytdlp/
Still unsure what exactly causes this, but at least this should prevent broken cryptodome installations from breaking yt-dlp.
</details>
=> [core] Catch broken cryptodome installations

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/spreaker.py
This is useful for the Spreaker extractor.
1. Added support for Episodes with Access Keys.
</details>
=> [ie/spreaker] Support episode pages and access keys

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/rutube.py
Rework the extractors
Fixes #9694
Fixes #10104
Fixes #11117
Fixes #11415
Fixes #11476
</details>
=> [ie/rutube] Rework extractors

yt_dlp/extractor/cloudflarestream.py
CloudflareStream has various domains and videodelivery.net has been returning unreliable data when doing GET requests.
In this pull request I change the domain being used to cloudflarestream.com, the one being used in official documentation: https://developers.cloudflare.com/stream/
With example video: https://watch.cloudflarestream.com/e8766bfd7771e53b5dc26c76b650d91a/
These are the results:
GET https://videodelivery.net/eaef9dea5159cf968be84241b5cedfe7/manifest/video.mpd
```
<html>
<body>Object not found</body>
</html>
```
(404)
GET https://cloudflarestream.com/eaef9dea5159cf968be84241b5cedfe7/manifest/video.mpd
```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" …
```
=> [ie/CloudflareStream] Avoid extraction via videodelivery.net

yt_dlp/extractor/goplay.py
This fixes the GoPlay extractor for both episodes and movies. They recently switched to Next.js
Fixes #10857
</details>
=> [ie/goplay] Fix extractor

yt_dlp/YoutubeDL.py, yt_dlp/extractor/afreecatv.py, yt_dlp/extractor/common.py
=> [ie/soop] Fix thumbnail extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/bandlab.py
For now, only track, video, revision, collection, and album extraction. User/Band support can be added later.
Fixes #7750
</details>
=> [ie/bandlab] Add extractors

yt_dlp/extractor/redgifs.py
This PR applies [the patch provided by bashonly](https://github.com/yt-dlp/yt-dlp/issues/7382#issuecomment-1602434417) in Issue #7382, and updates the tests accordingly. `hatch test RedGifsUserIE_all` reports that all tests pass.
Fixes #7382 
Fixes #9131 
- _@bashonly, I assume I shouldn't sign off on this unilaterally, since the patch came from you_
</details>
=> [ie/RedGifsUser] Fix extraction

yt_dlp/extractor/youtube.py
=> [ie/youtube] Remove broken OAuth support

yt_dlp/extractor/chaturbate.py
`_extract_from_webpage` is a reserved name, breaking embed detection.
</details>
=> Fix embed detection (Bugfix for 720b3dc453c342bc2e8df7dbc0acaab4479de46c)

yt_dlp/extractor/youtube.py
Support new lockupViewModel podcast pages
</details>
=> [ie/youtube] Fix podcasts tab extraction

README.md, yt_dlp/extractor/digitalconcerthall.py
Closes #11404
Supersedes #11436
</details>
=> [ie/digitalconcerthall] Support login with access/refresh tokens

yt_dlp/extractor/reddit.py
=> [ie/reddit] Improve error handling

Changelog.md, devscripts/changelog_override.json, yt_dlp/extractor/dailymotion.py
=> [cleanup] Misc (2024.11 part 2)

yt_dlp/extractor/stripchat.py
Recent changes in Stripchat API, resulting in No Stream Found Error
Fixes #11587
</details>
=> FIX: Stripchat recent changes

README.md, yt_dlp/YoutubeDL.py
Adds `playlist_webpage_url` field
Fixes #10827
</details>
=> Add `playlist_webpage_url` field

yt_dlp/extractor/youtube.py
Not as much pain as expected
Fixes #11524
</details>
=> [ie/youtube:tab] Fix playlists tab extraction

yt_dlp/extractor/chaturbate.py
This allows download if the initial API request returns a URL, even if room status is not "public", which may be the case if credentials were provided (for instance using `--cookies-from-browser`) for a user with access to a non-public stream.
Fixes #11623 
</details>
=> [ie/chaturbate] Support non-public (#11623)

yt_dlp/extractor/common.py
Thx to @seproDev for finding the bug
</details>
=> [ie] Handle fragmented formats in `_remove_duplicate_formats`

yt_dlp/extractor/dacast.py
=> [ie/dacast] Fix HLS AES formats extraction

yt_dlp/extractor/dropbox.py
=> [ie/dropbox] Fix password-protected video extraction

yt_dlp/extractor/mitele.py
Fixes #11690
"Mitele" seems to have added something else after the JSON data. Therefore, the regex that extract the video JSON data is now failing to convert the data to JSON. This PR adds an ending point to the JSON regex matching.
Does not fix any issue because I created the PR directly without opening an issue. But anyone can try a mitele URL and see it failing without this change applied.
</details>
=> [ie/Mitele] Fix regex extractor

yt_dlp/extractor/duoplay.py
Add new URL format support:
- https://duoplay.ee/9644?ep=185
</details>
=> [ie/duoplay] Fix extractor

yt_dlp/extractor/microsoftembed.py
Extraction currently fails due to ism formats no longer returning valid xml files
</details>
=> [ie/MicrosoftEmbed] Make format extraction non fatal

yt_dlp/extractor/vk.py
Closes #5832, Closes #11471, Closes #11646, Closes #11670
</details>
=> [ie/vk] Fix extractors

yt_dlp/extractor/youtube.py
=> [ie/youtube] Player client maintenance

test/test_youtube_signature.py, yt_dlp/extractor/youtube.py
Closes #11748
Depends on #11750
</details>
=> [ie/youtube] Fix signature function extraction

yt_dlp/extractor/soundcloud.py
=> [ie/soundcloud] Fix extraction

yt_dlp/extractor/patreon.py
=> [ie/patreon:campaign] Support /c/ URLs

yt_dlp/extractor/youtube.py
The ignore-whitespace flag (x), applied to youtube metadata parsing, leads to a unescaped space preventing the release_date group from ever matching.
For example, plugging in the description of https://www.youtube.com/watch?v=dSlYFtXENPo will not match the release_date, despite there very clearly being one present in the text.
My pull request escapes the single space in the regex, leading to correct extraction of release_date metadata.
note: I am new to contributing and just wanted to fix this one issue that's been bugging me for a long time; I apologize if my PR is formatted incorrectly.
Fixes #? (could not find a specific issue)
</details>
=> [youtube] Fix metadata extractor regex

yt_dlp/extractor/youtube.py
Fixed failed parsing of "lockupViewModel" in search results.
Fixes #11666
</details>
=> [Youtube] Fixed broken playlist search

test/test_youtube_signature.py, yt_dlp/extractor/youtube.py
=> [ie/youtube] Fix signature function extraction for `2f1832d2`

yt_dlp/extractor/brightcove.py, yt_dlp/extractor/dvtv.py, yt_dlp/extractor/nytimes.py, yt_dlp/extractor/vidyard.py
Make playlist extraction in multiple extractors lazy by using generator expressions instead of list comprehension.
</details>
=> [cleanup] Make more playlist extractions lazy

yt_dlp/update.py
Closes #11808
Tested and works: https://github.com/bashonly/yt-dlp/releases/tag/linux-updater-loop
</details>
=> [update] Fix endless update loop for `linux_exe` builds

yt_dlp/update.py
=> [update] Check 64-bitness when upgrading ARM builds

yt_dlp/extractor/youtube.py
=> [ie/youtube] Fix `uploader_id` extraction

yt_dlp/extractor/soundcloud.py
=> [ie/soundcloud] Various fixes

README.md, yt_dlp/extractor/youtube.py
Fix for one of the issues in https://github.com/yt-dlp/yt-dlp/issues/11868
It appears YouTube is rolling out what we presume is a PO Token requirement on iOS. It has the same characteristics as android: either immediate fail or fails part way through the download, and no StreamProtectionStatus is provided in the UMP/SABR responses.
iOS HLS formats appear to still work without PO Token.
This PR marks the iOS client as requiring a PO Token (except for HLS formats).
- Formats missing a PO Token that require one are **skipped** by default, unless `--extractor-args youtube:formats=missing_pot` is provided. 
- Improve warnings/logs around missing PO Token
</details>
=> [ie/youtube] Skip iOS formats that require PO Token

yt_dlp/extractor/youtube.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/11907
We were adding manifest format to "extracted" list before skipping it due to no PO Token. This meant the working manifest formats later in extraction were being incorrectly skipped
</details>
=> [ie/youtube] Fix DASH formats incorrectly skipped in some situations

yt_dlp/extractor/youtube.py
Rollout for `mweb` (with the iOS UA) is underway to require a PO Token
Related: https://github.com/yt-dlp/yt-dlp/issues/11868
</details>
=> [ie/youtube] Use `tv` instead of `mweb` by default 

yt_dlp/extractor/lbry.py
Some URLs contain a signature parameter that needs to be passed through. Example: redirect target of https://ody.sh/nB9gQ48eAz
</details>
=> [ie/LBRY] Support signed URLs

yt_dlp/extractor/rtvslo.py
RTVSLOShowIE: extract `description` and `thumbnail` from webpage's metadata
</details>
=> [ie/rtvslo.si:show] Extract more metadata

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/nest.py
Add support for Google Nest embedded videos.
Sometimes these become public webcams.
The tests include an example web page with an embed and the embed URL itself.
</details>
=> [ie/nest] Add extractors

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/bilibili.py
Fixes [#11726](https://github.com/yt-dlp/yt-dlp/issues/11726)
</details>
=> [ie/BiliBiliDynamic] Add extractor

yt_dlp/extractor/bluesky.py
The HLS formats provided in the bsky.app API response are reencoded from the blob provided by the PDS. There seems to always be a 360p and a 720p HLS format, regardless of the resolution of the blob, i.e. the HLS formats may be upscaled. An example is [this test case](https://bsky.app/profile/purpleicetea.bsky.social/post/3l7gv55dc2o2w) where the original blob is 360p and the 720p HLS format is clearly upscaled. In this case yt-dlp currently prefers the 720p HLS format based on resolution. Since the HLS formats are not actually better quality, give the blob format a higher quality value so that it is preferred instead.
</details>
=> [ie/Bluesky] Prefer source format

yt_dlp/extractor/youtube.py
=> [ie/youtube] Download `tv` client Innertube config

yt_dlp/extractor/youtube.py
Update of the iOS client. With the old one, YouTube denies more often requests for streaming information using the iOS client ("login needed").
</details>
=> [ie/youtube] Update iOS client

yt_dlp/extractor/goodgame.py
Not actual URL format is "https://goodgame.ru/channel/Pomi"
Now used URL is "https://goodgame.ru/Pomi"
Changed _VALID_URL regex. Removed word "channel".
Changed test case urls.
</details>
=> [ie/GoodGame] Fix extractor

yt_dlp/extractor/soundcloud.py
Support extraction of a user's commented tracks (e.g. https://soundcloud.com/one-thousand-and-one/comments)
</details>
=> [ie/soundcloud:user] Add `/comments` page support

yt_dlp/extractor/bilibili.py
Update regex for new urls.
PS: old urls redirect to uploader's space, not playlists' new urls.
Fixes #11959
</details>
=> [ie/bilibili] Update playlist url regex

yt_dlp/extractor/zdf.py
The channel extractor for ZDF now uses an API endpoint to get the necessary information instead of scraping the website. This has the following effects:
* Fixes #4782 because the API response contains all required data and there is no need to handle lazy-loaded parts of the page anymore.
* Adds a bunch of metadata that would be annoying to get from the HTML.
* Excludes unrelated "You might also like"-videos that show up on some pages but do not belong the the actual show.
* Fixes #10672 because it is somewhat related and an easy change.
</details>
=> [ie/ZDF] Rewrite channel extractor to use an API instead of HTML scraping

yt_dlp/extractor/naver.py
For some videos, m3u8 segment url requires param. HTTP error 400 occurs when param is missing.
Fixes #11953
</details>
=> [ie/naver] Fix m3u8 formats download

yt_dlp/extractor/pbs.py
PR to apply the patch created by @dirkf and incorporates the test for pbssocal added as part of PR #9740 
Fixes #11514 
</details>
=> [ie/pbs] #11514 pbs patch

yt_dlp/extractor/patreon.py
The Patreon extractor currently supports downloading media attachments for Patreon posts. Patreon posts may have an arbitrary number of attachments, each with it's own unique filename. However, the extractor does not use this information and only provides an index in the `id` field.
This PR updates the Patreon extractor to include the filenames that the Patreon author provided for each attachment in the `alt_title` field.
</details>
=> [ie/patreon] Include attachment filenames in metadata

yt_dlp/extractor/redgifs.py
Support alternative URLs like `https://www.redgifs.com/ifr/squeakyhelplesswisent` that contain `ifr` instead of `watch`.
These URLs would previously fall back to the generic extractor and fail with an error.
</details>
=> [redgifs] Support alternative URLs

yt_dlp/extractor/videocampus_sachsen.py
- **VIMP: Annotate instance URLs**
- **VIMPPlaylist: Update tests**
- **VIMPlaylist: Add support for tags**
</details>
=> VIMPPlaylist: Add support for tags

yt_dlp/extractor/pbs.py
* Fix existing tests for PBSIE
* Rework support for thirteen.org, whose URLs look a lot like pbs.org, but its HTML is a bit different. Not sure if the existing video.thirteen.org still matches something in the real world, but let's keep it for now.
</details>
=> [ie/pbs] Support www.thirteen.org URLs

yt_dlp/extractor/dropbox.py
=> [ie/dropbox] Fix extraction

yt_dlp/extractor/francetv.py
=> [ie/francetv:site] Fix extractor

yt_dlp/extractor/generic.py
Closes #12255
Give a chance for live dash to be detected
ex:
`yt-dlp -vU https://livesim2.dashif.org/livesim2/ato_10/testpic_2s/Manifest.mpd --dump-single-json --verbose
`
The problem is the returned json doesn't have the `is_live` property for live dash....to determine if` --downloader ffmpeg `option is required
</details>
=> [ie/generic] Extract `live_status` for DASH manifest URLs

yt_dlp/extractor/francetv.py
=> [ie/francetv:site] Fix livestream extraction

test/test_jsinterp.py, test/test_youtube_signature.py, yt_dlp/jsinterp.py
=> [jsinterp] Improve zeroise

yt_dlp/extractor/reddit.py
=> [ie/reddit] Bypass gated subreddit warning

yt_dlp/extractor/dreisat.py, yt_dlp/extractor/zdf.py
Closes #12391
Fixes regression introduced in 241ace4f104d50fdf7638f9203927aefcf57a1f7
</details>
=> [ie/3sat] Fix extractor

yt_dlp/extractor/youtube.py
=> [ie/youtube] nsig hotfix for `tce` player JS

yt_dlp/extractor/francetv.py
=> [ie/francetvinfo.fr] Fix extractor

yt_dlp/extractor/cbc.py
Closes #11848
**Does not fix login support for `CBCGemIE`**
</details>
=> [ie/gem.cbc.ca] Fix extractors

.github/workflows/codeql.yml, README.md, devscripts/run_tests.py, yt_dlp/__init__.py, yt_dlp/extractor/pbs.py
=> [cleanup] Misc (for 2025.02.xx release)

yt_dlp/extractor/niconico.py
=> [ie/niconico:live] Fix thumbnail extraction

yt_dlp/extractor/soundcloud.py
=> [ie/soundcloud] Extract tags

test/helper.py
Adjust the output of test diffing algorithm to always show all items (including their path)
<details><summary>Comparison: Download test</summary>
Old:
```
test/test_download.py:227: in test_template
expect_info_dict(self, tc_res_dict, tc.get('info_dict', {}))
test/helper.py:254: in expect_info_dict
expect_dict(self, got_dict, expected_dict)
test/helper.py:184: in expect_dict
expect_value(self, got, expected, info_field)
test/helper.py:176: in expect_value
self.assertEqual(
E   AssertionError: 'Big Bucks Bunny Trailer' != 'Big Buck Bunny Trailer'
E   - Big Bucks Bunny Trailer
E   ?         -
E   + Big Buck Bunny Trailer
E    : Invalid value for field title, expected 'Big Bucks Bunny Trailer', got 'Big Buck Bunny Trailer'
```
```
FAILED test/test_download.py::TestDownload::test_JWPlatform - …
```
=> [test] Show all differences for `expect_value` and `expect_dict`

yt_dlp/extractor/wsj.py
Fixes #Unsubmitted - WSJArticleIE hits a 401 soft wall
- [] I am not the original author of the code in this PR, but it is in the public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
- [] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [] Core bug fix/improvement
- [] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))
</details>
=> [ie/wsj] Support impersonation and opinion URLs

yt_dlp/extractor/extractors.py, yt_dlp/globals.py
=> Fix lazy extractor state (Fix 4445f37a7a66b248dbd8376c43137e6e441f138e)

yt_dlp/downloader/external.py, yt_dlp/postprocessor/ffmpeg.py
Fixes ffmpeg being wrongly detected as unavailable when its location is correctly specified.
</details>
=> Fix external downloader availability when using `--ffmpeg-location`

yt_dlp/extractor/globo.py
This fixes how the Globo extractor reads subtitles, as the API response it uses to fetch subtitle information apparently has changed.
</details>
=> [ie/globo] Fix subtitles extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/softwhiteunderbelly.py
This adds an extractor for the vimeo based documentary website [Soft White Underbelly](https://softwhiteunderbelly.com).
Fixes #
</details>
=> [ie/softwhiteunderbelly] Add extractor

yt_dlp/extractor/azmedien.py
The [azmedien] information extractor has been broken for a while now:
```
yt-dlp "https://www.telem1.ch/talktaeglich/energiegesetz-wie-weiter-159766997"
[AZMedien] Extracting URL: https://www.telem1.ch/talktaeglich/energiegesetz-wie-weiter-159766997
[AZMedien] energiegesetz-wie-weiter-159766997: Downloading JSON metadata
ERROR: energiegesetz-wie-weiter-159766997: An extractor error has occurred. (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
This PR fixes the [azmedien] information extractor.
</details>
=> [ie/azmedien] Fix extractor

yt_dlp/extractor/playsuisse.py
=> [ie/playsuisse] Fix login support

yt_dlp/extractor/cbc.py
=> [ie/gem.cbc.ca] Fix login support

yt_dlp/extractor/lbry.py
=> [ie/lbry] Raise appropriate error for non-media files

yt_dlp/extractor/lbry.py
=> [ie/lbry] Make m3u8 format extraction non-fatal

yt_dlp/extractor/weibo.py
Support mix_media_info
Fixes #12283
</details>
=> [ie/weibo] Support playlists

yt_dlp/extractor/dailymotion.py
=> [ie/Dailymotion] Improve embed detection

yt_dlp/extractor/cultureunplugged.py
=> [ie/CultureUnplugged]  Extend `_VALID_URL`

yt_dlp/extractor/youtube.py
Warn for https://github.com/yt-dlp/yt-dlp/issues/12482
</details>
=> [ie/youtube] Warn on missing formats due to SSAP

test/test_networking.py, test/test_utils.py, test/test_websockets.py, yt_dlp/networking/_curlcffi.py, yt_dlp/networking/_requests.py, yt_dlp/networking/_urllib.py, yt_dlp/networking/_websockets.py, yt_dlp/networking/common.py, yt_dlp/networking/impersonate.py, yt_dlp/utils/networking.py
Related: #11638
Closes: #10140
</details>
=> [networking] Add `keep_header_casing` extension

yt_dlp/extractor/magellantv.py
Fixes #12498
First two tests were replaced due to content no longer being available. Third test was updated since the original URL now 404s.
</details>
=> [ie/MagellanTV] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/tvw.py
This PR adds an extractor for [Washington State's public affairs network (TVW)](https://en.wikipedia.org/wiki/TVW_(Washington)), which hosts various governmental related H264/AAC videos using HLS m3u8 playlists.
</details>
=> [ie/tvw] Add extractor

yt_dlp/extractor/pinterest.py
Closes #12529
- https://github.com/yt-dlp/yt-dlp/issues/12529#issuecomment-2698701059
</details>
=> [ie/pinterest] Fix extractor

yt_dlp/extractor/vk.py
=> [ie/vk] Improve metadata extraction

yt_dlp/extractor/openrec.py
Fixes overly relaxed regex.
</details>
=> [ie/openrec] Fix URL validation regex

yt_dlp/extractor/cda.py
Fix error 400 on login into `cda` extractor.
Fix `cda` uploader meta extractor.
Fixes #10306
</details>
=> [ie/cda] Fix error 400

yt_dlp/extractor/reddit.py
Mirrors https://github.com/yt-dlp/yt-dlp/pull/12560 but for reddit.
The title can be unwieldy so it's truncated and preserved in `alt_title`. Additionally extract the post body as the description.
</details>
=> [ie/reddit] Truncate title

yt_dlp/extractor/youtube/_video.py
Adds a warning when DRM formats are detected. Help us identify https://github.com/yt-dlp/yt-dlp/issues/12563
</details>
=> [ie/youtube] Warn on DRM formats

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/canalsurmas.py
This pull request introduces a new extractor for the `www.canalsurmas.es` website, allowing videos from said website to be downloaded, thus resolving issue #5516.
Fixes #5516
</details>
=> [ie/Canalsurmas] Add extractor

yt_dlp/extractor/jamendo.py
This PR applies the patch provided in [issue 11779](https://github.com/yt-dlp/yt-dlp/issues/11779) to fix the extractor
Fixes #11779
</details>
=> [ie/jamendo] Fix thumbnail extraction

yt_dlp/extractor/bilibili.py
=> [ie/BilibiliPlaylist] Fix extractor

yt_dlp/extractor/mitele.py, yt_dlp/extractor/telecinco.py
=> [ie/mitele] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/vrt.py
Ketnet is now part of VRT MAX.  
Old URLs redirect to VRT MAX, but only to the program page (not the exact episode page), hence why I think a removal of the extractor is due.
Follow-up of #12479
CC/ @bashonly @seproDev
</details>
=> [ie/ketnet] Remove extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/loco.py
Add support for loco.com.
Everything is parsed from next.js data and live and VOD pages use the same structure.
Please, let me know if there are any issues with it.
Closes #12496
</details>
=> [ie/loco] Add extractor

yt_dlp/YoutubeDL.py
Oversight on failed VT init
Fixes regression introduced in f7a1f2d8132967a62b0f6d5665c6d2dde2d42c09
Fixes #12695
</details>
=> [core] Fix attribute error on failed VT init

pyproject.toml, test/test_networking.py, yt_dlp/YoutubeDL.py, yt_dlp/__init__.py, yt_dlp/networking/_curlcffi.py
Add support for curl-cffi 0.10.\*, drop support for 0.7.*
Needs testing ([release](<https://github.com/Grub4K/yt-dlp/releases/tag/pr12670>)):
Fixes #10613, Closes #11896
</details>
=> [rh:curl_cffi] Support `curl_cffi` 0.10.x

yt_dlp/extractor/youtube/_video.py
This also fixes the NSigDeno plugin
</details>
=> [ie/youtube] Fix PhantomJS nsig fallback

yt_dlp/extractor/generic.py
=> [ie/generic] Fix MPD base URL parsing

test/test_youtube_signature.py, yt_dlp/extractor/youtube/_video.py
=> [ie/youtube] Fix nsig extraction for player `4fcd6e4a`

yt_dlp/extractor/youtube/_video.py
Invalidate the cache if nsig extraction failed.
</details>
=> [ie/youtube] Only cache nsig code on successful decoding

test/test_jsinterp.py, yt_dlp/jsinterp.py
=> [jsinterp] Fix nested attributes and object extraction 

test/test_youtube_signature.py, yt_dlp/extractor/youtube/_video.py
=> [ie/youtube] Make signature/nsig extraction more robust

yt_dlp/extractor/youtube/_base.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/12759
</details>
=> [ie/youtube] Fix playlist continuation extraction

README.md, yt_dlp/options.py
Compatibility is through the roof.
</details>
=> Add `--compat-options 2024`

yt_dlp/extractor/sbs.py
=> [ie/sbs] Fix subtitles extraction

yt_dlp/extractor/generic.py
=> [ie/generic] Confirm URL is m3u8 before checking live status

yt_dlp/extractor/rtvs.py
Domain rtvs.sk was renamed to stvr.sk because state television and radio company was renamed to STVR.
Fixes #
</details>
=> [ie/stvr] Rename extractor from RTVS to STVR

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/francaisfacile.py
Add support for [Francais Facile](https://francaisfacile.rfi.fr/fr/)
Francais Facile is one of the services of [Radio France International](https://www.rfi.fr/en/) and offers news, podcasts and learning materials primarily targeted to students of the French language.
</details>
=> [ie/francaisfacile] Add extractor

yt_dlp/extractor/microsoftembed.py
=> [ie/MicrosoftLearnEpisode] Fix formats extraction

yt_dlp/extractor/on24.py
=> [ie/on24] Support `mainEvent` URLs

yt_dlp/extractor/vk.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/12509#issuecomment-2769475771
</details>
=> [ie/vk] Fix chapter extraction

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/roya.py
Add support for roya.tv live streams
Partially Fixes #12772
</details>
=> [ie/RoyaLive] Add extractor

yt_dlp/extractor/crowdbunker.py
=> [ie/CrowdBunker] Make format extraction non-fatal

yt_dlp/extractor/rumble.py
=> [ie/rumble] Improve format extraction

yt_dlp/extractor/agora.py
Stop querying for an AAC download URL. There seems to be no more AAC available, including for podcasts that used to have it like the test, and the endpoint returns a URL that results in HTTP 404 instead.
</details>
=> [ie/TokFMPodcast] Fix formats extraction

yt_dlp/extractor/yandexvideo.py
Fixes #10818, Fixes #11385, Fixes #11470
Closes #5523 (no longer required, and stale)
so linux.org.ru can finally be at peace
</details>
=> [ie/dzen.ru] Rework extractors

yt_dlp/extractor/common.py
=> [utils] `_yield_json_ld`: Make function less fatal

test/test_utils.py, yt_dlp/utils/_utils.py
update `url_or_none` to support WebSocket URLs
</details>
=> [utils] `url_or_none`: Support WebSocket URLs

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/kika.py
This PR adds playlist/series support for kika.de
Fixes #3658 
</details>
=> [ie/kika] Add playlist extractor

yt_dlp/downloader/niconico.py, yt_dlp/extractor/niconico.py
This PR fixes Niconico Live extractor by adapting new system.
Fixes #12365
I was able to fully download at least one live stream timeshift(archive), and my change seems to work on other live streams.
By reading the [announcement article](https://blog.nicovideo.jp/niconews/235926.html) linked in the original issue, it looks like the whole transition has been finished and it does not need to be backwards compatible, but who knows?
</details>
=> [ie/niconico:live] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/lrt.py
=> [ie/LRTRadio] Add extractor

test/helper.py, yt_dlp/extractor/youtube/_tab.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/12933. I've added the fetch for continuation after we try extract from renderers for the case there may be nested continuations, we want to prefer the one from the known renderers.
Hides the "Incomplete Data" warning on playlists when it tries to fetch the recommended videos feed (and gets no results). (fixes https://github.com/yt-dlp/yt-dlp/issues/8206)
Updated youtubetab tests, fixed some bugs in test suite
</details>
=> [ie/youtube:tab] Extract continuation from empty page

yt_dlp/extractor/youtube/_video.py
Currently only displaying "video unavailable", however sometimes this is due to YouTube requiring a recaptcha challenege
</details>
=> [ie/youtube] Add warning on playback recaptcha challenge

test/test_networking.py, yt_dlp/networking/__init__.py, yt_dlp/networking/_urllib.py, yt_dlp/networking/common.py
Add PATCH method support
</details>
=> [networking] Add PATCH request shortcut

yt_dlp/extractor/cda.py
Fixes #12918 by allowing hyphens in channel name for CDA service.
</details>
=> [ie/CDAFolder] Extend `_VALID_URL`

yt_dlp/extractor/tvp.py
Fixes #12917
accept negative numbers
</details>
=> [ie/tvp:vod] Improve `_VALID_URL`

yt_dlp/extractor/linkedin.py
=> [ie/linkedin] Support feed URLs

yt_dlp/extractor/panopto.py
=> [ie/panopto] Fix formats extraction

yt_dlp/extractor/abematv.py
Fixes #12858
Example:
Before: Unable to download thumbnail
After: Can download thumbnail via URL like https://abema.tv/channels/abema-anime/slots/DW8ofBXpcv6ugb
</details>
=> [ie/AbemaTV] Fix thumbnail extraction

yt_dlp/options.py
These options are shortcuts that are supposed to make using yt-dlp easier for new users. For now 5 presets are added:
- `mp3`: `-f ba[acodec=mp3]/ba/b -x --audio-format mp3` download any available mp3 format. If not available convert to mp3
- `aac`: `-f ba[acodec*=aac]/ba[acodec^=mp4a.40.]/ba/b -x --audio-format aac` download any available aac format. If not available convert to aac
- `mp4`: `--merge-output-format mp4 --remux mp4 -S vcodec:h264,lang,quality,res,fps,hdr:12,acodec:aac` if available download mp4 with h264 video and aac audio. If not use whatever is available, but mux in to an mp4. The first part might be controversial, but this option is intended to help novice users who will likely be unaware of the technical details of different codecs and what a container is. At least for …
=> Add `--preset-alias` option

yt_dlp/extractor/twitcasting.py
=> [ie/twitcasting] Fix livestream extraction

yt_dlp/extractor/cda.py
=> [ie/cda] Fix formats extraction

yt_dlp/extractor/getcourseru.py
Add one more embedded player url `cf-api-2.vhcdn.com` - probably it's now the default one, but we can't be sure so keeping existing one as well.
Fixes #12941
</details>
=> [ie/GetCourseRu] Fix extractors

yt_dlp/extractor/vk.py
Filing PRs from your phone is fun
Fixes #12967
</details>
=> [ie/vk] Fix uploader extraction

yt_dlp/extractor/rai.py
The drm property should be checked on the video json instead of the program info json to avoid incorrectly reporting drm videos
Fixes #12969
</details>
=> [ie/RaiPlay] Fix DRM detection

yt_dlp/extractor/youtube/_video.py
to be merged after https://github.com/yt-dlp/yt-dlp-wiki/pull/52
related: https://github.com/yt-dlp/yt-dlp/issues/11426
</details>
=> [ie/youtube] Add context to video request rate limit error

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/linkedin.py
=> [ie/linkedin:events] Add extractor

yt_dlp/extractor/bpb.py
=> [ie/bpb] Fix formats extraction

yt_dlp/extractor/reddit.py
=> [ie/reddit] Support `--ignore-no-formats-error`

yt_dlp/extractor/niconico.py
This PR rewrites and moves the login logic to `NiconicoBaseIE` to support password-based login for Niconico Live.
</details>
=> [ie/niconico] Fix login support

yt_dlp/extractor/youtube/_video.py
=> [ie/youtube] Cache signature timestamps

yt_dlp/extractor/weverse.py
=> [ie/weverse] Fix live extraction

.github/workflows/build.yml, pyproject.toml
Ref:
- https://github.com/yt-dlp/yt-dlp/issues/10294#issuecomment-2848326297
- https://github.com/pyinstaller/pyinstaller/issues/9075
- https://github.com/pyinstaller/pyinstaller/commit/97372400c13440c65d061bf4514c9f76fdae8480
</details>
=> [build] Bump PyInstaller to v6.13.0

yt_dlp/extractor/bitchute.py
=> [ie/bitchute] Fix extractor

yt_dlp/extractor/wat.py
=> [ie/wat.tv] Improve error handling

yt_dlp/extractor/nytimes.py
=> [ie/nytimesarticle] Fix extraction

yt_dlp/extractor/amcnetworks.py
The site uses Brightcove for its backend now instead of ThePlatform. Any content locked behind AdobePass is DRM-protected, so AP support was removed.
</details>
=> [ie/amcnetworks] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/jiosaavn.py
Fixes #10823, #12766
</details>
=> [ie/jiosaavn] enhancement: add artist and podcast support

yt_dlp/extractor/iprima.py
Authentication flow changed to a simpler one together with a change in the authentication url.
Fixes #12387
</details>
=> [ie/iprima] Fix login support

yt_dlp/extractor/firsttv.py
=> [ie/1tv] Fix extractor

yt_dlp/extractor/niconico.py
=> [ie/niconico] Fix error handling

test/test_youtube_misc.py, yt_dlp/extractor/youtube/_video.py
I fixed an issue with listing available countries when a youtube video is geo-blocked. The subreason youtube returns doesn't have a trailing comma, so I removed it from the extractor as well.
Before
```
$ python3 -m yt_dlp 'https://www.youtube.com/watch?v=qh_liphx2no'
[youtube] Extracting URL: https://www.youtube.com/watch?v=qh_liphx2no
[youtube] qh_liphx2no: Downloading webpage
[youtube] qh_liphx2no: Downloading tv client config
[youtube] qh_liphx2no: Downloading tv player API JSON
[youtube] qh_liphx2no: Downloading ios player API JSON
ERROR: [youtube] qh_liphx2no: Video unavailable. The uploader has not made this video available in your country
```
After
```
$ python3 -m yt_dlp 'https://www.youtube.com/watch?v=qh_liphx2no'
[youtube] Extracting URL: …
```
=> [ie/youtube] Fix geo-restriction error handling

test/test_jsinterp.py, test/test_youtube_signature.py, yt_dlp/jsinterp.py
~~This is very cringe and I hate it, but for now as a hotfix this has to suffice.~~
Hopefully we can deprecate jsinterp soon...
</details>
=> [jsinterp] Fix increment/decrement evaluation

test/test_cookies.py, yt_dlp/cookies.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/12885
Fixes desktop environment detection on Linux to properly match the logic implemented in Chromium.
the MATE desktop should now be detected properly, resulting in the correct keyring (gnome keyring) being chosen.
</details>
=> [cookies] Fix Linux desktop environment detection

yt_dlp/extractor/youtube/_video.py
Fixes a regression introduced in 32ed5f107c6c641958d1cd2752e130de4db55a13
See https://github.com/yt-dlp/yt-dlp/pull/13234#issuecomment-2902306349
</details>
=> [ie/youtube] Fix automatic captions for some client combinations

yt_dlp/extractor/patreon.py
=> [ie/patreon] Fix m3u8 formats extraction

yt_dlp/extractor/patreon.py
Fix e0d6c0822930f6e63f574d46d946a58b73ecd10c
Closes #13263
</details>
=> [ie/patreon] Fix referer header used for embeds

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/toutiao.py
Add support for [今日头条](https://www.toutiao.com/)
Closes #12125
</details>
=> [ie/toutiao] Add Extractor

yt_dlp/extractor/tenplay.py
=> [ie/10play] Fix extractor

yt_dlp/extractor/adobepass.py
This fixes the Philo login for TVE. It's been broken for a while but so was the adobepass, but now that it is fixed, figured we should get this up and running as well. This was tested and confirmed to work on aetv.com (updated with PR-13131)
Fixes #2603 
Tested:
```
[debug] Command-line config: ['--ap-mso', 'Philo', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-F', 'https://play.aetv.com/shows/neighborhood-wars/season-8/episode-99', '-v', '--no-cache-dir']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e] (pip)
[debug] Python 3.12.2 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 3.0.13 30 Jan 2024) 
[debug] exe versions: ffmpeg …
```
=> [ie/adobepass] Fix Philo MSO authentication

yt_dlp/extractor/odnoklassniki.py
=> [ie/odnoklassniki] Detect and raise when login is required

yt_dlp/extractor/umg.py
`_WORKING = False`: quite simple IE rework
</details>
=> [ie/umg:de] Rework extractor

test/test_youtube_signature.py, yt_dlp/extractor/youtube/_video.py
Implement new nsig function message matching strategy. pld-ty!
Also could be made more strict if need be, I only ported the smallest working match.
Fixes #13401
</details>
=> [ie/youtube] Rework nsig function name extraction

yt_dlp/extractor/aenetworks.py
When using yt-dlp on a series page it was giving 
ValueError: too many values to unpack (expected 2)
Once I fixed that, then was getting 400 on the graphql call. So switched to json.dumps to fix it.
</details>
=> [ie/aenetworks] Fix playlist extractors

yt_dlp/extractor/bilibili.py
Fix extraction for new bangumi episodes and add warning when only preview format can be extracted.
Fixes #13121
</details>
=> [ie/BiliBiliBangumi] Fix extractor

yt_dlp/extractor/startrek.py
`_WORKING = False`: simple IE rework
</details>
=> [ie/startrek] Fix extractor

yt_dlp/extractor/brightcove.py
filter out empty `tags` field
(needed for https://github.com/yt-dlp/yt-dlp/pull/13460)
</details>
=> [ie/brightcove:new] Improve metadata extraction

yt_dlp/extractor/cloudycdn.py, yt_dlp/extractor/lsm.py
Contains fixes to make replay.lsm.lv work again:
- Adds support for the new URL format
- Adds support for the new audio player
- Adds support for the new name of the CDN
Supersedes, closes #12298
</details>
=> [ie/lsm] Fix extraction

yt_dlp/extractor/huya.py
**huya:live**
- Fix variable name to `_TESTS`
- Simplify subdomain regex
- Update `IE_DESC`
**huya:video**
- Improve metadata extraction
- Fix formats extraction
extract formats from m3u8 URLs; mp4 URLs are optional for some videos
</details>
=> [ie/huya:live] Fix extractor

yt_dlp/extractor/bilibili.py
Fixes #13435
Collections may be configured as hidden mode, which shows only first video in uploads. This PR extracts them as playlists to allow downloading of all hidden videos from uploader.
- [x At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
</details>
=> [ie/BilibiliSpaceVideo] Extract hidden-mode collections as playlists

yt_dlp/extractor/hotstar.py
=> [ie/hotstar] Fix metadata extraction

yt_dlp/extractor/hotstar.py
All(?) content is authwalled now. Raise for login required if the user is not passing logged-in cookies.
Closes #10366
</details>
=> [ie/hotstar] Raise for login required

test/test_InfoExtractor.py, yt_dlp/extractor/common.py
Checks if a m3u8 manifest extraction content starts with the expected header.
Related: #10184
</details>
=> [ie] Implement check for HLS streaming header

yt_dlp/extractor/hotstar.py
Fixes b5bd057fe86550f3aa67f2fc8790d1c6a251c57b
</details>
=> [ie/hotstar] Fix formats extraction

yt_dlp/extractor/youtube/_base.py, yt_dlp/extractor/youtube/_video.py
=> [ie/youtube] Fix premium formats extraction

test/test_InfoExtractor.py, yt_dlp/extractor/common.py
Reverts 7b81634fb1d15999757e7a9883daa6ef09ea785b
Closes #13581
</details>
=> [ie] Fix m3u8 playlist data corruption

yt_dlp/extractor/kick.py
`XSRF-TOKEN` cookie was no longer being passed so downloads would 403. Found that `session_token` now contained the expected value.
Also removed `X-XSRF-TOKEN` header since it seems it isn't needed anymore (extractors works without it)
Fixes #13442
</details>
=> [ie/kick] Support subscriber-only content

test/test_networking.py, yt_dlp/networking/_requests.py
Fixes #13581 properly by working around https://github.com/urllib3/urllib3/issues/3636
</details>
=> [rh:requests] Work around partial read dropping data

test/test_InfoExtractor.py, yt_dlp/extractor/common.py
Reapply 7b81634fb1d15999757e7a9883daa6ef09ea785b, which was reverted in 500761e41acb96953a5064e951d41d190c287e46 bc of partial read bug in urllib3
</details>
=> [ie] Detect invalid m3u8 playlist data

test/test_jsinterp.py, test/test_youtube_signature.py, yt_dlp/extractor/youtube/_video.py, yt_dlp/jsinterp.py
=> [ie/youtube] Fix nsig extraction for `tce` player JS

yt_dlp/downloader/hls.py
Addresses https://github.com/yt-dlp/yt-dlp/issues/13632#issuecomment-3041932811
</details>
=> [fd/hls] Do not fall back to ffmpeg when native is required

yt_dlp/extractor/youtube/_tab.py
Adds support for `LOCKUP_CONTENT_TYPE_VIDEO` view models
Closes #13658
</details>
=> [ie/youtube:tab] Fix subscriptions feed extraction

yt_dlp/extractor/bilibili.py
=> [ie/BiliBiliBangumi] Fix geo-block detection

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/mir24tv.py
=> [ie/mir24.tv] Add extractor

yt_dlp/extractor/newspicks.py
Closes https://github.com/yt-dlp/yt-dlp/issues/10472
</details>
=> [ie/newspicks] Rework Extractor

yt_dlp/extractor/hotstar.py
Classified the account into two types and set headers accordingly to fetching formats for both subscribed and free account.
Fixes #13600 
</details>
=> [ie/hotstar] Fix: Headers & Parameters

yt_dlp/extractor/francetv.py
=> [ie/francetv] Improve error handling

yt_dlp/extractor/archiveorg.py
archive.org metadata now is included in a custom `play-av` tag and includes a `track` item.
Fixes #13704
</details>
=> [ie/archive.org] Fix extractor

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/blackboardcollaborate.py
Blackboard Collaborate is an online education platform used by many universities.
The extractor for blackboard collaborate has been lacking some features that the others have, such as **downloading subtitles**, **live chat** and videos that can only be seen **behind SSOs or with authentication tokens**.
- These features have now been added.
- BlackboardCollaborateLearnIE has been added to support the URL format that is given within the scheduler/previous recording viewer of Blackboard Class Collaborate.
- It also corrects an issue in which the time given in the infodict was passed in milliseconds when yt-dlp expects seconds, so when it would convert to hhmmss, it would be wayyy off.
- Finding a video with subtitles has been especially difficult but now it seems the host of the subtitled …
=> [ie/blackboardcollaborate] Support subtitles and authwalled videos

yt_dlp/extractor/aenetworks.py
=> [ie/aenetworks] Support new URL formats

yt_dlp/extractor/dangalplay.py
=> [ie/dangalplay] Support other login regions

yt_dlp/extractor/tenplay.py
Tested with the new 10.com.au urls an it appears to be working correctly :slightly_smiling_face: 
Fixes #13577
</details>
=> [ie/tenplay] Support new 10.com.au domain

yt_dlp/YoutubeDL.py, yt_dlp/downloader/__init__.py, yt_dlp/downloader/http.py, yt_dlp/extractor/common.py
=> Allow extractors to designate formats/subtitles for impersonation

yt_dlp/networking/_requests.py
=> [rh:requests] Refactor default headers

yt_dlp/extractor/youtube/_video.py
=> [ie/youtube] Use impersonation for downloading subtitles

yt_dlp/extractor/patreon.py
=> [ie/patreon:campaign] Fix extractor

yt_dlp/update.py
=> Raise minimum recommended Python version to 3.10

yt_dlp/extractor/archiveorg.py
=> [ie/archive.org] Fix metadata extraction

yt_dlp/extractor/streaks.py, yt_dlp/extractor/tver.py
=> [ie/TVer] Extract Streaks API info

yt_dlp/extractor/roya.py
=> [ie/RoyaLive] Support `en` URLs

yt_dlp/extractor/youtube/_base.py
=> [ie/youtube] Add player params to mweb client

yt_dlp/extractor/digitalconcerthall.py
=> [ie/digitalconcerthall] Fix formats extraction

yt_dlp/extractor/youtube/_base.py
=> [ie/youtube] Update player params

yt_dlp/extractor/weibo.py
- Fixed WeiboIE, WeiboUserIE 403 Forbidden error on certain ajax requests by adding a Referer header. 
- Fixed WeiboVideoIE case where regex was truncating the FID, which is no longer limited to only digits after the colon.
Fixes #13938
</details>
=> [ie/weibo] Fix extractors

yt_dlp/extractor/bilibili.py
=> [ie/BiliBili] Redirect BiliBiliBangumi AV/BV ID to EPID

yt_dlp/extractor/medialaan.py, yt_dlp/extractor/vtm.py
- Create `BaseIE` for Medialaan and unify processing with VTM (`_WORKING = False`)
- Improve metadata extraction
- Update regex
</details>
=> [ie/medialaan] Rework extractors

yt_dlp/YoutubeDL.py, yt_dlp/downloader/common.py, yt_dlp/extractor/common.py
=> [fd] Support `available_at` format field

README.md, yt_dlp/extractor/youtube/_base.py, yt_dlp/extractor/youtube/_video.py
Closes #13930
Reopens #12563
</details>
=> [ie/youtube] Fix extractor

Changelog.md, devscripts/changelog_override.json
=> [cleanup] Misc (for 2025.08.20 release)

.github/workflows/build.yml
=> [build] Post-release cleanup

yt_dlp/extractor/_extractors.py, yt_dlp/extractor/steam.py
- Fix YouTube embed detection
- Code cleanup
</details>
=> [ie/steam] Fix extractors

yt_dlp/extractor/youtube/_base.py
=> [ie/youtube] Update `tv` client config

yt_dlp/cookies.py
Ref: https://github.com/mozilla-firefox/firefox/commit/5869af852cd20425165837f6c2d9971f3efba83d
Related: 28b68f687561468e0c664dcb430707458970019f
Supersedes #14113
Closes #13559, Closes #14113
</details>
=> [cookies] Fix `--cookies-from-browser` with Firefox 142+

yt_dlp/extractor/youtube/_base.py
=> [ie/youtube] Improve `tv` client context

yt_dlp/extractor/itv.py
the problem is that some `content` entries don't have a `data` key
the extractor does have a bit for bailing out if a field in `data` isn't the expected value
i changed that bit to traverse_obj so it doesn't fail if `data` isn't there
Fixes #14156
</details>
=> [ie/ITVBTCC] Fix extractor

.github/workflows/build.yml, .github/workflows/cache-warmer.yml
Oops: https://github.com/yt-dlp/yt-dlp/actions/runs/17520055588/job/49762696064
Fix bug in 50136eeeb3767289b236f140b759f23b39b00888
</details>
=> [build] Fix cache warmer

yt_dlp/extractor/newspicks.py
Closes https://github.com/yt-dlp/yt-dlp/issues/14137
</details>
=> [ie/newspicks] Add preview warning for premium videos when unauthenticated

.github/workflows/test-workflows.yml, bundle/docker/linux/build.sh, devscripts/setup_variables_tests.py
=> [ci] Improve workflow checks

.github/workflows/build.yml
=> [build] Use PyInstaller 6.16 for Windows

yt_dlp/extractor/youtube/_video.py
Otherwise spams your console for every format 
</details>
=> [ie/youtube] Improve logging
