- youtube_dlc/postprocessor/embedthumbnail.py
- youtube_dlc/postprocessor/ffmpeg.py
Sometimes, video files will arrive with a timecode data stream
that causes `-map 0` to error out due to the stream not being
supported in the output container. These data streams generally do
not matter, so tell ffmpeg to ignore them rather than choking on
them.
> ffmpeg: ignore extra data streams with `-dn` (closes #2)

- .github/workflows/core.yml
- .github/workflows/download.yml
- .github/workflows/quick-test.yml
- README.md
- youtube_dlc/YoutubeDL.py
- youtube_dlc/__init__.py
- youtube_dlc/downloader/external.py
- youtube_dlc/extractor/cbs.py
- youtube_dlc/options.py
- youtube_dlc/postprocessor/__init__.py
- youtube_dlc/postprocessor/common.py
- youtube_dlc/postprocessor/movefilesafterdownload.py
- youtube_dlc/utils.py
```
-P, --paths TYPE:PATH            The paths where the files should be
downloaded. Specify the type of file and
the path separated by a colon ":"
(supported: description|annotation|subtitle
|infojson|thumbnail). Additionally, you can
also provide "home" and "temp" paths. All
intermediary files are first downloaded to
the temp path and then the final files are
moved over to the home path after download
is finished. Note that this option is
ignored if --output is an absolute path
```
Also, configuration files `yt-dlp.conf` or `youtube-dlc.conf` are now additionally loaded from the home path given by `-P "home:<path>"`, or from the current directory if no such path is given
Eg:
-P "home:D:\YTDL" -P "temp:C:\temp" -P "description:desc" -P "subtitle:subs" -P "infojson:info" -P …
> Option to give different paths for different types of files

- README.md
- youtube_dlc/YoutubeDL.py
- youtube_dlc/utils.py
Closes #43
Provides the ability to use `strfprint` to format date/time in the output template. The syntax is:
%(field_name>strf_format)general_format
Eg: `%(duration>%H-%M-%S)s - %(upload_date>%Y day%j)s`
Anyone reviewing/testing the code is appreciated
> Datetime format

- youtube_dlc/utils.py
---
---
Fixes decompression of HTTP head requests. This issue can be found with manifests from HBO. See https://github.com/ytdl-org/youtube-dl/issues/7181.
> Fix http HEAD requests decompression

- youtube_dlc/downloader/external.py
- youtube_dlc/downloader/hls.py
---
---
Fixes AES-128 support in external downloaders when multiple keys are used.
Multiple key example: https://cdn.theoplayer.com/video/big_buck_bunny_encrypted/stream-800/index.m3u8
Single key example: https://www.cartoonnetwork.com/video/bakugan/the-mysterious-revengerwynton-vs-lia-episode.html
> Fix HLS AES-128 with multiple keys in external downloaders

- youtube_dlc/downloader/fragment.py
- youtube_dlc/downloader/http.py
- youtube_dlc/downloader/youtube_live_chat.py
---
---
Attempts to fix https://github.com/pukkandan/yt-dlp/issues/82.
YouTube has removed support for the old GET based live chat API, and it's now returning 404 for all videos that I tested.
The new API needs `INNERTUBE_CONTEXT` and `INNERTUBE_API_KEY` from ytcfg, so the regex for that is copied from main extractor. I couldn't find a cleaner way to do it.
> use new POST API for live chat

- youtube_dlc/extractor/niconico.py
---
---
For channel movies and community only movies in niconico douga, support metadata 'channel', 'channel_id', 'uploader' and 'uploader_id'.
In other words, fix #77.
> [niconico] Support metadata 'channel' and 'channel_id' (fix #77).

- yt_dlp/utils.py
---
---
Fixes plugin loading when executing yt-dlp from a different working directory.
Tested on PyInstaller, Zipimport, and pip.
> Fix get_executable_path

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/bilibili.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
- yt_dlp/options.py
Make comment extraction lazy so that it only runs when the comment data is actually needed
Closes #94 
~~This is currently only a proof of concept. The code needs to be generalized so that other fields can also make use of lazy extraction in the future.~~
> Make comment extraction lazy

- yt_dlp/extractor/youtube.py
---
---
YouTube appears to be abandoning the old '`browse_ajax`' API for the new POST front-end API. This is evident with the rise in 404 related errors during playlist downloads. https://github.com/ytdl-org/youtube-dl/issues/28289 https://github.com/ytdl-org/youtube-dl/issues/28327 …
> [YouTube] Use new browse API for continuation page extraction.

- test/test_all_urls.py
- yt_dlp/extractor/youtube.py
History and trending are completely fixed
~~Mix needs a bit more work~~
Thanks to @colethedj for figuring out how to fix these
---
1. ~~Print proper messages to screen (downloading page n)~~
2. ~~Confirm the skipping code is correct~~
3. I have assumed that all inline playlists are mixes. It would be better to have a more concrete check to see if something is a mix or not
4. ~~The current implementation is recursive. So with enough pages, recursion limit could be reached. Any solutions?~~
5. ~~This should probably be moved to a new extractor~~
> [youtube] Fix history, trending and mix playlists

- yt_dlp/extractor/youtube.py
---
---
If there is something wrong with the continuation request (e.g. bad auth, or bad params due to some API change), YouTube may provide alerts in the response the same way it does for the initial page. This is more to help when developing/debugging when something goes wrong.
> [Youtube] Extract alerts from continuation response if present

- yt_dlp/extractor/youtube.py
---
---
**Current behavior:**
On multi-channel YouTube accounts, when accessing private feeds/playlists from the secondary channel account, the continuation of such pages will be accessed as if they were being called by the main channel account. 
This causes weird behavior - such as the continuation pages …
> [Youtube] Fix private feeds/playlists on multi-channel Youtube accounts.

- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
---
- [  ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) 
---
Very much WIP. This is a rewrite of the comments extraction. I have rewrote this in similar fashion to how the Tab Extractor `_entries` function works. This should also make switching API's easier if YouTube ever deprecates …
> [Youtube] Comments extraction rewrite

- README.md
- yt_dlp/__init__.py
- yt_dlp/options.py
- yt_dlp/postprocessor/__init__.py
- yt_dlp/postprocessor/ffmpeg.py
- yt_dlp/utils.py
Eg:
yt-dlp -v --split-chapters -o "chapter:%(id)s\%(part_number)s - %(part_title)s.%(ext)s" GIq3pcdz4Sw
PS: The names of the option and output template fields are not finalized
> Split video by chapters

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/downloader/dash.py
- yt_dlp/downloader/external.py
- yt_dlp/downloader/hls.py
- yt_dlp/downloader/rtmp.py
- yt_dlp/downloader/rtsp.py
- yt_dlp/extractor/ivi.py
- yt_dlp/options.py
- yt_dlp/postprocessor/embedthumbnail.py
- yt_dlp/postprocessor/ffmpeg.py
- yt_dlp/postprocessor/sponskrub.py
> Fixes and improvements in general and to external downloaders

- yt_dlp/extractor/amcnetworks.py
- yt_dlp/utils.py
---
---
Some videos couldn't be downloaded because of Fairplay encryption. Alternate video manifests are available that don't use Fairplay.
Additional thumbnail images were added, often larger than the single 1920x1080 image identified by the previous version of the extractor.
"season_number" and "series" were being added to "title" for some reason. That behavior was removed.
"series" now gets displayed as "NA" rather than "_" when its value is empty.
To do: Add fallbacks.
> fixed multiple bugs in amcnetworks.py extractor

- yt_dlp/extractor/nbc.py
---
---
Sorry for the repost. My repository somehow got corrupted and I didn't want to waste anymore time troubleshooting it. Anyway,
The nbc.py extractor was using the wrong information for video titles. This was noticeable in movies: For example, "The Fifth Element" would end up with the title "1 hr 48 min _ 1997". The extractor was using the secondaryTitle key from one JSON file instead of the title key from a different JSON file. The two keys usually have the same value for episodes of TV shows.
age_limit information was added.
Fallbacks were …
> nbc.py patch

- README.md
- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
---
Add video availability key to the info json
As requested by https://github.com/yt-dlp/yt-dlp/issues/185
Also related: https://github.com/ytdl-org/youtube-dl/issues/25631
TODO:
- documentation
- testing
- 'availability' vs 'visibility' for the key name?
> Add video availability/visibility key to info json

- yt_dlp/extractor/nitter.py
---
---
When the thumbnail url was gathered from og:image, it already contains base URL and therefore the link was wrong. See the thumbnails field in json in https://github.com/yt-dlp/yt-dlp/issues/215
> [nitter] fix thumbnails

- test/test_utils.py
- yt_dlp/extractor/youtube.py
- yt_dlp/utils.py
---
---
Adds a parser to parse the comment time text by YouTube into a UNIX timestamp. 
This is generally in the format `X units ago (edited)`, where `(edited)` is optional.
Due to the nature of the time_text, the resultant timestamp is an **estimate** (and probably becomes less accurate the greater the unit i.e. years vs minutes).
This extends the existing `date_from_str` util function into `datetime_from_str` to extend functionality (while keeping backwards compatibility). 
Notably, this adds to this function: 
- support time
- precision …
> [youtube:comments, utils] Implement parser for time_text

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nfhsnetwork.py
---
---
Adds extractor for NFHS Network, a subscription site for high school sporting events. This site has terrible security and all data can be accessed through unauthenticated API endpoints. I purposely left some things commented because I have a couple questions. 
1. Should `url` be hardcoded in each of the test's `info_dict`? Unlike most streaming sites today, NFHS Network uses static m3u8 urls with no parameters or variation of any kind. 
2. I'm not sure how to sort the formats, because `_sort_formats` incorrectly chooses `best` when given …
> Add NFHS Network extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nebula.py
---
This PR is a copy of https://github.com/ytdl-org/youtube-dl/pull/27859 (as of Feb 2021: in status Open)
However, that PR contains the full commit history (pretty clean and readable), while this one here is simply the squashed version.
This is a new extractor for the video platform Nebula (https://watchnebula.com/), created by the streamer community Standard. Nebula uses the Zype video infrastructure and this extractor is using the url_transparent mode to hand off video extraction to the Zype extractor (which has shown to be super reliable here).
All videos on Nebula require a subscription to access. Multiple authentication methods are supported, with the most convenient probably being .netrc, but a few alternatives (cookie jar, environment variable, token in --videopassword) have been …
> [nebula] Add Nebula (watchnebula.com) extractor

- yt_dlp/extractor/youtube.py
---
---
The channel syncid (or "delegated session id") is also available in the ytcfg. This PR adds support to the syncid extraction function to be able to extract it from ytcfg.
In ytcfg:
`DATASYNC_ID` is the exact same format as `datasyncId`
`DELEGATED_SESSION_ID` appears to be the channel syncid itself …
> [youtube] Improve channel syncid extraction to support ytcfg

- yt_dlp/extractor/youtube.py
---
---
Potential generalisation of the "retry" code that is starting to be repeated for calls to the API.
This will also be useful for https://github.com/yt-dlp/yt-dlp/pull/242
As well as for if the comments API changes to this new one.
This also adds upgrades the mix extractor to use the API.
> [youtube:tab] Generalise retry method for API calls

- yt_dlp/extractor/rai.py
---
As title.
Add support for direct http mp4 formats, with support for higher resolution as well (sometimes)
addresses #207
> [rai] add support for http formats

- yt_dlp/extractor/mildom.py
---
All the live stream needs is an appropriate `Referer` header, which is easily forged locally; this is exactly what this patch does. Relying on a third-party proxy not only created glaring reliability and privacy issues, but was, in fact, entirely superfluous.
In the future, I suggest putting a little more rigour into code review.
Fixes: #251, #252.
> [mildom] Remove dependency on third-party servers

- yt_dlp/extractor/niconico.py
This is part of my changes that I made when trying to fix #171, where I restored the behavior of using untranslated title, plus fixed the thumbnail extraction
> [niconico] minor fix of original title and thumbnail extraction

- yt_dlp/extractor/niconico.py
Thumbnails are still not downloading, but it's my fault. I realized `try_get()` only accept a list of lambda, so using `dict_get()` now. This time I have tested my PR to make sure things work.
> [niconico] fix a small mistake of thumbnail extraction

- yt_dlp/YoutubeDL.py
There are some inconsistencies in how youtube-dl and yt-dlp handles `playlist_index` when used with `--playlist-reverse` and similar options. Sometimes `playlist_index` is the index of the item in the actual playlist, and sometimes, it is the position of the item in the download queue, sometimes neither...
<details>
<summary>
1. Normal use, we get expected results (<code>1-10</code>)
</summary>
```
$ youtube-dl https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw/videos -o "%(playlist_index)s %(title)s" --get-filename --playlist-end 10
01 How (and why) to raise e to the power of a matrix _ DE6
02 Why Bayes rule is nicer with odds
03 Hamming codes part 2, the elegance of it all
04 Hamming codes and error correction
05 Group theory, abstraction, and the 196,883-dimensional monster
06 …
```
> Fix playlist_index's inconsistent behavior

- README.md
- yt_dlp/__init__.py
- yt_dlp/options.py
- yt_dlp/postprocessor/embedthumbnail.py
- yt_dlp/postprocessor/ffmpeg.py
---
---
Hi! This is my first pull request, so forgive me if there are any formatting errors or such in the code.
As mentioned in [youtube-dl PR #25717](https://github.com/ytdl-org/youtube-dl/pull/25717), both `ffmpeg` and `AtomicParsley` support embedding both JPEG and PNG files. Accordingly, if `yt-dlp` is given either a JPEG or PNG file, `yt-dlp` will pass the files along without issue to be embedded.
However, `yt-dlp` currently only supports converting thumbnails to JPG if they are in another, unsupported format. I believe this is behavior …
> Add support for PNG thumbnail conversion and default to it if necessary

- yt_dlp/extractor/vidio.py
---
---
Add another API endpoint for downloading premier-only videos (requires account regardless of video, so old URL may still be used)
(also adds subtitle support)
> [vidio] Add support for premier-exclusive videos

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/vidio.py
---
---
Add support for /premier/ playlists and /live/ streams
> [vidio] Add VidioPremierIE and VidioLiveIE

- pyinst.py
---
---
Currently there is no way of knowing what Python version provided `exe`s are bundled with. In particular, it's hard to find out whether the latest security fixes are included. To solve it, this pull request adds Python version to product version string.
> Show Python version in EXE metadata

- yt_dlp/extractor/youtube.py
…page
---
---
Alert reporting should raise a warning on error if fatal=False. We don't want unavailable video page extraction to be able to raise a fatal error in the future if youtube decides to remove it etc.
Noticed in #393
> [youtube] Alert reporting should be non-fatal for unavailable videos

- yt_dlp/downloader/youtube_live_chat.py
---
---
Reloads live chat before starting to download it so that the position that was previously used in the browser is not reused. On the website this is the same as clicking "top chat replay" and selecting the same option again. When reloading the chat, also set current player position to 0 ms. If the reload option doesn't exist, fall back to old behavior.
Now that this is done it would also be relatively easy to provide an option to choose between top chat and all chat, but that's not in the scope of this PR.
Fixes #417
> [youtube_live_chat] fix chat replay download with cookies

- yt_dlp/extractor/tbs.py
- yt_dlp/extractor/turner.py
---
---
Add support for TNT live streams. Hard coded that MVPD auth required because ~~I'm bad at coding~~ it's required to authenticate to view the live stream. Example log with this patch: 
```
./yt-dlp.cmd --ignore-config --proxy "http://localhost:8888" "https://www.tntdrama.com/watchtnt/east" --ap-mso …
```
> Implemented TNT live streams

- yt_dlp/downloader/youtube_live_chat.py
---
---
Fixes https://github.com/yt-dlp/yt-dlp/issues/433
I looked at my captures of members only live chat, and noticed that some of the API request payloads contained `clickTracking` but others didn't. It was always contained in the previous response when it was used. I still haven't been able to test this with an actual live members chat, but I tested that this doesn't break members replays or non-members chat, live or replay.
I'm hoping that @Lytexx could test this with cookies on a members live chat, but I might also be able to do that at …
> [youtube_live_chat] use clickTrackingParams

- yt_dlp/extractor/youtube.py
---
---
Recently, it became possible to download Youtube live chat live without having to wait until after a stream has ended. With a different patch, it became possible to download metadata about "upcoming" streams using the `--ignore-no-formats-error` option. Since live chat is often available before a livestream (or premiere), it is useful to be able to download live chat from the moment the URL comes up.
The support for downloading live chat this early is already there, however an oversight caused the "replay" API endpoint to be chosen by …
> Choose correct API endpoint for live chat on upcoming streams

- yt_dlp/extractor/soundcloud.py
---
Disabled login by api since it needs a rework. Instead added the option to use one of these `['token', 'auth', 'oauth', 'bearer', 'authorization']` as a username to let the extractor know the password will be an `oauth/access token`. You still can add `--add-header "Authorization: OAuth <access_token>"` as usual. However this patch allows you to use netrc to save your token.
I will try to see how long a token is valid exactly (from experience I used the same token once for at least a week). There is also `_soundcloud_session` which can be used to retrieve the token you got when you signed in. I assume it got a shorter time span but never glimpsed on it so I will try the one I've saved in a week or so. 
This workaround patch is rather for convenience
For simplicity use e.g. chrome …
> [soundcloud] disable login, require oauth token instead

- yt_dlp/extractor/bravotv.py
---
Download and parse ThePlatform metadata to get more metadata about the content including runtime, series name, season number, and episode number.
The only quirk is that I found that the series name is sometimes nested into a single element array so I added a handler for that.
I updated the existing test to also test these extra attributes.
> [BravoTV] Improve metadata extraction

- yt_dlp/extractor/youtube.py
---
---
`is_favorited` key for a comment is defined as " Whether the comment is marked as favorite by the video uploader"
Before the YouTube comment extractor was using `isLiked` key in the comment renderer, which is not if the uploader had favorited the comment, rather if the logged-in user had liked the comment.
> [youtube:comments] Fix `is_favorited` key

- yt_dlp/extractor/youtube.py
---
---
Switches default player_client to android for the time-being.
`get_video_info` still supports the android client. Since it can currently bypass the throttling issues (https://github.com/ytdl-org/youtube-dl/issues/29326), I have added support for such client.
> [youtube] Use android client by default for player API requests

- test/test_utils.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/rtp.py
- yt_dlp/utils.py
- **I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)**
- **Bug fix**
---
Related to #486.
This fixes broken RTP extraction, due to obfuscation the website apparently started employing a while ago. Apart from employing URL-encoded base64, the website code contains a handful of false pieces of data that more naïve regex search might capture instead of the real data; I suspect this may be specifically to throw off scrapers like this one. Coming up with a regex that captures the real data instead of the booby traps was somewhat tricky. I worry we may need to start preparing for an obfuscation arms race, and eventually add a full JavaScript parser and evaluator.
> RTP: fix extraction

- yt_dlp/extractor/youtube.py
---
---
- Adds `availability` key support for playlists.
- Adds fallback for `is_unlisted` in `YouTubeIE` (related: #501) (Note: without `microformat` we won't be able to detect if a video is public since unlisted will be None)
Currently only supports public, unlisted and private availability forms for playlists. I'm not aware of any other examples of the other types.
Note: as of writing, the `public` availability is only possible when the playlist is a personal public playlist and auth is given.
TODO:
> [youtube:tab] Add availability metadata for playlists

- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
<details>
<summary> Boilerplate </summary>
- **I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)**
- **Bug fix**
</details>
This adds subtitle extraction cases in the generic extractor that I missed in #247. It should address #512; despite the rather vague report, it did contain enough information to identify the likely source of the problem.
As a bonus, I also threw in similar detection of discarded subtitles in SMIL manifests that we had for all the other kinds (since clearly the approach is working) and added full SMIL manifest data extraction to the generic extractor.
> Extract subtitles in cases missed previously

- yt_dlp/extractor/yahoo.py
---
---
This PR relaxes `_VALID_URL` for `yahoo:gyao:player`
example URL: `https://gyao.yahoo.co.jp/episode/5fa1226c-ef8d-4e93-af7a-fd92f4e30597`
> [yahoo:gyao:player] relax _VALID_URL

- yt_dlp/extractor/youtube.py
---
---
`X-Goog-AuthUser` appears to relate to what account (not channel) is logged in. `SESSION_INDEX` in ytcfg appears to represent this.
Should fix #518
> [youtube] Extract session index for `X-Goog-AuthUser` (fixes #518)

- yt_dlp/extractor/nebula.py
---
Main conversation on issue: https://github.com/yt-dlp/yt-dlp/issues/496
* Support authentication from cookie jar.
* Token from cookie is preferred, if no cookie present or expired, credentials auth is run against login endpoint (with credentials required in `.netrc` or supplied on command line).
* Token retrieved from login endpoint is stored in cookie jar, if available.
* [tentative] If token is rejected by Nebula backend, reauthentication with credentials is attempted.
> [nebula] Support authentication via tokens from cookie jar

- yt_dlp/extractor/youtube.py
---
---
Even when authenticated, YouTube will ask if we are OK with watching a age-gated video. On web clicking the button adds has_verified=1 to the query, which is already implemented.
The equivalent API parameter appears to be `racyCheckOk=True` 
Interesting that racyCheckOk appears to be always false …
> [youtube] Fix age-gated videos over API when cookies are supplied

- yt_dlp/cookies.py
---
Prevent crashing when running with a python interpreter compiled without sqlite3 support (see #544)
> add support for python interpreters compiled without sqlite3 support. fixes #544

- yt_dlp/extractor/mediaset.py
---
As title, fixes #365 by creating cleaner http requests, more similar to the ones done by a web browser and not the ones done by apps or similar (where I think the previous method was taken)
- fixed video request
- fixed tests
- thumbnail extraction (can be improved)
> [mediaset] Fix #365

- README.md
- yt_dlp/extractor/youtube.py
---
---
Implements https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136 (tier-2 age-gate bypass).
> [YouTube] Tier 2 age-gate bypass implementation

- yt_dlp/extractor/mxplayer.py
---
---
```
[info] Available formats for 4b481d9c589e5aa4ea92bacc35949ebf:
ID                        EXT  RESOLUTION |   TBR  PROTO  | VCODEC             VBR  ACODEC     ABR  ASR    MORE INFO
------------------------- ---- ---------- - ------ ------ - ---------------- ------ --------- ---- ------- --------------------
hls-high-audio-stream_2-0 m3u8 audio only |        m3u8_n |                         unknown                stream_2
hls-high-audio-stream_2-1 m3u8 audio only |        m3u8_n |                         unknown                stream_2 …
```
> [MxplayerIE]Add H265 format extraction.

- README.md
- yt_dlp/extractor/youtube.py
---
---
Currently, age-restricted + non-embeddable videos do not work when trying to download them from the EU, because the `clientScreen`: `EMBED` bypass cannot be used for non-embeddable videos. Even with Cookies, users from the EU receive the `AGE_VERIFICATION_REQUIRED` status. Today I searched for more clientName's. I found the clientName `62`, which is used by YouTube Studio (Web). This client requires a user session, but no age verification. Furthermore, non-embeddable videos work.
Example Video from existing Unit Test: …
> [youtube] Add age-unverified account age-gate bypass (EU)

- yt_dlp/extractor/vrv.py
---
---
The VRV CMS API seems to have changed slightly since the release of the module, and the thumbnail part of the extractor has stopped working. The `video_data` now looks like [this.](https://gist.github.com/funniray/70edeed626ac98032b1a6ef74704e4a6)  
It appears that there may be able to be multiple thumbnails, however I was unable to find any episodes that have multiple thumbnails.
> Fix VRV Extractor

- yt_dlp/extractor/adobepass.py
---
---
This adds support for the Optimum/Cablevision MSO on adobepass. I've been using this for a while in my own fork of youtube-dl. Might as well add a PR for it here.
> [adobepass] Add support for Optimum/Cablevision

- yt_dlp/downloader/fragment.py
- yt_dlp/downloader/hls.py
- yt_dlp/webvtt.py
Description is in the commit message.
Related to #631; although that report has been filed about TTML-in-MP4 subtitles which this patch does not cover, the same issue appears in WebVTT streams served by the same host.
> Merge daisy-chained duplicate cues in segmented WebVTT streams

- yt_dlp/extractor/crunchyroll.py
---
---
The thumbnail for crunchyroll can no longer be taken from the XML api of Crunchyroll, however, the fallback for the thumbnail was pointed at media.metadata.thumbnail, however the thumbnail is just at media.metadata
> [crunchyroll] Fix thumbnail

- README.md
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/mirrativ.py
---
Note that the code is taken from [my fork](https://github.com/ytdl-patched/ytdl-patched/blob/ytdlp/yt_dlp/extractor/mirrativ.py), which is my own work.
---
This PR adds support for mirrativ.com, which is a streaming service in Japan.
example URL for live: https://www.mirrativ.com/live/xvbjsvT96UFjkPqaRj9ajg (running as of writing, but you can find new one at https://mirrativ.com/ )
example URL for user: https://www.mirrativ.com/user/7077880
> [mirrativ] add support for mirrativ.com

- yt_dlp/downloader/http.py
<details>
<summary>Boilerplate (not own code, bug fix)</summary>
- **I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)**
- **Bug fix**
</details>
The commit reverted here uses the value obtained from the `Content-Length` header to determine the length of data that will be downloaded in the HTTP request. The problem with this is that `Content-Length` is the size of the data *after* it has been processed by the encoding scheme specified in the `Content-Encoding` header, not of the raw bytestream, while the `urllib` library undoes the encoding transparently and operates on the decoded bytestream. (<https://stackoverflow.com/a/3819303/> contains references to the relevant specifications.) If …
> Revert erroneous use of the Content-Length header

- yt_dlp/extractor/youtube.py
---
---
The Innertube API appears to give useful error messages in the response payload for an HTTP Error. So, this PR attempts to extract such error and raise a warning. This might be useful for debugging future issues relating to the API.
The current implementation is to report the error as a non-fatal …
> [youtube:api] Extract error messages from HTTPError response

- devscripts/make_lazy_extractors.py
---
---
0b2e9d2c3051f2e1d79449adde3afbba3b5ec94f added code to "block plugins from loading", however it doesn't check for the existence of the plugins directory (`ytdlp_plugins`), and that directory is missing from the pypi tarball. When trying to build the package with `make_lazy_extractors`, it will fail due to the nonexistent directory.
I have to make [a patch in Nixpkgs](https://github.com/NixOS/nixpkgs/pull/133762/files#diff-33c1a0cd8efd7731bf4e179878b3d511527500c69fcb68c2536e136b07c73457R20-R24) but it would be great if this can be merged …
> [lazy_extractor] Check for plugins directory existence

- yt_dlp/extractor/eroprofile.py
---
It seems that the refactor done to my code in #658  skips pages. Running the test fails on current master:
```
[EroProfile:album] ...: Downloading playlist page 1
[EroProfile:album] ...: Downloading playlist page 2
[EroProfile:album] ...: Downloading playlist page 3
[...]
[EroProfile:album] ...: Downloading playlist page 8
[EroProfile:album] ...: Downloading playlist page 1
[EroProfile:album] ...: Downloading playlist page 27
[info] Writing playlist metadata as JSON to: ...
AssertionError: False is not true : Expected at least 486 in playlist, but got only 193
```
This seems to happen, because the new code presumes all page links are on page one. However, this is is not the case. Instead, page one contains a couple pages near it, but then "Next" and "Last" buttons.
This PR restores …
> [eroprofile] fix page skipping in albums

- yt_dlp/extractor/trovo.py
Replace 1 tab character `\x09` with space `\x20`.
> [trovo] [trivial] replace tab character with space

- yt_dlp/extractor/adobepass.py
---
This was originally submitted as ytdl-org/youtube-dl#19136, and originates from a public fork at https://bitbucket.org/ParadoxGBB/youtube-dl/commits/64bddfe15c1458a1b3461875bf9afd0a17ebeea0 with the LICENSE file still containing the Unlicense.
---
This fixes AdobePass login using `--ap-mso Verizon`. I have personally verified that this fix works on DisneyNOW at least.
> [adobepass] Fix Verizon SAML login error

- yt_dlp/options.py
---
---
--no-prefer-free-formats was actually setting the same value `store_true` as --prefer-free-formats , this fixes it to be proper value  `store_false` so it can work as intended and be an override to the yt-dlp config file.
> Fix --no-prefer-free-formats

- yt_dlp/extractor/nova.py
---
---
partially fixes https://github.com/ytdl-org/youtube-dl/issues/27840, but there are caveats:
Nova seems to have introduced DRM for downloads (SAMPLE-AES) that were published more than 7 days ago. Newer downloads are DRM free and work just fine. The NovaEmbedIE test still doesn't pass since it contains a very old episode and I haven't edited it because it'd get outdated very quickly.
Here's an example of downloading a recent episode:
with current master
```
[Nova] 76963-4094-dil: Downloading webpage
[debug] [Nova] Extracting URL: …
```
> [Nova] fix extractor

- yt_dlp/extractor/afreecatv.py
---
---
AfreecaTV marks segments of VODs, or entire VODs, as adult content. When accessing a VOD with adult segments from an underage account or when not logged in, the first request fails with a `PARTIAL_ADULT` error flag, and we retry with the `partialView=SKIP_ADULT` query parameter. This allows us to download the segments of the video that are not marked as adult.
Now, when accessing a VOD that is entirely marked as adult content, the first request fails with an `ADULT` error flag, *even if logged in to an adult account*. The web client …
> [afreecatv] Fix adult (19+) VODs

- yt_dlp/extractor/afreecatv.py
---
---
The AfreecaTV extractor currently relies on the fact that video filenames contain the upload date. Unfortunately, there appear to be some videos where this is not the case (I would cite examples, but all that I have encountered have since been deleted or made private). For these videos, the extractor puts junk data into the upload date field, which later causes a parse error that fails the download.
This commit adjusts the extractor's logic for parsing the upload date, so that after it extracts a candidate date value:
1. if the value does …
> [afreecatv] Tolerate failure to parse date string

- yt_dlp/extractor/tvplay.py
---
---
Fixes #820 
Appears that some Viafree urls were being picked up by the TVPlay/mtg extractor. These no longer with such extractor, however, do work with the existing Viafree extractor.
This PR also adds support for subtitles.
> [Viafree] Fix extractor and extract subtitles

- yt_dlp/extractor/xhamster.py
> [XHamster] fix: extract uploader_id

- yt_dlp/extractor/mediaset.py
---
---
This fixes extraction for <https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801> and possibly other videos, which worked before #564.
> [mediaset] Fix extraction for some videos

- yt_dlp/extractor/mtv.py
- yt_dlp/extractor/southpark.py
---
---
Related upstream PR: https://github.com/ytdl-org/youtube-dl/pull/28442
I notice youtube-dlc still worked with southpark.de and southpark.de/en, but https://github.com/yt-dlp/yt-dlp/commit/ee1e05581e32114c52e75e90983a66fb25fbc730#diff-170b237e5ae15340b8b6aae302f30b85bd4b59e85c365aab7290ea524ba0ce3b broke that support.
(youtube-dlc PR: https://github.com/blackjack4494/youtube-dlc/pull/188)
Changes:
- return `url` parameter in `mtv.py` from youtube-dlc (~~hopefully without breaking mtv~~ looks fine)
- implement more detailed tests from …
> [southpark] Fix SouthParkDE extractor

- yt_dlp/extractor/youtube.py
---
---
Retries on the 'Unknown Error' error sometimes received in an 200 OK response. (Fixes #839)
Also adds `only_once` to (unimportant) alert extraction. This fixes an issue where YouTube is displaying a different message regarding unavailable videos on every playlist page, regardless of if we are showing unavailable videos.
Might be worth investigating whether this may cause any issues with other messages.
> [youtube] Retry on 'Unknown Error' and do not repeat unimportant alerts

- README.md
- yt_dlp/extractor/youtube.py
---
---
Not sure what to call this.
This code was originally from  #682.
This PR adds:
- fallback player url extraction when it fails to be extracted from the webpage
- don't download js player unnecessarily for clients that don't require it
- try extract js player url from any additional client configs
- ability to skip the js player usage/download (inc iframe fallback).
-  This overrides the clients' config setting.
-  **This can be enabled with `--extractor-args youtube:player_skip=js`**
-  Formats that require signature decryption will be …
> [youtube] Add options to skip webpage and js player for video extraction

- .gitignore
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/musescore.py
---
---
Closes https://github.com/yt-dlp/yt-dlp/issues/911
Ln 46-47 is such that ln 48 it will break if id is matched from user provided url instead of url from webpage, this is intended.
mp3_url is also extracted in such way that it should break if json is irregular.
> Add MuseScoreIE.

- yt_dlp/extractor/canvas.py
---
---
may solve #976
To reproduce, run the following (causes login error because of invalid u/p):
`yt-dlp --ignore-config -v "https://www.vrt.be/vrtnu/a-z/het-scheldepeloton/1/het-scheldepeloton-s1a1/" --username "test" --password "test"`
> [VrtNU] Handle login errors

- test/test_postprocessors.py
- yt_dlp/postprocessor/modify_chapters.py
---
---
Multiple small fixes:
1. Restore a commit from https://github.com/yt-dlp/yt-dlp/pull/360 (@pukkandan force-pushed the `sponsor-block` branch from `eb3c813` to `e10ef4c` 15 days ago). Please consider using [--force-with-lease](https://blog.developer.atlassian.com/force-with-lease/) the next time.
2. <s>Standardized SHA256 hash sums.</s>
3. <s>Hash sums for TAR archive are currently missing.</s> Incorporated into https://github.com/yt-dlp/yt-dlp/pull/880.
4. Tiny chapters were unconditionally appended to the previous chapter. Now, if …
> SponsorBlock merge algorithm improvements

- yt_dlp/extractor/common.py
---
Hi,
I have come across an MPD manifest that includes a BaseURL attribute set to a root-relative URL. For example:
```
<BaseURL>/x/y/</BaseURL>
```
The current processing of BaseURL assumes the URL is either absolute (e.g. http://example.com/x/y/z) or relative (x/y/z). Root-relative URLs end up generating an incorrect fragment_base_url, failing to download content.
> Fix MPD BaseURL handling when root-relative URL

- yt_dlp/extractor/videa.py
---
---
This pull request fixes two issues with Videa:
* Player URL extraction when the URL is already in the form of `videa.hu/player?v=XXX`
* Extraction for videos where `hash_values` and `source_exp` doesn't exist. This was previously presumed to be required, but the video in the first test case seems to have dropped those values (if it ever had them).
Tests have also been added/updated to cover all these cases.
> [videa] Fix some extraction errors

- yt_dlp/extractor/sovietscloset.py
---
---
Fixes a crash when loading playlists for games that don't have the default "Misc" category and no category is specified.
The new behavior is to search for the "Misc" category but if it can't be found use the first category instead.
> [SovietsCloset] Fix finding playlists for games with only named categories

- yt_dlp/extractor/arte.py
The reference to video description within the JSON was wrong (null value)
---
---
Just change the JSON property referred to video description.
> Arte extractor : fix description reference

- yt_dlp/extractor/common.py
- yt_dlp/extractor/sovietscloset.py
---
---
Adds helper methods that add up m3u8 VOD segment durations and adds duration for SovietsCloset videos.
> [SovietsCloset] Add duration from m3u8

- yt_dlp/postprocessor/ffmpeg.py
---
---
Fixes issues with AAC HLS streams being truncated mid stream.
> [ffmpeg] Fix issues with AAC HLS streams being truncated mid stream.

- yt_dlp/utils.py
When there are bad certificates in windows store, `ssl.SSLContext.load_default_certs()` and therefore `ssl.create_default_context()` throws error without loading any certificate. This works around the issue by loading the certificates one by one instead
Closes https://github.com/yt-dlp/yt-dlp/issues/1060
See https://bugs.python.org/issue35665, https://bugs.python.org/issue4531
@MDM-79, please test this code and let me know
> Workaround for bug in `ssl.SSLContext.load_default_certs`

- yt_dlp/extractor/bbc.py
---
---
`mobile-tablet-main` only provides 540p25, so it shouldn't be used for the first attempt of fetching the mediaselector. Instead `pc` provides 540p50 up to 720p50.
> [bbc] Extract 720p50 instead of 540p25 on news videos

- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/common.py
- yt_dlp/utils.py
<details>
<summary>Boilerplate (original author, improvement/new feature)</summary>
- Improvement
- New feature
</details>
This extracts storyboards from SMIL manifests, as found in some ThePlatform streams. The storyboards are kept in a pretty… _interesting_ format: a JSON object containing a list of base64 data: URIs and some metadata.
The tested link was `http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000167059?mbr=true&manifest=m3u#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D`. I am unable to download the actual video stream, but storyboards do work fine.
Some fixups in surrounding code were necessary to make it work smoothly.
> SMIL storyboards

- yt_dlp/extractor/cbc.py
---
---
After discussion in [this](https://github.com/yt-dlp/yt-dlp/pull/1013#discussion_r720815687) subthread, I have removed some misleading comments from the CBC Gem extractor tests. I have also removed a `skip` param where it was not needed. This improves automated test coverage.
> Fix CBC Gem tests

- yt_dlp/extractor/coub.py
---
---
The existing code incorrectly labelled some formats as containing both audio and video. ~While it's true that these formats may include *an* audio stream in them, this is not the same thing as the "main" audio soundtrack for the Coub itself; this main audio is only delivered via a separate, audio-only format.~ On Coub, audio and video are always delivered via separate files.
Also, add `higher` as a recognized quality string, considered better than `high`. Without this, the extractor correctly lists the `higher` quality video, but it is …
> [Coub] Fix media format identification

- yt_dlp/extractor/mtv.py
---
---
So this seems to fix the download issues with most (I haven't tested all) of the networks currently using the MTVExtractor. The only thing this won't work on seems to be the video-clips portion of at least MTV.com but probably any other video-clip sections of the other sites. If anyone can get that up and running, it would be awesome, but for now this should get the vast majority of content able to download again.
> Update mtv.py to fix broken downloads

- .gitignore
- test/test_jsinterp.py
- test/test_youtube_signature.py
- yt_dlp/extractor/youtube.py
- yt_dlp/jsinterp.py
Overhauls jsinterp to handle youtube nsig decryption
Fixes: https://github.com/ytdl-org/youtube-dl/issues/29326
TODO:
> [youtube] Fix throttling by decrypting n-sig

- supportedsites.md
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rai.py
- yt_dlp/utils.py
---
---
Description of your pull request and other information
Support for www.raiplayradio.it added.
Notes:
- Using `--embed-thumbnail` produces ERROR: Conversion failed! on some links, like the one in the tests: I have no idea why that is happening, but the downloaded temporary image has a .jpg extension but it is encoded in webp (the URL is correct). The resolution and ratio are also different.
Here is an example:
`./yt-dlp --add-metadata -o '%(artist)s/%(album)s/%(title)s.%(ext)s' https://www.raiplayradio.it/playlist/2017/12/Alice-nel-paese-del …
> Raiplayradio

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/iprima.py
---
---
This pull request fixes the extractor for iPrima. With the exception of [cnn.iprima.cz](https://cnn.iprima.cz) and [autosalon.iprima.cz](https://autosalon.iprima.cz), all subdomains now use a new scheme that requires users to log in. 
The support for [autosalon.iprima.cz](https://autosalon.iprima.cz) is dropped as it currently uses neither the old nor the new scheme. [cnn.iprima.cz](https://cnn.iprima.cz) is still supported by the old extractor, which is kept with only minor fixes. It is also renamed to `IPrimaCNNIE` and only used for the …
> [iPrima] Fix extractor

- yt_dlp/extractor/youtube.py
---
---
For yt-dlp to handle Invidious links containing, e.g., playlist data, the other info extractors in youtube.py need to use the same list of Invidious sites that the main YoutubeIE class uses.
> [youtube] Use the full Invidious site list in playlist, tab extractors

- yt_dlp/extractor/canvas.py
---
---
updated according to a recent network trace in firefox. 
resolves #1557
testing: 
`python3 -m yt_dlp https://www.vrt.be/vrtnu/a-z/sabena/1/sabena-s1a1-het-grote-avontuur/ --netrc -Uv`
> fix vrt downloads

- yt_dlp/extractor/cbc.py
---
---
Fixes #1594
Some CBC Gem shows don't have all seasons available, maybe just seasons 10 to 21 for example. This PR tries to find the correct season by using the number in the JSON instead of just picking the 10th element in the seasons array for the 10th season.
> [CBC Gem] Support shows that don't start at season 1

- README.md
- yt_dlp/extractor/youtube.py
---
---
Minor improvement that adds a `default` player client, which is similar to `all` but adds whatever the default player clients are at the time. Might be useful when the user is wanting to add an extra client onto whatever is the default, but don't want to hard code the default as it may change in the future.
> [youtube] Add `default` player client

- yt_dlp/extractor/canalalpha.py
- yt_dlp/extractor/extractors.py
---
---
closes https://github.com/yt-dlp/yt-dlp/issues/1528
TODO:
* ~~Add tests~~
* ~~Improve json regex to not break for `&quot;`~~
* ~~Parse subtitles if avilable~~ (Not available)
> [CanalAlpha] Add extractor.

- yt_dlp/extractor/blogger.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
---
Adds support for blogger videos and embeds.
There is no discernable title field in any of the JSON or URLs,
and the title is mandatory so 'Blogger' is used as a substitute.
> [blogger] Add support for videos and embeds

- yt_dlp/downloader/hls.py
- yt_dlp/extractor/common.py
---
---
This pull request does two things:
* Report Adobe Flash Access as DRM instead of "No video formats found"
* Detect FairPlay/FlashAccess DRM when only specified HLS variant playlists rather than the master playlist (closes #1658)
> [hls] Improve DRM checks

- test/test_aes.py
- yt_dlp/aes.py
---
---
This PR adds support for ECB mode in aes.py, which is the simplest block cipher mode of operation.
This is mandatory for downloading from AbemaTV.
> AbemaTV batch 1/3: [AES] add ECB mode

- yt_dlp/extractor/bbc.py
---
---
Audio description is available in a separate manifest which is (at least sometimes) SD only. Sometimes BBC iPlayer will mistakenly mark it as the default format too.
Example:
```
yt-dlp --playlist-items 1 -F "https://www.bbc.co.uk/iplayer/episodes/p09twdp8/showtrial?seriesId=p09twdth"
```
I've changed the extractor to return all available formats, add the `types` field to format notes, and deprioritize audio described tracks.
Note: In this example audio description is tagged as `DubbedAudioDescribed`, but I check if the type contains …
> [bbc] Get all available formats, deprioritize audio description

- yt_dlp/extractor/generic.py
---
---
Support MPEG-DASH manifests that do not have ".mpd" in the url.
> [generic] Support mpd formats without file extension

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nebula.py
---
The primary purpose of this pull request is to add channel/playlist support to the Nebula extractor:
```
$ yt-dlp --netrc "https://nebula.app/lindsayellis"
[nebula:collection] Logging in to Nebula with supplied credentials
[nebula:collection] Authorizing to Nebula
[nebula:collection] Retrieving Zype access token
[nebula:collection] lindsayellis: Retrieving channel page 1
[...]
[nebula:collection] lindsayellis: Retrieving channel page 11
[download] Downloading playlist: Lindsay Ellis
[nebula:collection] playlist Lindsay Ellis: Collected 104 videos; downloading 104 of them
[download] Downloading video 1 of 104
[Zype] 617408d3a9f9bc0001f47b3e: Downloading JSON metadata
[...]
```
However, one thing led to another and this ultimately ended up being a complete rewrite. I think the new …
> [nebula] Rewrite extractor with channel support / fix #1690 "Unable to extract API key"

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/redgifs.py
---
---
Add extractor for redgifs.com. It is based on the gfycat extractor.
The generic extractor was not reliable for redgifs.com because:
- It downloads all the videos of different resolution instead of just downloading the best one.
- It does not work on some links as reported by https://github.com/yt-dlp/yt-dlp/issues/1504
> [redgifs] Add extractor

- yt_dlp/extractor/nova.py
---
Fixes the outdated NovaEmbed extractor due to recent changes on their website. Both unit tests are passing again with these changes.
> [NovaEmbed] Fix extractor

- yt_dlp/extractor/bilibili.py
> [Bilibili] Fix extractor

- yt_dlp/extractor/jamendo.py
Fixes #1857
---
---
Extractors which don't define `_VALID_URL_RE` but only `_VALID_URL` shouldn't try to use it directly.
Instead they should use `_match_valid_url` which is a method defined in the common extractor class.
> Fix Jamendo extractor by using _match_valid_url

- yt_dlp/extractor/common.py
- yt_dlp/extractor/sovietscloset.py
---
`yt_dlp/extractor/sovietscloset.py` is licensed under Unlicense.
---
Moves `parse_nuxt_jsonp` out from `sovietscloset.py` as a convenient function.
> [extractor/common] introduce `_search_nuxt_data`

- yt_dlp/extractor/ceskatelevize.py
After a site redesign on 2021-12-06, player iframe is no longer present in
the page from the start and is only inserted after pressing the "play"
button. We need to query /v-api/iframe-hash/ to get hash to pass to
iFramePlayer.php and extract "IDEC" id from a json in the original page.
---
---
Fix downloading from www.ceskatelevize.cz after website redesign of 2012-06-12.
> [ceskatelevize] Update to 2021-12-06 changes (#1899)

- yt_dlp/extractor/crackle.py
---
Original code from youtube_dl [80f772c28a3277376620ed7f50308e12437e358d](https://github.com/ytdl-org/youtube-dl/commit/80f772c28a3277376620ed7f50308e12437e358d)
---
Crackle has a metadata value called UseDRM. Currently yt-dlp interprets that as meaning _all_ formats are DRM protected. It seems to really mean that there is _at least one_ DRM protected format, but there may also be non-DRM formats. Letting the lower level extraction routines process all of the manifests will find the non-DRM formats and include or exclude the DRMed ones based on …
> [crackle] Always look for non-DRM formats

- yt_dlp/extractor/common.py
- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/skeb.py
- yt_dlp/utils.py
---
---
This PR adds support for skeb.jp. Not geo-restricted maybe.
> skeb.jp is a middleman to commission artists for pictures, voice works, animations, etc. 
the above quote is from, and partially closes https://github.com/ytdl-org/youtube-dl/issues/30287
> [skeb] add support for skeb.jp

- yt_dlp/extractor/cbc.py
---
---
This adds a new check to pull out "secret" video formats such at 6Mb 1080p. The original video formats begin with `hls-` while the new ones begin with `sec-`. Here is sample output with the changes (requires a free CBC account and geolocation within Canada):
```
~ % yt-dlp "https://gem.cbc.ca/media/murdoch-mysteries/s01e01" --username '***' --password '***' -F
[gem.cbc.ca] murdoch-mysteries/s01e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s01e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s01e01: Downloading …
```
> [CBC Gem] Support 1080p shows

- yt_dlp/extractor/zdf.py
---
---
This pull request adds support for videos that have their ptmd-template in mainVideoContent...streams.default, like some from FUNK. I have added a test for this kind of URL. No tests are failing, therefore I assume replacing the query instead of adding another is OK.
I have also removed a failing test (the URL currently returns a 410). If this should be in a different PR, please let me know.
> [zdf] add support for videos with different ptmd-template location

- README.md
- test/test_postprocessors.py
- yt_dlp/options.py
- yt_dlp/postprocessor/modify_chapters.py
- yt_dlp/postprocessor/sponsorblock.py
---
---
Filler Tangent category has been recently added to SponsorBlock: https://github.com/ajayyy/SponsorBlockServer/commit/db48953e39a6874774666100c5c4b29ce31bf81b
> [SponsorBlock]: Support for Filler category

- yt_dlp/extractor/brightcove.py
- yt_dlp/extractor/fujitv.py
---
---
added support for higher resolution thumbnail extraction for Tver (not sure for other sites that use this)
> [TVer/brightcove]added support for higher resolution thumbnail extraction

- README.md
- yt_dlp/extractor/archiveorg.py
---
- **a couple of the regexps used in metadata extraction are from old youtube-dl commits**
---
- Improved metadata extraction 
- currently best for polymer UI YouTube captures
- Title extraction should be fairly stable across almost all YouTube versions
- Extract `filesize` and `extension` from non-standard archive.org headers
- `unknown_video` extension should no longer occur
- Get archived thumbnails using CDX API
- Smarter webpage capture downloading 
- query CDX for only 200 OK response captures
- Tries multiple captures until it gets an …
> [web.archive:youtube] Improve extractor

- yt_dlp/extractor/fujitv.py
getting high resolution from android tv stream
---
---
fixes for fuji FOD and updated that it can extract 1080 stream from that
> Updated fujitv.py on extracting 1080P stream from tv_android m3u8

- yt_dlp/extractor/odnoklassniki.py
---
---
Some videos in Odnoklassniki only available in mobile website.
This adds fallback for the extractor to extract from mobile webpage, in case of PC webpage says not found.
Test case attached.
(note: not related to issue 1971)
> [ok.ru] add mobile fallback

- test/helper.py
---
Commit 0bb322b9c0 has broken unit tests by forgetting to include the new field in ignored_fields. 
```
AssertionError: {'webpage_url_domain'} is not false : Missing keys in test definition: webpage_url_domain
```
This PR fixes the regression.
> [test/download] ignore field webpage_url_domain

- test/test_InfoExtractor.py
- yt_dlp/extractor/common.py
---
---
* Support top-level @graph expressing implicit default graph
* Wrap the control flow block in a function, which is called recursively upon such a structure
* Per [W3C JSON-LD v1.1 §4.9 (non-normative ref)](https://www.w3.org/TR/json-ld11/#named-graphs):
> When a JSON-LD document's top-level structure is a map that contains no other keys than `@graph` and optionally `@context` (properties that are not mapped to an IRI or a keyword are ignored), `@graph` is  considered to express the otherwise implicit default graph.
* Extend …
> [extractor/common] Tweak JSON-LD extraction to support default implicit graph

- README.md
- devscripts/prepare_manpage.py
---
---
Cleaning up the docs as specified in #1448.
Tasks completed:
```
--option
Doc
````
format -> reactivated unused filter
> [docs] improve format of manpage

- README.md
- test/test_YoutubeDL.py
- yt_dlp/YoutubeDL.py
---
This pull requests adds a new internal operator to output templates: `&`. This causes the value of the field to be replaced by a given static string.
The purpose of this is to build output templates that are highly flexible, e.g. for handling non-playlist and playlist videos with the same configuration. Suppose you want to prefix the playlist index of a video in front of the filename. Using the following template works fine: ```%(playlist_index)s - %(title)s.%(ext)s```
But it has a flaw: if downloading non-playlist video (i.e. `playlist_index` is None), the filename is prefixed by `NA - `; we don't want that. A first improvement would be to use an empty default string like so:
```%(playlist_index|)s - %(title)s.%(ext)s```
This at least removes the `NA`, but still leaves the useless ` …
> Add replacement output template via `&`

- CONTRIBUTING.md
- README.md
- pyinst.py
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/sendtonews.py
- yt_dlp/jsinterp.py
- yt_dlp/options.py
---
This fixes the following typos and grammatical errors:
"allow to" → "allow one to"
compatability → compatibility
dependancies → dependencies
dependancy → dependency
exisiting → existing
prefered → preferred
reencode → re-encode
seperate → separate
seperated → separated
seperator → separator
specifc → specific
This specifically does not fix the spelling error of the 'seperate-video-versions' option, however.
> Fix some typos.

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/soundcloud.py
---
---
examples:
- https://soundcloud.com/wajang/sexapil-pingers-5/recommended
- https://soundcloud.com/wajang/sexapil-pingers-5/sets
- https://soundcloud.com/wajang/sexapil-pingers-5/albums
This is an initial patch for another soundcloud extractor. I still need to add some test values (only manual probing, i will look at test results tomorrow).
Specifically i'm requesting comments about:
- the regex change at line 75-77 (i don't know what a token is nor tested with one)
- the playlist id i'm giving at line 852 is just the id of the track, not …
> [soundcloud] Add related tracks extractor

- yt_dlp/extractor/abc.py
- yt_dlp/extractor/extractors.py
---
Add extractor for latest episode of an ABC iView show.
This allows to download using only the show URL instead of
having to find out the latest episode URL manually.
> [ABC] Add extractor for latest episode of an iView show

- yt_dlp/extractor/ondemandkorea.py
---
---
Currently, the ondemandkorea extractor is broken. The Javascript code containing the player configuration has changed on the website.
Before it was:
```javascript
odkPlayer.init({ 
PLAYER_CONFIG_IS_HERE
});
```
Now it is:
```javascript
var playlist = [{ PLAYER_CONFIG_IS_HERE }]
```
This PR updates the regex, so the same data can be extracted as before.
> [ondemandkorea] update jw_config regex

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/rtve.py
---
---
This adds support to audio only urls to the rtve extractor. So far this extractor did not support urls like Audio only episode . With this extension such audio only url is supported.
The class supporting the above mentioned url includes a test case which runs successfully here.
Taken over from https://github.com/ytdl-org/youtube-dl/pull/29023
> [rtve] Add support for audio only

- yt_dlp/extractor/njpwworld.py
---
---
Use `_extract_m3u8_formats`, `m3u8_native` for concurrent downloads.
> [NJPWWorld] use _extract_m3u8_formats

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/__init__.py
- yt_dlp/downloader/common.py
- yt_dlp/downloader/external.py
- yt_dlp/downloader/fragment.py
- yt_dlp/downloader/http.py
- yt_dlp/options.py
---
---
Closes #517. I marked this as an improvement because the problem is arguably not a bug in yt-dlp itself. This is more of a workaround for the behavior of Python's `open()` function (which may itself not be the root cause - it would certainly be a very longstanding issue).
I wanted to add a new parameter (something like `--fileopen-retries`) but because `sanitize_open` is a generic utility function, every call site would have to be modified (and some of them don't look like they can easily access options themselves). Instead I just set the …
> Add --fileopen-retries to retry on file access errors.

- yt_dlp/utils.py
---
---
Surprisingly, the date format `%Y%m%d%H%M` will successfully match against one-digit month, day, hour, and minute strings, even though `%m` et al. are [documented as being zero-padded](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes). For most of the year, one of the digits in a two-digit month is zero, which prevents the month from being misinterpreted as month and date. However, for dates in November, 11 can parse as January 1st (similarly, 12 as January 2nd). In this case, the actual day will be …
> Fix parsing YYYYMMDD dates in Nov/Dec

- yt_dlp/extractor/common.py
- yt_dlp/extractor/npr.py
Update `_extract_smil_formats` call. Pass `fatal=False` so that it it
does not fatally fail when a SMIL link returns a 404 error.
Also update InfoExtractor._extract_smil_formats_and_subtitles to
always return two elements.
This fixes #1934
---
---
> [npr] don't fatally fail when SMIL link 404s

- yt_dlp/extractor/youtube.py
---
---
Extracts preliminary, mostly lower-quality thumbnails from playlist. Mostly useful for when parsing data when using flat playlist.
Closes #1184
> [youtube:tab] Extract video thumbnails from playlist

- yt_dlp/extractor/generic.py
---
---
GenericIE support for KVS Player works only on sites that serve kt_player.js via HTTPS urls. On sites that serve the script via HTTP, GenericIE fails to work because the regex it uses assumes HTTPS.
* Fixes regex by allowing it to accept both HTTPS and HTTP urls.
* Adds a test to assert the fix for a site that uses HTTP (not HTTPS) to serve kt_player.js.
> [generic] Fix GenericIE KVS Player support via HTTP

- yt_dlp/extractor/common.py
- yt_dlp/utils.py
<details> <summary> Boilerplate (own code, improvement) </summary>
- Improvement
</details>
This is the [‘more long-term’ solution I alluded to before](https://github.com/yt-dlp/yt-dlp/issues/656#issuecomment-895087864). It makes the handling of subtitle vs non-subtitle streams in DASH manifests more uniform, and adds support for WebVTT-in-MP4 encapsulation (`wvtt` codec).
> Recognise timed-text codecs in DASH manifests (stpp and wvtt)

- yt_dlp/extractor/mixcloud.py
---
---
Some tracks on mixcloud can be restricted from being played. This patch adds proper detection of this, as well as throwing an error when a track is not found.
example track with licensing restriction: `https://www.mixcloud.com/mistabibs/mista-bibs-modelling-network-best-of-akon/`
> [mixcloud] add restriction detection

- yt_dlp/extractor/canvas.py
---
---
fixes #2146
internal json has _empty_ `title` >> adapt test to test if key exists:
`{'duration': 3121060, 'skinType': 'vod', 'title': '', 'shortDescription': None, 'drm': 'vrt|2021-12-28T.....Z|.../...', 'drmExpired': '2021-12-28...', 'aspectRatio': '16:9', 'posterImageUrl': None, 'channelId': None, 'targetUrls': [{'type': 'mpeg_dash', 'url': 'https://remix-cf.lwc.vrtcdn.be/remix/0603b9c1-b117-4caf-a4c1-xxx/remix.ism/.mpd'}, {'type': 'hls_aes', 'url': 'https://remix-cf.lwc.vrtcdn.be/remix/0603b9c1-b117-4caf-a4c1-xxx/remix_aes.ism/.m3u8'}, …
> [VrtNU] fix empty title in json test

- README.md
- yt_dlp/extractor/hotstar.py
---
---
Usage:  `--extractor-args 'hotstar:res=sd,hd;vcodec=h264;dr=sdr'`
> Add extractor arg for Hotstar to ignore tags

- test/test_InfoExtractor.py
- yt_dlp/extractor/common.py
---
The Json-ld extractor assumes `thumbnailUrl` is a string but it can be a list.
This fix sets `thumbnail` if a `compat_str` is found and `thumbnails` if a `list` is found.
Real-world example in this page: https://www.rainews.it/video/2021/12/Tg3-Frida-Bollani-8f449635-e334-4105-8357-563f2bde1158.html I could'n understand why it did't extracted the thumbnail and so I made this fix to the common.py file
> [common] extract thumbnail/s from JSON-LD

- yt_dlp/extractor/hrfensehen.py
Hessischer Rundfunk seems to have changed the data attribute from
data-hr-mediaplayer-loader to data-new-hr-mediaplayer-loader.
---
---
> [hrfernsehen] Fix extraction of ardloader

- test/test_utils.py
- yt_dlp/utils.py
---
---
This patch improves the usability of `get_elements_by_attribute` and all its' calling variants for parsing nested HTML elements and allowing it to also return the matched element rather than only its' content.
* Introduce `get_first_element_by_tag`, which matches the first element with the given tag and returns a tuple with the whole element and its' content
* This works with `HTMLBreakOnClosingTagParser`, which parses nested elements to a stack of tags and stops when it reaches the closing
tag for the first opening tag it encountered
* …
> [utils] Improve parsing for nested HTML elements

- yt_dlp/extractor/fox.py
---
---
Fix extractor for fox.com videos as originally discussed in #1216. Extractor no longer requires TV provider to access videos, thus no longer inherits from `AdobePass`. Videos from Fox can be downloaded simply by passing in the main player URL, e.g. https://www.fox.com/watch/b057484dade738d1f373b3e46216fa2c/. This is done by leveraging the "free preview" Fox makes available to all users.
> [fox] Fix extraction of m3u8 URL, do not inherit from AdobePass

- supportedsites.md
- yt_dlp/extractor/afreecatv.py
- yt_dlp/extractor/extractors.py
---
---
AfreecaTV is a platform for both prerecorded and live video content. Until now, `yt-dlp` has only supported downloading VODs from AfreecaTV. This PR adds a new extractor for live video from AfreecaTV. The new extractor inherits from the existing AfreecaTV extractor in order to reuse its authentication logic.
> [afreecatv] Add support for livestreams

- yt_dlp/extractor/nbc.py
---
---
Update the regexes in the `NBCSportsVPlayer` and `NBCSports` extractors to get proper URLS for ThePlatform. Closes #2059.
> [NBCSports] fix regexes to properly extract platform URLs

- yt_dlp/extractor/pornhub.py
- yt_dlp/extractor/youtube.py
---
In the YouTube extractor, this removes the v2 onions as support for them has finally been [removed](https://support.torproject.org/onionservices/v2-deprecation/) from Tor, and adds a couple Invidious instances as found in the [documentation](https://docs.invidious.io/Invidious-Instances.md), it does not remove the several that seem down though.
In the PornHub extractor, it replaces the v2 onion address with the current v3 address.
I'd like to sort the Invidious onion instances, but figured that'd make too much noise.
> [PornHub,YouTube] Refresh onion addresses.

- test/test_utils.py
- yt_dlp/utils.py
---
---
* Simplify regex to avoid catastrophic backtracking, noticed after #2129
* Loosely match anything between the tag and the AV-pair of interest (authored by @pukkandan)
* Only match up to the AV-pair of interest, rather than the end of the end of the opening tag
* Strictly match an unquoted value
* Likewise determine if quotes are optional around the matched value
* Avoid `re.DOTALL` as `.` is not used
* Yield directly in `re.finditer`, rather than append to and return a list
* Noop as both calling functions perform list comprehension
* But …
> [utils] Fix get_elements_text_and_html_by_attribute regex

- yt_dlp/extractor/veoh.py
---
This is an update of [youtube-dl PR 22661](https://github.com/ytdl-org/youtube-dl/pull/22661). It makes the following changes to the veoh extractor:
- Accept `videos` URLs.
- Prefer high quality (current master incorrectly marks "Regular" rather than "HQ" as "best").
- Extract metadata for `age_limit`, `categories`, and `tags`.
It also updates the test cases and removes the defunct `_extract_video` method.
Thank you!
> [veoh] Accept "videos" URLs; prefer HQ format; get additional metadata

- yt_dlp/extractor/twitcasting.py
---
---
Closes #2289. Looks like the situation happens when the streamer requires login to watch streams.
(The lint error is happened outside of this PR)
> [twitcasting] Throw proper error for login-only streams

- yt_dlp/extractor/yahoo.py
* Supported long playlist.
* Skip downloading unavailable videos.
---
---
Yahoo!GYAO!'s playlist API returns ~50 titles per page by default.
If number of titles is more than 50, multiple fetching are required.
Current extractor doesn't support it.
This patch repeats fetching playlists till getting all titles.
And skips downloading titles which are not yet available.
> [yahoo:gyao] Improved playlist handling

- yt_dlp/extractor/generic.py
---
---
Current generic KVS player extractor does not work correctly on porntrex.com and issues were identified in #2281.
This is the follow up PR.
> [generic] improve KVS player video extraction

- yt_dlp/extractor/dplay.py
---
DiscoveryPlus in Italy migrated to the standard discoveryplus.com, so I migrated the DiscoveryPlusItaly extractor as a subclass of DiscoveryPlus.
I also removed the old, no more working DiscoveryPlusItalyShow extractor.
This should fix #2138
> [dplay] Migrate DiscoveryPlusItaly to DiscoveryPlus

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/glomex.py
---
---
This patch adds support for Glomex videos, both embeddable and on the (demo) site video.glomex.com. Glomex operates a media exchange platform, which powers their video marketplace service, based on revenue sharing. This is used quite a lot in large parts of Europe, primarily by digital news outlets, which embed in their assets video clips provided by various content providers (for example TV channels), tied with advertising. 
* Add new IEs
* GlomexBaseIE: Base IE class
* GlomexIE: Extract videos from video.glomex.com (by deferring to …
> [extractor/glomex] Add new extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/megatvcom.py
---
---
This patch adds support for video extraction from megatv.com, a popular Greek content provider and (recently re-)established TV network.
* Add new IEs
* MegaTVComBaseIE: Base IE class
* MegaTVComIE: Extract from TV VOD pages and news articles, i.e. all sorts of pages showing videos on megatv.com
* MegaTVComEmbedIE: Extract iframe-embeddable megatv.com videos
* When video_id is not matched in the URL, namely for news articles, extract it (article_id) from a particular element on the web page
* Derive metadata and sources directly from the …
> [extractor/megatvcom] Add new extractor

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/generic.py
- yt_dlp/extractor/tvopengr.py
---
---
This patch adds support for video extraction from tvopen.gr and affiliated ethnos.gr, a popular Greek TV content provider and news outlet.
* Add new IEs
* TVOpenGrBaseIE: Base IE class
* TVOpenGrWatchIE: Extract videos from TV VOD pages on tvopen.gr and ethnos.gr
* TVOpenGrEmbedIE: Extract iframe-embeddable tvopen.gr or ethnos.gr videos
* For embeddable and `tvopengr:watch` videos not on tvopen.gr, redirect to the equivalent page at tvopen.gr/watch/... which includes better metadata
* `VideoObject` JSON-LD
* full (rather than truncated) …
> [extractor/tvopengr] Add new extractor

- yt_dlp/extractor/youtube.py
- yt_dlp/utils.py
---
---
From https://github.com/yt-dlp/yt-dlp/pull/2223
While investigation is needed for the `playerResponse` date issue, I think we should at least merge this.
> [youtube] Enforce UTC and use utcnow() in `datetime_from_str`

- yt_dlp/extractor/ard.py
<details><summary>Boilerplate (own code, improvement/feature)</summary>
- Improvement
- New feature
----
</details>
This extracts subtitle links from the XML document in the ARDIE extractor.
Supersedes or resolves:
- ytdl-org/youtube-dl#17766
- ytdl-org/youtube-dl#30543
> [ard] Extract subtitles

- README.md
- yt_dlp/extractor/crunchyroll.py
---
The existing crunchyroll beta support simply parses the page enough to find the non-beta url, then hands off to the non-beta extractor. This no longer functions for premium content for US users, since the non-beta site forcibly redirects to the beta site. See #1911.
This implements direct support for crunchyroll beta through the API, but only when a login cookie is present. Otherwise, it hands off to the non-beta extractor as usual (this is in line with what happens with an actual browser as well).
Notes:
- This is literally the first python code I have ever written. It's probably pretty horrible. I've tested that it works, but the way encoding issues are handled in python isn't familiar to me... I pretty much just tried random things until it started behaving as I wanted in that …
> [crunchyroll:beta] Add self-contained support for crunchyroll beta for logged in users

- yt_dlp/extractor/glomex.py
---
---
Avoid match objects iteration in `GlomexEmbedIE._extract_urls` to keep memory usage under control.
Fix #2512
> GlomexEmbedIE._extract_urls: Avoid match objects to keep mem usage under control

- yt_dlp/extractor/viki.py
---
---
This pull request fixes downloads from Viki returning a "Bad request" error. By using a different device ID, `drms=dt3` and then modifying the URL, it's still possible to get 1080p non-DRM streams.
Closes #2499.
> [viki] Fix "Bad request" error on manifest request

- yt_dlp/extractor/crunchyroll.py
---
Closes #1424 
Hardcodes some data that could be retrieved from self._LOGIN_URL if cloudflare wasn't so trigger-happy.
The data does appear to be constant, but I've left the retrieval method in comments so that if they do change, breakages can be easily fixed by anyone who can use a web browser's "view source" feature and knows a little python.
If anyone knows a way to reliably get around this and download the page, that would of course be preferable.
I have not tested this with the non-beta site, as I'm in the US and thus forced to the beta site, but it *should* work, and since it wasn't working before, it is, at worst, a no-op for those users.
> [crunchyroll] Login support

- yt_dlp/extractor/mildom.py
---
---
This should deal with issue #2519 , including the improvements I proposed. I have tested the changes in a couple of channels containing the problematic video IDs, plus a few livestreams, and everything seems to work as intended. Regarding the video IDs getting truncated in the download log, I must have misremembered it because I could not reproduce anything like that. The download archive seems to work normally.
* Fixed _VALID_URL regex (now it looks explicitly for an optional third digit block in the video ID)
* Added '__plataform=web' to …
> [mildom] Fixes and improvements (should close #2519 )

- yt_dlp/extractor/pladform.py
---
---
Fix external player redirect URL extraction. Examples:
http://out.pladform.ru/player?pl=18079&type=html5&videoid=100246529 -> rutube
http://out.pladform.ru/player?pl=18079&type=html5&videoid=100231282 -> rutube
> [Pladform] Fix redirection to external player

- yt_dlp/extractor/globo.py
---
---
Fixing #2524
Added 2 calls to download pages to setup cookies. First call is needed to set GLBEXP and glb_uid cookies. Second call is needed to set locksession
Changed playback video version to 2. 
Fixed the JSON format for the new version.
Added a new test case.
> Fixing globo #2524

- yt_dlp/extractor/glomex.py
The regex was trying to be too smart. Especially the `<x(a|b|.+)+>` pattern to detect attributes is terrible since it matches every `x` tag. The inability to use `[^>]` for `script` makes it worse and results in huge intermediate matches. Breaking up the regex makes memory use negligible while also giving 50-300x perf on random pages (from my naive profiling)
I have tested `iframe` and `glomex-player`. But can't find any example of `script`/`div`
@zmousm
Fixes #2512
> [glomex] Simplify embed detection

- yt_dlp/extractor/globo.py
---
---
Fixing #2730 
Added new video ID regex 
Removed fatal=False in _og_search_title to prevent double call.
```
D:\ytdlp\yt-dlp>flake8 yt_dlp\extractor\globo.py
D:\ytdlp\yt-dlp>
D:\ytdlp\yt-dlp>python -m yt_dlp -v "https://ge.globo.com/video/ta-na-area-como-foi-assistir-ao-jogo-do-palmeiras-que-a-globo-nao-passou-10287094.ghtml"
[debug] Command-line config: ['-v', 'https://ge.globo.com/video/ta-na-area-como-foi-assistir-ao-jogo-do-palmeiras-que-a-globo-nao-passou-10287094.ghtml']
[debug] User config …
```
> [globo] Adding new videoID regex #2730

- yt_dlp/extractor/globo.py
- yt_dlp/extractor/kaltura.py
- yt_dlp/extractor/svt.py
- yt_dlp/extractor/vimeo.py
<details> <summary>Boilerplate (own code, bugfix/improvement)</summary>
- Bug fix
- Improvement
---
</details>
This extracts subtitles from Vimeo, Kaltura, Globo and SVT; those were [found by searching the issue tracker](https://github.com/yt-dlp/yt-dlp/issues?q=%22ignoring+subtitle+tracks%22).
Resolves #2663.
> Extract subtitles from streaming manifests for more sites

- README.md
- yt_dlp/YoutubeDL.py
---
---
This adds a new format filter operater that allows to filter video formats by matching the string based format fields against a regex.
Example usage: -f `bestvideo*[vcodec~="(he|a)vc|[hx]26[45]"]+bestaudio/best`
Alternatively, single quotes can be used to delimit the regex.
This implements my feature request #2681.
> Add regexp operator to format filters

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/ruv.py
---
---
This adds an extractor for the new `https://ruv.is/*/spila/...` VOD platform. 
Creating this as draft because the duration returned by the API is not consistent with the duration shown in the player, I'll have to fix that.
Fixes #2122.
> [ruv.is] add extractor

- yt_dlp/cookies.py
If ~/Library/Cookies/Cookies.binarycookies doesn't exist use ~/Library/Containers/com.apple.Safari/Data/Library/Cookies/Cookies.binarycookies if it exist.
---
---
The Cookies.binarycookies file in macOS Monterey is in a different location. If the binarycookies file isn't found in the original location it'll check for the file in the new folder.
> Update Cookies.binarycookies location in cookies.py

- yt_dlp/extractor/bbc.py
---
---
Fixes "Unable to extract playlist data" error on BBC news articles (https://github.com/yt-dlp/yt-dlp/issues/1374)
`window.__INITIAL_DATA__` is now a JSON string which needs to be parsed twice. Blocks for articles are now nested in two more layers.
> [bbc] Fix extraction of news articles

- yt_dlp/downloader/fragment.py
- yt_dlp/extractor/youtube.py
---
---
This fixes bogus behavior of `--live-from-start` for YouTube, includes:
- Intermediate `Frag` files remains without being concatten
- Ctrl+C problem on Windows
- Merger doesn't run after downloading
I'm running a long-run tests now, but ready for preliminary review 
Memo for myself:
Long-lasting live: https://www.youtube.com/watch?v=fEvM-OUbaKs
Shorter live: find one here: https://nijisanji.net/ https://schedule.hololive.tv/
Known problems:
- Network socket leak (workaround: `ulimit -n 65536`)
> [downloader/fragment] Improve `--live-from-start` for YouTube livestreams

- yt_dlp/downloader/fragment.py
- yt_dlp/downloader/http.py
- yt_dlp/utils.py
---
---
See https://github.com/yt-dlp/yt-dlp/issues/2001#issuecomment-1052119472 and https://github.com/yt-dlp/yt-dlp/issues/2239#issuecomment-1052132403
Closes #2001
Closes #2239
This changes behavior for `--no-continue` when native downloader involves, but the current behavior is wrong since the option states "Do not resume partially downloaded fragments."
> [downloader/fragment] Fix bugs around resuming with Range

- yt_dlp/extractor/youtube.py
---
---
Fixes #2694 
Issue: when redirecting a channel, YouTube drops the current tab and params from the url.
> [youtube:tab] Follow non-standard redirect to regional channel

- yt_dlp/downloader/common.py
- yt_dlp/downloader/external.py
- yt_dlp/downloader/fragment.py
- yt_dlp/options.py
---
---
I'm still getting some file access errors on my laptop, so I extended the logic to cover a few more places. I added `try_remove`, matching `try_rename` to avoid bare `os.remove` calls. To avoid code duplication I turned the retry logic into a decorator that wraps `sanitize_open`, `try_remove` and `try_rename`.
Notes:
- `try_rename` had a custom error message. I couldn't add it to the decorator and I think it would have conflicted with the error handling so it now raises the built in error if it fails.
- I added `error.EINVAL` (error 22) to …
> Extend file access retries to check rename and remove as well

- yt_dlp/extractor/common.py
---
---
Bug found when working on #2908 
`mark_watched()` calls `_get_login_info()`, which assumes that `_NETRC_MACHINE` is defined as this should only be called if an extractor supports user/pass auth. However, username/password auth is not a requirement for `mark_watched()`
> [extractor/common] Fix bug with mark watched when extractor does not support user/pass auth

- yt_dlp/extractor/crunchyroll.py
---
Includes the server's error message in the output when login fails. Reaction to debugging interaction in #2930.
> [crunchyroll] better error reporting on login failure

- yt_dlp/extractor/peertube.py
---
Add the [Free Software Foundation Europe](https://media.fsfe.org)'s Peertube instance to the list. It is using the new video URL format, so is currently not detected by youtube-dl (see ytdl-org/youtube-dl#29475). Basically the same PR as ytdl-org/youtube-dl#30536. As media.fsfe.org is in the official peertube instances list, I decided to put it there.
> [peertube] Add support for media.fsfe.org

- yt_dlp/__init__.py
- yt_dlp/options.py
- yt_dlp/postprocessor/ffmpeg.py
- yt_dlp/utils.py
1. Split init code into multiple functions
2. Clean up validation code by grouping similar types of options
2. Expose `parse_options` to third parties to address usecases like https://github.com/deepjyoti30/ytmdl/issues/185
Drafted because:
1. [ ] Can the `validate_options` be further simplified/split?
2. [ ] Not fully tested
> Refactor `__init__.py`

- yt_dlp/YoutubeDL.py
---
When using option `--ignore-no-formats-error` the extractor might have an url field set to None. With the fix provided it is still possible to extract the rest of the metadata.
> [fix] avoid string concatenation if url is None

- yt_dlp/downloader/mhtml.py
- yt_dlp/extractor/francetv.py
- yt_dlp/extractor/youtube.py
---
---
As per [extractor/common.py](https://github.com/yt-dlp/yt-dlp/blob/a825ffbffa0bea322e3ccb44c6f8e01d8d9572fb/yt_dlp/extractor/common.py#L174-L182), a fragment can either have a relative url (`path`) or absolute url (`url`). MhtmlFD currently does not take into account fragments that have an absolute url.
This also fixes the FranceTV extractor which incorrectly uses `path` for the absolute url in fragments.
The fix is copied from the implementation in [DashSegmentsFD](https://github.com/yt-dlp/yt-dlp/blob/a825ffbffa0bea322e3ccb44c6f8e01d8d957 …
> [downloader/mhtml] Fix fragments with absolute urls

- yt_dlp/downloader/fragment.py
- yt_dlp/downloader/ism.py
- yt_dlp/downloader/mhtml.py
- yt_dlp/downloader/youtube_live_chat.py
---
Based on pukkandan's patch
---
Closes #3008
cc @pukkandan
> [fragment] Read downloaded fragments only when needed

- yt_dlp/extractor/paramountplus.py
---
---
ParamountPlus extractor was only downloading the first 50 episodes of TV series.  This fixes the extractor to download all episodes.
Tests `TestDownload.test_ParamountPlusSeries_1` and `TestDownload.test_ParamountPlusSeries_2` were failing, now passing.
This issue is mentioned in #1466, but does not completely solve what's reported there.
> [ParamountPlus] fix to download all episodes from series

- yt_dlp/extractor/afreecatv.py
---
---
AfreecaTV changed the format of their URLs for VODs. Downloading via the old URLs still works, because they redirect, but the extractor does not match the new URLs. This PR adds a URL pattern and a match-only test.
> [afreecatv] Match new vod url pattern

- test/test_utils.py
- yt_dlp/utils.py
---
---
Before `format_decimal_suffix` would fail with an exponent greater than 8. Now it should be able handle larger numbers. While file sizes this large may be unrealistic, we can get size info from an external source themselves so it's good to handle this case.
**Before:**
```python
>>> from …
```
> Fix format decimal suffix for exponents greater than 8

- yt_dlp/downloader/http.py
---
---
Makes the http downloader much more lenient on what it retries on, to survive any sort of brief network interruption etc. (given enough retries for such). 
We are thinking it is better to retry on more even though some may be unrecoverable, vs retrying on few, known and likely to be recoverable errors but missing many other cases.
Resolves https://github.com/yt-dlp/yt-dlp/issues/3056, https://github.com/yt-dlp/yt-dlp/issues/2071, https://github.com/yt-dlp/yt-dlp/issues/3034, https://github.com/yt-dlp/yt-dlp/issues/2969 and prob many …
> [downloader/http] Make retrying more lenient

- yt_dlp/downloader/http.py
---
---
Funimation seems to respond with 206 even if the start is before end, while it's supposed to respond 406. It addresses that problem.
I'm not confident with the code, but at least we can download video without corrupting anything.
> [downloader/http] Reject broken range before request

- yt_dlp/downloader/external.py
---
From https://github.com/ytdl-org/youtube-dl/pull/29343
---
wget `--proxy` argument accepts a bool for enable/disabling the proxy, not for setting what proxy to use.
so before it was sending the proxy url as a normal url to download...
see https://github.com/ytdl-org/youtube-dl/pull/29343 for more details
> [downloader/external] Fix WgetFD proxy

- yt_dlp/extractor/generic.py
---
---
This adds support for extracting subtitles from video.js embeds.
Example URL where it happens: https://www.nhk.or.jp/d-garage/catchup/r/325245.html (yt-dlp also gets sources from development code, but whatever)
> [generic] Extract subtitles from video.js

- yt_dlp/downloader/external.py
- yt_dlp/utils.py
---
---
Accept-Encoding header should be set for each downloader to what it supports, whether that is for native or external. 
This should fix #3142 
notes/findings for reference:
- httpie downloader automatically sets Accept-Encoding; it uses urllib3 underneath I believe.
- wget only supports gzip encoding (so potential issue in youtube-dl)
- Aria2cFD already adds the option to add gzip&deflate headers
Not sure about Axel or ffmpeg
> [core] Remove `Accept-Encoding` header from `std_headers`

- yt_dlp/extractor/fc2.py
- yt_dlp/utils.py
Authored by: Lesmiscore
---
---
Allow omitting `__enter__` invocation for WebSocketsWrapper.
> [utils] WebSocketsWrapper: Allow omitting `__enter__` invocation

- yt_dlp/extractor/go.py
- yt_dlp/extractor/viu.py
<details> <summary> Boilerplate (own code, improvement/feature/fix) </summary>
- Improvement
- New feature
- Bug fix
</details>
Previously in this series: #247, #515, #948, #2686.
The Go case was caught, again, on issue tracker: <https://github.com/yt-dlp/yt-dlp/issues/2764#issuecomment-1038542729>, <https://github.com/yt-dlp/yt-dlp/issues/2818#issuecomment-1046365267>. This PR is *not* expected to resolve the overall tickets, though.
The fix for viu is speculative, as the reporter in the upstream ticket (ytdl-org/youtube-dl#30779) used the direct stream URL instead of the player frontend URL. It is not certain if this will work, as I have no means to test it.
As a side note, …
> Manifest subtitles V

- test/test_utils.py
- yt_dlp/extractor/youtube.py
- yt_dlp/utils.py
---
---
On some feeds (channels and search atm), YouTube has replaced the duration overlay (which is where we were getting duration from) with a shorts badge :roll_eyes: 
This PR adds a fallback to extract the duration from the accessibility data. 
I've had to modify `yt_dlp.utils.parse_duration` slightly to handle the duration format.
This data looks like this for reference:
```
WEIRD Sandwich Hack 😳 #shorts by Lionfield 13 hours ago 15 seconds 207,566 views - play Short
Italians get mad at VIRAL Tiktok videos by Lionfield 6 days ago 4 minutes, …
```
> [youtube:tab] Fix duration extraction for shorts

- yt_dlp/extractor/bilibili.py
---
---
The `BiliIntlIE` extractor is currently written to download content with a series and episode ID. I believe this is generally used for series that have been licensed from a studio (sometimes described as "OGV" in this market). This is similar to the operating model of, say, Netflix or Crunchyroll.
However, BiliBili also supports user-generated content (UGC). These videos have a slightly different URL structure, and pass slightly different API parameters (`aid` instead of `ep_id`/`episode_id`). This PR updates the extractor to support UGC …
> [BiliIntl] Support user-generated content videos

- yt_dlp/extractor/twitcasting.py
---
---
Return as video when there's only one m3u8 manifest for the given archives.
It prevents previous file being overwritten by ConcatPP.
> [twitcasting] Don't return multi_video for archive with single hls manifest

- yt_dlp/extractor/bilibili.py
---
---
Extractor was cutting titles at first single quote. Related issue: #3289. This PR fixes that.
I uploaded a test file to test both single and double quotes after my changes and I added it to the tests. I also updated existing tests, because trying to run them all was failing for me (seems like they are outdated), I hope that's ok too.
> [bilibili] fixed extracting title with single quotes

- yt_dlp/downloader/fragment.py
---
---
This makes `--live-from-start` behave the same as multithreaded download. It happens when the user specified only one format using `-f`.
This changes nothing for normal downloads.
> [downloader/fragment] Make single thread download work for --live-from-start

- yt_dlp/postprocessor/embedthumbnail.py
---
---
Skips converting thumbnail when embedding thumbnails for mkv only. closes #3209
> Disable thumbnail conversion for mkv

- yt_dlp/extractor/bandcamp.py
---
---
Fixes #3318 by excluding items listed on Bandcamp user pages that link to merch items, where there is no media to be downloaded.
> [bandcamp] exclude merch links for user info extractor

- yt_dlp/downloader/external.py
---
---
As we discussed in #2696 , we need to specify our headers on each http input stream, otherwise they will only be applied to the first stream.
This fix allows us to stream to stdout from FranceTv
```bash
yt-dlp -f 'hls-2218+hls-audio-aacl-96-Audio_Français' -N 10 -o - https://www.france.tv/slash/skam-france/saison-1/1980815-seule-au-monde.html
```
Verbose log
```bash
[debug] Command-line config: ['-vU', '-f', 'hls-2218+hls-audio-aacl-96-Audio_Français', '-N', '10', '-o', '-', 'https://www.france.tv/slash/skam-france/saison-1/1980815-seule-au …
```
> [downloader/ffmpeg] Specify headers for each http input stream

- yt_dlp/extractor/niconico.py
---
niconico now requires MFA when logging in using username and password, breaking the current login method.  This patch updates the login flow and prompts user to input the code.
> Fix `NiconicoIE` login

- yt_dlp/extractor/twitcasting.py
---
---
Closes #3558
The root cause is that `_extract_m3u8_formats_and_subtitles` does not copy headers to each formats, this PR mitigates it.
> [twitcasting] Pass headers for each formats

- yt_dlp/extractor/common.py
---
---
As I explained in #2696 , we were getting 403 Forbidden when we tried using ffmpeg+bash because we were passing the wrong **base path** as input to ffmpeg.
The issue was that we were being redirected when we tried getting our **manifest.mpd**, but we didn't store this new redirected url, instead we used the original.
With this fix we're able to stream from FranceTv using Dash to stdout
**Note:** It's necessary to have a recent version of Ffmpeg ([builds](https://github.com/yt-dlp/FFmpeg-Builds/releases)) otherwise a parsing error might …
> [extractor/common] Use validated url for mpd extractor

- yt_dlp/extractor/infoq.py
---
---
Extractor will no longer fail on missing audio only format, closes #3441
Removed test case and handling of /cn/ urls since both the /cn/ test case and http://www.infoq.com/cn/presentations do not seem to exist anymore.
> [InfoQ] Don't fail on missing audio format, Remove 404 test case

- yt_dlp/extractor/common.py
---
---
Like in #3563 , let's be safe and use the validated url in all the remaining extractors that don't do this
> [extractor/common] Use validated url in various extractors

- yt_dlp/utils.py
---
This PR lets `YoutubeDLCookieJar` reject JSON files for input. 
Such files seem to contain cookies for a specific site, and as yt-dlp will overwrite JSON file with a text file, I don't think it's appropriate to convert to a valid cookie jar.
Confirmed example which dumps in the format: https://addons.mozilla.org/en-US/firefox/addon/etc2/
Sample file: https://gist.github.com/b33ae9cadae3e2a954853d7e50e8dd1d
> [utils] YoutubeDLCookieJar: Detect and reject JSON file

- yt_dlp/utils.py
---
Fixes #3557
#2994 contains an implementation error, where the special case of calling truncate() on a fd representing a FIFO results in a uncaught illegal seek because FIFO's do not support seeking.
[io.open()](https://github.com/python/cpython/blob/ad5e8520f3e117f45481513014548a39879d30d2/Modules/_io/fileio.c#L204) does not need code to handle this special case, because (on Linux) [namei.c](https://github.com/torvalds/linux/blob/b6b2648911bbc13c59def22fd7b4b7c511a4eb92/fs/namei.c#L3093) strips O_TRUNC for FIFO's.
Untested in Windows.
> [utils] ignore illegal seek on truncate()

- yt_dlp/extractor/lci.py
---
---
I fixed the regular expression that looks up the wat id in the webpage. I also changed the test as the old one failed and skipped download because of file size mismatch.
The LCI domain now redirects to tf1info.fr, I added support for the second domain since both work.
> [LCI] Fix extractor

- yt_dlp/extractor/trovo.py
---
---
This pull request updates the extractor to the new API (closes #3457) and makes it show a proper error for subscriber-only videos.
> [trovo] Update to new API, show proper error for subscriber-only videos

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/nebula.py
---
As requested by and closing #3609.
Nebula has a feed of all episodes from channels/collections the user is following, called `myshows` or `My Videos` in URLs and UI respectively.
This is the equivalent to YouTube's 'Subscriptions' page.
This change adds support for downloading this feed via the `/myshows` URL.
It also fixes extractor tests and replaces the call to `_get_login_info()` with the new `_perform_login()` system.
> [nebula] Add support for subscriptions

- yt_dlp/extractor/common.py
- yt_dlp/extractor/wat.py
---
Fixes #982
Fixes #1683
As described in the linked issues, the extractor was missing non-french streams and subtitles.
This is fixed by passing ` 'pver': '4020003'` as query parameter in the video request (I'm not sure what this value means, but TF1 always sends it).
The last commit is a small fix in `_parse_mpd_formats_and_subtitles`, because we weren't setting a `name` for mpd subtitles.
Extracting multi-language formats
```bash
yt-dlp -vU -F "https://www.tf1.fr/tf1/under-the-dome/videos/under-the-dome-s01-e01-coupes-du-monde-06184003.html"
```
```diff
[debug] Command-line config: ['-vU', '-F', 'https://www.tf1.fr/tf1/under-the-dome/videos/under-the-dome-s01-e01-coupes-du-monde-06184003.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp …
```
> [TF1/wat] Fix extraction of multi-language videos and subtitles

- yt_dlp/extractor/ina.py
---
This PR updates the extractor for https://www.ina.fr/ because the rss feed that it was using, no longer works
Fixes #2463
```bash
yt-dlp -vU "https://www.ina.fr/ina-eclaire-actu/video/cpb8205116303/les-jeux-electroniques"
```
```bash
[debug] Command-line config: ['-vU', 'https://www.ina.fr/ina-eclaire-actu/video/cpb8205116303/les-jeux-electroniques']
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Git HEAD: f5bd59f7f
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-110-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: …
```
> [ina] Update extractor

- yt_dlp/extractor/zattoo.py
---
Live streams were broken for the Zattoo extractor due to a simple typo. ("format" instead of "formats").
> [zattoo] Fix live streams

- test/test_InfoExtractor.py
- yt_dlp/extractor/common.py
---
Given the following HTML:
```
<video src="https://d1ggyt9m8pwf3g.cloudfront.net/protected/ap-northeast-1:1864af40-28d5-492b-b739-b32314b1a527/archive/clip/838db6a7-8973-4cd6-840d-8517e4093c92#t=1" controls="controls" type="video/mp4" preload="metadata" autoplay="autoplay" playsinline class="object-contain"></video>
```
`-F` gives `unknown_video` as extension even it's obviously MP4.
```
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[0000studio:clip] e46b0278-24cd-40a8-92e1-b8fc2b21f34f: Downloading webpage
[info] Available formats for e46b0278-24cd-40a8-92e1-b8fc2b21f34f:
ID EXT           RESOLUTION │ PROTO │ VCODEC  ACODEC
─────────────────────────────────────────────────────
0  unknown_video unknown    │ https │ unknown …
```
> [extractor/common] Recognize `src` attribute from HTML5 media elements

- yt_dlp/extractor/niconico.py
---
Essentially, the niconico series page went from using relative references to using absolute references so the current regex wasn't finding any video urls on the test cases.
> Fix Niconico Series extractor

- yt_dlp/extractor/common.py
- yt_dlp/extractor/npr.py
---
---
Extract JSON-LD from the NRP webpage if it's available. If the
"format" and "stream" fields in the multimedia dictionary are 
empty in the result returned by the NPR API, use the 
embedURL from the JSON-LD, if it exists, as a stream url.
Update `InfoExtractor._json_ld.traverse_json_ld` to look for a
VideoObject in "subjectOf" if the `item_type` is "NewsArticle".
Update `InfoExtractor._json_ld.extract_video_object` to extract
"embedUrl" from the VideoObject.
Addresses the issue downloading the [Bonobo Tiny Desk Concert][bonobo] (#1934) …
> [npr]: get stream url from json-ld

- yt_dlp/extractor/youtube.py
---
Was crashing when channel is None (this occurs on notifications such as premieres)
Also soft hyphens should be removed from the notification title before title extraction since the channel name may contain them (e.g. long channel name). 
This fixes the extractor from crashing, but there are still some issues:
- title for recommended notifications is not extracted. 
- channel is extracted, but title is in the form "Recommended: \<video title\>"
- no title or channel are extracted for YouTube feature(?) notifications
- but they may link to a video e.g. https://www.youtube.com/watch?v=EwY6doa-0Bg
> [youtube] Fix :ytnotifications extractor

- yt_dlp/cookies.py
All the Unix-like platforms (Linux, *BSD) use the same location for
the browser profile directories, so it makes some sense to make
that the default instead of tracking all the platform names; and
treat Windows and OSX as the exceptions they are (based on the number
of platform names, not installs). This is especially useful as the
"platform" name on at least FreeBSD changes with each major release
(e.g. freebsd12, freebsd13, ...) and would have to be updated for
every release without this change here.
At the same time, fix the error condition: the question is not whether
we are on a "supported" platform but if the browser profile directory
exists in the place where we expect it. That handles all the cases like
"browser not available", "browser not installed", "profile not
initialized …
> turn cookie store detection on it's feet

- yt_dlp/downloader/dash.py
- yt_dlp/downloader/fragment.py
- yt_dlp/extractor/youtube.py
---
---
See this PR as a demo/suggestion as the implementation is quirky. E.g. it does not work with concurrent fragment download.
When downloading a YouTube live video with `--live-from-start` and `--downloader native` I would like to see how many fragments are available, so I get a feeling, when the download is catching up with the current time. Total fragments will be updated as new fragments are available.
I don't think it is necessary to compute percentage or ETA since live videos have no determined end.
```
[download] 106.00MiB at 63.29KiB/s …
```
> [suggestion] show total frags when downloading YouTube live video with --live-from-start

- yt_dlp/extractor/zdf.py
---
By extracting the `tbr` quality from the mp4 urls (if available) and sorting formats by this value, we can do a better work identifying the best video quality
Fixes #4020 
```bash
yt-dlp -vU -F https://www.zdf.de/serien/soko-stuttgart/das-geld-anderer-leute-100.html
```
```bash
[debug] Command-line config: ['-vU', '-F', 'https://www.zdf.de/serien/soko-stuttgart/das-geld-anderer-leute-100.html']
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Git HEAD: da5a3dd54
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-113-generic-x86_64-with-glibc2.29
[debug] Checking exe version: …
```
> [zdf] Identify the best video quality

- yt_dlp/extractor/extractors.py
- yt_dlp/extractor/freetv.py
---
---
This PR adds support for freetv.com, as requested in #3486 
Currently it only handles correctly movies, since we need a direct link to make this work and series appear in a list (I've added a note about it).
**Note:** I'm not really used to using regex, so... if they can be improved, let me know 😃 
```bash
yt-dlp -vU "https://www.freetv.com/peliculas/atrapame-si-puedes"
```
```bash
[debug] Command-line config: ['-vU', 'https://www.freetv.com/peliculas/atrapame-si-puedes']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, …
```
> [freetv] Add an extractor for freetv.com

- yt_dlp/extractor/common.py
- yt_dlp/extractor/openload.py
- yt_dlp/postprocessor/ffmpeg.py
- yt_dlp/utils.py
---
Here is a minimal example for reproducing the bug `yt-dlp -v --ignore-config --xattrs "https://www.youtube.com/watch?v=UcxCt7KSTXs"`
Essentially what happens is that the video has a description that is too long for extended attributes, so setfattr executes unsuccessfully. We get  `<class 'bytes'>` instead of `str` from stderr, because the `text=True` was missing, resulting in a type error when parsing the output.
> Fix XAttrMetadataError type error

- yt_dlp/extractor/digitalconcerthall.py
---
Fixing of a critical code error, due to which the digitalconcerthall extractor did not work.
<details>
<summary>Error debug log</summary>
```bash
[debug] Command-line config: ['https://www.digitalconcerthall.com/en/concert/3439', '--playlist-items', '2', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Git HEAD: 44a6fcf
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-1017-aws-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: …
```
> [exctractor/digitalconcerthall] Fix code logic typo

- yt_dlp/extractor/lbry.py
---
Odysee livestream download currently fails with `This stream is not live`.
Odysee changed the URL and schema for querying livestream data by channel claim id.
This PR implements the needed fix.
> [lbry] update JSON API for livestream query

- yt_dlp/extractor/espn.py
---
A couple of improvements to the WatchESPN extractor from #2283.
1. Recognize ESPN+ videos that have the `BAM_DTC` source rather than `ESPN_DTC` (recently some MLS replays switched to this, and the extractor was wrongly treating these as TV provider access rather than cookies)
2. Add support for free videos, that require neither TV login nor cookies. Previously users would have to provide TV provider to download these videos.
> [WatchESPN] support for free videos and BAM_DTC

- yt_dlp/extractor/dropout.py
(I'm not sure which tests are relevant)
---
Fixes #4035 
Instead of logging in each time in the dropout extractor, check to see if a `_session` cookie exists and use it if possible. This causes a problem when the `_session` cookie refers to a logged out or unauthenticated session. However in that case the extractor tries to login again.
I also removed the logout after the video is extracted as I don't think this is needed and it speeds up the process if multiple video's are downloaded in a row.
> Use existing dropout session when found in cookies

- yt_dlp/utils.py
---
Back-porting from #2861 
Fixes (rare) bug introduced in https://github.com/ytdl-org/youtube-dl/commit/be4a824d74add1a3b78b8244dff12f4f078f168a
There is a function in `AbstractHTTPHandler` that adds a bunch of default headers to the request.
In particular, it adds `'Content-type':  'application/x-www-form-urlencoded'` header when data is present and no content-type header is added. Some extractors rely on this behaviour and sites may reject requests without (dailymotion)
The issue is this method is only called for HTTPS requests, not HTTP (hence this header not being added by default for HTTP). `YoutubeDLHandler` does not call `do_request_` (as it overrides both `http_request` and `https_request`). It is only called for `https_request` because of `YoutubeDLHTTPSHandler` which inherits …
> Fix bug when handling HTTP requests

- yt_dlp/update.py
---
See https://github.com/yt-dlp/yt-dlp/pull/4106#issuecomment-1168672707
The way I implemented it:
When I am on an early macos version it should upgrade to the legacy version. An alternative approach would be to somehow mark the binary to upgrade to legacy, but I am not sure how I would go about doing that. I doubt that anyone is using yt-dlp on Mojave that would be bothered by this upgrade, since it previously did not work on Mojave and older
> Fix Update for macos_legacy

- devscripts/make_lazy_extractors.py
Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/) I noticed that yt-dlp could not be built reproducibly.
This is due to `sort_ies` iterating over a Python `set()` data structure in a nondeterminstic order. This patch sorts the `type` objects according to their name.
I originally filed this in Debian as [bug #1014041](https://bugs.debian.org/1014041).
> Make the build reproducible

- yt_dlp/YoutubeDL.py
</details>
This is to skip some PPs if container conversion is to be done per user request.
These PPs (FixupM4a, FixupM3u8, FixupDuplicateMoov) are completely unnecessary as ffmpeg gracefully handles without doing before conversion.
They still run if the conversion doesn't change extension, e.g. `--remux mp4` when downloading a mp4 file.
> Skip some PPs if Remux or VideoConvertor is also queued

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/startrek.py
---
This adds a new extractor for single video pages on [StarTrek.com](https://www.startrek.com/).
Note that apparently non-US users will be redirected to `intl.startrek.com` instead of `www.`. Since I live in Germany, I have developed the extractor against `intl.` and also tested it against that host. I’d appreciate **US and Canadian citizens** to test whether it works for them, too, and whether the test works (because that’s using `intl.`).
Also, I don’t know what exactly the geo restrictions for StarTrek.com are, which is why I haven’t added any code about them.
Thumbnail extraction works, as do the subtitles and description.
There is apparently an internal, numerical ID for each of the videos (search for `mpx-id` in the source), but since it’s not shown anywhere, I have decided to use …
> [StarTrek] Add extractor for startrek.com videos

- README.md
- test/test_utils.py
- yt_dlp/utils.py
</details>
DESCRIPTION
Fixes #840
This allows you to create config files having different encodings. Preexisting config files continues to work with this method.
With this, you can have 3 config files with different encodings each other:
```
$ ./yt-dlp.sh --config sjis_config.conf --config euc_config.conf --config utf8_config.conf -v
[debug] Command-line config: ['--config', 'sjis_config.conf', '--config', 'euc_config.conf', '--config', 'utf8_config.conf', '-v']
[debug] | Config "sjis_config.conf": ['--exec', 'echo 日本語']
[debug] | Config "euc_config.conf": ['--exec', 'echo 日本語']
[debug] | Config "utf8_config.conf": ['--exec', 'echo 日本語']
[debug] yt-dlp …
```
> Allow users to specify encoding in each config files

- yt_dlp/extractor/wsj.py
The data-src text that was previously used to find the video id no longer exists. In its place I used the id= within the div for the video itself as well as 2 sections in the json field of the script tag: the embed url and the slug.
I tested all fallbacks on both the panda video in the tests and the  someziggyman provided. Fixes #4249
> Fix video id extractor for wsj articles

- yt_dlp/extractor/tubitv.py
Series on tubi include a self-reference in the fullContentById field in the extracted json. This doesn't prevent download but it throws an error because it tries to download a playlist as a video.
Fixes #4409
> Add check to exclude playlist id from playlist entries

- yt_dlp/extractor/crunchyroll.py
When thumbnail is missing returning json skips it instead of the NoneType error
</details>
DESCRIPTION
When Crunchyroll is missing thumbnail image processing code, here throws NoneType error and does not process the episode to the end.
Fixes #
During processing, if any issues come from a thumbnail, the result got ignored, and thumbnail data is missing from yt-dlp resulting JSON data.
> Crunchyroll missing thumbnail fix

- yt_dlp/extractor/arte.py
<details> <summary> Boilerplate (own code, improvement) </summary>
- Improvement
---
</details>
~~The v1 API code was removed for simplicity, even though it still mostly works.~~ ~~Not anymore.~~ ~~Not not anymore.~~ Not not not anymore, the v1 API is now completely down (404).
I have left a number of ‘XXX’ comments in, please take a look before merging.
The testcases for this extractor are stale. I have not updated them, other than throwing away `upload_date`, which the updated code no longer extracts.
Fixes or subsumes:
- #3086 
- #3428
- #3502
- ytdl-org/youtube-dl#29640
- ytdl-org/youtube-dl#29653
- ytdl-org/youtube-dl#29870
- ytdl-org/youtube-dl#30816
- …
> [arte] Move to v2 API

- README.md
- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
</details>
As I suggested in issue #1564, I have added `is_post_live_dvr` to the variables returned by Youtube downloads. Now, an expression like `--match-filter '!is_post_live_dvr'` should skip any videos that have not been fully processed by Youtube yet, and thus are potentially problematic. It is not a fix but I thought it might help as a workaround, in particular with archival scripts.
The value of the variable should be `is_post_live_dvr` if the video has not been fully processed (and thus could potentially encounter the issue if it is also >4h long), and `None` once it is.
EDIT: I forgot to mention that the variable name is a bit of a mouthful, and quite obscure. I only switched the original name within the extractor from camelCase to …
> [extractor/youtube] Added is_post_live_dvr to returned info

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/holodex.py
All videos on holodex are youtube embeds so for individual videos we just call out to the YoutubeIE for all the heavy lifting. Playlists are only found in the url as playlist=playlist_id after a video and it's ambiguous whether someone wants to download the playlist or just the video. This extractor assumes the entire playlist because there's no other user-facing way to specify that.
Fixes #726
> Add support for holodex

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/angel.py
</details>
This PR adds an extractor for the angel (https://www.angel.com/). All of the information required for the episodes were in an `application/ld+json` tag in the webpage.
One thing to note is that there were several transformations on the thumbnail url in the JSON-LD in the that I have removed. I thought it would be best to remove all transformations and just return the original thumbnail. These transformations can result in returning smaller thumbnails for example:
1. https://images.angelstudios.com/image/upload/f_auto,c_limit,w_3840,q_auto/c_fill,q_auto,ar_16:9,g_north/v1643403801/angel-app/tuttle-twins/videos/season_1/Episode_1_App_Thumbnail.jpeg
2. https://images.angelstudios.com/image/upload/b_rgb:000000,c_fill,h_630,w_1200,g_north/v16 …
> [angel] Add extractor

- test/test_utils.py
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/rai.py
- yt_dlp/utils.py
- added support for raisudtirol.rai.it website to improve the generic exctraction
- added '%d-%m-%Y %H:%M' pattern to DATE_FORMATS_DAY_FIRST list
- added relative test for newly added pattern
Fixes #4206
> [rai] added raisudtirol support (fix #4206)

- README.md
- yt_dlp/extractor/crunchyroll.py
Fixes #4452
Somewhat alters the usable values of the `format` extractor arg, but the values I expect might actually be in use (`adaptive_hls` and `adaptive_dash`) don't seem to change behavior.
It's possible that while we're making yt-dlp follow the browser's behavior more exactly, we should also switch the default `format` to `adaptive_dash`? That is apparently what the browser actually uses, currently at least, but I'm not sure it's worth changing. Unfortunately, I don't recall what the thought behind using `adaptive_hls` was at the time.
> [crunchyroll:beta] follow browser api accesses more exactly

- yt_dlp/extractor/youtube.py
</details>
YouTube is currently A/B testing a change where, at least for the android Innertube client, it detects third party use and replaces the player response _for any video_ with one for https://www.youtube.com/watch?v=aQvGIIdgFDM.
Unfortunately updating the client versions (as done in https://github.com/yt-dlp/yt-dlp/commit/a0c830f488170db9007979da0ba13ebf9ebad5b1) supposedly doesn't help.
See: https://github.com/TeamNewPipe/NewPipe/issues/8713, https://github.com/iv-org/invidious/issues/3230, https://github.com/Tyrrrz/YoutubeExplode/issues/647
In this case, depending on the format sorting and requested video's formats, the bad video's formats may be downloaded as if they were the requested video's. **In other words, we'll end up downloading `aQvGIIdgFDM ` but under the metadata …
> [extractor/youtube] Guard against YouTube returning a player response of a different video

- yt_dlp/extractor/rai.py
- [rai] check DRM directly in the manifest because sometimes is not present in the page
- [rainews] using _EMBED_REGEX and _VALID_URL fix
- [rainews] added TEST url for iframe and DRM in manifest but not in page
- [raisudtirol] using different url for TEST because the old one was a changing weekly
- [raisudtirol] using 'formats' instead of direct 'url' to provide media info to the user
- [general] re-checked all TESTS in various classes and fixed ploblems
> [extractor/rai] various fixes and improvements

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/mlb.py
</details>
Adds a new extractor for MLB.tv videos. MLB.tv contains full video and audio replays of every Major League Baseball game. Videos are probably not actually geolocked, but will require a subscription which unfortunately I am unwilling to share.
This pull request is fully "functional," in that it can extract the m3u8 URLs and appropriate headers for each game. However, there are a number of concerns that need to be addressed before merge.
1. Due to the nature of the streams, and limitations with ffmpeg, the issue raised in #4211 means that videos may not download properly. The stream of the actual game is separate from that for the commercials, even though both alternate in the variant m3u8 file. When cleaning up, ffmpeg will only return the stream that starts the playlist. Most …
> [MLB.tv] New Extractor

- yt_dlp/extractor/redbee.py
</details>
In #4479 I changed the `title` extractor from `title` to `subtitle` because, for videos at least, the `subtitle` is more descriptive. https://github.com/yt-dlp/yt-dlp/pull/4479#issuecomment-1200308965
But unfortunately, livestreams don't contain a `subtitle` so we fail extracting it. This is fixed by adding a fallback to `title` in case `subtitle` doesn't exist.
**Livestreams using RedBee**
Also all streams have started using RedBee, but the previous api still returns m3u8 and mpd manifests that contain a 20s video that is completely unrelated, so we need to ignore them since they're 'fake'. https://github.com/yt-dlp/yt-dlp/issues/4656#issuecomment-1214461092
**RedBee DRM formats**
And last but not least, some RedBee …
> [extractor/rtbf] Update stream extractor

- yt_dlp/extractor/medaltv.py
</details>
It would appear as though medal.tv reworked a lot of their front-end code, breaking the current extraction logic for the site. Although a lot of the functionality is the same, we unfortunately have to make an additional request to their /_next API to get the relevant clip data.
I'm not exactly sure when they made these breaking changes, but I was notified of it today (since I was the one who originally added support for the site).
They also changed the URL format:
Old: https://medal.tv/clips/xitf8v3RqmUcd/DlgzpPE0KSmv
New: https://medal.tv/games/fortnite/clips/xitf8v3RqmUcd/DlgzpPE0KSmv
Fortunately, the old links redirect to the new links, so there is backwards compatibility with the current extractor.
> [extractor/medaltv] Fix extraction and account for new url format

- yt_dlp/extractor/screencastomatic.py
</details>
Adds support for password-protected videos to the ScreencastOMatic extractor.
> [screencastomatic] Add support for protected videos

- yt_dlp/extractor/youtube.py
</details>
Thwart latest third-party client detection by using mobile user agent for ANDROID client. See: https://github.com/iv-org/invidious/issues/3230#issuecomment-1226887639
This currently doesn't affect us (again) due to the "story" player parameters being used. 
I have also made it so these story parameters are only used if we are sure we are grabbing stories (via stories extractor) or for ANDROID client player requests (for the guard). This is just in case these cause unwanted effects later, so we will still have the WEB client without them by default.
Not the nicest looking solution but should get the job done for now. I'm planning on rewriting our Innertube handling sometime.
<details …
> [extractor/youtube] Use mobile user-agent for mobile client requests

- yt_dlp/extractor/youtube.py
* Update the client version of the various iOS apps
* Add the iOS Music/Studio's user-agent strings (following the same pattern as the other app's UA. Note: I haven't tried to MitM an actual app to check if the UA corresponds).
> [youtube] Bump iOS clients versions & Add Creator/Music apps UA

- yt_dlp/extractor/crunchyroll.py
Eliminates the beta -> non-beta redirect code, due to changes in the api making it impossible. Instead, uses anonymous access to the beta api, which already works, and its momentarily used by the browser before redirect.
Closes #4692
Ran all beta tests, both with and without an `etp_rt` cookie.
> [crunchyroll:beta] Use anonymous access instead of redirecting

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/__init__.py
- yt_dlp/cookies.py
- yt_dlp/options.py
</details>
This adds support for Firefox containers to the `--cookies-from-browser` option.
Containers are a relatively new [built-in Firefox feature](https://support.mozilla.org/en-US/kb/containers#w_for-advanced-users) that allow for cookie isolation. A user may have multiple containers that are logged in to the same site with different accounts. As such, using the `--cookies-from-browser firefox` option as it currently stands can cause issues with overlapping/conflicting auth cookies for users of Firefox containers, since the current behavior loads all cookies from FF's cookie database. This PR is intended to solve that problem.
The proposed new argument syntax is:
`--cookies-from-browser BROWSER[+KEYRING][:PROFILE[:CONTAINER]]`
The name of the Firefox container can be passed as …
> Add optional firefox container selection to --cookies-from-browser

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/eurosport.py
</details>
This PR add site support for www.eurosport.com. At the moment, this PR didn't include geo-block detection and not tested geo-blocked link. Any help to test geo-blocked video is appreciated.
Fixes #2487 
KNOWN ISSUE:
- ~Some link (eg: https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml) raise PostProcessorError, but it works when we input the url manually to ffmpeg~ fixed by setting `m3u8` at `protocol`
- ~Eurosport actually support video file in mss type. I didn't know how to extract this type, so this is unsupported at the moment~ already supported
TO DO:
- ~Set better error on …
> [extractor/eurosport] Add extractor

- README.md
- yt_dlp/__init__.py
- yt_dlp/cookies.py
- yt_dlp/options.py
</details>
Reverts default behavior of `--cookies-from-browser` and firefox containers to what it was before 9bd13fe
- `--cookies-from-browser firefox` will load all cookies from all containers and those not belonging to any container
- `--cookies-from-browser firefox:PROFILE:CONTAINER` will load cookies only from the container name specified as `CONTAINER`
- `--cookies-from-browser firefox:PROFILE:none` will only load cookies not belonging to any container
`PROFILE` may also now be left empty when specifying a container, e.g:
- `--cookies-from-browser firefox::none` will load cookies not belonging to any container from the most recently used profile
- `--cookies-from-browser firefox::` behaves the same as `--cookies-from-browser firefox`
Fixes #4800 
<details …
> Revert default behavior of --cookies-from-browser and firefox

- yt_dlp/extractor/openload.py
</details>
I was taking a look at #4292, but I was getting a different error related to phantomjs:
```bash
[debug] Command-line config: ['https://www.iq.com/play/hikaru-no-go-episode-1-slxk4ry5to?lang=en_us', '-F', '--verbose']
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (source)
[debug] Git HEAD: 1a7c9fad9
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-125-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.1.1-20220901 (setts), …
```
> [phantomjs] Fix error in get function

- test/test_utils.py
- yt_dlp/utils.py
</details>
The DiscoveryPlus extractor was failing because most of the stream urls contain a signature and expiration inside the url, e. g.
```bash
https://dplus-northamerica.media-edge.prod-vod.h264.io/bc116fee-6065-46e7-908d-debae79aaf99/dash_clear_fmp4/edge-cache-token=Expires=1662321057&KeyName=media-edge-key-prod-northamerica-200d417&Signature=jmhv-P8gPV6XVlhC5Xp1KOh-2YGTnDJWnjdKuzVYAONdRawTPr-2S6PSqdpbndDuoJPeoCxifKgZl666WRfGBA/master.mpd
```
The problem is that without this fix, we ignore these values when getting our base_url
```diff
- https://dplus-northamerica.media-edge.prod-vod.h264.io/bc116fee-6065-46e7-908d-debae79aaf99/dash_clear_fmp4/
+ https://dplus-northamerica.media-edge.prod-vod.h264.io/bc116fee-6065-46e7-908d-debae …
```
> [utils] Do not ignore base_url path components that contain ampersand

- devscripts/make_lazy_extractors.py
Fixing `OSError: [Errno 18] Invalid cross-device link` when a Docker image is created during the compilation process of the `yt-dlp` binary. In particular, this error raises when the `python3 devscripts/make_lazy_extractors.py` step is executed.
I am interested to create a Docker image having the `yt-dlp` command. My (preliminary) `Dockerfile` looks as follows:
```
FROM ubuntu
ARG CONTAINER_USER="yt-dlp"
ARG WORKDIR="/workdir"
ENV CONTAINER_USER=${CONTAINER_USER}
ENV WORKDIR=${WORKDIR}
RUN useradd ${CONTAINER_USER}
RUN apt update && apt install -y python3 python3-pip git ffmpeg
WORKDIR ${WORKDIR}
RUN git clone https://github.com/yt-dlp/yt-dlp.git
WORKDIR ${WORKDIR}/yt-dlp
RUN python3 -m pip install -U pyinstaller -r requirements.txt …
```
> Fixing [Errno 18] Invalid cross-device-link appearing on 'python3 devscripts/make_lazy_extractors.py' execution

- yt_dlp/extractor/rutv.py
</details>
This fixes the following warnings:
```
$ ./yt-dlp.sh -s https://player.vgtrk.com/iframe/live/id/19201 
[RUTV] 19201: Downloading JSON
[RUTV] 19201: Downloading m3u8 information
WARNING: [RUTV] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: "view_count" field is not numeric - forcing int conversion, there is an error in extractor
[info] 19201: Downloading 1 format(s): rtmp-1600
```
And format sorting bug caused by absence of `('source', )`
`--list-subs` shows:
```
$ ./yt-dlp.sh -s …
```
> [extractor/RUTV] Fix warnings for livestreams

- yt_dlp/extractor/heise.py
- yt_dlp/extractor/youtube.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/1520
For YouTube embed extraction, the site wraps the embed in what I assume is a custom "a-iframe" (alias of iframe?)
```
<figure class="video video--fullwidth a-u-inline">
<div class="video__yt-container">
<a-iframe allowfullscreen class="video__iframe" frameborder="0" name="Youtube" needs-consent src="//www.youtube-nocookie.com/embed/6kmWbXleKW4" title="YouTube video player"></a-iframe>
</div>
</figure>
```
For one of the existing tests, the Kaltura extraction fails for the video (noted with a comment). I think this is an issue with the Kaltura extractor rather than Heise in this case. 
> [extractor/heise] Fix extractor

- yt_dlp/extractor/arte.py
Remove duplicate streams if it is a subtitle only stream (`cc` or `OGsub`).
Fixes #4510
> [extractor/artetv] Remove duplicate stream urls

- yt_dlp/extractor/dplay.py
</details>
Add the cookie/auth part in class DiscoveryPlusItaly, so that all request will be authenticated (from cookie or with a anonymous token)
Fixes #2950 and #2138
Follow up of #4905
I've checked this PR with and without cookies.
> [extractor/dplay:Italy] Add default authentication for free videos

- yt_dlp/extractor/audioboom.py
Fix JSON extraction and `uploader_url`  extraction.
When given a direct mp3 URL this extractor currently downloads the mp3 file as a webpage to be scraped and fails.
Sanitize the URL before downloading to be of type `https://audioboom.com/posts/<video_id>` to get the correct page.
I get random ads inserted into the beginning of the downloaded mp3 file, so the md5 tests fail.
> [extractor/audioboom] Sanitize webpage URL before downloading

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/tencent.py
</details>
This PR adds a new extractor for iflix.com which is like variant of WeTv. 
Iflix extractor needs its own api_url, platform, host and referer, but the extraction code is identical from WeTv. To avoid code duplication I moved the extraction code from WeTvEpisode and WeTvSeries to WeTvBase, and re-use it for Iflix.
Fixes #4823
```bash
[debug] Command-line config: ['https://www.iflix.com/en/play/daijrxu03yypu0s/a0040kvgaza', '-v', '-F']
5[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (source)
[debug] Git HEAD: a8ba287e2
[debug] Python 3.8.10 …
```
> [extractor/tencent] Add Iflix extractor

- yt_dlp/extractor/malltv.py
</details>
This PR fix the video_id in mall tv. The site seems change their layout a bit so the current extractor can't get the video_id. This PR use `player-id-name`  value as video_id to prevent archive broke because the value is identical to old video id. The 'real' video_id is located in `video['VideoId']`
Fixes #4870 
> [extractor/malltv] Fix video_id extraction

- .gitignore
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/microsoftembed.py
</details>
An Extractor for Microsoft.com embedded videos. 
This feature proposal was created in support of the yt-dlp project during Hacktoberfest. It allows a user to scrape videos, metadata, thumbnails and subtitles. More information about this extractor can be found in issue #2638.
All lint errors have been resolved using `flake8` and a test has succeeded using CPython 3.10. The test used the `__main__.py` file as the entrypoint of a command line invocation.
This is a typical printout from a linux desktop's test:
sushimint@sushimint:~/Desktop/Workshop/yt-dlp-fork$ cd yt_dlp
sushimint@sushimint:~/Desktop/Workshop/yt-dlp-fork/yt_dlp$ python3 __main__.py https://www.microsoft.com/en-us/videoplayer/embed/RWL07e -v --write-subs
[debug] Command-line config: …
> Extractor for Microsoft embedded videos

- yt_dlp/extractor/redgifs.py
</details>
I figured out the backend OAuth token that is used by their website. Further testing identified this as to be a long-lived and static token. Other issues I encountered were specific to my setup, and this fix should be all that is needed.
In addition, the tests were not quite working because slightly different metadata is returned now. Fixed those while I was in there.
Fixes #4805 
> [redgifs] Fix extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/tv24ua.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/4287
Adds support for 24tv's custom video embed.
I also added support for extracting embeds from articles. Sometimes the iframe embeds are url encoded and stored within an html attribute, but would otherwise be able to be extracted via generic. To make this work I extract the url encoded HTML iframe, decode it, then return it back to generic via a data url. It is a bit hacky but I'm not sure what other way would be best to do this.
> [extractor/24tv.ua] Add extractors

- yt_dlp/extractor/livestreamfails.py
</details>
Support  alternatives URLs that contain /post instead of /clip (e.g. https://livestreamfails.com/post/139200 instead of https://livestreamfails.com/clip/139200).
> [livestreamfails] Support alternative URLs

- yt_dlp/extractor/tnaflix.py
</details>
Fix Tnaflix 500 error code for video download
this MR
```
yt-dlp is up to date (2022.10.04)
[debug] [TNAFlix] Extracting URL: https://www.tnaflix.com/hd-videos/Pantat-Bulat-dan-Montok-Dedek-Hijab-bikin-Tegang/video4651785
[TNAFlix] Pantat-Bulat-dan-Montok-Dedek-Hijab-bikin-Tegang: Downloading webpage
[TNAFlix] Pantat-Bulat-dan-Montok-Dedek-Hijab-bikin-Tegang: Downloading metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 4651785: Downloading 1 format(s): 720p
[download] Pantat Bulat dan Montok Dedek Hijab bikin …
```
> Tnaflix 500 err

- yt_dlp/postprocessor/embedthumbnail.py
</details>
Removed quotation marks around the 'comment' tag which was causing it to not be set properly. If the thumbnail metadata is not properly set then in some cases it could cause issues with audio software (e.g. Spotify tends to bug around if not everything is set in a certain way). 
`ffprobe -show_streams` output:
Before
After
> Fix MP3 EmbedThumbnail Metadata

- yt_dlp/extractor/reddit.py
</details>
Some Reddit videos (hosted on v.redd.it) have a higher quality video format that was not being extracted. 
`fallback_url` was already a field in the `reddit_video` JSON object: the extractor was previously using the value to find the video ID, but was not extracting the URL as a format. For some videos the `fallback_url` format's resolution can be up to 1080p, which is better than any formats found in the DASH MPD. I assume this is only the case with videos where the original source was 1080 or better.
Note: even though it is a direct http URL, the `fallback_url` is a video-only mp4 format, and Reddit seems to treat it like a DASH variant: the URL basename is usually `DASH_1080.mp4` or `DASH_{bitrate}.mp4`
Fixes #5160 
> [extractor/reddit] Add fallback format

- test/test_utils.py
- yt_dlp/utils.py
</details>
It is common to see a pattern like `traverse_obj(obj, ...) or []` since the default is currently `None`.
This can cause developers to fall into the trap of doing `for item in traverse_obj(obj, ...)`.
This PR addresses this issue by defaulting to `[]` if the last path did not match and no default was provided.
Closes #5162
> [utils] `traverse_obj`: return `[]` if last path branches without default

- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
@coletdjnz Check that this works well enough your requirement. Will merge after you have confirmed
* I have tried to make minimal changes. But there is still changes to some of the extraction. But these only ever add more metadata, so it should be fine. Besides, there are changes that would eventually be needed for #4517 anyway
* It's not viable to make `_extract_embeds` a `classmethod`. But we still need to access it from other extractors. One option would be to move it into `common.py`, but then any related functions will also have to be moved there. Instead, Ive opted to create the `_extract_generic_embeds` wrapper. After #4517, if this function ends up being simple enough, we could still move it into common, replacing the current wrapper
* ~~I added a check to prevent accidental …
> [extractor/generic] Separate embed extractor into own function

- yt_dlp/YoutubeDL.py
</details>
Fixes 'section_end' param to YoutubeDL.py being ignored.
This fixes YouTube clip extraction. Currently for clips, we download the beginning of the clip to the end of the entire video. The YoutubeClipIE extractor gets the correct start and end times as seen here: https://github.com/yt-dlp/yt-dlp/commit/471d0367c76e1413bb35e0be45765a277e469ee2
However, the `section_end` param that is passed to YoutubeDL.py is discarded here: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L2723
```py
offset, duration = info_dict.get('section_start') or 0, info_dict.get('duration') or float('inf')
end_time = offset + min(chapter.get('end_time', duration), duration)
if chapter or offset:
new_info.update({
'section_start': …
```
> Fix YouTube clip end_time not being set.

- yt_dlp/extractor/paramountplus.py
Fixes broken API requests by updating the token.
Closes #5273 
```shellsession
$ yt_dlp -v -F https://www.paramountplus.com/shows/video/kGirBXHpqTs8cDR1lLP2JPUTsw414PIv/
[debug] Command-line config: ['-v', '-F', 'https://www.paramountplus.com/shows/video/kGirBXHpqTs8cDR1lLP2JPUTsw414PIv/']
[debug] yt-dlp version 2022.10.04 [4e0511f27]
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: …
```
> [extractor/paramountplus] Update API token

- yt_dlp/extractor/americastestkitchen.py
`cookscountry.com` and `cooksillustrated.com` now redirect to `americastestkitchen.com/cookscountry` and `americastestkitchen.com/cooksillustrated`, respectively.
This PR fixes the `_VALID_URL` for both extractors and adjusts the `AmericasTestKitchenSeasonIE` logic to account for the new URL format.
Fixes #5337 
> [extractor/americastestkitchen] Fix `_VALID_URL` and season extraction

- yt_dlp/extractor/youtube.py
</details>
Fixes #5378
Upcoming premieres on YouTube have the `lengthSeconds` field in `video_details` set to the string '0', making the call to `int_or_none` short-circuit and return `None`.
This PR switches around the order to look up the value in `microformats` first, which does return the video duration.
Output of command in listed issue (`-U` omitted):
```
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=AtwcZeFLvpI', '-s', '--ignore-no-f', '--print', '%(duration)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source) …
```
> [extractor/youtube] Fix `duration` extraction for upcoming premieres

- yt_dlp/extractor/kaltura.py
</details>
Adds support for downloading Kaltura playlists URLs. Existing Kaltura fetching code would only work for URLs with a specific video ID, and not a playlist ID which is specified with `flashvars[playlistAPI.kpl0Id]`. The existing Kaltura downloading code would give "Invalid URL".
Split the generic processing code into a function which can then be called in a loop when fetching all videos in the playlist. Also checks whether the URL uses the `html5lib/v2` player, which requires a slightly different invocation when calling `_kaltura_api_call` in order to start the widget session. And in this processing code, sets the widgetId properly when the partnerId contains an underscore, since when specified via `params['wid']` the first character was being stripped assuming it was an …
> [kaltura] Add support for playlists to Kaltura downloader

- yt_dlp/extractor/youtube.py
</details>
Fixes https://github.com/yt-dlp/yt-dlp/issues/5373
Adds support for the new playlist layout that is rolling out:
This new layout has ditched the playlist sidebar renderer for the playlist header renderer. The playlist header renderer does already exist in the old version (I started noticing it some time ago when rewriting the playlist availability detection). 
I have removed extraction from the sidebar where the same data exists in the header renderer in the old layout, however have keep it in where it isn't. When this layout fully rolls out we can remove the remaining bits of code.
> [extractor/youtube] Update playlist metadata extraction for new layout

- yt_dlp/extractor/epoch.py
- yt_dlp/utils.py
Updates the Epoch Times video id regular expression to tolerate empty `data-trailer` attributes.
Fixes #5359
> [extractor/epoch] Support videos without data-trailer

- yt_dlp/extractor/redgifs.py
</details>
RedGifs provides a temporary auth token which eventually expires. It gets stuck in the saved headers, so a mechanism to refresh the token is needed.
Fixes #5351
> [RedGifs] Refresh auth token when API returns HTTP 401

- yt_dlp/extractor/generic.py
- yt_dlp/extractor/rumble.py
</details>
Rumble provides additional m3u8 formats. This PR supports them and sets the appropriate live status.
The JSON provides a 'live' code which reads as follows:
* 0 - not live
* 1 - was live / dvr
* 2 - currently live
Upcoming videos have live status code 1 but the HLS formats are not downloadable (HTTP 404)
The other mp4 files provide a preview/announcement of about 6 seconds.
Fixes #5277 
Fixes #5177
> [rumble] add HLS formats

- yt_dlp/extractor/youtube.py
* Fixes https://github.com/yt-dlp/yt-dlp/issues/5486
* Tries to make similar issues less likely in future
* Add metadata for the wrapping playlist
* Improves [`--flat-playlist --get-id`](https://github.com/yt-dlp/yt-dlp/pull/5439#issuecomment-1309054679) using [method 3](https://github.com/yt-dlp/yt-dlp/pull/5439#issuecomment-1309322019) (still not sure whether this is the best approach)
@coletdjnz Pls review, especially https://github.com/yt-dlp/yt-dlp/commit/905956cb63356f3d7316d20c5a5ec1e204b72c44 - is there some other metadata that should not be copied into parent?
> [youtube] Fixes for redesign Part 2

- yt_dlp/YoutubeDL.py
(this code was co-authored by @Grub4K and @pukkandan)
The purpose of this patch is so that `_downloader.params.get('simulate')` will return a truthy value if any of the `list_only` options have been passed:
- `--list-formats` / `-F` / `listformats`
- `--list-subs` / `listsubtitles`
- `--list-thumbnails` / `list_thumbnails`
Per the documentation, any of these options should imply `--simulate` unless the `--no-simulate` option is also passed.
Here is one specific issue that this will fix:
Listing formats for a URL that returns a `multi_video` playlist causes yt-dlp to raise an error, because it still tries to run postprocessing (ffmpeg concatenation) after the playlist extraction finishes, even though no downloading occurred.
If we look at the postprocessor code for `FFmpegConcatPP`, we can …
> Fix bug with `simulate` param and `list_only` options

- yt_dlp/extractor/tencent.py
</details>
For some China-only videos, the api returns a direct m3u8 link that the extractor didn't handle before and therefore failed.
The warnings seem to be network/proxy related, but the OP confirmed that it works without errors on its side
```bash
[debug] Command-line config: ['https://v.qq.com/x/cover/mcv8hkc8zk8lnov/x0036x5qqsr.html', '--verbose', '--proxy', 'private-proxy', '-F']
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source)
[debug] Git HEAD: 62fd10172
[debug] Python 3.10.7 (CPython 64bit) - …
```
> [extractor/tencent] Fix geo-restricted video extraction

- yt_dlp/extractor/generic.py
Fixes regression in 0f60ba6e656516ec24d619d20d61249be6296105 which caused generic JSON LD manifests to be directly downloaded instead of extracted
Closes #5572 
> [extractor/generic] Fix JSON LD manifest extraction

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/screencastify.py
Adds support for screencastify.com
Closes #5603
> [extractor/screencastify] Add extractor

- yt_dlp/extractor/naver.py
Per a report in the yt-dlp discord server, now.naver.com URLs have changed and the `id` capture group is now alphanumeric instead of only numeric. This PR updates the `_VALID_URL` accordingly and adds a test. The issue reporter provided multiple examples of this new URL format and I confirmed that they are downloadable with this patch.
> [extractor/naver] Improve `_VALID_URL` for `NaverNowIE`

- yt_dlp/extractor/youporn.py
---
Closes #2701. Youporn sends a JS challenge with TLS1.3-
> [youporn] Fix extraction of metadata

- yt_dlp/extractor/swearnet.py
Bug in 049565df2e24d9611a9ffdd033c80a6dafdabbe0
Closes #5643
> [extractor/swearnet] Fix description bug

- yt_dlp/extractor/plutotv.py
This pull request fixes several cases when the Pluto TV extractor would appear to download the content successfully. However, the resulting file would be very small and upon play would be
just the station ident / logo bumper. This did not occur in all cases so it was initially unclear why this occurred for certain videos.
Examples which exhibited this issue include:
https://pluto.tv/en/on-demand/movies/attack-of-the-killer-tomatoes-1977-1-1-ptv1
https://pluto.tv/en/on-demand/movies/pandorum-2009-1-1
This occurred when the content does not match the first regular expression case and when matching the second case, it starts from a URL which does NOT end with 000000.ts.
The second regexp then errorneously matches the bumper URL instead.
This change fixes this to work with both 000000.ts and …
> [extractor/plutotv] Fix extraction for videos with non-zero ts start

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/rumble.py
Currently rumble URLs are supported via embedded links found by Generic extractor.
The native webpages on rumble.com contain some additional metadata which can be extracted (description, view_count, like_count, release_timestamp)
There were other attempts (#3031) but they required an additional web request, which is time consuming.
This PR adds a dedicated extractor for rumble.com URLs which uses the info from RumbleEmbedIE and updates it with the metadata from the webpage, hence using the same number of web requests as before.
Via `_EMBED_REGEX` it automatically supports some special playlist pages like:
* https://rumble.com/videos
* https://rumble.com/live-videos
* https://rumble.com/editor-picks
* https://rumble.com/license-videos
Fixes #2846
> [rumble] add dedicated RumbleIE extractor class

- yt_dlp/YoutubeDL.py
- yt_dlp/downloader/external.py
- yt_dlp/extractor/generic.py
This PR aims to fix HTTP headers not being passed to ffmpeg for formats that need to be merged.
For example, if you try to use ffmpeg to download an HLS stream that has separate media playlists for video and for audio, yt-dlp (latest release+master) will not pass any http headers to ffmpeg (see last line of log):
```shellsession
$ yt-dlp --downloader ffmpeg -v 'https://d1akq03u1jevln.cloudfront.net/wp-gmg/20221127/6383f78294dbac7cdab246cb/t_66e94b28caed4cafb71caa599f58eb5a_name_video/hlsv4_master.m3u8'
[debug] Command-line config: ['--downloader', 'ffmpeg', '-v', 'https://d1akq03u1jevln.cloudfront.net/wp-gmg/20221127/6383f78294dbac7cdab246cb/t_66e94b28caed4cafb71caa599f58eb5a_name_video/hlsv4_master.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, …
```
> Fix headers for ffmpeg and video+audio formats

- yt_dlp/extractor/foxsports.py
- yt_dlp/extractor/uplynk.py
The FoxSports website has been revamped since the last time this extractor was touched, and has a new URL format and a new API. The VOD content now only uses ThePlatform as a redirection service, and the VOD now seems to be entirely Uplynk Preplay HLS. (ThePlatform is not able to find any content for the old extractor test case, and I can't get it to play in my browser, either.)
This PR only focuses on fixing VOD extraction. The site also has provider-locked livestreams (via AdobePass); these are not currently supported.
The Uplynk manifest URLs yielded from the FoxSports extractor will return a 403 error unless the request has a foxsports.com `Origin` header. This necessitated header smuggling into the Uplynk and UplynkPreplay extractors. `UplynkPreplayIE` was improperly subclassed from …
> [extractor/foxsports] Fix extractor

- yt_dlp/extractor/bilibili.py
- yt_dlp/utils.py
</details>
Looks like BiliBili is offering HEVC-over-FLV formats, which isn't in standards and even not supported by ffmpeg. ([How do browsers play? There's a library to demux for them](https://github.com/xqq/mpegts.js/blob/6bf10e8a5be96543aaf3fb4bb7dcfcf8e7a21f02/src/demux/flv-demuxer.js#L843))
Although they could have been skipped, I think they should be available for download for anyone interested in.
ref. https://trac.ffmpeg.org/ticket/6389
ref. #5821
... wait, should we implement some scheme to deprioritize such formats (i.e. impossible or out-of-spec combination of container/codecs) globally? @pukkandan 
#5821
> Deprioritize HEVC-over-FLV formats

- yt_dlp/extractor/curiositystream.py
</details>
Probably a week or two ago yt-dlp stopped downloading full videos, only downloaded "trial" ones (first 2 minutes). This happened also when I tried fresh master (commit 935bac1e).
`flake8` passes, but I am not sure how to run specific tests. When running all tests it seemed there is a lot of missing videos from other extractors.
I have tested it on `https://curiositystream.com/video/5893`. Before the downloaded file was cut at 2 minutes (42MB), after this fix it has full duration of 11 minutes (229MB). Used command:
```
python -m yt_dlp --no-playlist --no-check-certificate --force-ipv4 --no-call-home -f 'bv+ba[language=en]' -v --cookies-from-browser vivaldi https://curiositystream.com/video/5893
```
> [couriositystream] Fix passing auth.

- yt_dlp/extractor/spankbang.py
</details>
This PR updates the `spankbang` extractor to be able to retrieve the playlist title which is now nested in an `<em>` tag. Additionally, the regex for finding playlist items was updated in order to resolve the issue with some playlists as described in #5731.
Fixes #5731 
> [spankbang] fix missing playlist title and #5731

- test/test_utils.py
- yt_dlp/utils.py
</details>
This partially reverts https://github.com/yt-dlp/yt-dlp/commit/f55523cfdd18dcd578f5d96cbb06266663169d35 which JSON encoded all `js_to_json` vars. This broke \_\_NUXT_JSONP\_\_ parsing because JS numbers turned into strings (`123` to `"123"`) and JS strings turned into quoted strings (`"abc"` to `"\"abc\""`).
> [extractor/sovietscloset] Fix __NUXT_JSONP__ extraction

- yt_dlp/extractor/odnoklassniki.py
> [extractor/odnoklassniki] Extract subtitles

- yt_dlp/extractor/fifa.py
Credit to @dirkf for the patch
Fixes #5839
> [extractor/fifa] Fix Preplay extraction

- yt_dlp/extractor/iqiyi.py
Fixes the regex that's used to extract the site's JS player code
Closes #5702
> [extractor/iqiyi] Fix `Iq` JS regex

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/__init__.py
- yt_dlp/options.py
</details>
Backported from #2861 
Closes https://github.com/yt-dlp/yt-dlp/issues/3675
> Add `--enable-file-urls`

- yt_dlp/extractor/bilibili.py
This PR fix error that caused because the `video_data` failed to extract, this error seems only applied to user-generated content. Here's the relevant code line:
https://github.com/yt-dlp/yt-dlp/blob/933ed882e94ebfacc5e407dbd74fa25e672092c4/yt_dlp/extractor/bilibili.py#L991-L992
If the `video_data` failed and not a get season id, the code will execute this line
https://github.com/yt-dlp/yt-dlp/blob/933ed882e94ebfacc5e407dbd74fa25e672092c4/yt_dlp/extractor/bilibili.py#L1001
in this state, `video_data` get value as `None` and then getting error on `_parse_video_metadata`:
https://github.com/yt-dlp/yt-dlp/blob/933ed882e94ebfacc5e407dbd74fa25e672092c4/yt_dlp/extractor/bilibili.py#L886-L892
Before this PR:
```shell …
```
> [extractor/biliIntl] Temporary workaround for failed `video_data` extraction

- yt_dlp/extractor/common.py
- yt_dlp/extractor/slideslive.py
* I had previously written the extractor so that core code would take care of setting chapter end times, but the video's duration was not being extracted, so the final chapter's end time was being set as `None`. [This causes problems with postprocessing.](https://github.com/yt-dlp/yt-dlp/issues/5818#issuecomment-1380926974) With this PR, the extractor tries to extract duration from the m3u8 media playlist and falls back to extracting from the MPD manifest. (This was not an issue with the youtube embeds.)
* ~~SlidesLive serves several different "versions" of slides, and I had previously assumed that "v3" slides were available as both .jpg and .png based off of the only v3 example URL I was able to find, so I had written the extractor to use .jpg URLs for the thumbnails. [This assumption …
> [extractor/slideslive] Fix thumbnails and chapters/duration

- test/test_utils.py
- yt_dlp/utils.py
Add transformation functions and type filters (through wrapping them into a `set`) and named groups for `re.Match` in filter functions to `traverse_obj`. It also adds a sanity check for filter functions in debug mode to require 2 parameters.
```py
traverse_obj(obj, ("some", "path", {int_or_none}))  # Convert to int
traverse_obj(obj, ("some", "path", {int}))  # Filter non int values
traverse_obj(re.findall("...", "..."), (..., lambda k, _: k.startswith("name")))
traverse_obj(..., lambda x: ...)  # Error in debug mode
```
</details>
> [utils] `traverse_obj`: Add `set` transformations/filters and `re.Match` group names

- test/test_utils.py
- yt_dlp/utils.py
This PR adapts the expected results from the previous version to closer mimic what is desirable in an extractor context.
Branch prediction is removed and instead replaced by the `apply_key` result of `branching, result` (either `False, <value>` or `True, <values iterable>`).
- Values now get pruned if they are decided unhelpful (that is they are falsy and not `bool`, `int` or `float`).
- A trailing `dict` key now always returns a dictionary, making `**traverse_obj(None, {})` safe.
- `traverse_string` is now correctly handled when `is_user_input` is `False` (though not branching).
- `is_user_input` no longer supports string keys containing `:`.
- `default` now always applies to the values in the last `dict` key (`traverse_obj(None, {}, …
> [utils] `traverse_obj`: Fix several behavioral problems

- yt_dlp/extractor/pornez.py
This PR fixes the iframe extraction issue as reported in #6162 by joining the path of the iframe, pulled from the iframe src attribute, to the domain for pornez.  
Fixes #6162
</details>
> [pornez] fix: resolve iframe extraction issue

- yt_dlp/extractor/radiko.py
Can't download radiko.jp Time Free.
See also: #6090 
The update of radiko.jp.
Some of supplied hosts are not supported by FFmpeg.
Note that the version of FFmpeg is not related with this issue.
Filter supplied hosts before check details of them.
- Condition is little complex.
- To simplify, stop to use `is_onair` and implement method like `is_unsupported_host()` into class: `RadikoIE` and `RadikoRadioIE` instead and move condition into its method.
- However, this pull request leave it since this is hotfix.
- Download radiko.jp Live
- Download radiko.jp Time Free
- Play downloaded AAC file
- Check format of donwloaded AAC file by [MediaInfo](https://mediaarea.net/MediaInfo)
- Check which supplied host is available or not
- Live has dedicated host
- The host: `radiko.jp` is the firstest …
> Hotfix for radiko.jp

- yt_dlp/extractor/common.py
Fixes `_search_nuxt_data` incorrectly handling strings containing commas.
For example
```py
webpage = '''
<script>
window.__NUXT__=(function(a,b){return
{str1:a,str2:b}}("cool,string","lame string"));
</script>
'''
print(self._search_nuxt_data(webpage, None, traverse=None))
```
should produce
`{'str1': 'cool,string', 'str2': 'lame string'}`
instead of
`{'str1': 'cool', 'str2': 'string'}`
</details>
> [extractor/common] Fix _search_nuxt_data

- yt_dlp/YoutubeDL.py
Currently when `--write-subs --write-auto-subs` is enabled and no explicit format is mentioned, `yt-dlp` tries to search for the specific `en` subtitles for both uploaded and auto subs. This works most of the times.
However, many videos have english subtitles of the form [en-US](https://www.youtube.com/watch?v=rpwkgMX4IlQ) or even something like [en-qlPKC2UN_YU](https://www.youtube.com/watch?v=9H6muyZjms0). For videos like these, yt-dlp currently will not select the uploaded english subtitle but instead will either select the auto `en` one or some other arbitrary non english subtitle such as [es-419](https://www.youtube.com/watch?v=wW920zWkIQI), [ja](https://www.youtube.com/watch?v=UxMlGRThKws), etc.
This PR is a quick fix to first sort all english subtitles that start with `en`, uploaded …
> Improve how default youtube subs are selected

- yt_dlp/downloader/http.py
- yt_dlp/utils.py
Our YoutubeDLHandler is doing auto-decompression, so that we cannot compare Content-length to the size of extracted data. Although HttpFD has specified Youtubedl-no-compression, the web server may still ignore this and return deflated data (as the situation in #3772).
This change attempts to retain the Content-encoding header for later comparison in HttpFD so that we could discard data_len when the web server returns compressed data. I didn't find the reason why this header was previously removed but didn't yet find a counter example either.
Fixes #3772 in my experiments.
</details>
> [utils] Don't trust Content-length when Content-encoding is present

- yt_dlp/cache.py
- yt_dlp/utils.py
Call `os.makedirs` with `exist_ok=True`, rather than performing a separate check with `os.path.exists`.
This fixes a race condition that can occur when spawning multiple `yt-dlp` processes with the same output directory, where one of the processes crashes with `Unable to create directory [Errno 17]: File exists`, due to the interleaving of calls to `os.path.exists` and `os.makedirs`.
</details>
> [utils] Fix race condition in `make_dir`

- yt_dlp/__init__.py
- yt_dlp/postprocessor/ffmpeg.py
The ffmpeg postprocessor was still using an outdated workaround for replacing file extensions. Switched to using `os.path.splitext()`, which was already in use in the repo.  
Fixes #5968
</details>
> updated path extension replace in ffmpeg postproc

- README.md
- yt_dlp/extractor/tencent.py
* Use HEVC codec
* Supports 4K and HDR
* More information
</details>
> [extractor/tencent]: Add more formats and info

- yt_dlp/extractor/ntvru.py
> [extractor/ntvru] Extract HLS and DASH formats

- yt_dlp/extractor/yle_areena.py
> [extractor/yle_areena] Extract non-Kaltura videos

- yt_dlp/extractor/bilibili.py
Fixes #6357
Now yt-dlp get bilibili videos' `subtitle_url` through its api, instead of extract it from webpage (which is wrong if it is not the first part of the video).
</details>
> [bilibili/fix] fix yt-dlp always downloads the subtitle of the first video when downloads videos with multiple parts from bilibili

- yt_dlp/extractor/prankcast.py
At some point in the last week the tags field has changed from a JSON list to a string. This caused the extractor to fail:
> ERROR: [PrankCast] 1380: 1380: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
I've changed the tests to reflect this change and updated the extractor to no longer try to parse the string into JSON.
I'm not sure if it would be better to try and "convert" the string into a list manually (replacing commas with the proper formatting for a list) or just leave it as it is. If converting it to a …
> [Prankcast] Tags are no longer a JSON list

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/telecaribe.py
Telecaribe is a Colombian TV Station that provides some VODs and a livestream.
**Note:** VOD episodes don't have a direct link, that's why we can only extract the whole series as a playlist.
Fixes #6001
```bash
[debug] Command-line config: ['https://www.play.telecaribe.co/breicok', '--verbose', '-F']
[debug] yt-dlp version 2023.02.17 [a0a7c0154] (source)
[debug] Git HEAD: f187755c9
[debug] Python 3.10.7 (CPython x86_64 64bit) - Linux-5.19.0-31-generic-x86_64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg N-108931-g4dda3b1653-20221104 (setts), ffprobe …
```
> [extractor/telecaribe] Add TelecaribePlay extractors

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/tunein.py
TuneIn is a platform for live radio and podcasts
The page has changed a lot since the last update to these extractors (2018) and the following extractors have been removed because their url extractors no longer exist:
- TuneInClipIE
- TuneInProgramIE
- TuneInTopicIE
Extractors added:
- TuneInPodcastIE
- TuneInPodcastEpisodeIE,
Fixes #2973
```bash
[debug] Command-line config: ['https://tunein.com/radio/BBC-Radio-1-988-s24939/', '--verbose', '-F']
[debug] yt-dlp version 2023.02.17 [a0a7c0154] (source)
[debug] Git HEAD: da6f212c7
[debug] Python 3.10.7 (CPython x86_64 64bit) - …
```
> [extractor/tunein] Fix broken extractors

- yt_dlp/extractor/tubetugraz.py
This PR adds two-factor authentication to the TubeTuGraz extractor. This allows login to work again, since 2FA became mandatory a while ago. Until this fix, metadata download for many lecture videos was effectively broken in YT-DLP, since it was impossible to log in.
Since accounts on [tube.tugraz.at](https://tube.tugraz.at) cannot be created by anyone (only students and university personnel), I cannot provide an automated testcase that anyone can verify. However, there is a testcase that is already in the code can be used by any TU Graz student to check whether TFA works:
`yt-dlp https://tube.tugraz.at/paella/ui/watch.html?id=2df6d787-e56a-428d-8ef4-d57f07eef238 --username USERNAME`
- expected title without login: `TubeTuGraz video #2df6d787-e56a-428d-8ef4-d57f07eef238`
- expected title …
> [extractor/tubetugraz] Implement two-factor authentication (#6424)

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/teamcoco.py
The Teamcoco extractor needed a complete overhaul:
- some content from teamcoco.com has been moved to the new site conanclassic.com (added new extractor `ConanClassic`)
- teamcoco.com no longer uses GraphQL or any API calls
- conanclassic.com uses a "legacy" version of the graphQL that is slightly different
Closes #6339
</details>
> [extractor/teamcoco] Fix extractor

- yt_dlp/extractor/youtube.py
This PR adds the client names to `format_note` returned by the Youtube extractor for convenience
If you wish to enforce this to all the formats (MPD and HLS), a little rewrite would be required
p.s. make a release before reviewing this
```
$ ./yt-dlp.sh -s test:youtube_2 --extractor-args youtube:player_client=all -F
[TestURL] Extracting URL: test:youtube_2
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&v=yZIXLfi8CZQ
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc&v=yZIXLfi8CZQ
(snip)
[info] Available formats for BaW_jenozKc:
ID      EXT  RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────── …
```
> [extractor/youtube] Add the first 3 characters of client name in `format_note`

- yt_dlp/extractor/parler.py
This PR seeks to fix the parler extractor by updating the api endpoint used to pull the video related data and maintaining as close as possible the fields originally returned. 
Fixes #6068 
</details>
> [Parler] update parler extraction with new api call

- yt_dlp/extractor/youtube.py
Currently observing YouTube giving incomplete data for this initial data occasionally, leading to missing metadata (and non-UTC upload date in some situations).
Added functionality so it falls back to the API in this case. In YoutubeTab we re-download the webpage in this case, but since the webpage in YoutubeIE is downloaded as part of the player response process it is probably easier to do it this way.
```
yt-dlp --print upload_date https://www.youtube.com/watch\?v\=tjjjtzRLHvA -v --proxy ''
[debug] Command-line config: ['--print', 'upload_date', 'https://www.youtube.com/watch?v=tjjjtzRLHvA', '-v', '--proxy', '']
[debug] User config "/home/coletdjnz/.config/yt-dlp.conf": ['--ffmpeg-location', '/opt/yt-dlp-ffmpeg']
[debug] Encodings: …
```
> [youtube] Check for incomplete data in watch initial data

- yt_dlp/extractor/youtube.py
Youtube's extractor can now correctly parse comment count values containing unit suffixes (i.e. `K`, `M`, etc.).
Fixes #5849
</details>
> [extractor/youtube] Fix parsing `comment_count` with unit suffix

- yt_dlp/extractor/drtv.py
**Problem:** the extractor relies on retrieving a video id which can be extracted from a JSON blob with the following format: `<script>window.__data = {JSON_DATA}</script>`. However, since a few months back, this JSON blob has not been available on radio pages, i.e. pages under the url `dr.dk/lyd/*`, causing the extractor to fail for those pages.
**Fix:** the radio pages contain another JSON blob with the following format: `<script id="__NEXT_DATA__" type="application/json">{JSON_DATA}</script>`. The same video id is retrieved from this JSON data instead. Additionally, many of the tests referred to outdated pages and have been updated.
</details>
> [extractor/drtv] Fix video id parsing on radio pages

- yt_dlp/extractor/rozhlas.py
> [extractor/rozhlas] Extract manifest formats

- README.md
- yt_dlp/extractor/generic.py
* Add extractor-arg `variant_query` to passthrough the master m3u8 URL query to its variant playlist URLs (similar to how `fragment_query` works on fragment URLs)
* Add extractor-arg `hls_key` for generic m3u8s with AES-128 encryption:
Usage: `generic:hls_key=(URI|KEY)[,IV]`
```bash
--extractor-args "generic:hls_key=https://example.com/hls/key,0x1234567890ABCDEF"
--extractor-args "generic:hls_key=1234567890ABCDEF,0x9876543210FEDCBA"
--extractor-args "generic:hls_key=https://example.com/hls/key"
--extractor-args "generic:hls_key=1234567890ABCDEF"
--extractor-args "generic:hls_key=,0x9876543210FEDCBA"
```
</details>
> [extractor/generic] Add extractor-args `hls_key` and `variant_query`

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/brightcove.py
- yt_dlp/extractor/cbs.py
The site is press releases and promotional videos for CBS and other Paramount-owned media. I decided to put the extractor in `cbs.py`, since it's closely related. Maybe `paramountplus.py` would make more sense, but the ParamountPlus extractor may soon cease to exist since it looks like its entire catalog has been given the DRM treatment.
All videos on the site are Youtube embeds or Brightcove embeds. It uses the Brightcove API differently than I've seen before, sending requests to `edge-auth.api.brightcove.com` instead of `edge.api.brightcove.com`, and instead of sending a policy key with the request, it sends a bearer auth token. `BrightcoveNewIE` has been modified to handle this.
Closes #6597
</details>
> [extractor/cbs] Add `ParamountPressExpress` extractor

- yt_dlp/extractor/telecaribe.py
> [extractor/telecaribe] Expand livestream support

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/pgatour.py
> [extractor/pgatour] Add extractor

- test/test_utils.py
- yt_dlp/utils.py
Rel: https://github.com/yt-dlp/yt-dlp/pull/6505#discussion_r1132854567
Note that I have not really tested against edge cases and only in isolation. More tests are probably required. However I currently lack a lot of time and so just wanted to share this. Feel free to use.
Additionally the current implementation of `template_substitute` works only okayish (`undefined`/`void *` => `null` instead of `undefined`). Generally we would have to provide the real string value of each object which seems out of scope for `js_to_json`.
</details>
> [utils] `js_to_json`: Implement template strings

- yt_dlp/postprocessor/embedthumbnail.py
- yt_dlp/postprocessor/ffmpeg.py
This PR fixes a potential error (therefore a hidden bug) that caused by yt-dlp has failed to pass ffmpeg a `file:`-prepended path
This bug remained undiscovered because of "insane" filename sanitization
This log explains the situation:
```
[debug] Command-line config: ['-f', '141', '--embed-metadata', '--embed-thumbnail', '--write-info-json', '--no-clean-infojson', '--throttled-rate', '100k', '--no-playlist', '--header', 'Accept-Language:ja', '--parse-metadata', '%(album,channel,uploader)s:%(meta_album)s', '--fixup', 'force', '--extractor-args', 'youtube:player_client=web_music,android_music,web;preferred_langs=ja;player_skip=webpage', 'vuwvOHt5R-k', '5GPs1Pn94yI', '--remux', 'mka', '-kv', '--force-over']
[debug] User config …
```
> [postprocessor/EmbedThumbnail,postprocessor/FFmpegMetadata] Fix potential error on attaching thumbnails and info json for mkv/mka

- yt_dlp/extractor/youku.py
Added suggested clean_html change. Also removed several tests that were returning 404s - most seemed redundant with subsequent tests, but couldn't find a replacement for the password-protected URL that was no longer working.
Fixes #6551
</details>
> Fix youku extractor

- yt_dlp/extractor/zoom.py
The zoom extractor broke recently due to upstream changes. This is an attempt to fix that.
Fixes #6677
</details>
> [extractor/zoom] Update extraction logic

- yt_dlp/extractor/zoom.py
`/share/` URLs need to be redirected before the `file_id` can be extracted, and the redirect URL path comes from an additional API request to the `share-info` endpoint.
I had to move some code around, since hypothetically we will want both types of webpages to be checked for password inputs if/when someone manages to fix password-protected video extraction. But otherwise I didn't touch the password validation code.
One thing to note is that the redirect URL/`play` ID returned from the `share-info` endpoint is dynamically generated. No two requests return the same ID (even for the same video). So for the video's `id`, I thought it best to just use whatever ID is in the user-provided URL, regardless of whether it is a `play` ID or a `share` ID. 
Addresses …
> [extractor/zoom] Fix share URL extraction

- yt_dlp/postprocessor/ffmpeg.py
> [FFmpegFixupM3u8PP] Fix postprocessing for non-AAC audio codecs

- README.md
- yt_dlp/extractor/generic.py
The generic extractor can try to detect HLS livestreams by calling `_extract_m3u8_vod_duration` on one of the media playlist m3u8 URLs. This common extractor method checks if the `#EXT-X-ENDLIST` tag is present in the playlist, and returns the duration if so. The tag is a good indicator of whether the native HLS downloader or ffmpeg should download the m3u8; the playlist needs to be refreshed/re-requested if the tag is absent. So if the method returns `None`, then the generic extractor will assume the m3u8 is for a livestream.
This check does add another request to generic m3u8 extraction, but IMO livestream detection is worth the cost, and there's also the beneficial side effect of extracting duration for VOD HLS (and then we get `filesize_approx` too, if it's a master m3u8 that lists …
> [extractor/generic] Attempt to detect live HLS

- yt_dlp/extractor/gronkh.py
Also parse the duration and chapters on gronkh.tv.
Fixes #
</details>
> [extractor/gronkh] add duration and chapters

- yt_dlp/extractor/sbs.py
- yt_dlp/utils.py
From dirkf's PR: Australian provider SBS has changed its hosting arrangements and APIs, breaking the existing extractor.
The PR is intended to deal with the new APIs.
Some specialisations of extractor methods are included:
-    `_download_webpage_handle()` detects geo-restriction
-    `_extract_m3u8_formats()` defaults to the native downloader.
That PR was developed for upstream, so adjusted for deprecations and other legacy compatibility inclusions. It also addresses issue with extracting and converting dxfp subtitles to other formats, since SBS deliver their UTF-8 encoded files with `encoding='UTF-16'`, in error. The workaround is included in utils.py. Note that it will *not* be triggered where a file actually encoded with UTF-16 is downloaded.
Fixes #6543. Adapt dirkf's PR …
> [extractor/sbs] Overhaul extractor for new APIs

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/nhk.py
This PR adds support for [NHK らじる★らじる](https://www.nhk.or.jp/radio/), the radio streaming site of Japan's public broadcaster.
- [About page](https://www.nhk.or.jp/radio/info/about.html) (in Japanese)
- [Wikipedia article](https://ja.wikipedia.org/wiki/NHK%E3%83%8D%E3%83%83%E3%83%88%E3%83%A9%E3%82%B8%E3%82%AA_%E3%82%89%E3%81%98%E3%82%8B%E2%98%85%E3%82%89%E3%81%98%E3%82%8B) (in Japanese)
It supports downloading individual episodes and entire series (or at least, what's available - the episodes expire eventually), but does not support the live streams.
Downloading entire series sometimes gets episodes that aren't listed on the site, but are still in the API. Example: [site listing](https://user-images.githubusercontent.com/76261416/232220 …
> [extractor/nhk] Add NHK Radiru (らじる) extractor

- test/test_utils.py
- yt_dlp/utils.py
This allows things like `traverse_obj(..., ('key', {dict.items}, ...))`
</details>
> [utils] `traverse_obj`: Allow iterables in traversal

- yt_dlp/extractor/niconico.py
Basically the url format for series pages on niconico changed from just pointing at the series to including the user information in the url. Example:
https://www.nicovideo.jp/series/110226 now redirects to https://www.nicovideo.jp/user/44113208/series/110226
Old urls are still valid through the redirect but the previous extractor's way of extracting  the videos is not so that was updated as well.
Also in lieu of adding a specific test for this new url format I just edited one of the old format ones since we had multiple.
</details>
> Niconico seriesIE no longer working after url update

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/globalplayer.py
This PR adds support for [Global Player](https://globalplayer.com), the streaming site for [Global Media](https://en.wikipedia.org/wiki/Global_Media_%26_Entertainment)'s radio stations and podcasts. (ironically, Global only operates in the UK*.)
It supports: 
- Live Radio
- Radio Catch-up
- Podcasts
- "Live Playlists" - similar to live radio, but upfront about the fact that it's basically just someone's itunes playlist
- Limited support for videos (not all metadata is extracted)
I've tried to use `traverse_obj` more than in [my last PR](https://github.com/yt-dlp/yt-dlp/pull/6819), as that was one of the main changes made in the code review. I've also added a BaseIE for functions that multiple extractors use, but I may not have done it …
> [extractors/globalplayer] add Global Player extractors

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/dlf.py
Deutschlandfunk is a radio broadcasting corporation based in Germany. They cover a wide variety of contemporary news topics.
Currently, this extractor exclusively supports pre-recorded broadcasts. DLF distributes its pre-recorded audio sources in one of the `mp3` or `m3u8` formats. ~~The tests check for both of these cases.~~ I do not have a single-recording test case for `m3u8` sources.
As suggested in #6430, this extractor retrieves all the metadata from the `<button>` tag's HTML attributes.
Fixes #6430 
</details>
> [extractor/dlf] Add support for Deutschlandfunk

- yt_dlp/utils.py
This workaround is needed for some filesystems like virtiofs where any file locking or unlocking operation must be non-blocking
This PR adds a workaround for the file unlocking operation on some filesystems like virtiofs by adding the `UNLOCK_NB` flag on error.
Fixes #6823
</details>
> [utils] Fix non-blocking only filesystems

- README.md
- yt_dlp/extractor/wrestleuniverse.py
The site began requiring the `deviceId` parameter for (and broke extraction of) `/lives/` URLs. Unfortunately, this UUID value is only saved in browser local storage and cannot be extracted via cookie. Any random UUIDv4 will work, but the site uses this ID to track how many devices have watched paid livestream content, as some paid lives have device limits.
This PR's solution is to:
1. cache the `device_id` to disk
2. add a `device_id` extractor-arg to allow users to pass their browser's `device_id`
3. have `_real_initialize` first check the extractor-arg, then fallback to cache, then fallback to generating random uuid4, and store it in disk cache only when a new value is passed/generated
The PR also adds login support. When logging in with credentials, a refresh token is granted (also …
> [extractor/wrestleuniverse] Fix extraction, add login

- yt_dlp/extractor/daftsex.py
This PR implements the fix, provided by @NiklasFarber1024, for #5881 by updating the VALID_URL regex with the new domain as well as updating the url for the embed player where the video parameters are parsed. 
Fixes #5881
</details>
> [daftsex] fix: update domain and embed player url

- yt_dlp/extractor/cbc.py
Walkaround CBC.ca returning a return code of 426 when querying the file data.
```
curl -v https://services.radio-canada.ca/ott/cbc-api/v2/assets/murdoch-mysteries/s11e08
*   Trying 23.78.210.233:443...
* TCP_NODELAY set
* Connected to services.radio-canada.ca (23.78.210.233) port 443 (#0)
* {truncated for pertinence}
* Mark bundle as not supporting multiuse
< HTTP/1.1 426 Upgrade Required
< {truncated for pertinence}
<
{"id":"murdoch-mysteries/s11e08","title":"Brackenreid Boudoir","description":"To investigate an artist’s murder, Brackenreid picks up his paintbrush again and attracts a wealthy patron’s very personal attention.","image":"https://images.radio-canada.ca/v1/synps-cbc/episode/perso/cbc_murdoch_mysteries_season_11e08_thumbna …
```
> [extractor/cbc] Workaround CBC returning a http 426 when querying file data

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/recurbate.py
This is a new extractor to support the NSFW website Recurbate.com, by default the website support 1 free download, so a premium subscription is required
Fixes #
</details>
> [recurbate.com] Add recurbate extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/discogs.py
Add an extractor for the playlists embedded in Release and Master Release pages on discogs.com (an online music database). The generic extractor used to be able to read these, but that stopped working a long time ago.
Example URLs:
- https://www.discogs.com/release/1-The-Persuader-Stockholm
- https://www.discogs.com/master/113-Vince-Watson-Moments-In-Time
</details>
> [extractor/discogs] Add extractor

- .github/workflows/build.yml
- .github/workflows/release.yml
- requirements.txt
pip is failing to install yt-dlp 2023.11.14 on linux systems with CPython 3.11+ that do not have Rust installed, since PyPI does not provide pre-built py3.11+ wheels for `cryptography` (a dependency of `secretstorage`).
This partially reverts 9970d74c8383432c6c8779aa47d3253dcf412b14, but we can continue to include `secretstorage` in the Linux builds, and aim to add it properly as an optional dependency after #8550 is complete.
</details>
> [build] Make `secretstorage` an optional dependency

- yt_dlp/extractor/nintendo.py
This rewrite redirects Nintendo Direct extraction to the GraphQL-API endpoint.
</details>
> [ie/nintendo] Fix Nintendo Direct extraction

- yt_dlp/extractor/abematv.py
1. Set `season_number` instead of `series_number`
2. Fix key name for extracting `season` from api response
It looks like ``season_number`` is appropriate here, as
- `series_number` is not listed in [OUTPUT TEMPLATE](https://github.com/yt-dlp/yt-dlp#output-template), and
- api response from abematv suggests `season` has number while `series` does not:
> "series":{"id":"194-25","title":"異世界食堂２", ...
> "season":{"id":"194-25_s2","sequence":2,"name":"シーズン2", ...
I wonder if `series_number` should be left for backward compatibility. Just remove the line if it is not necessary.
</details>
> [ie/abematv] Fix season extraction

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/floatplane.py
Alternative implementation to #5912, supporting audio entries and multiple videos in a single post.
Most posts on the site only contain a single video; thus I decided to only return a single video instead of a playlist in those cases and use the post metadata for that video. This is also how the site visually represents it.
Posts with multiple videos/audio files get returned as a playlist.
Fixes #5877, Closes #5912
</details>
> [ie/floatplane] Add extractor

- yt_dlp/postprocessor/ffmpeg.py
Previously, stream metadata (e.g. `language`) was only being embedded in downloads that were merged video+audio. This patch will make it so the postprocessor also embeds stream metadata in single format downloads.
Closes #8568
</details>
> [pp/FFmpegMetadata] Embed stream metadata in single format downloads

- yt_dlp/extractor/twitcasting.py
Fixed regex so that we get url results
Closes #8653
</details>
> [ie/TwitCastingUser] Fix extraction

- yt_dlp/extractor/bfmtv.py
Regex fix
Closes #8425
</details>
> [ie/bfmtv] Fix extractors

- yt_dlp/extractor/mediastream.py
This PR fixes the mediastream extractor for sites that uses `access_token` or extra arguments in the HLS link.
The fix targets particularly to the iframe link of these two sites (the iframe link has to be extracted using the browser, it'll be the url passed to `yt-dlp`):
- `https://www.tvn.cl/en-vivo`
- `https://www.mega.cl/senal-en-vivo/`
These streams have a geo restriction and can only be accessed from Chile.
I have not made any new test, what would be the recommended way to test these changes?.
Fixes #
</details>
> Fixed mediastream when hls uses extra arguments

- test/test_networking.py
- test/test_websockets.py
OpenSSL 3.2 slightly tweaked its error messages which was causing some of our networking tests to fail:
```
FAILED test/test_networking.py::TestHTTPRequestHandler::test_ssl_error[Urllib] - AssertionError: Regex pattern did not match.
FAILED test/test_networking.py::TestHTTPRequestHandler::test_ssl_error[Requests] - AssertionError: Regex pattern did not match.
FAILED test/test_websockets.py::TestWebsSocketRequestHandlerConformance::test_ssl_error[Websockets] - AssertionError: Regex pattern did not match.
```
The new error message is:
```
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure
```
vs. the old:
```
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure
```
</details>
> [test:networking] Update tests for OpenSSL 3.2

- .github/workflows/build.yml
- .github/workflows/release.yml
- test/test_update.py
- yt_dlp/update.py
Some improvements & cleanup for the release/build workflows and Updater:
<details><summary>Updated repository variables</summary>
```yml
vars.PUSH_VERSION_COMMIT: Push a version update commit to master during release workflow
vars.UPDATE_TO_VERIFICATION: Test --update-to functionality during build workflow
secrets.GPG_SIGNING_KEY: Private GPG key used for signing SHA files
secrets.ARCHIVE_REPO_TOKEN: Personal Access Token with contents:write permission for any/all archive repos
vars.BUILD_NIGHTLY: Create a scheduled nightly pre-release
vars.NIGHTLY_ARCHIVE_REPO: Repository for archiving nightly pre-releases, e.g. `yt-dlp/yt-dlp-nightly-builds`
secrets.NIGHTLY_ARCHIVE_REPO_TOKEN: Personal Access Token with contents:write permission for nightly archive repo (overrides …
```
> [core] Release workflow & Updater maintenance

- test/test_YoutubeDL.py
- yt_dlp/YoutubeDL.py
With Python 3.12 the internally used parser changed. This caused a parse error for the format selector, as it uses `tokenize.tokenize` internally. Input like `7_a` was treated as an incorrect number and caused a parse error.
We can work around this by prepending a random letter only prefix so it doesn't treat it like a number anymore
</details>
> [core] Fix format selection parse error for CPython 3.12

- yt_dlp/extractor/ard.py
Adds support for the following URL scheme: `https://www.ardmediathek.de/serie/…`, e.g. https://www.ardmediathek.de/serie/nachtstreife/staffel-1/Y3JpZDovL3N3ci5kZS9zZGIvc3RJZC8xMjQy/1
Fixes #7666
</details>
> Support ARD Mediathek URLs with "serien" (fixes #7666)

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/ard.py
Reworks the ARD extractor. Some notes:
I changed the ID to the actual video ID and not the legacy tracking ID. This does come at the cost of having longer IDs and thus potentially issues with filename length. Open to feedback on if you think this is the right call.
`ARDMediathekBaseIE` can't yet be removed due to still being used by SWR. This can be addressed in a seperate PR.
The API always seems to return that the video is not geo-blocked. The CDN then redirects to a geo-blocking video. On some servers (ARD), this can be circumvented with xff.
To support accounts (watching age restricted videos during the daytime) requires a bit more work, re-implementing parts of their auth flow. This can also be done in a separate PR.
Fixes #8731, …
> [ie/ARDBetaMediathekIE] Rework extractor

- yt_dlp/extractor/bigo.py
Fixes Bigo extractor.
For some reason `getInternalStudioInfo` endpoint now returns xml in python by default
<details>
<summary>Response</summary>
```xml
<OfficialCommonResult>
<code>0</code>
<data>
<sid>2622124741</sid>
<siteId>805516745</siteId>
<uid>582287518</uid>
<avatar>http://esx.bigo.sg/na_live/3a3/1dB9jT.jpg</avatar>
<nick_name>Chaise</nick_name>
<country_code>US</country_code>
<gameTitle></gameTitle>
<gameId>0</gameId>
<roomTopic> Back in the hospital </roomTopic>
<snapshot>http://esx.bigo.sg/na_live/3a3/1DljJQ.jpg</snapshot>
<alive>1</alive>
<roomId>7049898423382340293</roomId>
<roomStatus>0</roomStatus>
<covers/>
<client_ip>152.32.180.207</client_ip>
<hls_src>https://86488B67.cubetecn.com:1444/list_3453011328_2622124741_0.m3 …
```
> [Bigo] Fix json extraction

- yt_dlp/cookies.py
I recently opened issue #8898 regarding `--cookies-from-browser firefox:<profile>` on macOS. When trying to find a Firefox profile on macOS, yt-dlp was looking in `~/Library/Application Support/Firefox/` instead of the proper path, `~/Library/Application Support/Firefox/Profiles/`. 
Firefox has used the `Profiles/` subdirectory to store profiles on macOS [as far back as 2016](https://www.howtogeek.com/255587/how-to-find-your-firefox-profile-folder-on-windows-mac-and-linux/) (and probably earlier than that, this was the first result in a Google search), so this is likely a bug on yt-dlp's part that has gone unreported.
Fixes #8898
</details>
> [bugfix] Fix FireFox profile folder path for macOS

- test/test_utils.py
- yt_dlp/utils/traversal.py
This PR adds support for `xml.etree.ElementTree.Element` in general traversal (`...`, `lambda a, b: ...` as well as `int`/`slice`)
It also adds xpath support when using a `str` key, applying manual special transformations that come in handy, like `@attribute` (get value of that attribute), `@` (get attribute dict) and `text()` (get inner text). The xpath returns a list, except when the key is only `@attr` or `text()`, at which case it returns the value directly.
</details>
> [utils] `traverse_obj`: Support `xml.etree.ElementTree.Element`

- yt_dlp/extractor/ard.py
Using the new id is [inconvenient for users](<https://github.com/yt-dlp/yt-dlp/issues/8731#issuecomment-1874398283>) bc it is just too long. Since the old id might be removed eventually though, this PR provides a fallback to the new id if it ever breaks, with a warning to open an issue about the breakage
People should use `--print-to-file "%(_old_archive_ids)#l" archive.txt` to put the new id into their archives, so when the old id disappears the connection is not completely lost
</details>
> [ie/ard] Revert to using old id

- yt_dlp/extractor/aenetworks.py
Certain shows without ratings on AE networks will crash and not allow the download to complete.
To duplicate this:
`yt-dlp -V https://play.history.com/shows/kennedy/season-1/episode-2`
or 
`yt-dlp -V https://play.history.com/shows/kennedy/season-1/episode-3`
(not sure if one will get ratings in the meantime of this being merged and prevent duplication)
I found code already in this project from the amcnetworks.py extractor that fixes the problem there. I copied that code over to the aenetworks.py and tested it manually. It works.
</details>
> [aenetworks] Prevent missing ratings extractor crash

- yt_dlp/extractor/abematv.py
The extractor fails with
```
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: "abematv-license" (requests, urllib)
```
and
```
File "/home/sefidel/projects/contrib/yt-dlp-fork/yt_dlp/extractor/abematv.py", line 79, in _get_videokey_from_ticket
(license_response['cid'] + self.ie._DEVICE_ID).encode('utf-8'),
~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```
because when `yt-dlp` fetches the token from cache, it triggers an early return.
Which resulted in `add_opener` not being called, and `_DEVICE_ID` being unset.
This commit fixes the issue by also calling the `add_opener` function when fetching the token from cache, and …
> [ie/abematv]: fix extraction when using cache

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/news9.py
- yt_dlp/extractor/ninenews.py
Initial video extractor for the ``9News`` website.
Fixes #8831 
</details>
> [9News] Add Extractor

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/kukululive.py
Extractor for KukuluLive
The URL is the same for live streams and for saved videos (VODs).
Here is the difference between generated HTML for live stream and for VODs:
https://gist.github.com/DmitryScaletta/b62a032a10eb0f632b702f4cf4ba110d/revisions
First we need to determine is it live strean or VOD.
The best solution that I came up with is to check this lines:
```js
var _url = "live.player.fplayer.php";    // live stream
var _url = "live.timeshift.fplayer.php"; // VOD
// or
var timeshift = false; // live stream
var timeshift = true;  // VOD
```
I noticed HD/SD buttons in the player.
They use H264 and HEVC codecs and an `action` query param determines what to use: `getZliveByAjax` for H264 and `getForceLowliveByAjax` for HEVC.
```bash …
```
> [KukuluLive] Add extractor

- README.md
- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/adn.py
Add support for the newly launched German site. The German site is accessible from DE, AT, CH, LI, LU under animationdigitalnetwork.de (instead of .fr). Backend API is the same as on the French site.
German site provides German subtitles and dubs (currently none available).
And while I'm at it, might as well add season download support as requested in #6643 
</details>
> feat(ADN): Add German variant and season downloads

- yt_dlp/extractor/gopro.py
The GoPro extractor fails even when used on the URLs recorded in the tests with an error like:
```
[GoPro] Extracting URL: https://gopro.com/v/KRm6Vgp2peg4e [GoPro] KRm6Vgp2peg4e: Downloading webpage
ERROR: [GoPro] KRm6Vgp2peg4e: KRm6Vgp2peg4e: Failed to parse JSON (caused by JSONDecodeError('Expecting \',\' delimiter in \'"shop_url"=>"https:/\': line 1 column 5120 (char 5119)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
File "/storage/avn/git/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
...
```
- The JSON in the webpage now contains semicolons as part of HTML entities such as `&quot;`. This …
> Fix GoPro extractor.

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/mx3.py
Add a simple, basic extractor for mx3.ch.
(mx3.ch is a site that hosts music uploaded by bands from or in Switzerland. As a first approximation I'd say it's government funded.)
</details>
> [extractor/mx3] Add extractor

- yt_dlp/extractor/patreon.py
It seems the `post_file['name']` attribute no longer exists in the Patreon video attributes (at least in the posts I tested, but unsure if it may exist in some cases), so the check for the case of m3u8 downloads was being skipped, so I changed it to also check for `post_file['duration']` and assume it is a video in this case. Is this a good enough check for this case?
Fixes #8973
</details>
> [patreon] fix not being able to download embedded videos

- yt_dlp/extractor/floatplane.py
Floatplane post can contain multiple items of video/audio, not just one. I'll call these playlist posts as opposed to regular posts
The extractor properly picks up all the entries in a playlist post. Downloading works fine. However some of the fields that would be available when downloading a regular post were not available for playlist entries. 
I ran into this myself when I tried to use `%(release_date)s` in an output template. 
This change:
- collects common fields for the post entry and playlist entries ...
- ... and spreads them in 1) the post info, and 2) every playlist entry
- adds a test to verify.
Fixes #
</details>
> [floatplane] feat: share playlist post fields with playlist entries

- yt_dlp/extractor/redtube.py
Reason: because https://www.redtube.com is not added to the beginning of the URL of the videoURL variable. I added it and it worked fine
```
[debug] Command-line config: ['-Fv', 'https://www.redtube.com/103228341']
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, …
```
> fix download redtube.com

- yt_dlp/extractor/rumble.py
> [extractor] Fix Rumble extractor

- .gitignore
- yt_dlp/extractor/adn.py
ADN DE requires an account and subscription for all videos
add error message for missing subscription case if logged in
ADN only supports login using username/password. Adjust `raise_login_required` call accordingly.
Also the German site is still somewhat restricted as it doesn't provide free ad supported content (yet). Added checks for this and raise Exceptions if the user isn't logged in or doesn't have a subcription.
Fixes #9067
</details>
> [ie/adn] require subscriptions in German

- yt_dlp/extractor/vbox7.py
Workaround for Vbox7 while DASH http ranges are not yet supported. Works by modifying the URL to get direct http and hls urls.
Fixes #1098
</details>
> [ie/Vbox7] Fix extractor

- yt_dlp/extractor/radiko.py
Adds the following information as metadata that can be obtained from radiko.jp for the target program:
- Performers
- Duration
</details>
> [ie/radiko]add Metadata info (performer, duration)

- yt_dlp/extractor/bilibili.py
Related issue: #8499
Add `--no-playlist` support for `BilibiliPlaylistIE` when url contains the currently playing video_id (`bvid=XXX`).
Bilibili appends `bvid` query to the url for the video currently opened in the webpage. This allows users to download only the current video that they are watching on the webpage, without need for providing access to the playlist.
(It is not clear why #8499 got that error code for playlist extraction. The issue author considered downloading current video is a fix, but I am aligned to keep the issue open rather than mark it as fixed.)
</details>
> [extractor/bilibili] support noplaylist option for BilibiliPlaylistIE

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/nytimes.py
This is the first PR of my attempt to overhaul the existing, non working, extractor.
I'm pretty sure there is a lot to optimize on the code I'm submitting.
To try and facilitate the process, I decided to break all the adjustments I made in different PRs.
This first PR covers:
- General Articles
- Cooking Recipes
- Cooking Guides
Fixes #8605 #2899
Future PRs will cover the extraction of:
- Video Playlist (and single video)
- Podcasts / Audio / Book Review
</details>
> [ie/NYTimes] - Extractor overhaul - Article, Cooking Recipes and Guides

- yt_dlp/extractor/tvp.py
> [extractor/tvp] fix live via vod

- Makefile
BSD Make can't do `$(shell ...)`. We were already using it in the `MARKDOWN` and `SYSCONFDIR` vars, but by using it in `CODE_FOLDERS` and `CODE_FILES` I broke the `yt-dlp` target for bmake.
Also:
- immediately raise error if GNU Make <4 is being used
- include fixes for the `yt-dlp` target if bmake is run in jobs mode
- remove vestigial `SYSCONFDIR` var assignment
- exclude `__pyinstaller` subdir from tarball
GNU Make versions older than 4.0 don't support `!=`, but considering that gmake 4.0 was released in 2013 IMO we shouldn't need to support it. Apparently Debian was holding onto make 3.8x for a while, but as of Jessie it was bumped to 4.0 (and all Debian versions up-to-and-including Jessie ship EOL Python anyways). CentOS 7 still has make 3.8x, but it is EOL as of the end of June. …
> [build:Makefile] Ensure compatibility with BSD `make`

- yt_dlp/extractor/rai.py
Since recently the media provider disabled download of certain media types so a check before adding those to the formats_list is now necessary to avoid polluting the formats_list with unavailable medias
Fixes #9154
</details>
> [rai] fix #9154

- yt_dlp/extractor/onefootball.py
I am not sure if the way I use `filter_dict` here to filter out the URL is desirable.
</details>
> [ie/OneFootball] Fix extractor

- yt_dlp/extractor/niconico.py
Hi.
Fixes #8684
See also: #6773
CAUTION: This PR completely removes the code about legacy danmaku extraction.
The "new danmaku extraction" logic works fine, by the way.
It seems that all `/comment/threads/.../server` are empty strings, I guess the legacy endpoint has been shut down.
Here is the `api_data` of [sm16309076 - 「Thousand Cherry Blossoms」 Played it【Piano】 - ニコニコ動画](https://www.nicovideo.jp/watch/sm16309076):
```JSON
{
...
"comment": {
"server": {
"url": ""
},
"keys": {
"userKey": ""
},
"layers": [
{
"index": 0,
"isTranslucent": false,
"threadIds": [
{
"id": 1322648373,
"fork": 1,
"forkLabel": "owner"
}
]
},
{
"index": 1,
"isTranslucent": false,
"threadIds": [
{
"id": 1322648373,
"fork": 0,
"forkLabel": "main"
},
{
"id": …
```
> [ie/niconico] remove unusable legacy danmaku (comments, subtitle) extraction

- Makefile
- pyproject.toml
- yt_dlp/__pyinstaller/hook-yt_dlp.py
Bugfix for 775cde82dc5b1dc64ab0539a92dd8c7ba6c0ad33
`__pyinstaller` needs to be included in the sdist and wheel so that pyinstaller works properly when yt-dlp is installed in a venv
</details>
> [build] Fix pyinstaller hooks

- yt_dlp/extractor/nhk.py
Pieces that make up an extended description are available through a
programme info API. They are, in order:
- short summary
- longer description
- the host(s)
- list of songs played
The host(s) field is free text, so it wouldn't be practical to put it in
`cast`. the order of items is copied from the mobile app - other orders
are used on the website's timetable, but I couldn't find the API etc
where they actually come from.
API info is gotten from https://www.nhk.or.jp/radio/config/config_web.xml,
which is the same endpoint used in NhkRadiruLiveIE. I don't think a
BaseIE etc is worth it at this time.
I've made an attempt to only download the API info once when downloading 
a playlist. I'm not sure it's the best/proper way to do it, but …
> [ie/NhkRadiru] Extract extended description

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/flextv.py
Extractor for another Korean twitch alternative.
<details>
<summary>API Response</summary>
```json
{
"id": 570421,
"title": "고라니율님의 방송국",
"description": null,
"thumbUrl": "https://ivs.flextv.co.kr/ivs/v1/585677956555/eGQ2LbyfNcxr/2024/2/10/9/1/sI5dno2WETsd/media/latest_thumbnail/thumb.jpg",
"fanIcons": [],
"subBadge": [
{
"id": 63,
"status": 1,
"channelId": 570421,
"imgUrl": "https://rlbmnicudtfv5809615.cdn.ntruss.com/sub-badge/1x821qelrugjx8h.png",
"month": 1,
"createdAt": "2024-01-26T09:45:58.000Z",
"updatedAt": null
},
{
"id": 64,
"status": 1,
"channelId": 570421,
"imgUrl": "https://rlbmnicudtfv5809615.cdn.ntruss.com/sub-badge/1x821qelrugk2wv.png",
"month": 2,
"createdAt": "2024-01-26T09:46:05.000Z",
"updatedAt": null
},
{
"id": 65,
"status": 1,
"channelId": 570421,
"imgUrl": …
```
> [FlexTV] Add extractor

- yt_dlp/plugins.py
This pull request introduces a modification to the `load_plugins` function within `plugins.py` to gracefully handle `PermissionError` exceptions that occur during the plugin loading process. The modification ensures that `yt-dlp` can continue to run without crashing when it encounters permission issues, specifically when trying to access directories for which it does not have permissions.
This issue has been observed in environments where `yt-dlp` attempts to access restricted directories (e.g., `/root/yt_dlp_plugins`) and throws a `PermissionError`, leading to the program's termination. Such behavior has been reported when running `yt-dlp --version` in a virtual environment and similarly affects other operations, including starting …
> Handle permission errors during plugin loading

- yt_dlp/extractor/openrec.py
Fixes #6946; add missing Referer header for all m3u8 requests since it is requested by the server since last year.
</details>
> [ie/openrec] add referer for m3u8 (fix #6946)

- yt_dlp/extractor/nerdcubed.py
Fixes the extractor and makes it more useful by using the actual homepage as a URL instead of a random json.
The extractor wasn't outright removed due to potentially still being useful for reducing the number of API requests to YouTube and to have multiple channels combined.
</details>
> [ie/NerdCubedFeed] Rework extractor

- .github/workflows/build.yml
Currently, if a build job fails due to a github runner/container issue, re-running the job causes issues with the meta files (since the `meta_files` job is always run before the workflow aborts). For an example, see the SHA2SUMS files in [the last nightly release](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.02.23.232656) whose ARM build jobs [randomly failed on the 1st attempt](https://github.com/yt-dlp/yt-dlp/actions/runs/8026312632/attempts/1).
This patch ensures that the meta files from a previous attempt are discarded and overwritten. [Click here](https://github.com/bashonly/yt-dlp/actions/runs/8026829208) to see a successful test release
</details>
> [build] Support failed build job re-runs

- yt_dlp/extractor/chzzk.py
Fixes an issue where `--wait-for-video` or `--retries` do not work and yt-dlp exits with an error due to raising `ExtractorError` when the channel is not live.
I've confirmed it works, but I'm not sure if and how I should add tests for this change.
<details><summary>Before Fix</summary>
```
[debug] Command-line config: ['-i', '--wait-for-video', '1', '--progress', '--retries', 'infinite', '-v', '-o', '20240227.mp4', 'https://chzzk.naver.com/live/68f895c59a1043bc5019b5e08c83a5c5']
[debug] yt-dlp version nightly@2024.01.28.232706 from yt-dlp/yt-dlp-nightly-builds [41b6cdb41] (zip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - …
```
> [ie/CHZZK] Raise UserNotLive when the channel is not live.

- yt_dlp/extractor/youtube.py
Per a trusted source:
> YouTube is removing support of 17.XX.XX clients, they only keep support of the two latest major versions
Closes #9316
</details>
> [ie/youtube] Bump Android/iOS client versions to 18.x

- yt_dlp/extractor/francetv.py
- yt_dlp/extractor/lumni.py
> [ie/francetv] Fix extraction

- yt_dlp/extractor/niconico.py
This PR is a quick fix about a failed modification in #9282 .
> Can't we just check if api_data["media"] exists or not?
Of course, I agree.
Videos for Premium users do not work with this check. If the user gets no format, they do not have access to that video.
Thanks to @betsu0 for the detailed feedback. Thanks to @fireattack for the professional analysis.
<br>
</details>
> [ie/niconico] correctly check if the user has access to the video

- yt_dlp/extractor/francetv.py
Per [this comment](https://github.com/yt-dlp/yt-dlp/commit/9749ac7fecbfda391afbadf2870797ce0e382622#commitcomment-139300092) by @boulderob, francetv's HLS formats are generally superior to their DASH formats, and were no longer being extracted after the API changes that were handled by 9749ac7fecbfda391afbadf2870797ce0e382622.
This PR also does some much-needed cleanup: removing dead code paths (`FranceTVIE` hadn't been doing anything with all the `catalog` params being passed to it since 2021) and removing dead subdomains/hostnames (`videos.francetv.fr`, `sivideo.webservices.francetelevisions.fr`) from the URL regex patterns and tests.
</details>
> [ie/francetv] Fix m3u8 formats extraction

- test/test_websockets.py
Seemingly, something got faster on Windows, causing the timeout tests to now (sometimes) fail. This PR reduces the timeout to ~`2.2e-308` which is significantly shorter than the Planck time, so I think we should be good for a while.
</details>
> [test:websockets] Reduce timeout

- yt_dlp/extractor/francetv.py
Some livestreams have a `workflow` value of `dai` instead of `token-akamai`, which was causing their m3u8 URLs to remain untokenized and return 403 errors. Since tokenizing the URL is non-fatal (and I can't find any examples of URLs that do not need to be tokenized), we might as well try to do it no matter what the workflow value is.
Addresses https://github.com/yt-dlp/yt-dlp/issues/9323#issuecomment-1983097622
Closes #9382
</details>
> [ie/francetv] Fix DAI livestreams

- yt_dlp/extractor/roosterteeth.py
This PR makes the Rooster Teeth extractor grab ad-free streams instead of streams with embedded ads.
Based on the videos I've looked at, by default `video_data['attributes']['url']` contains ads and `video_data['links']['download']` does not. Preferring the latter over the former is enough to download ad-free streams.
Additionally, passing in a `Client-Type: web` header forces both URLs to be the same ad-free stream. This PR includes that header as well for some slight future-proofing.
The RoosterTeeth tests were failing due to incomplete attribute data in test cases so this PR fixes that too.
Fixes #7647 
</details>
> [roosterteeth] Download ad-free streams

- yt_dlp/YoutubeDL.py
104a7b5a46dc1805157fb4cc11c05876934d37c1 added a check for the existence of both the deprecated singular info dict fields and the new pluralized info dict fields, and outputs a deprecation warning if both are found.
This is a problem for `--load-info-json`, since when we `--write-info-json` (or `--dump-json` etc), we are writing the new plural fields **and** the old singular fields to the info json, and then when we load it back we get deprecation errors:
```shell
ERROR: Do not return 'artist' when 'artists' is present; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: Do not return 'creator' when 'creators' is present; please report this issue on …
```
> Bugfix for 104a7b5a46dc1805157fb4cc11c05876934d37c1

- yt_dlp/extractor/crunchyroll.py
> [ie/crunchyroll] Extract `vo_adaptive_hls` formats by default

- .github/workflows/build.yml
- devscripts/install_deps.py
- pyproject.toml
This PR reworks the `unix` job in the build workflow and the `install_deps` devscript so that we can have a single `pyinstaller` optional dependency group.
</details>
> [build] Optional dependencies cleanup

- yt_dlp/extractor/common.py
- yt_dlp/networking/common.py
Add an impersonate API for the extractors.
Proposed implementation:
Add `impersonate` and `require_impersonation` params to the following extractor helper methods:
- `_request_webpage()`
- `_download_webage()` and `_download_webpage_handle()`
- `_download_json()` and `_download_json_handle()`
- `_download_xml()` and `_download_xml_handle()`
- `_download_socket_json()` and `_download_socket_json_handle()`
```
impersonate -- the impersonate target. Can be any of the following entities:
- an instance of yt_dlp.networking.impersonate.ImpersonateTarget
- a string in the format of CLIENT[:OS]
- a list or a tuple of CLIENT[:OS] strings or ImpersonateTarget instances
- a boolean value; True means any impersonate target is sufficient
require_impersonation -- flag to toggle whether the request …
```
> [ie] Add extractor impersonate API

- yt_dlp/extractor/soundcloud.py
Adapts the soundcloud extractor's format sorting to the change in 86a972033e05fea80e5fe7f2aff6723dbe2f3952
Before:
```shell
ID           EXT  RESOLUTION │  FILESIZE  TBR PROTO │ VCODEC     ACODEC   ABR
─────────────────────────────────────────────────────────────────────────────
hls_mp3_128  mp3  audio only │ ~ 5.99MiB 128k m3u8  │ audio only mp3     128k
http_mp3_128 mp3  audio only │ ~ 5.99MiB 128k http  │ audio only mp3     128k
hls_aac_256  aac  audio only │ ~11.99MiB 256k m3u8F │ audio only aac     256k
http_aac_256 aac  audio only │ ~11.99MiB 256k http  │ audio only aac     256k
hls_opus_64  opus audio only │ ~ 3.00MiB  64k m3u8  │ audio only opus     64k
download     wav  audio only │  64.54MiB      https │ audio only unknown
```
After:
```shell
ID           EXT  RESOLUTION │ …
```
> [ie/soundcloud] Adjust format sorting

- README.md
- devscripts/changelog_override.json
- yt_dlp/YoutubeDL.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
- yt_dlp/utils/_utils.py
As brought up in https://github.com/yt-dlp/yt-dlp/issues/1400#issuecomment-1988222479 the `filesize_approx` calculation for yt-dlp was inaccurate.
Initially, this was [diagnosed](https://github.com/yt-dlp/yt-dlp/issues/1400#issuecomment-1988317902) as the YouTube extractor falsely returning a bitrate to a scale of 1000 instead of 1024. Due to the norm being to use a scale of 1000 for networking, and 1024 for filesizes, this causes the displayed bitrate of the YouTube extractor to vary from other tooling (see: https://github.com/yt-dlp/yt-dlp/issues/1400#issuecomment-2005080565).
This change was also inconsistent with other extractors (including generic [m3u8](https://github.com/yt-dlp/yt-dlp/blob/e5d4f11104ce7ea1717a90eea82c0f7d230ea5d …
> [core] Fix `filesize_approx` calculation

- test/test_traversal.py
- yt_dlp/utils/traversal.py
Adds support for:
- `http.cookies.Morsel`
- Multi type filters (`{type, type}`)
- Update docs with changes
</details>
> [utils] `traverse_obj`: Convenience improvements

- yt_dlp/extractor/soundcloud.py
The Soundcloud extractor has to make an API request to get each format URL, and Soundcloud enforces a rate-limit of approx 600 requests per 10 minutes. Previously, the `_download_json` call in the extractor was only non-fatal, so if the rate-limit was reached, it would warn and continue, pointlessly burning through the rest of the format requests/playlist for the next 10 minutes.
This PR adds a `RetryManager` so the user can configure the rate-limited behavior with `--extractor-retries` and `--retry-sleep`.
</details>
> [ie/soundcloud] Enable retries for rate-limiting

- .github/workflows/build.yml
In light of what happened with xz's tarballs, I think it would be good to provide a verifiable "chain of custody" from our git repo to our release assets (tarball, binaries).
Our GitHub Actions logs for the build workflow will have a section that looks like this now:
<https://github.com/bashonly/yt-dlp/actions/runs/8497175700/job/23275527118>
```
Make SHA2-SUMS files
Run cd ./artifact/
cd ./artifact/
sha256sum * | tee ../SHA2-256SUMS
sha512sum * | tee ../SHA2-512SUMS
shell: /usr/bin/bash -e {0}
cd1214ccda412c384c0850443dfab2db81e382ee23e6e5fe638a7f2fbd15ee3a  yt-dlp
5d658358b341a90d6c99f56e404b9e4e42f55181d5ed59b5143b75eb98699b92  yt-dlp.exe
8a303ed7e113b1870591d4fc9ddbf7a5d1c8d602c5370914e753cbe81c825a92  yt-dlp.tar.gz
d7484dcc965c308dfaaaa44e2f659ab001f9d65d55112725d34e21df1bc15e93 …
```
> [build] Add SHA2-SUMS to GHA logs

- yt_dlp/extractor/cbc.py
This fixes the CBCPlayerIE after a change in the URL structure broke it. The URL no longer holds the video ID from ThePlatform, but an internal ID instead. As a result, the IE needs to extract the "mediaID" from the webpage. After that has finished, everything else can resume as usual. ~As to the question of which ID should be used by yt-dlp internally - I've stuck with the mediaID, but am unsure of whether that's the best decision. Essentially it comes down to:~
~Pros of the current approach:~
- ~This allows one ID to be used across the CBCPlayerIE, CBCCaffeinePlayerIE (see below) and ThePlatformIE~
- ~This doesn't break the archival of previous videos using the `--download-archive` option, and this option would make it recognize …
> [ie/cbc.ca:player] Support new URL format

- yt_dlp/extractor/joqrag.py
Fixes #8384
Sometimes "https://www.uniqueradio.jp/aandg" gave us the following content:
```js
var Program_name = '';
var Program_img = '';
var Program_link = '';
var Program_text = '';
var Program_personality = '';
var Program_adimg1 = '';
var Program_adlink1 = '';
var Now_music = '';
var Now_artist = '';
```
The broadcast had stopped at that time, but we were still trying downloading the stream.
I fixed it.
</details>
> [ie/joqrag] Fix live_status check when "Program_name" is empty

- yt_dlp/extractor/patreon.py
~~This change prioritizes downloading from m3u8 instead of vimeo embeds (or embeds in general), which in some cases may no longer exist and only the m3u8 video attachment does.~~
This change adds checks to verify if external embeds of Patreon posts are still valid before trying to download them (since they may have been deleted from vimeo/dropbox/etc. but still be attached to the Patreon post), and if it is invalid then it tries other options
Example, using `python -m yt_dlp https://www.patreon.com/posts/hunter-x-hunter-34007913` (this video is public, so no need for cookies/account to test with)
```sh
python -m yt_dlp https://www.patreon.com/posts/hunter-x-hunter-34007913
[Patreon] Extracting URL: …
```
> [patreon] fix some vimeo embed downloads

- yt_dlp/networking/_helper.py
Added the possibility to log the ssl keys of secure communications by specifying the standard env variable SSLKEYLOGFILE for request handles using the SSLContext. 
Fixes yt-dlp/yt-dlp#9531
</details>
> Adding ssl keys log using SSLKEYLOGFILE env var for SSLContext (yt-dlp/yt-dlp#9531)

- README.md
- yt_dlp/extractor/afreecatv.py
AfreecaTV's API will serve different m3u8 URLs depending on the value of the `return_type` parameter we send. The `return_type` value is a CDN ID, and each ID is tied to a CDN hostname. 
We are given a CDN ID to use in an earlier API response, but sometimes this is a bad ID that results in an unresolvable hostname (e.g. Korea gets `gs_cdn` which returns an m3u8 URL with the unresolvable hostname `chromecast.afreeca.gscdn.com` -- this is what 9073ae6458f4c6a832aa832c67174c61852869be attempted to fix).
But hardcoding a single working CDN ID is problematic since the best CDN for a given user is dependent upon the user's region; see #6497 and https://github.com/yt-dlp/yt-dlp/issues/9345#issuecomment-2048088892 .
This PR attempts to solve this by doing the following:
- Adding a fallback/retry …
> [ie/afreecatv:live] Add `cdn` extractor-arg

- yt_dlp/extractor/patreon.py
The request to check the Vimeo embed URL didn't include the referer header, so it was returning 403s / false negatives.
Also cleaned up the code and got rid of the `compat_urllib_unquote` and `try_get`s.
`_html_search_regex` is needed or else we get `&amp;`s in the Vimeo URL query string
Closes #9709
Fixes regression in 36b240f9a72af57eb2c9d927ebb7fd1c917ebf18
</details>
> [ie/patreon] Fix Vimeo embed extraction

- yt_dlp/extractor/stacommu.py
- yt_dlp/extractor/wrestleuniverse.py
The site has changed its URL format to always include a `/[language]/` path. This patch adapts the extractors' `_VALID_URL`s. Also makes the `_search_nextjs_data` call during metadata extraction non-fatal, since having it be fatal was breaking our handling of expected errors.
</details>
> [ie/theatercomplextown] Fix extractors

- yt_dlp/extractor/crunchyroll.py
CR is requiring Switch-specific auth tokens now for the Switch stream info API endpoint that the extractor uses.
This makes auth via the website useless and breaks our cookies support.
`--username`+`--password` and `--netrc` still work, and using no auth still works for free content.
Closes #9745
</details>
> [ie/crunchyroll] Fix auth and remove cookies support

- yt_dlp/extractor/wrestleuniverse.py
Some master m3u8s for PPV/livestreams actually provide variants for two separate streams, e.g. `https://vod.asset.wrestle-universe.com/2e6gptHzDNQS47VDSvUPGQ/live-b.m3u8` has a `live-a` stream and a `live-b` stream:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=23383278,AVERAGE-BANDWIDTH=20222400,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.970
live-b_1080p_2997fps.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=23383278,AVERAGE-BANDWIDTH=20222400,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.970
live-a_1080p_2997fps.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=10416034,AVERAGE-BANDWIDTH=9011200,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=29.970
live-b_720p_2997fps.m3u8 …
```
> [ie/wrestleuniverse] Avoid partial stream formats

- test/test_networking.py
- yt_dlp/networking/_curlcffi.py
- yt_dlp/networking/common.py
- yt_dlp/networking/impersonate.py
this can be useful during extractor error handling, [e.g. in the crunchyroll extractor](https://github.com/bashonly/yt-dlp/commit/e1ff1e1dff52ecda258d2a8fe61f29d786ad0881), where we want to expect the 403 error and a offer a cloudflare bypass hint if impersonation was not used, or else raise w/ a bug report message if impersonation was used.
</details>
> [networking] Add response extensions for impersonate info

- yt_dlp/YoutubeDL.py
Warns the user when the selected format on the default format selection differs due to FFmpeg missing.
As this is part of the `_default_format_spec` function we don't need to check if the user has passed any custom format selection.
To suppress this warning, the user can pass `-f best/bestvideo+bestaudio`.
Fixes #9843
</details>
> [core] Warn user when FFmpeg is missing

- yt_dlp/extractor/bilibili.py
Fixes #9528.
When not using cookies, this request at 
https://github.com/yt-dlp/yt-dlp/blob/ac817bc83efd939dca3e40c4b527d0ccfc77172b/yt_dlp/extractor/bilibili.py#L1029-L1047
returns something like 
```python
{'code': -352, 'message': '风控校验失败', 'ttl': 1, 'data': {'v_voucher': 'voucher_45ccfacf-4359-4103-**************'}}
```
where the message means something like "Risk control verification failed", i.e. they suspect you're a bot.
So raise an error similar to code -401 above and ask the user to use cookies.
</details>
> [ie/BilibiliSpace] better error message

- yt_dlp/extractor/bilibili.py
Fixes #9797.
Also use geo verification proxy for normal video IE (`BiliBiliIE`) because there are videos that are not bangumis also restricted to certain region (e.g. [this video](https://www.bilibili.com/video/av531424561/) can only be played in China.)
</details>
> [ie/bilibili] apply geo-verification-proxy to webpage download

- yt_dlp/extractor/yandexvideo.py
The site has changed their JSON format, causing the failure of stream urls extraction. Basically this patch extracts stream urls from the new JSON format
Fixes #9803 
</details>
> [ie/yandexvideo] Fix extractor

- test/conftest.py
- test/helper.py
- test/parameters.json
- test/test_http_proxy.py
- test/test_networking.py
- test/test_websockets.py
- yt_dlp/networking/_curlcffi.py
- adds tests for http/https proxies (standard and CONNECT)
- fixes https proxies in curl-cffi
- various minor test suite improvements
</details>
> [test] Add http proxy tests

- yt_dlp/cookies.py
Partially Fixes #5534
The chrome (and brave, have not checked other chrome based browsers) cookies database has 2 columns related to cookie expiry: expires_utc and has_expires. yt-dlp only checks the expires_utc column:
- For session cookies expires_utc is set to 0 and has_expires to 0. 
- For expiring cookies expires_utc is set to a utc timestamp and has_expires to 1
The current logic in yt-dlp takes expires_utc only and the phyton cookie will consider a value of 0 as expired:
```python
class Cookie:
def is_expired(self, now=None):
if now is None: now = time.time()
if (self.expires is not None) and (self.expires <= now):
return True
return False
```
To support session_cookies we should therefore set expires to None, since they do not …
> Enable use of session cookies in chrome

- yt_dlp/YoutubeDL.py
Added "add the --list-subs flag to see a list of available subtitle formats" to YoutubeDL.py. 
also its my first issue :)
Fixes #9760 
</details>
> Suggest --list-subs when no matching subtitle format found (Resolve #9760)

- yt_dlp/extractor/googledrive.py
- yt_dlp/extractor/youtube.py
We import those from the Youtube extractor, and also add:
'50':'mp3',
for mp3 files scrapping.
Fixes #8281
</details>
> [extractor/GoogleDrive] Add more supported types

- yt_dlp/extractor/eplus.py
Related to #9515.
An "ex/player" url without "show_id" points to either a player page or a collection of multiple player page urls.
Maybe we should change the regex to `https?://live\.eplus\.jp/ex/player\?ib=.+` ?
</details>
> [ie/eplus] Check if it's a pass ticket url; replace a dead url in test

- yt_dlp/extractor/common.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/9773.
This appends the hash of the POST data to the dump file name.
@bashonly's [suggestion](https://github.com/yt-dlp/yt-dlp/issues/9773#issuecomment-2096689990) is applied.
</details>
> Apends the hash of the POST data to the dump file name with --write-pages

- test/test_networking.py
- test/test_websockets.py
- yt_dlp/networking/common.py
Fixes https://github.com/yt-dlp/yt-dlp/issues/9659
removed the lower threshold, it is unnecessary 
</details>
> [test] Fix connect timeout test

- README.md
- bundle/py2exe.py
py2exe builds that are bundled with `requests` >=2.32.0 [fail to execute](https://github.com/yt-dlp/yt-dlp/actions/runs/9165401164/job/25199052454)
This PR excludes `requests` and `urllib3` from the py2exe bundle
[And it works](https://github.com/bashonly/yt-dlp/actions/runs/9165934523/job/25200358730)
</details>
> [build] Exclude `requests` from `py2exe`

- pyproject.toml
Fixes [broken macOS builds](https://github.com/bashonly/yt-dlp/actions/runs/9180166463/job/25244391798) due to today's problematic release of setuptools 70.0.0.
Refs:
- https://github.com/pypa/setuptools/issues/4374
- https://github.com/pyinstaller/pyinstaller/issues/8554
We also need to specify `>=66.1.0` or else installing dependencies fails on Python 3.12.
Ref:
- https://github.com/pypa/setuptools/blob/main/NEWS.rst#v6610
> Fix improper usage of deprecated/removed `pkgutil` APIs in Python 3.12+.
[example of broken setuptools <66.1.0](https://github.com/bashonly/yt-dlp/actions/runs/9180939393/job/25246533378)
[successful example with this patch](https://github.com/bashonly/yt-dlp/actions/runs/9181173439)
</details>
> [build] `macos` job requires `setuptools<70`

- README.md
- yt_dlp/extractor/soundcloud.py
The Soundcloud extractor needs to make an API call for every format available in order to extract the actual format URL (and other format metadata such as bitrate).
This is already a problem since this format endpoint has a rate-limit, and users frequently hit the rate-limit when extracting a playlist/batch of songs.
Ideally, [lazy info dict](https://github.com/yt-dlp/yt-dlp/pull/8512) would solve this problem. But now Soundcloud has introduced `encrypted-hls` (AES-128 HLS) formats, which are just dupes of the `hls` formats we already extract, so now every song makes almost double the requests to the rate-limited API endpoint.
Since lazy info dict still has a ways to go before merge, and since the `hls-aes` formats have severely compounded the problem, the best solution is to implement an …
> [ie/soundcloud] Add `formats` extractor-arg

- yt_dlp/extractor/orf.py
* add better DRM detection: ref:  #9652
* add parsing of the v4.3 api for subtitles
* better url parsing
example for 7 digits: https://on.orf.at/video/3229173
* better tests
the new test data has `killdate: None` as attribute, so this should be more stable for the future
sadly I did't found any video with age restriction and `right: "worldwide"` only with restriction to Austria and/or with a `killdate` < 2025, IMHO not worth to add as will create future problem
</details>
Open Questions:
*  I did't get the other subtitles formats working `'xml', 'srt', 'sami', 'ttml', 'stl'` that are available so I comment them out
*  should `display_id` be remove?! as it is not included with all urls from …
> [ie/orf:on] Improve extraction

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/taptap.py
Add support for video extraction from `taptap.cn` posts and game topic pages
Fixes #9643
</details>
> [ie/taptap] Add extractors

- yt_dlp/extractor/common.py
Some SMIL files like [this one](https://api-ovp.piksel.tech/ws/get_smilv2/od/http/tr_projectuuid_d8125233/tr_programuuid_v80kqp41/3279887.smil) (from [here](https://player.piksel.tech/v/v80kqp41?de-responsive=true&de-html-default=true)) set a base URL like so
```xml
<meta name="base" content="https://uscourts-back.cdn.piksel.tech/543007" />
```
And the actual video path like this:
```xml
<video src="/mm/flvmedia/...
```
Due to yt-dlp's use of `urllib.parse.urljoin` the trailing `543007` gets removed from the URL.
<https://github.com/yt-dlp/yt-dlp/blob/f78814923748277e7067b796f25870686fb46205/yt_dlp/extractor/common.py#L2386>
This PR fixes that by always appending a slash to the base URL.
I think this shouldn't break any other SMIL …
> [ie] Fix parsing of base URL in SMIL manifest

- .github/workflows/build.yml
- pyproject.toml
This PR bumps the minimum required version of Pyinstaller to 6.7.0 for our build jobs (and for our users who wish to bundle yt-dlp themselves).
`setuptools` v70 was released last week and broke yt-dlp builds when using Pyinstaller <6.7:
- https://github.com/pyinstaller/pyinstaller/issues/8554
We had done a quick and dirty fix of pinning setuptools to `>=66.1,<70`, but this is untenable moving forward.
---
For the `macos` (universal2) builds, ever since including `curl-cffi`, we had to pin Pyinstaller to 5.13.2, since Pyinstaller >=6 produced "universal2" builds that did not actually work on arm64 architecture. I knew that this was the problem, but I didn't know exactly why. @seproDev further investigated this issue:
> The curl-cffi x86_64 wheels include `libssl.3.dylib` and …
> [build] Bump Pyinstaller to `>=6.7.0` for all builds

- yt_dlp/extractor/patreon.py
> [ie/PatreonCampaign] Fix `campaign_id` extraction

- README.md
- bundle/py2exe.py
- pyproject.toml
- yt_dlp/networking/_requests.py
OpenSUSE's `python-requests` package breaks `requests` support in yt-dlp, and likely won't be the only one to do it. Details: https://github.com/yt-dlp/yt-dlp/issues/10078#issuecomment-2142640582
The only proper solution is to bump the minimum required version of `requests` to 2.32.2 with its new "stable" API.
This PR also removes `requests` from the `py2exe` builds, which are broken by `requests>2.31.0`. Newer versions try to load certifi's `cacert.pem` which throws a `FileNotFoundError`, since `certifi` is not (and cannot be) properly included in the py2exe builds. We never really should have been including `requests` in the py2exe builds anyways, since `requests` has had a hard dependency on `certifi` for as long as yt-dlp as supported `requests`.
A user-made build would also fail like …
> [rh:requests] Bump minimum version requirement for `requests` to 2.32.2

- README.md
- yt_dlp/YoutubeDL.py
- yt_dlp/downloader/external.py
- yt_dlp/downloader/hls.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/generic.py
Currently, the value of the `extra_param_to_segment_url` format field will be passed through to both the HLS fragment URLs and the HLS AES-128 decryption key URL (if there is one). There is no way to pass the decryption key URL its own query if it needs different params than the fragment URL query params.
This PR adds a `extra_param_to_key_url` format field, and also a `key_query` extractor-arg for the generic IE so that this functionality can be used with generic m3u8 URLs.
Needed for #10098
</details>
> [fd/hls] Apply `extra_param_to_key_url` from info dict

- yt_dlp/extractor/podbayfm.py
The `id` that was being extracted was not unique, and the `id`s we were extracting with the channel extractor were completely wrong.
These URLs would result in `id` collision with the single podcast extractor:
```
https://podbay.fm/p/the-rest-is-history-667328/e/1704067800
https://podbay.fm/p/leading-682335/e/1704067800
```
And here's what the channel extractor used to do:
```shell
$ yt-dlp -I1-9 --print id "https://podbay.fm/p/behind-the-bastards"
1373812661
1373812661
1373812661
1373812661
1373812661
1373812661
1373812661
1373812661
1373812661
```
</details>
> [ie/podbayfm] Fix extraction

- yt_dlp/extractor/youtube.py
Failing to decode the nsig param now results in HTTP Error 403 instead of download speed throttling. We need to skip the affected formats when this happens instead of slightly deprioritizing them, and update our warning messages accordingly. See https://github.com/ytdl-org/youtube-dl/issues/32815
</details>
> [ie/youtube] Skip formats if nsig decoding fails

- yt_dlp/compat/imghdr.py
- yt_dlp/postprocessor/embedthumbnail.py
Tackles the following problems:
- Incorrect `imghdr.what` detection
- Cryptic `imghdr.what` fail message
- Incorrect AtomicParsley error handling
Fixes #10245
</details>
> [pp/embedthumbnail] Fix 

- test/test_download.py
It was recently brought to my attention that download test network errors (e.g. cert errors raised during extractor requests) are being silently ignored by pytest: https://github.com/yt-dlp/yt-dlp/pull/10268#discussion_r1657872204 
@seproDev dug into this and found dd508b7c4f0dd8881de07a4e8593d4fcdef9bae7, which clarifies that this retry+warn+pass behavior was intended for the ytdl CI and not for extractor development. 
Since this warn+pass behavior is actually detrimental to extractor dev, this PR partially reverts that commit so that network errors will again raise when the retries are exhausted.
</details>
> [test:download] Raise on network errors

- yt_dlp/extractor/youtube.py
I have a cron script that tries to back up my YouTube favorites playlist (because videos tend to disappear off the net without warning).  I recently started using yt-dlp for this purpose.  It works very well, except it emits a single warning even in quiet mode:
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
which makes cron send me an email about it.
This PR suppresses that warning.
</details>
> Ignore "Unavailable videos are hidden" warnings from YouTube

- README.md
- yt_dlp/YoutubeDL.py
This has been requested on discord a couple times, and it seems like a reasonable and useful request.
</details>
> Add `playlist_channel` and `playlist_channel_id` fields

- yt_dlp/__init__.py
Fixes bug in 5ce582448ececb8d9c30c8c31f58330090ced03a
</details>
> [core] Fix `--compat-opt allow-unsafe-ext`

- yt_dlp/utils/_utils.py
Fixes regression in 5ce582448ececb8d9c30c8c31f58330090ced03a
Authored by: Grub4K
Closes #10344
</details>
> [core] Fix `--ignore-no-formats-error`

- test/test_youtube_signature.py
- yt_dlp/extractor/youtube.py
> [ie/youtube] Fix failing nsig decoding for player `b22ef6e7`

- yt_dlp/extractor/soundcloud.py
Soundcloud's API has a rate-limit of ~600 requests per 10 minutes for the format URL endpoint, which the extractor was previously handling by retrying individual requests format URLs upon receiving HTTP Error 429. This was only partially effective, since format URLs extracted before the retry sleep interval will expire by the time extraction completes and downloading begins. This patch moves the 429 `RetryManager` loop outside of `_extract_info_dict()` so that all format URLs can be (re-)extracted after the rate-limit has reset.
</details>
> [ie/soundcloud] Fix rate-limit handling

- yt_dlp/extractor/youtube.py
> [ie/youtube] Remove `n` function extraction fallback

- yt_dlp/extractor/youtube.py
The nsig breakage tracked in #10391 was only partially fixed by 6c056ea7aeb03660281653a9668547f2548f194f and 297b0a379282a15c80d82d51f3757c961db2dae1, at which point version 2024.07.08 was released. With only these two fixes applied, yt-dlp would cache improperly extracted JS code to disk.
Shortly after 2024.07.08 was released, 7ead7332af69422cee931aec3faa277288e9e212 was applied, which actually fixed the nsig breakage and fixed the problem with yt-dlp storing incorrect cache data. This patch was included in the 2024.07.09 release.
The problem is that any user who had updated to version 2024.07.08 (or its equivalent nightly or master releases) may have had yt-dlp store bad nsig function data in their cache, and they will continue to experience nsig breakage even after updating to …
> [ie/youtube] Invalidate nsig cache from < 2024.07.09

- .github/workflows/build.yml
- README.md
- pyproject.toml
curl_cffi 0.7.0 does not work under Windows 7 and will cause yt-dlp to crash. The crash occurs with both the `win_exe` and Python installations. It appears to be an issue with curl_cffi's forked curl-impersonate library, see: https://github.com/yifeikong/curl-impersonate/issues/72
Until that issue is resolved on curl_cffi's end, or until we [drop support for Windows 7](https://github.com/yt-dlp/yt-dlp/issues/10086) in October/November, we'll need to pin `curl_cffi` to version 0.5.10 for Windows. A side effect of this is the complete removal of curl_cffi from the `yt-dlp_x86.exe` builds, since version 0.5.10 doesn't support 32-bit Windows (while 0.7.X does).
Closes #10426
</details>
> [build] Pin `curl_cffi` to 0.5.10 for Windows

- yt_dlp/extractor/youtube.py
YouTube seems to be rolling out an experiment related to PO tokens. videoplayback URLs from sessions affected by this experiment return with a 403 if more than ~1 MB is requested.
As of right now, it is unknown what experiment `51217476` and `51217102` exactly do. They are, however, consistently present in requests that fail with a 403, and not present in requests that succeed. It is likely that this is related to botguard.
This PR consists of two parts:
- First, the initial player response is ignored if the PO token experiments are present, and instead the innertube API is called.
- Second, the innertube API calls are retried if the PO token experiments are present. If they are repeatedly present, that player_client is skipped. …
> [ie/youtube] Avoid poToken experiment player responses

- yt_dlp/extractor/afreecatv.py
**EDIT**: Since 150ecc45d9cacc919550c13b04fd998ac5103a6b has been merged and a `legacy_ssl` request extension has been implemented, we can leverage that instead of impersonation and fix the login regression in a much simpler way.
The old/outdated PR description is below
---
Currently, afreecatv is not actually performing any TLS fingerprinting, they are just using SSL ciphers that are incompatible with any request handler other than curl_cffi. We were using `impersonate=True` with some of these extractors' API requests so that the user doesn't need to manually pass `--legacy-server-connect`. (The only alternative was downgrading these API requests to `http:`, which was not a viable solution since account session cookies are passed with these requests.)
We were not using …
> [ie/afreecatv] Fix login and use `legacy_ssl`

- yt_dlp/extractor/generic.py
Fixes regression in the generic extractor due in 5ce582448ececb8d9c30c8c31f58330090ced03a
Closes #10459
</details>
> [ie/generic] Fix direct video link extensions

- yt_dlp/YoutubeDL.py
- yt_dlp/__init__.py
- yt_dlp/options.py
> [core] Support `auto-tty` and `no_color-tty` for `--color`

- yt_dlp/update.py
Fixes inscrutable error output like https://github.com/yt-dlp/yt-dlp/actions/runs/9963205202/job/27528793760
</details>
> [update] Fix network error handling

- pyproject.toml
setuptools 71.0.0 and 71.0.1 break our pyinstaller builds:
- https://github.com/pypa/setuptools/issues/4482
- https://github.com/pypa/setuptools/issues/4480#issuecomment-2236507819
- https://github.com/pypa/setuptools/issues/4477
- https://github.com/pyinstaller/pyinstaller/issues/8665
The issue has been resolved in setuptools 71.0.2.
</details>
> [build] Pin `setuptools` version

- yt_dlp/extractor/abematv.py
Fixes a regression caused by a dependence on buggy behavior that was corrected in 150ecc45d9cacc919550c13b04fd998ac5103a6b
Closes #10489
</details>
> [ie/abematv] Migrate key retrieval to request handler framework

- test/test_youtube_signature.py
- yt_dlp/extractor/youtube.py
This now:
```js
;a.D&&(b="nn"[+a.D],c=a.get(b))&&(c=rDa[0](c),a.set(b,c),rDa.length||rma(""))}};
```
</details>
> [ie/youtube] Fix `n` function name extraction for player `3400486c`

- yt_dlp/extractor/_extractors.py
- yt_dlp/extractor/tva.py
- yt_dlp/extractor/unsupported.py
Everything is `tvaplus.ca` now. Valid (non-DRM) `qub.ca` URLs will redirect to their new `tvaplus.ca` counterparts, and the old `videos.tva.ca` URLs are all dead and redirect to the `tvaplus.ca` homepage. There is also now QUB VRAI, which is completely DRM-protected, and has been added to `yt_dlp.extractor.unsupported` as such.
Closes #10555
</details>
> [ie/tva] Fix extractor

- test/test_utils.py
- yt_dlp/utils/_utils.py
`unified_timestamp` wasn't parsing dates that began with `(?i)sun(?:day)?`
</details>
> [utils] `unified_timestamp`: Recognize Sunday

- yt_dlp/extractor/tver.py
I have added support for videos of the Paris Olympics on TVer (excluding LIVE). Since these videos are expected to be unavailable after the Olympic period ends, I have set _TESTS to `only_matching`.
Fixes #10583
Sample URLs:
- https://tver.jp/olympic/paris2024/video/6359575021112/
- https://tver.jp/olympic/paris2024/video/6359590242112/
- And more...
- 207 videos available at: https://tver.jp/olympic/paris2024/video/?type=latest
</details>
> [ie/TVer] Add support for downloading Paris Olympic (2024) VOD

- test/test_youtube_signature.py
- yt_dlp/extractor/youtube.py
Also adds a fallback regex search which looks for the function itself
Closes #10608
</details>
> [ie/youtube] Fix `n` function name extraction for player `20dfca59`

- yt_dlp/extractor/youtube.py
When passing the `player_client` youtube extractor-arg, this patch allows a client name to be prefixed with `-` so it can be excluded from `all` or `default`, e.g.:
```
--extractor-args "youtube:player_client=all,-web,-web_safari,-android,-android_music"
--extractor-args "youtube:player_client=default,-web_creator"
```
Closes #10699
</details>
> [ie/youtube] Support excluding `player_client`s in extractor-arg

- yt_dlp/utils/_utils.py
> [utils] `mimetype2ext`: Recognize `aacp` as `aac`

- yt_dlp/extractor/espn.py
No linked issue as this was a fix I wanted to implement myself. Previously ESPN+ extractor used an id_token to authenticate, which expired every 24 hours. This meant it was not useful for any sort of automation because the user would need to resupply cookies every day. Now, the extractor uses the refresh_token to get an id_token every call, and the refresh_token expires every ~6 months.
The **_big problem_** that must be resolved before merge is that I cannot figure out how to send the appropriate POST request using yt-dlp's `_download_json`. I need to send some JSON data but so far I've only gotten it to work via the `json` argument of `requests.post`. I've tried to convert it to string with both `json.dumps` and …
> Better authentication for ESPN+

- yt_dlp/extractor/dplay.py
Closes #10984
Thanks to @rdamas for investigating the issue and finding a solution
</details>
> [ie/HGTVDe] Fix extractor

- pyproject.toml
- yt_dlp/networking/_curlcffi.py
Ref: https://github.com/lexiforest/curl_cffi/issues/394
</details>
> [networking] Pin `curl-cffi` version to < 0.7.2

- test/test_YoutubeDL.py
- test/test_utils.py
- yt_dlp/utils/_utils.py
The actual `vcodec` values for vp9 are like 
- `vp09.00.10.08`
- `vp09.02.11.10.01.09.18.09.00`
The existing situation:
`FormatSorter` handles `vcodec` as an `ordered`, with separate entries for vp9.2 and general vp9.
In practice vp9.2 is probably used because it has hdr support but sometimes vp9 with hdr is not supported for hardware decode when basic sdr vp9 is, for instance in nvdec with some nvidia cards (https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) so they are distinguished as different categories of vcodec value for sorting. Great.
However the regex `FormatSorter` uses for vp9.2 does not match the actual `vcodec` values seen for it -- it does not match the leading `0` of the `02` -- so it is treated as just another regular vp9.
This is separate from …
> vp9.2 vcodec format sort bug fix

- yt_dlp/YoutubeDL.py
- yt_dlp/__init__.py
- yt_dlp/cookies.py
Exit early when encountering a cookie load error. See this log:
```console
$ yt-dlp --cookies-from-browser whale test:youtube test:youtube
[TestURL] Extracting URL: test:youtube
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
Extracting cookies from whale
ERROR: could not find whale cookies database in "/home/grub4k/.config/naver-whale"
[TestURL] Extracting URL: test:youtube
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
Extracting cookies from whale
ERROR: could not find whale cookies database in "/home/grub4k/.config/naver-whale"
```
Since the cookiejar is created lazily, the error now gets thrown inside the `_handle_extraction_exceptions` function, silencing the error (because …
> [cookies] Fix cookie load error handling

- yt_dlp/postprocessor/xattrpp.py
Some filesystems limit the size of extended attributes (e.g., 4kB on ext4). The description can easily get close to or exceed this. By writing it last, we avoid missing out on the other ones.
Also catch each write_xattr() failure individually, so we can report which attributes were not written.
</details>
> Make extended attribute writing more robust against filesystem limits.

- devscripts/run_tests.py
Allows running `hatch test test/test_utils.py::TestUtil::test_sanitize_path` directly, so that you don't have to wait for gathering (takes long especially on Windows).
</details>
> [test] Allow running tests explicitly

- test/test_traversal.py
- yt_dlp/extractor/common.py
- yt_dlp/utils/_utils.py
- yt_dlp/utils/traversal.py
Adds the following changes:
- `session_cookies` method to login hint
- `traversal`:
- `filter` key
- `require` helper
- `find_element` and `find_elements` helpers
- `subs_list_to_dict` helper
- `value` helper
- Allow `{int_or_none(scale=10)}`/`{float_or_none(scale=10)}`
</details>
> Add extractor helpers

- yt_dlp/extractor/adobepass.py
> [ie/adobepass] Use newer user-agent for provider redirect request

- .github/workflows/build.yml
Ref: https://github.com/actions/runner-images/issues/10721
Successful build: https://github.com/bashonly/yt-dlp/actions/runs/11310920438
Successfully tested on `macOS-11.6-arm64-arm-64bit`
</details>
> [build] Use `macos-13` image for macOS builds

- yt_dlp/extractor/youtube.py
> [ie/youtube] Fix `comment_count` extraction

- README.md
- test/test_plugins.py
- test/testdata/plugin_packages/testpackage/yt_dlp_plugins/extractor/package.py
- yt_dlp/__init__.py
- yt_dlp/options.py
- yt_dlp/plugins.py
- yt_dlp/utils/_utils.py
Closes #3260
Lets you specify `--plugin-locations` 1 or more times and then goes to each specified location and looks for `<package name>/yt_dlp_plugins/` as normal. Via CLI or config file.
</details>
> Add option for specifying plugins directories

- yt_dlp/extractor/youtube.py
The `tv_embedded` client now requires sign-in for every video, so it is no longer useful for extracting age-restricted videos when unauthenticated.
Closes #11296
</details>
> [ie/youtube] Remove broken age-restriction workaround

- pyproject.toml
This makes the Python optional depedencies *actually* optional by moving them into the `default` optional dependency group (i.e. the `default` extra).
yt-dlp's current documentation<sup>[[1]](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#update)</sup><sup>[[2]](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip)</sup> already reflects this change, which means that when installing via pip/pipx, the `default` group/extra will need to be specified in the install/upgrade command, e.g.:
```
python3 -m pip install -U "yt-dlp[default]"
```
The documentation was updated over 7 months ago<sup>[[1]](https://github.com/yt-dlp/yt-dlp/commit/cf91400a1dd6cc99b11a6d163e1af73b64d618c9)</sup><sup>[[2]](https://github.com/yt-dlp/yt-dlp-wiki/commit/e68fe1dcf88e7d7cf27d8b0173a0340a205fd9ac)</su …
> [build] Move optional dependencies to the `default` group

- yt_dlp/__init__.py
Currently, passing `--plugin-dirs ~/path/to/plugins` in a shell works, but the same doesn't work in a config file.
Similarly, passing `--plugin-dirs '~/path/to/plugins'` doesn't work in a shell or in a config file.
We need to call `expand_path` on the path values like we do for all of the other options that accept path values.
Bugfix for 0f593dca9fa995d88eb763170a932da61c8f24dc
</details>
> Expand paths in `--plugin-dirs`

- yt_dlp/YoutubeDL.py
- yt_dlp/utils/_utils.py
The tbr was calculated in format sorter, but that happened after filesize_approx was calculated, so it wasnt accessible.
Fixes a regression introduced in 39f32f1715c0dffb7626dda7307db6388bb7abaa
Closes #8730
</details>
> [core] Populate format sorting fields before dependent fields

- yt_dlp/utils/traversal.py
Fix bug in d710a6ca7c622705c0c8c8a3615916f531137d5d
`find_element(cls='example')` would raise an assertion error since we were always setting `tag` when falsy
</details>
> [utils] Fix `find_element` by class

- yt_dlp/utils/_utils.py
Fix 5ce582448ececb8d9c30c8c31f58330090ced03a
Closes #11407
</details>
> Allow thumbnails with `.jpe` extension

- test/test_InfoExtractor.py
- test/testdata/netrc/netrc
- test/testdata/netrc/print_netrc.py
- yt_dlp/extractor/common.py
- yt_dlp/extractor/youtube.py
Closes #11413
From https://github.com/yt-dlp/yt-dlp/issues/11413#issuecomment-2447664513:
> there was a change in Python's `netrc` stdlib module in 3.11: https://github.com/python/cpython/commit/15409c720be0503131713e3d3abc1acd0da07378
> ```
>       The entry in the netrc file no longer needs to contain all tokens.  The missing
>       tokens' value default to an empty string.  All the tokens and their values now
>       can contain arbitrary characters, like whitespace and non-ASCII characters.
>       If the login name is anonymous, it won't trigger the security check.
> ```
> so it's currently impossible to pass an empty string password as `""` via netrc file with Python versions 3.10 and older > (the yt-dlp `win_exe` builds are 3.8/3.10) …
> Fix `--netrc` empty string parsing for Python <=3.10

- test/test_traversal.py
- test/test_utils.py
- yt_dlp/utils/_utils.py
- yt_dlp/utils/traversal.py
TODO:
- to be done in cleanup PR
</details>
> [utils] Allow partial application for more functions

- .github/workflows/release.yml
Digital attestation for PyPI trusted publishing currently does not work with reusable workflows, e.g. `release-nightly.yml` calling `release.yml`. [This breaks our nightly PyPI releases.](https://github.com/yt-dlp/yt-dlp/actions/runs/11603267731)
It was turned "on by default" in v1.11.0 of `pypa/gh-action-pypi-publish` (yesterday). We need to temporarily disable it until reusable workflows are supported.
- https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.11.0
- https://github.com/pypa/gh-action-pypi-publish/discussions/255
- https://github.com/pypi/warehouse/issues/11096
</details>
> [build] Disable attestations for trusted publishing

- test/test_aes.py
- yt_dlp/aes.py
The AES decryption code was fine, just the tag validation failed due to incorrect pad length calculation.
In case of 16 byte aligned data no padding should be added. The old code added 16 null bytes.
```
> len(data)
64
> len(data) // 16 * 16
64
> (BLOCK_SIZE_BYTES - len(data) + pad_len)
16
```
```
> len(data)
64
> (BLOCK_SIZE_BYTES - (len(data) % BLOCK_SIZE_BYTES)) % BLOCK_SIZE_BYTES
0
```
Fixes #10169
</details>
> [aes] Fix gcm pad length calculation

- yt_dlp/extractor/anvato.py
- yt_dlp/extractor/nfl.py
The site's API changed somewhat, and it now directly serves the m3u8 URLs instead of routing through the Anvato API. The token generator endpoint is now gone (404), so removed the dead code in `AnvatoIE`.
Haven't been able to test with a premium account, but know that the NFLPlus extractors were definitely broken due to the dead token endpoint.
</details>
> [ie/nfl] Fix extractors

- test/test_cookies.py
- yt_dlp/cookies.py
Fixes issue discussed in thread at https://github.com/yt-dlp/yt-dlp/issues/6564
Fixes #6564 
</details>
> [cookies] Support chrome table version 24

- yt_dlp/extractor/adobepass.py
Fixes a regression introduced in dcfeea4dd5e5686821350baa6c7767a011944867
Closes #11469
</details>
> [ie/adobepass] Fix provider requests

- .github/workflows/build.yml
- .github/workflows/release-master.yml
- .github/workflows/release-nightly.yml
- .github/workflows/release.yml
428ffb75aa3534b275cf54de42693a4d261519da disabled digital attestations for trusted publishing to PyPI. This was due to reusable workflows not being supported by the attestation system.
I did some further reading into this issue, and per https://github.com/pypi/warehouse/issues/11096#issuecomment-2260686299, reusable workflows have *never* actually been supported by trusted publishing (with or without attestation); it's only a happy accident that the particular reusable workflow strategy we use happens to work (without attestation). This means our nightly release workflow could break again at any time.
428ffb75aa3534b275cf54de42693a4d261519da will only continue to work as a band-aid until 1 of these 3 things happen:
1. trusted publishing adds proper support for reusable workflows (probably …
> [build] Enable attestations for trusted publishing

- pyproject.toml
websockets 14.0 causes CI test failures (a lot more of them)
</details>
> [build] Pin `websockets` version to >=13.0,<14

- .github/workflows/build.yml
- pyproject.toml
https://github.com/pyinstaller/pyinstaller/releases/tag/v6.11.1
Relevant bugfix:
> - (Windows) Add a retry loop to onefile temporary directory cleanup as an attempt to mitigate situations when bundled DLLs and python extension modules remain locked by the OS and/or anti-virus program for a short while after the application process exits. ([#8870](https://github.com/pyinstaller/pyinstaller/issues/8870))
</details>
> [build] Bump PyInstaller version pin to `>=6.11.1`

- yt_dlp/extractor/archiveorg.py
Fixes an issue with the archive.org extractor where a review that's missing the `'reviewbody'` key causes a `TypeError` when string concatenation is attempted in order to include the review's body into `infodict['comments']`.
Added a new test for an affected URL (the one referenced in the related Issue).
Fixes #11526 
</details>
> [ie/archiveorg] Fix crash (TypeError) when a review's body is None

- test/test_traversal.py
- test/test_utils.py
- yt_dlp/utils/_utils.py
- yt_dlp/utils/traversal.py
Fix `join_nonempty(*[])` to not create a `partial`.
To pass `kwargs` to a `join_nonempty` traversal now, do the following:
```diff
-traverse_obj(sth, [..., {unpack(join_nonempty(delim=' ')}])
+traverse_obj(sth, [..., {unpack(join_nonempty, delim=' ')}])
```
</details>
> [utils] Fix `join_nonempty`, add `**kwargs` to `unpack`

- test/test_traversal.py
- yt_dlp/utils/traversal.py
Common pattern where we have a default language for the subtitle
</details>
> [utils] `subs_list_to_dict`: Add `lang` default parameter

- yt_dlp/extractor/patreon.py
The issue appeared to have to do with comments that replied to other comments. These comment objects, in the 'included' block, could be picked up by the traverse_obj call, but were not actually parse-able as comments.
In the attached JSON and screenshot, the string `"153434567"` (the inner red box) is the object referenced by the `comment` variable at the time of the crash, which leads to the `AttributeError` and the crashout. Moving `comment.get('id')` into a `try_call`, and moving the `comment_id is not None` check to the very beginning of the loop body resolved the issue.
Fixes #11483 
[11483.json](https://github.com/user-attachments/files/17737236/11483.json)
</details>
> [ie/patreon] Fix comments extraction

- README.md
- yt_dlp/extractor/sonyliv.py
`--playlist-reverse` doesn't play nice with this site, and true reverse extraction requires a different query param to be passed with the API calls
</details>
> [ie/SonyLIVSeries] Add `sort_order` extractor-arg

- yt_dlp/extractor/bilibili.py
[site-bug]
the site has removed `window.__playinfo__` from the page source. This pr adds a fallback by downloading the playinfo from the API on extraction failure and fixes the error handling for member only videos.
Fixes #11665
</details>
> [ie/bilibili] Provide fallback for playinfo extraction

- yt_dlp/extractor/bilibili.py
Update bilibili url of info api with wbi
seems bilibili update they subtitle api url:
old:  https://api.bilibili.com/x/player/v2?aid=113470703931990&cid=26731938624
new: https://api.bilibili.com/x/player/wbi/v2?aid=113470703931990&cid=26731938624
subtitles info is different (empty some time, or random text other) everytimes the old url is requested:
#1:
`        "subtitle": {
"allow_submit": false,
"lan": "",
"lan_doc": "",
"subtitles": [
{
"id": 1610305384030071000,
"lan": "ai-zh",
"lan_doc": "中文（自动生成）",
"is_lock": false,
"subtitle_url": "//aisubtitle.hdslb.com/bfs/ai_subtitle/prod/113384720701738265043985411da261a20ff661ad1742661f045442eb?auth_key=1733141553-2cb7a684118a43b0805fb8218fa0d3d5-0-3a8c2b0ae88228cf5e2abd7305e0a3dd", …
> [ie/bilibili] Fix subtitles and chapters extraction

- yt_dlp/extractor/bilibili.py
remove playinfo extraction from `window.__playinfo__` and always download it from the API _after_ the `is_interactive` check(`_get_interactive_entries` doesn't need playinfo). This also fixes HD formats' extraction because `window.__playinfo__` was added back by the site and it doesn't contain HD formats
Fixes #10554
</details>
> [ie/bilibili] remove playinfo extraction from `window.__playinfo__`

- README.md
- yt_dlp/extractor/soundcloud.py
The site made some changes to the formats they served. The extractor was making some assumptions about the formats, which are now wrong (e.g. not all aac formats are 256kbps). Had to rework most of the formats extraction code.
</details>
> [ie/soundcloud] Fix formats extraction

- test/test_youtube_signature.py
- yt_dlp/extractor/youtube.py
Closes #11744
Signature function extraction (not n-sig) is also broken and needs to be fixed in separate PR
</details>
> [ie/youtube] Fix `n` sig extraction for player `3bb1f723`

- yt_dlp/extractor/youtube.py
This adds an age-gate workaround for *some* age-restricted videos. They must be embeddable.
Fixes #11296
</details>
> [ie/youtube] Add new age-gate workaround

- README.md
- test/test_YoutubeDL.py
- yt_dlp/YoutubeDL.py
- yt_dlp/options.py
Remove all filename sanitization on non-windows systems except for `/` and `\0` when `--no-windows-filename` is passed. Closes #4547, closes #8464
> Don't sanitize filename on Unix when `--no-windows-filenames`

- yt_dlp/__init__.py
Validate `--*-retries` options to be non-negative.
Fixes #11926
</details>
> [core] Validate retries values are non-negative

- yt_dlp/YoutubeDL.py
Fixes regression introduced in 6fc85f617a5850307fd5b258477070e6ee177796
Closes #11987
</details>
> Fix filename sanitization with `--no-windows-filenames`

- yt_dlp/extractor/youtube.py
Update to reflect what youtube web does these days.
It creates hashes for the other SID cookies as well as includes the user session id in the hash
</details>
> [ie/youtube] Refactor cookie SID auth

- yt_dlp/extractor/dropout.py
The vhx embed URLs now have query strings that will be extracted with `&amp;`s instead of `&` without this patch
Closes #12103
</details>
> [ie/dropout] Fix extraction

- test/test_utils.py
- yt_dlp/utils/_utils.py
Fixes the following sanitization behaviors:
- `sanitize_path('C:abc\\..\\')` => `'C:'` (was `'C:..'`)
- `sanitize_path('./abc/..')` => `'.'` (was `''`)
To further test the sanitization function, for the non replacement tests, we double check that it matches the `nt._path_normpath` result.
</details>
> [utils] `sanitize_path`: Fix some incorrect behavior

- yt_dlp/extractor/bilibili.py
this pr passes `dm_img_list`, `dm_img_str`, `dm_cover_img_str`, and `dm_img_inter` to the API endpoint to enable `BilibiliSpaceVideoIE` to extract without logging in
this pr also updates `BilibiliSpaceAudioIE` and `BilibiliSpaceVideoIE`'s `_VALID_URL` and makes `BilibiliSpaceAudioIE` handle empty playlists properly
I've also noticed a risk-control param `w_webid`(a jwt) for `https://api.bilibili.com/x/space/wbi/arc/search` but it's optional. In case someone needs it, they can use the patch below.
<details><summary>patch</summary>
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index 685447f10..c09b53ee6 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -25,8 +25,10 @@ …
```
> [ie/bilibilispacevideo] extract without logging in

- yt_dlp/extractor/youtube.py
See #11991: When Shorts are accessed e. g. through the Shorts subscriptions feed and with --flat-playlist, there is no title available since the property for that is not present. The full title is contained within the present accessibilityText property though, so it is attempted to extract it from there. A test of 2000 feed entries with various types of titles and view counts resulted in 100% recovered titles. Not sure how to approach adding actual test cases for this yet. 
Fixes #11991
</details>
> [ie/youtube] Attempt to extract title for Shorts from accessibilityText as fallback (#11991)

- yt_dlp/extractor/abematv.py
Adds functionality to specify and download a specific season for series with multiple seasons.
- Implemented support for downloading a specific season when explicitly specified in the URL
- Handles season selection through URL parameters (e.g., `?s=420-61_s2`)
- Resolves issue #10602
Example:
- Before: Unable to download season 2 or later
- After: Can download season 2 via URL like https://abema.tv/video/title/420-61?s=420-61_s2
</details>
> [ie/abematv] support season

- yt_dlp/extractor/xhamster.py
-fixed incorrect extractor on ln287
-updated regex on ln23
-updated tests to include required keys : thumbnail, uploader_url, description, view_count, comment_count, updated tests should fulfill the requirement for testing extractor key change 
-added test for new url matching on ln139-141
This was talked about in #7629 but no resolution seemed to come of it as proper tests werent added. currently all tests are passing using the suggested `hatch test XHamsterIE_all`
Fixes #7620 
</details>
> [ie/xhamster] wrong key used in extractor

- yt_dlp/extractor/acast.py
This adds support for Acast's new episode and channel URL schemes.
(@pabs3)
</details>
> [ie/acast] Support shows.acast.com URLs

- test/test_jsinterp.py
- yt_dlp/jsinterp.py
Helper method, implementing `Number.prototype.toString(radix)` (and by extend some of `ToString(Number)`)
See https://es5.github.io/#x9.8.1
</details>
> [jsinterp] Add `js_number_to_string`

- yt_dlp/downloader/hls.py
In cases where the EXT-X-MAP tag had the BYTERANGE attribute set it would set the byte_range variable in a too-broad scope.
If subsequent fragments didn't have their own byterange specified (for example because they had unique URIs or the byterange was in the URI) the fragment would erroneously limit its byterange to that of the MAP.
This commit decouples the MAP byterange from Media Segment byteranges and makes Media Segment byteranges picked up from a previous EXT-X-BYTERANGE tag follow the RFC8216 spec by only using it on the next Media Segment.
Fixes #9400
I believe the issue is the root cause of #3810, #3578 and #1297 too. I need testers from those issues.
</details>
> [downloader/hlsnative] Fix byterange logic

- test/helper.py
These `missing_keys` in the hint have not been sorted since it was added (a9c2896e2252839c2e4801189f10acce7ff6413e).
```
[info] Writing video metadata as JSON to: ....json
'info_dict': {
'id': '...',
'title': '...',
'upload_date': '...',
'age_limit': ...,
'timestamp': ...,
},
F
======================================================================
FAIL: test_Webpage_all (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
...
File ".../yt-dlp/test/helper.py", line 274, in expect_info_dict
self.assertFalse(
~~~~~~~~~~~~~~~~^
missing_keys,
^^^^^^^^^^^^^
'Missing keys in test definition: {}'.format(', '.join(sorted(missing_keys)))) …
```
> [test:download] Validate and sort info dict fields

- .github/ISSUE_TEMPLATE/1_broken_site.yml
- .github/ISSUE_TEMPLATE/2_site_support_request.yml
- .github/ISSUE_TEMPLATE/3_site_feature_request.yml
- .github/ISSUE_TEMPLATE/4_bug_report.yml
- .github/ISSUE_TEMPLATE/5_feature_request.yml
- .github/ISSUE_TEMPLATE/6_question.yml
- devscripts/make_issue_template.py
Fix 517ddf3c3f12560ab93e3d36244dc82db9f97818
see https://github.com/yt-dlp/yt-dlp/issues/12326#issuecomment-2648898464
Technically, the OP of that issue didn't do anything wrong because we no longer say "do not remove the issue template." I want to eliminate that technicality
</details>
> [misc] Clarify that the issue template cannot be removed

- yt_dlp/YoutubeDL.py
- yt_dlp/downloader/hls.py
- yt_dlp/extractor/common.py
- yt_dlp/utils/_utils.py
`--write-pages` is currently only supported within the extractors, which covers pretty much everything we need **except** for the m3u8 media playlists. These are typically downloaded by the native HLS downloader. Given that many m3u8 URLs are now requiring specific headers (e.g. all akamai CDN m3u8 URLs) or cookies, just being able to copy the URL from the verbose output or IE result is insufficient. Adding `--write-pages` support for these m3u8s will make some debugging a much smoother experience.
In order to implement this, I had to move `_request_dump_filename` to somewhere that both the downloader and the extractors could use it. This meant either make it a `YoutubeDL` method or a `utils` function. I chose `YoutubeDL` because it uses `params['trim_file_name']` and the function cannot …
> [fd/hls] Support `--write-pages` for m3u8 media playlists

- devscripts/make_supportedsites.py
Add a bit of an explanation to `supportedsites.md`
</details>
> [docs] Add note to `supportedsites.md`

- yt_dlp/extractor/niconico.py
Use the name provided by the server as the video format name instead of the generated name
Added `quality` fields for each format for video and audio, modified so that the correct format is selected.
Format selection logic during download ignores server's qualityLevel field.
The server's response includes a qualityLevel item, and a format with a higher value is considered to have higher video quality.
However, the current logic refers only to the resolution of the video and may select the wrong format
Also, the format name of the video should respect the server's id
新・豪血寺一族 -煩悩解放 - レッツゴー！陰陽師 ( https://www.nicovideo.jp/watch/sm9 )
This video has `video-h264-360p`(`360p`) and `video-h264-360p-lowest`(`低画質`/`low resolution`).
(However, the current yt-dlp displays the generated format name, …
> [ie/niconico] Fix format sorting

- yt_dlp/networking/_requests.py
- yt_dlp/networking/_websockets.py
Add ` (unsupported)` tag for `urllib3`, `requests` and `websockets`
Fixes #12625
</details>
> [networking] Always add unsupported suffix on version mismatch

- yt_dlp/extractor/msn.py
[Extractor] Add MSN extractor
Allows download of videos from msn.com
> Fully supports the _TESTS cases (direct MP4s, playlists, and embedded videos).
> Extracts additional metadata (e.g., duration, uploader) expected by yt-dlp.
> Handles embedded content (e.g., YouTube, Dailymotion) by delegating to other extractors.
> Improves error handling and robustness.
> Maintains compatibility with yt-dlp’s conventions.
> Full Metadata Support
* Added description, duration, uploader, and uploader_id extraction from json_data or 
webpage metadata (using _html_search_meta).
* Uses unescapeHTML to clean titles/descriptions.
> Embedded Video Handling:
* Added _extract_embedded_urls to detect iframes with YouTube, Dailymotion, etc.
* If no direct formats are found, returns a single url_result (for one …
> [ie/msn] Rework extractor

- yt_dlp/extractor/nbc.py
NBC affiliate sites seem to be using new `Object.assign(nbc, {...` syntax for assigning to the `nbc` global var
Fixes #
</details>
> [ie/NBCStations]allow for new nbc_data syntax

- test/test_utils.py
- yt_dlp/utils/_utils.py
`_search_json` together with `transform_source=js_to_json` can currently be fatal. What happens is that the regex extracts part of the html, then `js_to_json` runs and crashes on part of the html. By suppressing the error the html doesn't get transformed. This is not an issue since `LenientJSONDecoder` just discards the additional html data.
From what I can tell it is actually intended that `_search_json` extracts part of the html data. With regex's you can only really either match the first closing `}` or the last `}`. So the function matches the last and then any additional data gets discarded by `LenientJSONDecoder`.
</details>
> [utils] `js_to_json`: Make function less fatal

- yt_dlp/extractor/mlb.py
> [ie/mlbtv] Fix radio-only extraction

- yt_dlp/extractor/loco.py
> [ie/loco] Fix extractor

- yt_dlp/extractor/generic.py
Fixes regression introduced in 5086d4aed6aeb3908c62f49e2d8f74cc0cb05110
</details>
> [ie/generic] Fix MPD extraction for `file://` URLs

- yt_dlp/extractor/dacast.py
In hindsight we probably should've used `f'{user_id}-vod-{video_id}'` as the `id`, but oh well
</details>
> [ie/dacast] Support tokenized URLs

- yt_dlp/extractor/youtube/_video.py
If the user is passing the `lang` extractor-arg, they'll get a player JS variant with a different locale in the URL path (e.g. `uk_UA` instead of `en_US` when passing `--extractor-arg "youtube:lang=uk"`; [log](https://github.com/yt-dlp/yt-dlp/issues/12994#issue-3015353889)). We were previously only hardcoding `en_US` in our variant detection code, which would cause player JS variants from other locales to not be properly detected. This PR fixes that
</details>
> [ie/youtube] Detect player JS variants for any locale

- yt_dlp/extractor/youtube/_base.py
Detect and warn when YouTube account cookies that were provided to yt-dlp are invalidated due to being rotated in the browser. This points users to https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies.
Related: https://github.com/yt-dlp/yt-dlp/issues/8227
```
[debug] [youtube:playlist] Found YouTube account cookies
[youtube:playlist] Extracting URL: LL
[debug] [youtube:tab] Found YouTube account cookies
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=LL
[youtube:tab] LL: Downloading webpage
WARNING: [youtube:tab] The provided YouTube account cookies are no longer valid. They have likely been rotated in the browser as a security measure. For tips on how to effectively export YouTube cookies, refer to …
```
> [ie/youtube] Detect when account cookies are rotated

- yt_dlp/extractor/tv2dk.py
> [ie/TV2DK] Fix extractor

- yt_dlp/extractor/youtube/_video.py
Deprioritization was redundant; they're already hidden behind an extractor-arg
</details>
> [ie/youtube] Do not strictly deprioritize `missing_pot` formats

- yt_dlp/extractor/youtube/_video.py
This PR fixes the issue with youtube extractor, where if `--live-from-start` is used against YouTube premiere video and the download was happening during premiering, it will result in the following error.
```
ERROR: 'manifest_url'
Traceback (most recent call last):
File "yt_dlp/YoutubeDL.py", line 1587, in wrapper
File "yt_dlp/YoutubeDL.py", line 1743, in __extract_info
File "yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
File "yt_dlp/YoutubeDL.py", line 2952, in process_video_result
File "yt_dlp/YoutubeDL.py", line 3365, in process_info
File "yt_dlp/YoutubeDL.py", line 3139, in dl
File "yt_dlp/downloader/common.py", line 455, in download
File "yt_dlp/downloader/dash.py", line 63, in real_download
File "yt_dlp/downloader/fragment.py", line 421, in …
```
> [ie/youtube] Fix `--live-from-start` support for premieres

- .github/workflows/build.yml
From https://github.com/uraimo/run-on-arch-action:
> [!NOTE]
> **New major release addressing sporadic segmentation faults**
> 
> The release 3.0.0 addresses sporadic segmentation faults noticed with recent kernel releases, please update your action to this new major release (e.g. @v3) if you start noticing random or systematic CI failures.
We've definitely been experiencing this :point_up: with the Linux ARM builds.
</details>
> [build] Bump run-on-arch-action to v3

- yt_dlp/extractor/youtube/_clip.py
- yt_dlp/extractor/youtube/_redirect.py
- yt_dlp/extractor/youtube/_video.py
For `YoutubeIE` results, the `media_type` field can now be one of these values:
- `'livestream'`: an active or saved livestream
- `'short'`: a video that is eligible for YouTube Shorts, thus YT effectively treats it as a short
- `'clip'`: a YouTube Clip
- `'video'`: any other video
</details>
> [ie/youtube] Extract `media_type` for all videos

- yt_dlp/extractor/nebula.py
Allow Nebula videos, classes and podcasts to be marked as read on download with the `--mark-watched` option
</details>
> [ie/nebula] Support `--mark-watched`

- yt_dlp/extractor/lrt.py
Currently LRT.lt website is being refactored which leads to some regressions in their API introduced from time to time. Media download stopped to work from their site probably because of changed values in API.
Reproduction steps on recent "master" branch ([20f288bd](https://github.com/yt-dlp/yt-dlp/commit/20f288bdc2173c7cc58d709d25ca193c1f6001e7)) commit was used):
```shell
$ git clone git@github.com:yt-dlp/yt-dlp.git
$ make
$ ./yt-dlp https://www.lrt.lt/radioteka/irasas/2000404991/gyvates-valgo-gyvates-arba-kaip-susije-prodiuseris-roax-ir-peledu-persekiotojas\?season\=%2Fmediateka%2Faudio%2Fdrugelio-efektas%2F2025
[LRTRadio] Extracting URL: https://www.lrt.lt/radioteka/irasas/2000404991/gyvates-valgo-gyvates-arba-kaip-susije-prodiuseris...gelio-efektas%2F2025
[LRTRadio] 2000404991: …
```
> [ie/LRTRadio] Fix extractor

- yt_dlp/extractor/youtube/_video.py
I was able to reproduce this with both the stock tv client, and a safari client with my POT.
```
❯ ./yt-dlp.cmd -Uv https://www.youtube.com/watch?v=Aof3f58xw9E --config-locations="$(scoop prefix yt-dlp-master)/yt-dlp.conf"
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=Aof3f58xw9E', '--config-locations=~\\scoop\\apps\\yt-dlp-master\\current/yt-dlp.conf']
[debug] | Config "~\scoop\apps\yt-dlp-master\current/yt-dlp.conf": ['--cookies-from-browser', 'firefox:%APPDATA%/librewolf/Profiles/xxxxxxxx.dev-edition-default', '--mark-watched', '--simulate']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.04.30 from yt-dlp/yt-dlp [505b40079] (source) …
```
> [ie/youtube] Fix `--mark-watched` support

- yt_dlp/extractor/weverse.py
This replaces broken username/password login support (since it requires captcha now), and improves the login hints to clarify that `--cookies-from-browser` doesn't work with this extractor (since the cookies it needs are session cookies).
Closes #7806
</details>
> [ie/weverse] Support login with oauth refresh tokens

- yt_dlp/extractor/dreisat.py
- yt_dlp/extractor/zdf.py
This PR fixes an issue where the reported language for some audio-only files was incorrect. Additionally some more changes have been done to improve the format sorting and provided metadata for those formats. Additional details can be found in the individual commit messages.
Fixes #13118
<details><summary>Format comparison</summary> 
Before:
```
$ yt-dlp -qF https://www.zdf.de/video/serien/the-tourist-110/iren-sind-menschlich-100
ID                                 EXT  RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio0-Originalton_englisch-0  mp4  audio only     │                  m3u8  │ audio only …
```
> [ie/zdf] Fix language extraction and format sorting

- devscripts/changelog_override.json
Just changelog overrides because I forgot how `make_changelog` interprets reverted commits
> [cleanup] Misc

- yt_dlp/networking/_requests.py
I'm sorry
Fixes 2GB preallocation and MemoryError on py3.9
</details>
> [rh:requests] Do not allocate 2GB on read

- devscripts/bash-completion.in
Fix bash completion of file and directory names with whitespace.
Files and directory names, as completed for yt-dlp's options `--load-info-json` and `--cache-dir` (among others), are split into words when tab-completiing in bash, instead of expanding to the full names. Additional actions are required in the completions script.
Fixes #13619
I checked the methods used by other bash-completions scripts, and found this minor modification which works very well.
</details>
> [devscripts] Fix filename/directory Bash completions

- test/test_InfoExtractor.py
- yt_dlp/extractor/common.py
Considering the [Patreon next.js v13 data](https://www.patreon.com/cw/anythingelse) and how its campaign `id`s are not accessible with the current implementation of `_search_nextjs_v13_data`, it's apparent that we need to extract the flight segments that are objects/dicts, not only the arrays/lists.
Also, the `prefix` of the flight segment (e.g. `1a`) can be referenced in another data object (e.g. `$1a`), and these seem to be in the same namespace as the flight segment `name` (e.g. `$L1a`).
Conclusion: we should flatten to a dict instead of a list, with the `prefix`es/`name`s as the keys, and return that. (And the keys should have the `$` and `$L` prefixes stripped)
Fixes 5245231e4a39ecd5595d4337d46d85e150e2430a
</details>
> [ie] Rework `_search_nextjs_v13_data` helper

- yt_dlp/utils/_utils.py
Related: https://github.com/yt-dlp/yt-dlp/issues/13743
</details>
> [utils] `urlhandle_detect_ext`: Use `x-amz-meta-file-type` headers

- yt_dlp/YoutubeDL.py
> [core] Don't let format testing alter the return code

- yt_dlp/extractor/mlb.py
Currently, the extractor removes the token segment from the m3u8 URL path and passes the token as a custom http header instead. This seems to be an unnecessary step with the undesirable side effect of breaking downloads via ffmpeg (or playback via ffmpeg-based media players such as mpv), since ffmpeg apparently struggles with sending the custom header with all requests. This PR removes the unnecessary step, thus eliminating this side effect.
</details>
> [ie/mlbtv] Make formats downloadable with ffmpeg

- yt_dlp/downloader/external.py
> [fd/external] Work around ffmpeg's `file:` URL handling

- yt_dlp/update.py
> Deprecate `darwin_legacy_exe` support

- yt_dlp/cookies.py
The current implementation is rejecting valid cookies because we are using `str.isdigit`, which will return `False` for a stringified float value.
Float timestamps are valid:
https://github.com/python/cpython/blob/3.13/Lib/http/cookiejar.py#L776
https://github.com/python/cpython/blob/3.9/Lib/http/cookiejar.py#L768
</details>
> [cookies] Load cookies with float `expires` timestamps

- yt_dlp/downloader/dash.py
> [fd/dash] Re-extract if using --load-info-json with --live-from-start

- yt_dlp/update.py
Ref: https://github.com/yt-dlp/yt-dlp/issues/13976
</details>
> Deprecate `linux_armv7l_exe` support

- yt_dlp/extractor/svt.py
This PR improves the `SVTPlay` extractor to differentiate between *forced* subtitles and closed caption/SDH. In the same fashion as the [SBS extractor](https://github.com/yt-dlp/yt-dlp/blob/404bd889d0e0b62ad72b7281e3fefdc0497080b3/yt_dlp/extractor/sbs.py#L131) and the [Arte extractor](https://github.com/yt-dlp/yt-dlp/blob/404bd889d0e0b62ad72b7281e3fefdc0497080b3/yt_dlp/extractor/arte.py#L137), it adds "-forced" after the language code. This means that by default, the language subtitles that are downloaded are the closed caption ones. 
Fixes #14020 
</details>
> SVT sv-forced subtitles for forced subtitles

- yt_dlp/extractor/youtube/_base.py
> [ie/youtube] Use alternative `tv` user-agent when authenticated

- yt_dlp/extractor/kick.py
Adds `is_live` for Kick VODs, which someone asked for earlier today on Discord.
</details>
> [ie/kick:vod] Support ongoing livestream VODs

- .github/workflows/core.yml
- test/test_utils.py
`test_sanitize_path` is failing on Windows CPython 3.11 because 3.11's `nt._path_normpath` implementation was wrong, and instead of fixing it properly, a workaround was patched into `os.path.normpath`. In Python 3.12+, `nt._path_normpath` was fixed and the workaround in `os.path.normpath` was removed.
</details>
> [test:utils] Fix `sanitize_path` test for Windows CPython 3.11

- yt_dlp/extractor/xhamster.py
Fix 404 errors on XHamster video downloads by handling base64-encoded XOR-encrypted URLs.
The site now encodes some video URLs using base64 with an XOR cipher using the key 'xh7999'. This change detects base64-encoded URLs starting with 'xor_', decodes the content, and applies XOR decryption before processing the URL. (patch by [arand](https://github.com/arand))
Fixes #14145 
</details>
> [ie/xhamster] Fix extractor
